//! The crate's one integration-test binary: every other `tests/*.rs` is a
//! module here. Generated by `python tools/check-tests-harnessed.py --write`;
//! the gate fails when a test file is missing from this list.

mod unit_lexer;
