//! **A page's `/Annots` can name anything, and `delete_annotation` believed
//! it** (`Pass 190.1`).
//!
//! ## The defect
//!
//! `annot::page_annotations` accepts any `/Annots` entry that resolves to a
//! dictionary. That is the right posture for a **reader** — `ARCHITECTURE.md`
//! §10's fail-clean rule says one odd entry must not cost the operator the
//! page — and it is a hole under a **deletion**, which removes the object the
//! entry names.
//!
//! `annotation_deletion_guards` tested `/F` bit 8, `/TrapNet` and `/Widget`.
//! All three ask *what kind of annotation is this*; none asked whether it was
//! one at all. So a page whose `/Annots` names the **document catalog** made
//! `delete_annotation` delete the catalog, return `Ok`, and produce a file
//! with no page-tree root — caught only by a `#[cfg(debug_assertions)]`
//! postcondition that is compiled out of the build operators run.
//!
//! Found by `fuzz/fuzz_targets/annot_delete_sequence.rs` within seconds of
//! that target first existing, on a **173-byte** input. A second signature
//! from the same site was `BadKid` — the same bug with a page-tree node in
//! `/Annots` instead of the catalog.
//!
//! ## ★★ This is `Pass 185.1`/`185.2` in a second carrier, and that is the
//! ## part worth keeping
//!
//! There, an `/AcroForm` `/Fields` named an object that was also a `/Page`.
//! Here, a page's `/Annots` does. The general fact underneath both:
//!
//! > **An entry in a structural array is not necessarily the kind of object
//! > that array is for**, and every deletion verb that trusts one has this
//! > defect until it is told not to.
//!
//! `refuse_if_in_page_tree` was written for the form half in `Pass 185.1` and
//! **was never called from the annotation half**. The fix already existed; the
//! second caller did not. So the lesson is not "add a guard" — it is that a
//! guard written for one carrier is a claim about a class, and the other
//! members of that class need enumerating at the time, not when a fuzzer finds
//! them one by one.
//!
//! ## The fixtures are the reducer's own output
//!
//! `structural-annots-catalog.pdf` is the 173-byte crash input with its 8-byte
//! fuzz program prefix stripped and its truncated tail closed so it loads.
//! Generated by `tools/gen-annot-structural-fixtures.py`; wholly synthetic
//! (`LEGAL.md` §5 category (a)) — a fuzzer's mutation of pdfcer's own bytes is
//! pdfcer's own bytes.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use pdfcer_core::document::Document;
use pdfcer_core::edit::{EditError, EditSession};
use pdfcer_core::graph::ObjectGraph;
use pdfcer_core::object::ObjId;
use pdfcer_core::page_tree;
use std::path::{Path, PathBuf};

fn fixture(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures/synthetic/annot")
        .join(name)
}

fn session(name: &str) -> EditSession {
    EditSession::new(Document::load(&fixture(name)).expect("load fixture"))
}

/// Every object a page's `/Annots` names, in order — including the ones that
/// are not annotations, which is the whole point.
fn annots_of_page(s: &EditSession, page_index: usize) -> Vec<ObjId> {
    let g = s.graph();
    let pages = page_tree::pages_in(&g).expect("a page tree");
    let page = &pages[page_index];
    let Some(pdfcer_core::object::Object::Dict(d)) = g.value(page.id) else {
        return Vec::new();
    };
    let Some(pdfcer_core::object::Object::Array(items)) =
        d.get(b"Annots").map(|o| g.resolve(o).clone())
    else {
        return Vec::new();
    };
    items
        .iter()
        .filter_map(pdfcer_core::object::Object::as_reference)
        .collect()
}

/// ★★★ The headline. Deleting the catalog must be refused, by name.
///
/// Asserted on the **page tree still walking afterwards**, not only on the
/// error — because the error is the mechanism and the walkable document is the
/// property. A future refactor that returns the right error and still writes
/// the removal would pass an error-only assertion.
#[test]
fn an_annots_entry_that_is_the_catalog_is_refused_not_deleted() {
    let mut s = session("structural-annots-catalog.pdf");
    let ids = annots_of_page(&s, 0);
    assert!(!ids.is_empty(), "the fixture's /Annots must name something");

    let mut refusals = 0;
    for id in &ids {
        match s.delete_annotation(*id) {
            Err(EditError::AnnotationObjectIsStructural { .. })
            | Err(EditError::FieldObjectIsInPageTree { .. }) => refusals += 1,
            // Any other refusal is acceptable — this fixture is malformed and
            // several guards could legitimately claim it first.
            Err(_) => {}
            Ok(_) => panic!(
                "deleted object {id:?}, which is named in /Annots but is part of the document's \
                 structure"
            ),
        }
    }
    assert!(
        refusals > 0,
        "at least one entry is structural and must be refused BY NAME, so the operator is told \
         what collided rather than being given a generic failure"
    );

    // The property, not the mechanism: the document still opens.
    assert!(
        page_tree::pages_in(&s.graph()).is_ok(),
        "the page tree must still walk — this is the postcondition whose \
         #[cfg(debug_assertions)] form was the ONLY thing that noticed, and which is compiled \
         out of the build operators run"
    );
}

/// The `BadKid` signature: the same defect with a page-tree node in `/Annots`
/// rather than the catalog. Asserted separately because it reaches a different
/// half of the guard — the page-tree walk, not the `/Type` test.
#[test]
fn an_annots_entry_that_is_a_page_tree_node_is_refused_not_deleted() {
    let mut s = session("structural-annots-pages-node.pdf");
    for id in annots_of_page(&s, 0) {
        if s.delete_annotation(id).is_ok() {
            panic!("deleted object {id:?}, which is a page-tree node");
        }
    }
    assert!(page_tree::pages_in(&s.graph()).is_ok());
}

/// ★ The guard must not refuse a REAL annotation. Without this the whole
/// feature could be "fixed" by refusing everything, and the two tests above
/// would still pass.
#[test]
fn an_ordinary_annotation_on_the_same_shape_still_deletes() {
    let mut s = session("structural-annots-mixed.pdf");
    let ids = annots_of_page(&s, 0);
    assert_eq!(ids.len(), 2, "one real annotation and one structural entry");

    let outcomes: Vec<bool> = ids
        .iter()
        .map(|id| s.delete_annotation(*id).is_ok())
        .collect();
    assert!(
        outcomes.contains(&true),
        "the genuine /Square annotation must still be deletable"
    );
    assert!(
        outcomes.contains(&false),
        "and the structural entry beside it must still be refused"
    );
    assert!(page_tree::pages_in(&s.graph()).is_ok());
}
