//! **`/AP` can name anything, and cascade 3 deleted whatever it reached**
//! (`Pass 191.0`).
//!
//! ## The defect
//!
//! `EditSession::appearance_streams_owned_by` — cascade 3 of
//! `delete_annotation` — collects the objects an annotation's `/AP` reaches and
//! hands the whole set to deletion. It never checked that any of them was a
//! **stream**.
//!
//! ISO 32000-1 §12.5.5 leaves no room: *"Each appearance stream **is a form
//! XObject**"*, and where Table 168's `/N`, `/R` or `/D` holds a subdictionary
//! instead, *"the subdictionary **shall define multiple appearance streams**
//! corresponding to different appearance states"*. Every object that function
//! reaches shall be a stream; anything else is some other object the file
//! pointed `/AP` at.
//!
//! Concretely, the code branched on the resolved type: a **stream** was doomed
//! directly, and a **dictionary** was treated as an appearance-state
//! subdictionary and had *every reference inside it* harvested as an
//! appearance state. Feed it a dictionary that is not a state subdictionary and
//! that second branch becomes a deletion primitive aimed at an attacker-chosen
//! object.
//!
//! ## What was measured, and why it was not sized from the assert
//!
//! Found on the `BadKid(ObjId 3)` route that `Pass 190.1` left open, tracked as
//! `fuzz/corpus/annot_delete_sequence/seed_openbug_badkid_dupobjnum.bin`. A
//! `/Stamp` whose `/AP` `/N` referenced a `/Widget` **dictionary** put the code
//! in the subdictionary branch, so the widget's `/P` — which points at the
//! **page** — was collected. The page was deleted, `cut_selection` returned
//! `Ok`, and `to_full_bytes` wrote a 904-byte file that reloads with
//! `PageTreeError::BadKid`.
//!
//! Standing rule `R238` is why that sentence says *measured* rather than
//! *reasoned*: a `debug_assert` tells you **where the check runs**, never
//! **what the shipping build does when the property is false**. Here the
//! shipping build does the worst of the three — returns `Ok` and writes wrong
//! bytes. Two accidents hid it. `debug_assert_page_tree_still_walks` is
//! compiled out of a release build; and the *incremental* save path happened to
//! refuse this particular document for an entirely unrelated reason (a
//! recovered base cross-reference), which is exactly the kind of coincidence
//! that lets a route be recorded as harmless. `save_full` — the sanctioned path
//! for a recovered document, and therefore the one an operator actually reaches
//! — carried the corruption straight through.
//!
//! ## Why the guard is a type test and not a structural-object blacklist
//!
//! `annotation_deletion_guards` refuses structural objects **by name** —
//! catalog, `/Pages`, `/Page` — for the deletion *target*, and that check would
//! have caught this reproducer. It would also have left every other non-stream
//! reachable: a font dictionary, an `/AcroForm`, a `/Metadata`, an unrelated
//! annotation. The type test is **categorical** and needs no enumeration to
//! stay correct. That is `R219`'s widened trigger applied deliberately — *a
//! guard written for one carrier is a claim about a class* — so the guard is
//! written about the class rather than about the reproducer.
//!
//! ## ★ Three of these five tests are CONTROLS
//!
//! Cascade 3 exists to delete appearance streams, and a "fix" that simply stops
//! deleting anything would pass both hostile fixtures while silently orphaning
//! a stream in every subsequent save. So the real-stream cases assert deletion
//! **positively**, and the two state-subdictionary controls cover the branch
//! that broke (`/N` a *reference to* a dictionary) and its inline twin (`/N` a
//! *direct* dictionary) separately — a fix applied to one branch and not the
//! other is a shape this project has shipped before.
//!
//! ## The assertions are on the BYTES
//!
//! Every test here saves and reloads. A verb's outcome struct is a reader the
//! verb writes itself: `AnnotationDeletion` reports what the plan *intended*,
//! and on the defect this file pins, that report was correct while the bytes
//! were not. Asserting on `appearance_streams_removed` would have gone green
//! throughout.
//!
//! Fixtures generated by `tools/gen-annot-ap-cascade-fixtures.py`; wholly
//! synthetic (`LEGAL.md` §5 category (a)).

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use pdfcer_core::document::Document;
use pdfcer_core::edit::EditSession;
use pdfcer_core::graph::ObjectGraph;
use pdfcer_core::object::{ObjId, Object};
use pdfcer_core::page_tree;
use pdfcer_core::writer::SaveOptions;
use std::path::{Path, PathBuf};

fn fixture(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures/synthetic/annot")
        .join(name)
}

fn session(name: &str) -> EditSession {
    EditSession::new(Document::load(&fixture(name)).expect("load fixture"))
}

/// Every object id a page's `/Annots` names, in order — including the ones that
/// are not annotations.
fn annots_of_page(s: &EditSession, page_index: usize) -> Vec<ObjId> {
    let g = s.graph();
    let pages = page_tree::pages_in(&g).expect("a page tree");
    let Some(Object::Dict(d)) = g.value(pages[page_index].id) else {
        return Vec::new();
    };
    let Some(Object::Array(items)) = d.get(b"Annots").map(|o| g.resolve(o).clone()) else {
        return Vec::new();
    };
    items.iter().filter_map(Object::as_reference).collect()
}

/// Save by **full rewrite** and reload, returning the reloaded document.
///
/// `save_full` rather than the incremental path on purpose. The incremental
/// path refuses a recovered document, and it was that refusal — not any guard —
/// that hid this defect from the fuzz harness's own save-and-reload assertion.
/// A test that inherited the same accident would inherit the same blind spot.
fn save_full_and_reload(s: &EditSession) -> Document {
    let (bytes, _) = s
        .to_full_bytes(&SaveOptions::identity())
        .expect("a full rewrite must succeed");
    Document::from_bytes(bytes).expect("pdfcer must be able to reopen what pdfcer wrote")
}

/// Does the reloaded document still resolve object `id` to a stream?
///
/// The positive half of the contract. `is_none()` on the value would also be
/// true for an object that was never there, so the controls check the *loaded*
/// document for the stream's presence before deleting as well as after.
fn resolves_to_stream(doc: &Document, id: ObjId) -> bool {
    matches!(doc.view().graph().value(id), Some(Object::Stream(_)))
}

/// ★★★ The headline, and the exact shape the fuzzer found.
///
/// `/AP` `/N` names a `/Widget` dictionary whose `/P` is the page. Deleting the
/// stamp must not take the page with it.
///
/// Asserted on the saved-and-reloaded page tree rather than on the session's,
/// because the session's graph and the bytes are two different claims and it
/// was the bytes that were wrong.
#[test]
fn an_ap_entry_that_is_a_dictionary_does_not_donate_its_references_to_deletion() {
    let mut s = session("ap-cascade-widget-reaches-page.pdf");
    let ids = annots_of_page(&s, 0);
    assert_eq!(ids.len(), 1, "the fixture lists exactly one annotation");
    let page_before = page_tree::pages_in(&s.graph()).expect("walks before").len();

    s.delete_annotation(ids[0])
        .expect("a /Stamp with a malformed /AP is still a deletable annotation");

    let reloaded = save_full_and_reload(&s);
    let pages = page_tree::pages_in(reloaded.view().graph()).unwrap_or_else(|e| {
        panic!(
            "deleting a /Stamp destroyed the page tree ({e:?}). Its /AP /N named a /Widget, and \
             the widget's /P named the page — so the page was collected as though it were an \
             appearance state and deleted. The verb returned Ok."
        )
    });
    assert_eq!(
        pages.len(),
        page_before,
        "the page count must be unchanged — deleting an annotation is not a page operation"
    );
}

/// The other route to the same destruction: `/AP` `/N` names the **catalog**.
///
/// Separate from the test above because the structural object is reached at a
/// different depth — there the page was one hop inside a widget, here the
/// page-tree node is one hop inside the catalog — and because this one destroys
/// the tree without the collected object ever being a `/Page`, which is what
/// makes a name-based blacklist insufficient.
#[test]
fn an_ap_entry_that_is_the_catalog_does_not_take_the_page_tree_with_it() {
    let mut s = session("ap-cascade-names-catalog.pdf");
    let ids = annots_of_page(&s, 0);
    assert_eq!(ids.len(), 1);

    // A refusal here would also be correct; what must not happen is a
    // successful deletion that eats the page tree.
    let _ = s.delete_annotation(ids[0]);

    assert!(
        page_tree::pages_in(&s.graph()).is_ok(),
        "the live page tree must still walk"
    );
    let reloaded = save_full_and_reload(&s);
    assert!(
        page_tree::pages_in(reloaded.view().graph()).is_ok(),
        "the SAVED page tree must still walk — /AP /N named the catalog, whose /Pages was \
         harvested as an appearance state and deleted"
    );
}

/// ★ CONTROL: a real, solely-owned appearance stream MUST still be deleted.
///
/// Without this, the whole defect could be "fixed" by admitting nothing, and
/// both tests above would still pass while every deletion orphaned a stream.
#[test]
fn a_genuine_appearance_stream_is_still_deleted() {
    let mut s = session("ap-cascade-single-stream.pdf");
    let stream_id = ObjId::new(5, 0);
    assert!(
        resolves_to_stream(&save_full_and_reload(&s), stream_id),
        "the fixture must actually contain the appearance stream before deletion, or this \
         control asserts nothing"
    );

    let ids = annots_of_page(&s, 0);
    s.delete_annotation(ids[0]).expect("an ordinary /Stamp");

    let reloaded = save_full_and_reload(&s);
    assert!(
        !resolves_to_stream(&reloaded, stream_id),
        "the appearance stream nothing else reaches must be removed — leaving it behind orphans \
         a stream in every subsequent save, which is the failure cascade 3 exists to prevent"
    );
    assert!(page_tree::pages_in(reloaded.view().graph()).is_ok());
}

/// ★ CONTROL for the branch that actually broke: `/N` is a **reference to** an
/// appearance-state subdictionary whose members really are streams.
///
/// Same resolved type as the hostile fixture — a dictionary — and the opposite
/// required outcome. This is the test that stops the fix from degenerating into
/// "a dictionary under `/N` is always suspect".
#[test]
fn a_state_subdictionary_reached_by_reference_still_deletes_its_streams() {
    let mut s = session("ap-cascade-state-subdict-ref.pdf");
    let (on, off) = (ObjId::new(6, 0), ObjId::new(7, 0));
    let before = save_full_and_reload(&s);
    assert!(
        resolves_to_stream(&before, on) && resolves_to_stream(&before, off),
        "both state streams must be present before deletion"
    );

    let ids = annots_of_page(&s, 0);
    s.delete_annotation(ids[0]).expect("an ordinary /Stamp");

    let reloaded = save_full_and_reload(&s);
    assert!(
        !resolves_to_stream(&reloaded, on) && !resolves_to_stream(&reloaded, off),
        "§12.5.5's subdictionary form defines multiple appearance STREAMS, and every one of them \
         belonged to the deleted annotation alone"
    );
    assert!(page_tree::pages_in(reloaded.view().graph()).is_ok());
}

/// ★ CONTROL for the inline twin: `/N` written as a **direct** dictionary.
///
/// A different code path from the test above — the direct-dictionary branch
/// rather than the resolve-a-reference one. Kept separate because a guard
/// applied to one branch and not the other is precisely the omission this
/// project keeps finding, most recently in `Pass 190.1`.
#[test]
fn a_direct_state_subdictionary_still_deletes_its_streams() {
    let mut s = session("ap-cascade-state-subdict-inline.pdf");
    let (on, off) = (ObjId::new(5, 0), ObjId::new(6, 0));
    let before = save_full_and_reload(&s);
    assert!(resolves_to_stream(&before, on) && resolves_to_stream(&before, off));

    let ids = annots_of_page(&s, 0);
    s.delete_annotation(ids[0]).expect("an ordinary /Stamp");

    let reloaded = save_full_and_reload(&s);
    assert!(
        !resolves_to_stream(&reloaded, on) && !resolves_to_stream(&reloaded, off),
        "the inline subdictionary form must behave identically to the by-reference form"
    );
    assert!(page_tree::pages_in(reloaded.view().graph()).is_ok());
}
