//! **Eight deletion verbs dereferenced a key, believed what it named, and
//! destroyed the document** (`Pass 191.1`).
//!
//! # The class
//!
//! > A verb dereferences a dictionary key, assumes the pointee is the kind of
//! > object that key is *defined* to hold, and deletes it — or deletes and
//! > overwrites objects reached through it.
//!
//! `Pass 185.1` found it at `/AcroForm` `/Fields`. `Pass 190.1` found it again
//! at a page's `/Annots`. `Pass 191.0` found it a third time at `/AP` `/N` and,
//! rather than fixing only that, ran an audit of **all eleven object-removal
//! sites in `pdfcer-core`**. Eight more were claimed, and all eight were then
//! **measured** — twelve hostile cases, every one of them R238's third and
//! worst rung: **the verb returned `Ok` and `to_full_bytes` wrote a file that
//! reloads with no walkable page tree.**
//!
//! The debug/release split is the reason this went unnoticed. All twelve
//! **panic in a debug build** (`debug_assert_page_tree_still_walks` firing) and
//! **return `Ok` in release**. That pairing is itself the finding: the
//! assertion knows, and the build operators run does not.
//!
//! # What is asserted, and why it is not the error variant
//!
//! Each hostile case asserts **the property**: after the verb, the page tree
//! walks, *and* a full rewrite round-trips through `Document::from_bytes` with
//! a walkable page tree. It deliberately does **not** assert that a particular
//! `EditError` came back, and both halves of that are load-bearing:
//!
//! - **A refusal is not the only correct answer.** Four of the twelve are
//!   fixed by a *filter* rather than a refusal — the pointee is **collateral**
//!   (an appearance stream, an `/EF` stream, a `/CIDSet`), so the right
//!   behaviour is for the operator's actual command to succeed while pdfcer
//!   simply declines to free an object of the wrong kind. Requiring `Err` here
//!   would enshrine the worse design.
//! - **An error-variant assertion would have gone green on a wrong message.**
//!   It did, in fact: `refuse_if_in_page_tree` gained seven new carriers in
//!   this Pass, and its message still said *"the file says that object is BOTH
//!   a form field and a page"* — false for a bookmark, an attachment, a
//!   redaction mark. Every variant was right; the sentence the operator reads
//!   was wrong. **A guard written for one carrier is a claim about a class, and
//!   so is its error message.** Caught by reading the probe's output, not by
//!   any assertion, and recorded on the variant itself.
//!
//! # ★ EIGHT of the twenty cases are CONTROLS — 12 hostile + 8 control
//!
//! Every one of these verbs has a legitimate success path, and a "fix" that
//! refused everything would pass all twelve hostile cases. The controls are
//! what make the hostile assertions mean anything — they use the
//! `*-control.pdf` fixtures and are asserted to **succeed**, several of them on
//! a *count* rather than on `Ok`, because a guard that silently skipped every
//! target would otherwise look identical to one that worked.
//!
//! ★ That split is **measured, not asserted**: neutering the three guards
//! reddens exactly the twelve and leaves the eight green
//! (`cargo test --release -p pdfcer-core --test deletion_collateral_structural`
//! under sabotage). Per `R239` the figure above is one a reader can re-derive —
//! count the tests naming a `*-control.pdf` fixture — rather than one they have
//! to trust. **It was wrong when first written** (it said "seven of the
//! nineteen"), and the sabotage run is what corrected it.
//!
//! # Fixtures
//!
//! `fixtures/synthetic/deletion-collateral/`, generated by
//! `tools/gen-deletion-collateral-fixtures.py`. Wholly synthetic, byte-authored
//! (`LEGAL.md` §5 category (a)). They live in their own directory rather than
//! under `annot/`, `forms/` or `outline/` because the eight sites span
//! annotations, forms, outlines, attachments and fonts — filing one defect
//! class across five subject directories would hide that it is one class.
//!
//! `crates/pdfcer-core/examples/collateral_probe.rs` prints the same twenty
//! cases as a table and is the measurement this file was written from. The
//! probe reports; this file **gates**.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use pdfcer_core::document::Document;
use pdfcer_core::edit::EditSession;
use pdfcer_core::font_unembed::UnembedRequest;
use pdfcer_core::object::ObjId;
use pdfcer_core::page_tree;
use pdfcer_core::writer::SaveOptions;
use std::path::PathBuf;

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures/synthetic/deletion-collateral")
        .join(name)
}

fn session(name: &str) -> EditSession {
    let bytes = std::fs::read(fixture(name))
        .unwrap_or_else(|e| panic!("fixture {name} must exist (run the generator): {e}"));
    EditSession::new(Document::from_bytes(bytes).expect("fixture must load"))
}

/// The whole contract, in one place: **whatever the verb decided, the document
/// survived it.**
///
/// Checks the live graph *and* the saved bytes, because they are two different
/// claims. `Pass 191.0`'s defect had the live graph broken too, but the
/// 2026-08-20 `/Contents` corruption did not — it read back fine in memory and
/// wrote a file pdfcer could not reopen. Asserting only one of the two would
/// miss one of the two shapes this project has actually shipped.
///
/// `to_full_bytes` rather than the incremental path, deliberately: the
/// incremental writer refuses a recovered document outright, and it was that
/// unrelated refusal — not any guard — that hid `Pass 191.0`'s defect from the
/// fuzz harness's own save-and-reload assertion. **A refusal that fires for an
/// unrelated reason is not a guard**, and a test that inherits the coincidence
/// inherits the blind spot.
fn assert_document_survived(s: &EditSession, case: &str) {
    let live = page_tree::pages_in(&s.graph());
    assert!(
        live.is_ok(),
        "{case}: the live page tree no longer walks ({:?}). The verb reported success; \
         nothing but a #[cfg(debug_assertions)] postcondition would have noticed, and that \
         is compiled out of the build operators run.",
        live.err()
    );
    let (bytes, _) = s
        .to_full_bytes(&SaveOptions::identity())
        .unwrap_or_else(|e| panic!("{case}: a full rewrite must succeed: {e}"));
    let reloaded = Document::from_bytes(bytes)
        .unwrap_or_else(|e| panic!("{case}: pdfcer wrote a file it cannot reopen: {e}"));
    assert!(
        page_tree::pages_in(reloaded.view().graph()).is_ok(),
        "{case}: the SAVED file reloads but has no walkable page tree — the shape of both the \
         2026-08-20 /Contents corruption and Pass 191.0's BadKid"
    );
}

/// The first ce dimension the sidecar model knows about.
///
/// Read from the model rather than hard-coded. A hand-written `DimensionId`
/// that the sidecar parser had silently dropped would make every ce-dimension
/// case refuse with `DimensionNotFound` — a green test produced by the
/// fixture's own defect rather than by a guard, which is the worst outcome
/// this file could have.
fn first_dimension(s: &EditSession) -> pdfcer_core::dimension::DimensionId {
    s.dimension_model()
        .dimensions()
        .first()
        .map(|d| d.id)
        .expect("the fixture's /PieceInfo sidecar must model a ce dimension")
}

// ===================== SITE 1 — the ce-dimension sidecar =====================

/// The sidecar's `/Ap` is an unvalidated, attacker-supplied object id:
/// `/PieceInfo` is ordinary PDF content and `check_dimension_sidecar` compares
/// a **version integer** and nothing else.
#[test]
fn delete_dimension_does_not_free_a_sidecar_ap_that_is_not_a_stream() {
    let mut s = session("dim-sidecar-ap-names-pagetree.pdf");
    let d = first_dimension(&s);
    let _ = s.delete_dimension(d);
    assert_document_survived(&s, "delete_dimension /Ap");
}

/// The sidecar's `/Annot` is unvalidated too. The only thing downstream
/// implicitly requires of it is a `/P` reference — which a hostile file adds to
/// the catalog in one line.
#[test]
fn delete_dimension_does_not_delete_a_sidecar_annot_that_is_structural() {
    let mut s = session("dim-sidecar-annot-names-pagetree.pdf");
    let d = first_dimension(&s);
    let _ = s.delete_dimension(d);
    assert_document_survived(&s, "delete_dimension /Annot");
}

/// ★ CONTROL: an ordinary ce dimension still deletes.
#[test]
fn delete_dimension_control_still_works() {
    let mut s = session("dim-sidecar-control.pdf");
    let d = first_dimension(&s);
    s.delete_dimension(d).expect("an ordinary ce dimension");
    assert_document_survived(&s, "delete_dimension CONTROL");
}

// ============ SITE 2 — regenerate_dimension_writes, via a LABEL EDIT ==========

/// ★★★ THE HEADLINE OF THIS PASS. `set_dimension_label` is the least
/// destructive-looking verb in the whole set — it renames a caption — and it
/// reaches `regenerate_dimension_writes`, which **overwrites** whatever object
/// the sidecar's `/Ap` names. Measured before the fix: `Ok(changed=true)`, and
/// a saved document whose page-tree root had been replaced by a form XObject.
#[test]
fn a_label_edit_cannot_overwrite_a_structural_object() {
    let mut s = session("dim-sidecar-ap-names-pagetree.pdf");
    let d = first_dimension(&s);
    let _ = s.set_dimension_label(d, Some("HOLD"));
    assert_document_survived(&s, "set_dimension_label /Ap");
}

/// ★ CONTROL: a label edit on a well-formed ce dimension still changes it.
/// Asserted on `changed`, not merely on `Ok` — a verb that returned success
/// while doing nothing would pass a bare `is_ok()`.
#[test]
fn a_label_edit_control_still_changes_the_label() {
    let mut s = session("dim-sidecar-control.pdf");
    let d = first_dimension(&s);
    let outcome = s
        .set_dimension_label(d, Some("HOLD"))
        .expect("an ordinary ce dimension");
    assert!(outcome.changed, "the label edit must actually apply");
    assert_document_survived(&s, "set_dimension_label CONTROL");
}

// ==================== SITE 3 — delete_redaction_mark ========================

/// The verb's own doc comment asserted this was safe: the `/AP` `/N` is
/// *"authored by `add_redaction` solely for that mark"*. Nothing enforces that
/// authorship — `redact::redaction_marks` recognises a mark by two
/// attacker-writable facts (listed in some page's `/Annots`, `/Subtype`
/// `/Redact`).
#[test]
fn deleting_a_redaction_mark_does_not_free_a_non_stream_appearance() {
    let mut s = session("redact-ap-names-pagetree.pdf");
    let _ = s.delete_redaction_mark(ObjId::new(4, 0));
    assert_document_survived(&s, "delete_redaction_mark /AP /N");
}

/// ★ The TARGET arm, and it needed the guard **inside the verb** because this
/// verb has two routes. `delete_annotation` runs `annotation_deletion_guards`
/// before routing a `/Redact` here, so that path was safe — but the GUI calls
/// this verb directly with an id taken from the review panel, and a page-tree
/// root wearing `/Subtype /Redact` appears in that panel.
#[test]
fn deleting_a_redaction_mark_that_is_structural_is_refused() {
    let mut s = session("redact-mark-is-pagetree-node.pdf");
    let _ = s.delete_redaction_mark(ObjId::new(2, 0));
    assert_document_survived(&s, "delete_redaction_mark annot_id");
}

/// ★ CONTROL: an ordinary unapplied mark still deletes.
#[test]
fn deleting_an_ordinary_redaction_mark_still_works() {
    let mut s = session("redact-control.pdf");
    s.delete_redaction_mark(ObjId::new(4, 0))
        .expect("an ordinary /Redact mark");
    assert_document_survived(&s, "delete_redaction_mark CONTROL");
}

// ======================== SITE 4 — flatten_fields ===========================

/// ★★ `Pass 185.1`'s exact input against a verb that never received that fix.
/// `refuse_if_in_page_tree` was wired into `delete_field`, `delete_field_group`
/// and `delete_widget` and not into `flatten_fields`, although it reads the
/// same `/Fields` array and deletes what it names.
///
/// It also reached further than the audit claimed: the `emptied_parents`
/// cascade reads a page's `/Parent` — the `/Pages` node — as a *field's*
/// `/Kids`, finds no survivors, and deletes the page-tree root too.
#[test]
fn flattening_a_field_that_is_also_a_page_is_refused() {
    let mut s = session("flatten-field-is-page.pdf");
    let _ = s.flatten_fields(None);
    assert_document_survived(&s, "flatten_fields /Fields->/Page");
}

/// ★ CONTROL: an ordinary form still flattens, and actually flattens
/// something — asserted on the count, not on `Ok`.
#[test]
fn flattening_an_ordinary_form_still_works() {
    let mut s = session("flatten-control.pdf");
    let outcome = s.flatten_fields(None).expect("an ordinary AcroForm");
    assert!(
        outcome.fields_flattened > 0,
        "the control must flatten a field, or it is not controlling for anything"
    );
    assert_document_survived(&s, "flatten_fields CONTROL");
}

// ================ SITE 5 — outline_subtree / delete_outline_item =============

/// §12.3.3 Tables 152-153 define `/First` and `/Next` as naming outline item
/// dictionaries. The walk accepted any dictionary it reached and pushed every
/// one onto the removal list, so a bookmark whose `/First` names the `/Pages`
/// node deleted it. **Document-driven** — a hostile bookmark, no caller error.
#[test]
fn an_outline_first_that_names_a_page_tree_node_is_refused() {
    let mut s = session("outline-first-names-pagetree.pdf");
    let _ = s.delete_outline_item(ObjId::new(5, 0));
    assert_document_survived(&s, "outline /First->/Pages");
}

/// The weaker arm, kept separate because its reach differs: the entry gate
/// accepts any dictionary carrying a `/Parent`, which every `/Page` satisfies
/// by definition (§7.7.3.3 makes `/Parent` required). Reached when a caller
/// supplies the id — the CLI takes an operator-supplied item number.
#[test]
fn deleting_an_outline_item_that_is_a_page_is_refused() {
    let mut s = session("outline-item-is-page.pdf");
    let _ = s.delete_outline_item(ObjId::new(3, 0));
    assert_document_survived(&s, "delete_outline_item(page)");
}

/// ★ CONTROL: an ordinary bookmark still deletes.
#[test]
fn deleting_an_ordinary_outline_item_still_works() {
    let mut s = session("outline-control.pdf");
    s.delete_outline_item(ObjId::new(5, 0))
        .expect("an ordinary outline item");
    assert_document_survived(&s, "outline CONTROL");
}

// ===================== SITE 6 — cascade 1's /Popup ==========================

/// The guards ran on the target; the command deletes a **set**. Cascade 1 adds
/// the `/Popup` the annotation names *after* `annotation_deletion_guards` has
/// run, so an id nobody guarded reached `removals`.
///
/// The plan's own popup test is real but not sufficient: it requires the
/// pointee to be listed in some page's `/Annots` and to carry `/Subtype
/// /Popup`, and both are attacker-writable.
#[test]
fn a_popup_that_is_a_page_tree_node_is_not_deleted_as_collateral() {
    let mut s = session("popup-is-pagetree-node.pdf");
    let _ = s.delete_annotation(ObjId::new(4, 0));
    assert_document_survived(&s, "delete_annotation /Popup");
}

/// ★ CONTROL: a genuine `/Popup` companion is still removed with its parent.
/// Asserted on `popup_removed`, because the cascade doing nothing would
/// otherwise look identical to the cascade working.
#[test]
fn an_ordinary_popup_is_still_removed_with_its_parent() {
    let mut s = session("popup-control.pdf");
    let outcome = s
        .delete_annotation(ObjId::new(4, 0))
        .expect("an ordinary annotation with a /Popup");
    assert!(
        outcome.popup_removed,
        "cascade 1 must still take the pop-up companion"
    );
    assert_document_survived(&s, "delete_annotation CONTROL");
}

// ========================= SITE 7 — detach_file =============================

/// §7.11.3: `/Names /EmbeddedFiles` maps a name to a **file-specification
/// dictionary**. The name-tree value was freed without checking what it was.
#[test]
fn detaching_a_name_tree_value_that_is_structural_is_refused() {
    let mut s = session("attach-namevalue-is-pagetree.pdf");
    let _ = s.detach_file(b"trap");
    assert_document_survived(&s, "detach_file name-tree value");
}

/// §7.11.4 Table 45 defines `/EF` `/F` and `/UF` as embedded file **streams**.
/// Collateral, so the fix is a filter: the attachment still detaches.
#[test]
fn detaching_does_not_free_an_ef_entry_that_is_not_a_stream() {
    let mut s = session("attach-ef-is-pagetree.pdf");
    let _ = s.detach_file(b"trap");
    assert_document_survived(&s, "detach_file /EF /F");
}

/// ★ CONTROL: an ordinary attachment still detaches.
#[test]
fn detaching_an_ordinary_attachment_still_works() {
    let mut s = session("attach-control.pdf");
    s.detach_file(b"note.txt").expect("an ordinary attachment");
    assert_document_survived(&s, "detach_file CONTROL");
}

// ==================== SITE 8 — unembed_fonts /CIDSet ========================

/// §9.7.4.2 Table 117 defines `/CIDSet` as a **stream**. Its `/FontFile*`
/// sibling has always been guarded by a real `Object::Stream` test ten lines
/// upstream; `/CIDSet` was never routed through it. The fix existed and the
/// second caller did not — `R219`'s trigger, for the third time in this
/// project.
#[test]
fn unembedding_does_not_free_a_cidset_that_is_not_a_stream() {
    let mut s = session("cidset-names-pagetree.pdf");
    let _ = s.unembed_fonts(&UnembedRequest::all_removable());
    assert_document_survived(&s, "unembed_fonts /CIDSet");
}

/// ★ CONTROL: an ordinary embedded font still unembeds.
#[test]
fn unembedding_an_ordinary_font_still_works() {
    let mut s = session("cidset-control.pdf");
    let outcome = s
        .unembed_fonts(&UnembedRequest::all_removable())
        .expect("an ordinary embedded font");
    assert!(
        !outcome.targets.is_empty(),
        "the control must actually unembed a font, or it is not controlling for anything --          a guard that silently skipped every target would otherwise pass this test"
    );
    assert_document_survived(&s, "unembed_fonts CONTROL");
}
