//! Placing a raster image on a page as an image XObject (§8.9.5).
//!
//! ## What these tests are really checking, and why they read the BYTES
//!
//! An image placement is **four coordinated writes**: the image XObject, an
//! optional `/SMask`, a content stream that invokes it, and one patch to the
//! page dictionary carrying both `/Contents` and `/Resources`. Any three
//! without the fourth produce a document that is broken in a way nothing
//! reports — a page whose resources name an XObject its content never
//! invokes shows nothing at all, and every in-memory assertion about the
//! image still passes.
//!
//! Worse, the load-bearing property of this whole feature is a claim about
//! *bytes*: that a JPEG's codestream reaches the document **unchanged**, and
//! that a PNG's `IDAT` is reused verbatim under `/Predictor 15`. A model
//! that says "the image is there" cannot see a stream that holds the right
//! pixels behind the wrong filter, or the right filter over re-compressed
//! bytes. **R159** names exactly this: *"a defect that lives in the BYTES
//! must be asserted in the BYTES."*
//!
//! So the assertions here mostly run over the SAVED FILE, extracted with a
//! deliberately dumb scanner ([`object_body`], [`stream_payload`]) that does
//! no repair of its own — because a lenient parser is precisely what would
//! hide the failures this feature can have.
//!
//! ## Fixture provenance
//!
//! Every image under `fixtures/synthetic/images/` is generated by
//! `tools/gen-image-fixtures.py` from pixel data this project authored.
//! Nothing is downloaded (project rule 7, `LEGAL.md` §5). See that
//! directory's `PROVENANCE.md`.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use pdfcer_core::document::Document;
use pdfcer_core::edit::{EditError, EditSession, ImageFit, NewImage};
use pdfcer_core::graph::ObjectGraph;
use pdfcer_core::image_import::{
    self, ImageCompression, ImageImportError, ImportFilter, ImportOptions, ImportedImage,
    Orientation, PdfFeature, RecompressReason, SUPPORTED_FORMATS,
};
use pdfcer_core::object::{Dict, Name, ObjId, Object};
use pdfcer_core::page_tree::Rect;
use pdfcer_core::writer::SaveOptions;
use std::path::{Path, PathBuf};

// ---------------------------------------------------------------------------
// Harness
// ---------------------------------------------------------------------------

fn fixture(rel: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures/synthetic")
        .join(rel)
}

fn image_bytes(name: &str) -> Vec<u8> {
    std::fs::read(fixture(&format!("images/{name}")))
        .unwrap_or_else(|e| panic!("read fixture images/{name}: {e}"))
}

fn imported(name: &str) -> ImportedImage {
    image_import::import(&image_bytes(name)).unwrap_or_else(|e| panic!("import images/{name}: {e}"))
}

/// A 400 × 400 single-page document with an empty content stream.
fn session() -> EditSession {
    EditSession::new(Document::load(&fixture("dimension/plain-base.pdf")).expect("load fixture"))
}

fn rect(llx: f64, lly: f64, urx: f64, ury: f64) -> Rect {
    Rect { llx, lly, urx, ury }
}

/// Save incrementally and return the whole output file.
fn saved(s: &mut EditSession) -> Vec<u8> {
    s.to_incremental_bytes(&SaveOptions::identity())
        .expect("incremental save")
        .0
}

/// The body of indirect object `id` **as it appears in the saved bytes**.
///
/// Takes the LAST occurrence, because an incremental update appends a new
/// definition after the original and the newest one is what a reader
/// resolves. Deliberately a byte scan rather than a parse: this helper must
/// not be able to repair, normalise, or reinterpret anything on the way
/// in — that is the whole point of asserting here rather than on a model
/// (R159).
fn object_body(pdf: &[u8], id: u32) -> Vec<u8> {
    let needle = format!("\n{id} 0 obj");
    let start = pdf
        .windows(needle.len())
        .enumerate()
        .filter(|(_, w)| *w == needle.as_bytes())
        .map(|(i, _)| i + needle.len())
        .next_back()
        .unwrap_or_else(|| panic!("object {id} is not in the saved file"));
    let end = pdf
        .windows(6)
        .enumerate()
        .skip(start)
        .find(|(_, w)| *w == b"endobj")
        .map(|(i, _)| i)
        .unwrap_or_else(|| panic!("object {id} has no endobj"));
    pdf.get(start..end).unwrap_or_default().to_vec()
}

/// The raw stream payload inside an object body — between the EOL that
/// follows the `stream` keyword and the `endstream` that closes it
/// (§7.3.8.1).
fn stream_payload(body: &[u8]) -> Vec<u8> {
    let kw = b"stream";
    let at = body
        .windows(kw.len())
        .enumerate()
        .find(|(_, w)| *w == kw)
        .map(|(i, _)| i + kw.len())
        .expect("the object has a stream keyword");
    // "shall be followed by CRLF or LF alone, and NOT by CR alone".
    let start = if body.get(at) == Some(&b'\r') {
        at + 2
    } else {
        at + 1
    };
    let end = body
        .windows(9)
        .enumerate()
        .filter(|(_, w)| *w == b"endstream")
        .map(|(i, _)| i)
        .next_back()
        .expect("the object has an endstream");
    // There should be an EOL before `endstream` and it is not part of the
    // data, so trim exactly one.
    let mut stop = end;
    if body.get(stop.wrapping_sub(1)) == Some(&b'\n') {
        stop -= 1;
    }
    if body.get(stop.wrapping_sub(1)) == Some(&b'\r') {
        stop -= 1;
    }
    body.get(start..stop).unwrap_or_default().to_vec()
}

fn contains(hay: &[u8], needle: &[u8]) -> bool {
    hay.windows(needle.len()).any(|w| w == needle)
}

/// A one-page document at an arbitrary declared version, with a real
/// §7.5.4 cross-reference table.
///
/// Written byte by byte with computed offsets rather than by any PDF
/// library — the same discipline the fixture generators follow, so the file
/// cannot inherit a normalization from the code under test. Offsets are
/// derived from the emitted bytes, so the table is correct by construction
/// rather than by a hand count that rots when a byte changes.
fn minimal_pdf(version: &str) -> Vec<u8> {
    let bodies = [
        "<< /Type /Catalog /Pages 2 0 R >>",
        "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] /Resources << >> >>",
    ];
    let mut out = format!("%PDF-{version}\n%\u{e2}\u{e3}\u{cf}\u{d3}\n").into_bytes();
    let mut offsets = Vec::new();
    for (i, body) in bodies.iter().enumerate() {
        offsets.push(out.len());
        out.extend_from_slice(format!("{} 0 obj\n{body}\nendobj\n", i + 1).as_bytes());
    }
    let startxref = out.len();
    out.extend_from_slice(b"xref\n0 4\n0000000000 65535 f \n");
    for off in &offsets {
        out.extend_from_slice(format!("{off:010} 00000 n \n").as_bytes());
    }
    out.extend_from_slice(b"trailer\n<< /Size 4 /Root 1 0 R >>\nstartxref\n");
    out.extend_from_slice(format!("{startxref}\n%%EOF\n").as_bytes());
    out
}

/// The image XObject dictionary as the RELOADED document sees it — the
/// other half of the R159 pairing: the bytes say one thing, and a fresh
/// parse of those bytes must agree.
fn reloaded_image(pdf: &[u8], id: ObjId) -> (Document, Dict, Vec<u8>) {
    let doc = Document::from_bytes(pdf.to_vec()).expect("the saved file reloads");
    let (dict, raw) = {
        let obj = doc.get(id).expect("the image object survives a reload");
        let Object::Stream(stream) = &obj.value else {
            panic!("the image object is not a stream");
        };
        let raw = doc
            .view()
            .slice(stream.data_span)
            .expect("the stream's bytes are addressable")
            .to_vec();
        (stream.dict.clone(), raw)
    };
    (doc, dict, raw)
}

fn dict_int(d: &Dict, key: &[u8]) -> Option<i64> {
    d.get(key).and_then(Object::as_int)
}

fn dict_name(d: &Dict, key: &[u8]) -> Option<Vec<u8>> {
    d.get(key)
        .and_then(Object::as_name)
        .map(|n| n.as_bytes().to_vec())
}

/// The `/XObject` subdictionary the page's resources end up with.
fn page_xobjects(s: &EditSession, page_index: usize) -> Dict {
    let graph = s.graph();
    let page = s.pages().expect("pages")[page_index].id;
    let dict = graph.resolved(page).as_dict().expect("page dict").clone();
    let res = graph
        .resolve(dict.get(b"Resources").expect("page has /Resources"))
        .as_dict()
        .expect("/Resources is a dictionary")
        .clone();
    graph
        .resolve(res.get(b"XObject").expect("/Resources has /XObject"))
        .as_dict()
        .expect("/XObject is a dictionary")
        .clone()
}

// ---------------------------------------------------------------------------
// THE headline: bytes in, same bytes out
// ---------------------------------------------------------------------------

/// A JPEG's codestream reaches the document **byte-identical**, behind
/// `/DCTDecode`, with no `/DecodeParms` and no `/Decode`.
///
/// This is the single most important assertion in the file. A re-encode
/// would still produce a working document with a plausible-looking image —
/// it would simply be a slightly worse copy, every time, invisibly. Only a
/// byte comparison catches it.
#[test]
fn a_jpegs_bytes_survive_byte_identical_into_dctdecode() {
    let source = image_bytes("rgb.jpg");
    let img = image_import::import(&source).unwrap();
    assert_eq!(img.filter, ImportFilter::DctDecode);

    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(50.0, 50.0, 200.0, 200.0), &img))
        .expect("place the JPEG");
    let pdf = saved(&mut s);

    let body = object_body(&pdf, out.image_id.num);
    assert_eq!(
        stream_payload(&body),
        source,
        "the /DCTDecode stream IS the source file, not a re-encoding of it"
    );
    assert!(contains(&body, b"/Filter /DCTDecode"), "{body:?}");
    assert!(
        !contains(&body, b"/DecodeParms"),
        "Table 13 makes the codestream's APP14 marker outrank /ColorTransform, \
         so writing the entry could only agree redundantly or disagree wrongly"
    );
    assert!(
        !contains(&body, b"/Decode ["),
        "R29: /Decode is never written on import — it is the sole polarity \
         control and pdfcer has no polarity opinion to record"
    );

    // …and a fresh parse of those bytes agrees.
    let (_doc, dict, raw) = reloaded_image(&pdf, out.image_id);
    assert_eq!(raw, source);
    assert_eq!(dict_name(&dict, b"Subtype").as_deref(), Some(&b"Image"[..]));
    assert_eq!(
        dict_name(&dict, b"ColorSpace").as_deref(),
        Some(&b"DeviceRGB"[..])
    );
    assert_eq!(dict_int(&dict, b"BitsPerComponent"), Some(8));
    assert_eq!(dict_int(&dict, b"Width"), Some(6));
    assert_eq!(dict_int(&dict, b"Height"), Some(4));
    assert_eq!(
        dict_int(&dict, b"Length"),
        Some(i64::try_from(source.len()).unwrap()),
        "§7.3.8 Table 5: /Length counts the bytes between `stream` and `endstream`"
    );
}

/// A non-interlaced PNG's `IDAT` payload is reused verbatim as a
/// `/FlateDecode` stream under `/Predictor 15` — no inflate, no re-deflate,
/// no arithmetic at all.
#[test]
fn a_pngs_idat_is_reused_verbatim_under_predictor_15() {
    let source = image_bytes("rgb8.png");
    let idat = extract_idat(&source);
    let img = image_import::import(&source).unwrap();

    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 120.0, 80.0), &img))
        .expect("place the PNG");
    let pdf = saved(&mut s);

    let body = object_body(&pdf, out.image_id.num);
    assert_eq!(
        stream_payload(&body),
        idat,
        "the /FlateDecode stream IS the source IDAT"
    );
    assert!(contains(&body, b"/Filter /FlateDecode"));
    for parm in [
        &b"/Predictor 15"[..],
        b"/Colors 3",
        b"/BitsPerComponent 8",
        b"/Columns 6",
    ] {
        assert!(
            contains(&body, parm),
            "Table 8 parameter {} is required for correctness, not decoration",
            String::from_utf8_lossy(parm)
        );
    }
    assert!(img.notes.recompressed.is_none());
}

/// The passthrough is not merely byte-equal — it **decodes to the right
/// pixels through pdfcer's own filter stack**. A `/Predictor 15` stream that
/// happened to be byte-equal to the IDAT while describing the wrong row
/// geometry would pass the previous test and produce noise here.
#[test]
fn the_passthrough_stream_decodes_to_the_original_pixels() {
    let source = image_bytes("rgb8.png");
    let img = image_import::import(&source).unwrap();
    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 120.0, 80.0), &img))
        .unwrap();
    let pdf = saved(&mut s);
    let (_doc, dict, raw) = reloaded_image(&pdf, out.image_id);

    let samples = pdfcer_core::filters::decode_stream(&dict, &raw).expect("the stream decodes");
    // 6 × 4 RGB at 8 bits = 18 bytes per row, 4 rows.
    assert_eq!(samples.len(), 6 * 4 * 3);
    // The generator's ramp: red goes 0 → 255 across the row, blue is its
    // complement, green goes 0 → 255 down the column. Row 0 (the TOP row,
    // §8.9.4) therefore has green = 0.
    assert_eq!(samples.get(0..3), Some(&[0u8, 0, 255][..]), "top-left");
    assert_eq!(samples.get(15..18), Some(&[255u8, 0, 0][..]), "top-right");
    // Last row: green = 255.
    let last = samples.len() - 3;
    assert_eq!(
        samples.get(last..),
        Some(&[255u8, 255, 0][..]),
        "bottom-right"
    );
}

fn extract_idat(png: &[u8]) -> Vec<u8> {
    let mut out = Vec::new();
    let mut i = 8;
    while i + 8 <= png.len() {
        let len = u32::from_be_bytes(png.get(i..i + 4).unwrap().try_into().unwrap()) as usize;
        if png.get(i + 4..i + 8) == Some(b"IDAT") {
            out.extend_from_slice(png.get(i + 8..i + 8 + len).unwrap());
        }
        i += 12 + len;
    }
    out
}

// ---------------------------------------------------------------------------
// Transparency
// ---------------------------------------------------------------------------

/// A PNG's alpha channel becomes a real `/SMask` image — not a flattened
/// composite against white, and not a dropped channel.
#[test]
fn a_pngs_alpha_becomes_an_smask() {
    let img = imported("rgba8.png");
    assert_eq!(img.notes.recompressed, Some(RecompressReason::AlphaSplit));

    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(10.0, 10.0, 130.0, 90.0), &img))
        .expect("place the transparent PNG");
    let smask_id = out.soft_mask_id.expect("an /SMask object was created");
    let pdf = saved(&mut s);

    // The image dictionary points at it, in the BYTES.
    let body = object_body(&pdf, out.image_id.num);
    assert!(
        contains(&body, format!("/SMask {} 0 R", smask_id.num).as_bytes()),
        "{}",
        String::from_utf8_lossy(&body)
    );

    // And the mask itself is a DeviceGray image of the same size.
    let (_doc, mask, raw) = reloaded_image(&pdf, smask_id);
    assert_eq!(dict_name(&mask, b"Subtype").as_deref(), Some(&b"Image"[..]));
    assert_eq!(
        dict_name(&mask, b"ColorSpace").as_deref(),
        Some(&b"DeviceGray"[..]),
        "a soft mask carries opacity, which has one component"
    );
    assert_eq!(dict_int(&mask, b"Width"), dict_int(&mask, b"Width"));
    assert_eq!(dict_int(&mask, b"Width"), Some(6));
    assert_eq!(dict_int(&mask, b"Height"), Some(4));
    assert!(
        mask.get(b"Mask").is_none() && mask.get(b"SMask").is_none(),
        "the conservative shape: a soft mask has no mask of its own"
    );
    let alpha = pdfcer_core::filters::decode_stream(&mask, &raw).unwrap();
    assert_eq!(alpha.len(), 6 * 4);
    assert_eq!(alpha.first(), Some(&0), "the generator's ramp starts at 0");
    assert_eq!(alpha.last(), Some(&255), "…and ends at 255");

    // The disclosures the operator is owed.
    assert!(out.disclosures.soft_mask_written);
    // ★ THIS ASSERTION WAS INVERTED WHEN THE RENDERER LEARNED TO COMPOSITE.
    //
    // It read `assert!(out.disclosures.transparency_not_previewed)` with the
    // reason *"pdfcer-render does not composite /SMask yet, and an operator who
    // sees an opaque preview must be told that is pdfcer's gap, not a lost
    // channel."* That was true, and the disclosure was right to exist.
    //
    // `pdfcer-render` now composites both mechanisms `add_image` can write, so
    // the warning would fire when nothing is wrong — which is precisely how an
    // operator learns to stop reading the channel it arrives on.
    //
    // Kept as a NAMED absence rather than deleted: "this no longer warns" is
    // the behaviour, and a test that merely stopped checking would let the
    // warning creep back the next time someone edits the disclosure block.
    assert!(
        !out.disclosures.transparency_not_previewed,
        "the renderer composites /SMask now, so there is nothing left to warn \
         about — a disclosure that fires when nothing is wrong is worse than \
         no disclosure at all"
    );
}

/// A single transparent colour becomes a colour-key `/Mask` array — and the
/// image data still passes through verbatim, which is the whole reason this
/// case is handled separately from an alpha channel.
#[test]
fn a_single_transparent_colour_becomes_a_colour_key_mask() {
    let source = image_bytes("rgb-trns.png");
    let img = image_import::import(&source).unwrap();
    assert!(img.notes.transparent_colour_to_mask);

    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &img))
        .unwrap();
    assert!(
        out.soft_mask_id.is_none(),
        "no second image object is needed"
    );
    assert!(out.disclosures.colour_key_mask_written);

    let pdf = saved(&mut s);
    let body = object_body(&pdf, out.image_id.num);
    assert!(
        contains(&body, b"/Mask [0 0 0 0 255 255]"),
        "§8.9.6.4 wants [min1 max1 … minn maxn] in SOURCE sample space: {}",
        String::from_utf8_lossy(&body)
    );
    assert_eq!(
        stream_payload(&body),
        extract_idat(&source),
        "transparency did not cost the passthrough"
    );
}

/// Palette transparency keeps the indexed image verbatim and derives only
/// the mask — the branch that would be easy to collapse into "alpha always
/// means decode everything".
#[test]
fn palette_transparency_keeps_the_indexed_image_verbatim() {
    let source = image_bytes("indexed-trns.png");
    let img = image_import::import(&source).unwrap();
    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &img))
        .unwrap();
    let pdf = saved(&mut s);

    let body = object_body(&pdf, out.image_id.num);
    assert_eq!(stream_payload(&body), extract_idat(&source));
    assert!(out.soft_mask_id.is_some());
    assert!(img.notes.palette_alpha_to_soft_mask);
    assert!(img.notes.recompressed.is_none());
}

/// An indexed PNG lands as `[/Indexed /DeviceRGB hival <lookup>]` with the
/// lookup as a byte string (§8.6.6.3 permits a stream *or* a string, and a
/// ≤768-byte table does not deserve its own object).
#[test]
fn an_indexed_png_writes_an_indexed_colour_space() {
    let img = imported("indexed8.png");
    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &img))
        .unwrap();
    let pdf = saved(&mut s);
    let body = object_body(&pdf, out.image_id.num);
    assert!(
        contains(&body, b"/ColorSpace [/Indexed /DeviceRGB 5 <"),
        "the lookup rides inline as a byte string (§8.6.6.3 permits a stream \
         OR a string, and a 18-byte table does not deserve its own object): {}",
        String::from_utf8_lossy(&body)
    );
    assert!(
        contains(&body, b"/Colors 1"),
        "an Indexed image has ONE component — the index — however many the \
         base space has"
    );
}

// ---------------------------------------------------------------------------
// Placement geometry
// ---------------------------------------------------------------------------

/// `Stretch` honours the rectangle exactly and produces §8.9.4's own
/// `w 0 0 h x y cm` form.
#[test]
fn stretch_places_the_image_in_exactly_the_rectangle_asked_for() {
    let img = imported("rgb8.png");
    let mut s = session();
    let r = rect(100.0, 200.0, 250.0, 280.0);
    let out = s
        .add_image(&NewImage::new(0, r, &img).stretching())
        .unwrap();
    assert_eq!(out.placed_rect, r);

    let pdf = saved(&mut s);
    let content = stream_payload(&object_body(&pdf, out.content_id.num));
    let text = String::from_utf8_lossy(&content).to_string();
    assert!(
        text.contains("150 0 0 80 100 200 cm"),
        "§8.9.4's own example form — width, height, then the lower-left \
         corner: {text}"
    );
    assert!(
        text.contains(&format!(
            "/{} Do",
            String::from_utf8_lossy(&out.resource_name)
        )),
        "{text}"
    );
    assert!(
        text.starts_with('q') && text.trim_end().ends_with('Q'),
        "§8.4: q/Q shall be balanced, and the image's CTM must not leak into \
         whatever the page draws next: {text}"
    );
    // 6 px across 150 pt = 2.88 dpi.
    assert!(
        out.disclosures.aspect_distorted,
        "6:4 stretched into 150:80"
    );
    assert!(out.disclosures.below_screen_resolution);
}

/// `Contain` — the default — preserves the aspect ratio and centres, and
/// says so.
#[test]
fn contain_preserves_the_aspect_ratio_and_centres() {
    let img = imported("rgb8.png"); // 6 × 4, aspect 1.5
    let mut s = session();
    // A 300 × 100 box: height is the binding constraint, so the image is
    // 150 × 100 and gets 75 points of slack on each side.
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 300.0, 100.0), &img))
        .unwrap();
    let p = out.placed_rect;
    assert!((p.llx - 75.0).abs() < 1e-9, "{p:?}");
    assert!((p.urx - 225.0).abs() < 1e-9, "{p:?}");
    assert!((p.lly - 0.0).abs() < 1e-9, "{p:?}");
    assert!((p.ury - 100.0).abs() < 1e-9, "{p:?}");
    assert!(out.disclosures.letterboxed);
    assert!(!out.disclosures.aspect_distorted);

    let pdf = saved(&mut s);
    let content = stream_payload(&object_body(&pdf, out.content_id.num));
    assert!(
        contains(&content, b"150 0 0 100 75 0 cm"),
        "{}",
        String::from_utf8_lossy(&content)
    );
}

/// A rectangle that already matches the aspect ratio is NOT reported as
/// letterboxed — a disclosure that fires on every placement is a
/// disclosure nobody reads.
#[test]
fn a_matching_rectangle_reports_no_letterboxing() {
    let img = imported("rgb8.png");
    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 150.0, 100.0), &img))
        .unwrap();
    assert!(!out.disclosures.letterboxed);
    assert!(!out.disclosures.any() || out.disclosures.below_screen_resolution);
}

/// An EXIF orientation is applied to the PLACEMENT MATRIX, and the
/// codestream is still verbatim. A rotate-90 photograph must come out
/// upright without a single pixel being re-encoded.
#[test]
fn an_exif_orientation_turns_the_placement_not_the_pixels() {
    let source = image_bytes("exif-rot90.jpg");
    let img = image_import::import(&source).unwrap();
    assert_eq!(img.orientation, Orientation::Rotate90);
    assert_eq!(
        img.display_size_px(),
        (4, 6),
        "a stored 6 × 4 turned 90° displays as 4 × 6"
    );

    let mut s = session();
    // A square box: `Contain` fits the DISPLAYED 4 × 6 shape, so the result
    // is taller than wide.
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 120.0, 120.0), &img))
        .unwrap();
    let p = out.placed_rect;
    assert!((p.urx - p.llx - 80.0).abs() < 1e-9, "{p:?}");
    assert!((p.ury - p.lly - 120.0).abs() < 1e-9, "{p:?}");
    assert_eq!(out.disclosures.exif_orientation_applied, Some(6));

    let pdf = saved(&mut s);
    assert_eq!(
        stream_payload(&object_body(&pdf, out.image_id.num)),
        source,
        "the rotation cost nothing — the codestream is untouched"
    );
    let content = stream_payload(&object_body(&pdf, out.content_id.num));
    // O6 = [0 -1 1 0 0 1]; w = 80, h = 120, origin (20, 0).
    //   a = 0·80 = 0     b = -1·120 = -120   c = 1·80 = 80
    //   d = 0·120 = 0    e = 0·80 + 20 = 20  f = 1·120 + 0 = 120
    assert!(
        contains(&content, b"0 -120 80 0 20 120 cm"),
        "{}",
        String::from_utf8_lossy(&content)
    );
}

/// A rectangle with no area is refused rather than producing a singular
/// transform every reader resolves differently.
#[test]
fn a_degenerate_rectangle_is_refused() {
    let img = imported("rgb8.png");
    let mut s = session();
    for r in [rect(10.0, 10.0, 10.0, 50.0), rect(10.0, 10.0, 50.0, 10.0)] {
        assert!(matches!(
            s.add_image(&NewImage::new(0, r, &img)),
            Err(EditError::ImageRectDegenerate { .. })
        ));
    }
    assert!(!s.is_modified(), "a refusal changes nothing");
}

#[test]
fn a_page_out_of_range_is_refused_by_index() {
    let img = imported("rgb8.png");
    let mut s = session();
    assert!(matches!(
        s.add_image(&NewImage::new(7, rect(0.0, 0.0, 10.0, 10.0), &img)),
        Err(EditError::PageOutOfRange { index: 7, count: 1 })
    ));
}

// ---------------------------------------------------------------------------
// Document wiring, round trip, undo
// ---------------------------------------------------------------------------

/// All four writes land: the resource names the image, the content invokes
/// that name, and the page's ORIGINAL content stream is still listed and
/// still byte-identical.
///
/// The third clause is R46: a feature that adds page content must not
/// rewrite the content that was already there.
#[test]
fn the_image_is_named_invoked_and_the_original_content_is_untouched() {
    let before = std::fs::read(fixture("dimension/plain-base.pdf")).unwrap();
    let img = imported("rgb8.png");
    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &img))
        .unwrap();

    // The name is in the page's effective /Resources /XObject…
    let xobj = page_xobjects(&s, 0);
    assert_eq!(
        xobj.get(out.resource_name.as_slice())
            .and_then(Object::as_reference),
        Some(out.image_id),
        "the resource entry points at the image object"
    );

    let pdf = saved(&mut s);
    // …the content stream invokes exactly that name…
    let content = stream_payload(&object_body(&pdf, out.content_id.num));
    assert!(contains(
        &content,
        &[b"/", out.resource_name.as_slice(), b" Do"].concat()
    ));

    // …the page's /Contents lists BOTH streams, in order…
    let page_body = object_body(&pdf, 3);
    assert!(
        contains(
            &page_body,
            format!("/Contents [4 0 R {} 0 R]", out.content_id.num).as_bytes()
        ),
        "the overlay is APPENDED, so it draws on top of what was there: {}",
        String::from_utf8_lossy(&page_body)
    );

    // …and the original content stream object is byte-identical, because
    // the incremental save never re-emitted it (R46, ARCHITECTURE.md §5).
    assert_eq!(
        pdf.get(..before.len()),
        Some(before.as_slice()),
        "an incremental save appends; it never rewrites the input prefix"
    );
    assert!(
        !contains(pdf.get(before.len()..).unwrap_or_default(), b"\n4 0 obj"),
        "object 4 — the page's original content stream — was not touched, so \
         it must not appear in the update section at all"
    );
}

/// The saved file reloads, the image decodes through pdfcer's ordinary image
/// pipeline, and the samples are the ones that went in. This is the
/// end-to-end round trip: file → import → place → save → reload → decode.
#[test]
fn the_document_round_trips_and_the_image_decodes() {
    for name in [
        "rgb8.png",
        "gray8.png",
        "indexed8.png",
        "indexed4.png",
        "gray16.png",
        "rgb.jpg",
        "gray.jpg",
        "progressive.jpg",
        "rgb24.bmp",
        "pal8.bmp",
        "topdown24.bmp",
        "rgba8.png",
        "graya8.png",
    ] {
        let img = imported(name);
        let mut s = session();
        let out = s
            .add_image(&NewImage::new(0, rect(0.0, 0.0, 120.0, 80.0), &img))
            .unwrap_or_else(|e| panic!("{name}: {e}"));
        let pdf = saved(&mut s);
        let (doc, dict, raw) = reloaded_image(&pdf, out.image_id);

        let coded = pdfcer_core::image_codec::decode_image(&doc, &dict, &raw, false)
            .unwrap_or_else(|e| panic!("{name} does not decode after a round trip: {e}"));
        assert_eq!(coded.width, img.width, "{name} width");
        assert_eq!(coded.height, img.height, "{name} height");
    }
}

/// Undo removes every trace, and re-saving reproduces the input byte for
/// byte — the property §11.1's diff-against-base design exists to give.
#[test]
fn undoing_a_placement_reproduces_the_input_byte_for_byte() {
    let before = std::fs::read(fixture("dimension/plain-base.pdf")).unwrap();
    let img = imported("rgba8.png");
    let mut s = session();
    s.add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &img))
        .unwrap();
    assert!(s.is_modified());

    assert!(s.undo().is_some(), "one placement is ONE undo entry");
    assert!(
        !s.is_modified(),
        "the image XObject, the /SMask, the content stream and BOTH page-dict \
         patches undo together — a partial undo would leave a page naming an \
         object that no longer exists"
    );
    assert_eq!(saved(&mut s), before);

    // …and redo puts it back.
    assert!(s.redo().is_some());
    assert!(s.is_modified());
}

/// Two images on one page get distinct resource names and both survive —
/// the second must not shadow the first.
#[test]
fn two_images_on_one_page_get_distinct_names() {
    let a = imported("rgb8.png");
    let b = imported("gray8.png");
    let mut s = session();
    let first = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &a))
        .unwrap();
    let second = s
        .add_image(&NewImage::new(0, rect(100.0, 0.0, 160.0, 40.0), &b))
        .unwrap();
    assert_ne!(first.resource_name, second.resource_name);

    let xobj = page_xobjects(&s, 0);
    assert_eq!(
        xobj.get(first.resource_name.as_slice())
            .and_then(Object::as_reference),
        Some(first.image_id)
    );
    assert_eq!(
        xobj.get(second.resource_name.as_slice())
            .and_then(Object::as_reference),
        Some(second.image_id)
    );

    let pdf = saved(&mut s);
    let page_body = object_body(&pdf, 3);
    assert!(
        contains(&page_body, b"/Contents [4 0 R "),
        "both overlays are appended to the ONE /Contents array: {}",
        String::from_utf8_lossy(&page_body)
    );
}

/// A page whose `/Resources` are inherited must get its OWN, so the
/// addition does not leak the image into every sibling page (§7.7.3.4).
#[test]
fn an_inherited_resource_dictionary_is_materialised_onto_the_page() {
    let doc = Document::load(&fixture("addtext/inherited-resources.pdf")).expect("fixture");
    let mut s = EditSession::new(doc);
    let img = imported("rgb8.png");
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &img))
        .unwrap();
    let xobj = page_xobjects(&s, 0);
    assert_eq!(
        xobj.get(out.resource_name.as_slice())
            .and_then(Object::as_reference),
        Some(out.image_id)
    );
}

// ---------------------------------------------------------------------------
// Refusals — every one by name, with the working formats named too
// ---------------------------------------------------------------------------

/// A format pdfcer does not place is refused by NAME, and the message says
/// which formats do work. A silent failure, or a wrong-looking placement,
/// would both be worse.
#[test]
fn an_unsupported_format_refuses_by_name() {
    // TIFF WAS in this list and has been removed, because TIFF is now
    // imported rather than refused. The stub bytes it used —
    // `II\x2a\x00\x08\x00\x00\x00` — are a valid little-endian TIFF
    // header whose first directory offset points past the end, so they now
    // reach the decoder and come back as `Corrupt`, which is the right
    // answer to a truncated TIFF and the wrong one for this test.
    //
    // Noted rather than silently deleted: a refusal test shrinking is
    // normally a red flag (it is how coverage quietly erodes), and the
    // distinction between "we stopped refusing this because we support it"
    // and "we stopped refusing this because something broke" is exactly
    // what a future reader needs. The support is pinned in
    // `tests/image_tiff.rs`.
    for (bytes, format) in [
        (b"GIF89a\x01\x00\x01\x00".to_vec(), "GIF"),
        (b"RIFF\x00\x00\x00\x00WEBPVP8 ".to_vec(), "WebP"),
    ] {
        let err = image_import::import(&bytes).unwrap_err();
        assert_eq!(err, ImageImportError::UnsupportedFormat { format });
        let msg = err.to_string();
        assert!(msg.contains(format), "{msg}");
        assert!(msg.contains(SUPPORTED_FORMATS), "{msg}");
    }

    let err = image_import::import(&image_bytes("not-an-image.bin")).unwrap_err();
    assert_eq!(err, ImageImportError::NotAnImage);
    assert!(err.to_string().contains(SUPPORTED_FORMATS));
}

/// Sub-features of supported formats are refused with a stable key, so a
/// front end can explain the specific thing rather than "could not read
/// image".
#[test]
fn unsupported_sub_features_refuse_with_a_stable_key() {
    for (file, feature) in [
        ("interlaced.png", "PNG/interlaced"),
        ("arithmetic.jpg", "JPEG/arithmetic"),
        ("rle8.bmp", "BMP/rle8"),
    ] {
        assert_eq!(
            image_import::import(&image_bytes(file)).unwrap_err(),
            ImageImportError::Unsupported { feature },
            "{file}"
        );
    }
}

// ---------------------------------------------------------------------------
// Disclosures
// ---------------------------------------------------------------------------

/// R30's shape, mirrored onto the write direction: a CMYK JPEG whose
/// polarity nothing declares is embedded unchanged (R29) and NAMED.
#[test]
fn a_cmyk_jpeg_is_embedded_unchanged_and_its_polarity_is_named() {
    let source = image_bytes("cmyk.jpg");
    let img = image_import::import(&source).unwrap();
    assert!(img.notes.cmyk_polarity_unverifiable);

    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &img))
        .unwrap();
    assert!(out.disclosures.cmyk_polarity_unverifiable);

    let pdf = saved(&mut s);
    let body = object_body(&pdf, out.image_id.num);
    assert_eq!(stream_payload(&body), source);
    assert!(contains(&body, b"/ColorSpace /DeviceCMYK"));
    assert!(
        !contains(&body, b"/Decode"),
        "R29: no inversion, ever, on any branch"
    );
}

/// A BMP always reports that it was re-compressed, and a 32-bit one reports
/// that its fourth byte was ignored.
#[test]
fn a_bmp_discloses_its_recompression_and_its_ignored_fourth_byte() {
    let img = imported("rgb32.bmp");
    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &img))
        .unwrap();
    assert_eq!(
        out.disclosures.recompressed,
        Some(RecompressReason::NoCompressedSource)
    );
    assert!(out.disclosures.bmp_fourth_byte_ignored);
    assert!(!out.disclosures.soft_mask_written, "BI_RGB has no alpha");
}

/// A feature newer than the document's own version is disclosed rather than
/// silently upgrading `%PDF-x.y`.
#[test]
fn a_feature_newer_than_the_document_is_disclosed() {
    // A minimal PDF 1.3 document — old enough that a 16-bit image (PDF 1.5)
    // is ahead of it. Built with a real §7.5.4 cross-reference table rather
    // than left for the recovery path, because a RECOVERED base refuses an
    // incremental save (and rightly so), and the header check below has to
    // run over an incremental output.
    let doc = Document::from_bytes(minimal_pdf("1.3")).expect("a valid 1.3 document");
    let mut s = EditSession::new(doc);
    let img = imported("gray16.png");
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &img))
        .unwrap();
    let (feature, doc_version) = out
        .disclosures
        .version_ahead_of_document
        .expect("16 bpc is a PDF 1.5 feature in a PDF 1.3 file");
    assert_eq!(feature, PdfFeature::BitsPerComponent16);
    assert_eq!(doc_version.major, 1);
    assert_eq!(doc_version.minor, 3);

    // …and the header is NOT rewritten.
    let pdf = saved(&mut s);
    assert!(pdf.starts_with(b"%PDF-1.3"), "the header is left alone");
}

/// The same image in a modern document reports nothing about versions —
/// the disclosure fires on a real mismatch, not on the feature's existence.
#[test]
fn a_modern_document_reports_no_version_mismatch() {
    let img = imported("gray16.png");
    let mut s = session(); // %PDF-1.7
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &img))
        .unwrap();
    assert!(out.disclosures.version_ahead_of_document.is_none());
}

/// The effective resolution is reported as a number, and the
/// below-72-dpi flag fires only when the image is genuinely being enlarged
/// past its own resolution.
#[test]
fn the_effective_resolution_is_reported() {
    let img = imported("rgb8.png"); // 6 × 4 px
    let mut s = session();
    // 6 px across 6 points = 72 dpi exactly.
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 6.0, 4.0), &img).stretching())
        .unwrap();
    let (dx, dy) = out.disclosures.effective_dpi;
    assert!((dx - 72.0).abs() < 1e-9, "{dx}");
    assert!((dy - 72.0).abs() < 1e-9, "{dy}");
    assert!(!out.disclosures.below_screen_resolution);

    // Twice the size is half the resolution.
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 12.0, 8.0), &img).stretching())
        .unwrap();
    assert!((out.disclosures.effective_dpi.0 - 36.0).abs() < 1e-9);
    assert!(out.disclosures.below_screen_resolution);
}

/// A tagged document is disclosed: pdfcer writes no structure element for
/// the image, so it has no alternate text and assistive technology cannot
/// describe it.
#[test]
fn a_tagged_document_is_disclosed() {
    let doc = Document::load(&fixture("addtext/tagged.pdf")).expect("fixture");
    let mut s = EditSession::new(doc);
    let img = imported("rgb8.png");
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &img))
        .unwrap();
    assert!(out.disclosures.tagged_document);
    assert!(out.disclosures.any());
}

/// A certified document refuses placement by name — placing an image
/// changes what the page renders, so it takes the strict gate.
#[test]
fn a_certified_document_refuses_placement() {
    let doc = Document::load(&fixture("addtext/certified-locked.pdf")).expect("fixture");
    let mut s = EditSession::new(doc);
    let img = imported("rgb8.png");
    assert!(matches!(
        s.add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &img)),
        Err(EditError::CertificationForbidsChange { .. })
    ));
    assert!(!s.is_modified());
}

/// `any()` must answer for every field. A disclosure struct that grows a
/// field the summary predicate forgets is a disclosure that silently stops
/// being shown — so the two are pinned together here.
#[test]
fn an_ordinary_placement_with_nothing_to_say_says_nothing() {
    let img = imported("rgb8.png");
    let mut s = session();
    // Exactly 72 dpi, exact aspect ratio, no transparency, no profile, a
    // modern untagged document: there is genuinely nothing to disclose.
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 6.0, 4.0), &img))
        .unwrap();
    assert!(
        !out.disclosures.any(),
        "nothing was inferred, so nothing is claimed: {:?}",
        out.disclosures
    );
}

/// Every fixture in the corpus either imports or refuses by name — never a
/// panic, never a generic failure. The cheapest possible guard against a
/// parser that walks off the end of a real file.
#[test]
fn every_fixture_either_imports_or_refuses_by_name() {
    let dir = fixture("images");
    let mut seen = 0usize;
    for entry in std::fs::read_dir(&dir).expect("the fixture directory exists") {
        let path = entry.expect("dir entry").path();
        // ★ A SUBDIRECTORY IS NOT A FIXTURE, AND WITHOUT THIS LINE IT KILLS
        // THIS TEST WITH A MESSAGE THAT NAMES THE WRONG PROBLEM.
        //
        // `std::fs::read` on a directory fails with `PermissionDenied` /
        // "Access is denied." on Windows, so the panic reads as a filesystem
        // rights problem and sends the reader after their antivirus rather
        // than after the directory.
        //
        // Measured 2026-08-27: `tools/check-image-colorspace-truth.py` writes
        // a `_truth/` subdirectory beside the images it scores, and pointing
        // that gate at this corpus is the obvious thing to do — so RUNNING ONE
        // OF THIS PROJECT'S OWN GATES BROKE ONE OF ITS OWN TESTS. Skipping
        // directories is the fix; `.gitignore` would not have helped, because
        // the failure is on disk and has nothing to do with what is tracked.
        if path.is_dir() {
            continue;
        }
        let bytes =
            std::fs::read(&path).unwrap_or_else(|e| panic!("read fixture {}: {e}", path.display()));
        seen += 1;
        match image_import::import(&bytes) {
            Ok(img) => {
                assert!(img.width > 0 && img.height > 0, "{path:?}");
                assert!(!img.data.is_empty(), "{path:?}");
            }
            Err(
                ImageImportError::Unsupported { .. }
                | ImageImportError::UnsupportedFormat { .. }
                | ImageImportError::NotAnImage,
            ) => {}
            Err(other) => panic!("{path:?} failed unhelpfully: {other}"),
        }
    }
    assert!(
        seen >= 20,
        "the fixture corpus shrank unexpectedly ({seen})"
    );
}

/// The names pdfcer gives its own resources are recognisable in the saved
/// file — a small thing, but it is what lets a later Pass (or a human
/// reading the PDF) tell pdfcer's additions from the producer's.
#[test]
fn authored_resources_carry_the_pdfcer_prefix() {
    let img = imported("rgb8.png");
    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &img))
        .unwrap();
    assert!(
        out.resource_name.starts_with(b"pdfceIm"),
        "{:?}",
        String::from_utf8_lossy(&out.resource_name)
    );
    let _ = Name::from(out.resource_name.as_slice());
}

// ---------------------------------------------------------------------------
// Compression policy (per image; operator request, 2026-08-08)
// ---------------------------------------------------------------------------

fn imported_as(name: &str, compression: ImageCompression) -> ImportedImage {
    let options = ImportOptions::new().with_compression(compression);
    image_import::import_with(&image_bytes(name), &options)
        .unwrap_or_else(|e| panic!("import images/{name}: {e}"))
}

/// The default is passthrough, and the default is what an operator who says
/// nothing gets. Pinned as its own test because a default that quietly
/// changed would degrade every image in every document with no diff to read.
#[test]
fn the_default_policy_is_passthrough() {
    let img = imported("rgb.jpg");
    assert_eq!(
        img.notes.requested_compression,
        ImageCompression::Passthrough
    );
    assert_eq!(img.notes.applied_compression, ImageCompression::Passthrough);
    assert_eq!(img.data, image_bytes("rgb.jpg"));
    assert_eq!(ImportOptions::new(), ImportOptions::default());
}

/// `Lossless` on a JPEG is the ONE combination that changes the bytes: the
/// codestream is decoded and its samples stored as `/FlateDecode`.
#[test]
fn lossless_on_a_jpeg_decodes_and_stores_the_samples() {
    let img = imported_as("rgb.jpg", ImageCompression::Lossless);
    assert_eq!(img.filter, ImportFilter::Flate);
    assert_eq!(
        img.notes.recompressed,
        Some(RecompressReason::LosslessRequested)
    );
    assert_eq!(img.notes.applied_compression, ImageCompression::Lossless);
    assert!(
        img.notes.lossless_from_lossy,
        "the operator must be told that this recovers nothing"
    );
    assert_ne!(img.data, image_bytes("rgb.jpg"), "the bytes changed");

    // The stream really is the decoded samples: 6 x 4 RGB at 8 bits.
    let samples = pdfcer_core::filters::flate::decode(&img.data, None).unwrap();
    assert_eq!(samples.len(), 6 * 4 * 3);

    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &img))
        .unwrap();
    assert!(out.disclosures.lossless_from_lossy);
    assert_eq!(
        out.disclosures.applied_compression,
        ImageCompression::Lossless
    );
    let pdf = saved(&mut s);
    let body = object_body(&pdf, out.image_id.num);
    assert!(contains(&body, b"/Filter /FlateDecode"), "{body:?}");
    assert!(!contains(&body, b"DCTDecode"));
}

/// A CMYK JPEG stored losslessly keeps `DeviceCMYK` and is still NOT
/// inverted (R29) — the decode path applies the Table 13 / TN #5116 §13.1
/// transform and nothing else, so the lossless branch cannot become a back
/// door for the polarity flip decision 006 forbids.
#[test]
fn lossless_on_a_cmyk_jpeg_keeps_devicecmyk_and_does_not_invert() {
    let img = imported_as("cmyk.jpg", ImageCompression::Lossless);
    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &img))
        .unwrap();
    let pdf = saved(&mut s);
    let body = object_body(&pdf, out.image_id.num);
    assert!(contains(&body, b"/ColorSpace /DeviceCMYK"), "{body:?}");
    assert!(
        !contains(&body, b"/Decode"),
        "R29 holds on every branch, including this one"
    );
    let samples = pdfcer_core::filters::flate::decode(&img.data, None).unwrap();
    assert_eq!(samples.len(), 6 * 4 * 4, "four components per sample");
}

/// `Lossless` on a source that was ALREADY lossless keeps the source's own
/// bytes and reports the substitution. Re-deflating identical pixels is
/// strictly worse than not doing it, and silently doing the worse thing
/// because it matched the word the operator typed would be the wrong kind of
/// literal-mindedness.
#[test]
fn lossless_on_an_already_lossless_source_keeps_the_original_bytes() {
    let img = imported_as("rgb8.png", ImageCompression::Lossless);
    assert_eq!(img.data, extract_idat(&image_bytes("rgb8.png")));
    assert_eq!(img.notes.requested_compression, ImageCompression::Lossless);
    assert_eq!(
        img.notes.applied_compression,
        ImageCompression::Passthrough,
        "applied == Passthrough means, and only means, that the source's own \
         compressed bytes are in the document unchanged"
    );

    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &img))
        .unwrap();
    assert_ne!(
        out.disclosures.requested_compression,
        out.disclosures.applied_compression
    );
    assert!(
        out.disclosures.any(),
        "a substituted policy is always worth saying"
    );
}

/// `Passthrough` on a format with nothing to pass through reports the
/// substitution in the other direction.
#[test]
fn passthrough_on_a_bmp_reports_that_it_could_not_happen() {
    let img = imported("rgb24.bmp");
    assert_eq!(
        img.notes.requested_compression,
        ImageCompression::Passthrough
    );
    assert_eq!(
        img.notes.applied_compression,
        ImageCompression::Lossless,
        "a BMP stores no compressed bytes, so there was nothing to keep"
    );
    assert!(
        !img.notes.lossless_from_lossy,
        "a BMP is not a lossy source"
    );
}

/// A PNG whose alpha forced a split is reported as `Lossless`, not
/// `Passthrough` — the requested policy could not be honoured literally even
/// though nothing was degraded.
#[test]
fn a_split_alpha_png_reports_lossless_rather_than_passthrough() {
    let img = imported("rgba8.png");
    assert_eq!(img.notes.applied_compression, ImageCompression::Lossless);
    assert_eq!(img.notes.recompressed, Some(RecompressReason::AlphaSplit));
    assert!(!img.notes.lossless_from_lossy);
}

// ---------------------------------------------------------------------------
// `ImageCompression::Jpeg` — the re-encode
//
// Every assertion here is deliberately at the level a structural check
// cannot reach. The failure modes this policy has are: a picture that comes
// out inverted (renders fine, looks deliberate, decision 006), a quality knob
// that does nothing, a clamp nobody was told about, and — the regression that
// would matter most — a new code path that disturbs the verbatim passthrough
// the rest of the module exists to protect.
// ---------------------------------------------------------------------------

/// Decode a bare `/DCTDecode` codestream exactly the way `pdfcer-render`
/// would, so a test can compare PIXELS rather than bytes.
///
/// Goes through `image_codec` rather than any second decoder for the reason
/// **R31** gives: a reference decoder that applies its own normalisation is
/// how a polarity investigation gets a confident wrong answer (Pillow's
/// `CMYK;I`, the `jpeg-decoder` crate's unconditional four-component
/// inversion). The only decoder whose conventions are already established
/// here is pdfcer's own — and it is also the one whose output actually
/// determines what an operator sees.
fn decode_dct(data: &[u8]) -> pdfcer_core::image_codec::CodedImage {
    struct NoGraph;
    impl ObjectGraph for NoGraph {
        fn value(&self, _id: ObjId) -> Option<&Object> {
            None
        }
        fn trailer_entry(&self, _key: &[u8]) -> Option<&Object> {
            None
        }
    }
    let mut dict = Dict::new();
    dict.insert(
        Name::from(b"Filter"),
        Object::Name(Name::from(b"DCTDecode")),
    );
    let graph = NoGraph;
    let view = pdfcer_core::view::DocumentView::new(
        &graph,
        &[],
        pdfcer_core::PdfVersion { major: 1, minor: 7 },
    );
    pdfcer_core::image_codec::decode_image_view(&view, &dict, data, false)
        .expect("the re-encoded codestream must decode")
}

/// The Adobe APP14 `ColorTransform` byte in a codestream, or `None` if the
/// marker is absent.
///
/// Walked rather than searched for the literal `b"Adobe"` anywhere in the
/// file, because entropy-coded scan data can contain any byte sequence at
/// all and a naive search would happily "find" a marker inside the picture.
fn app14_transform(jpeg: &[u8]) -> Option<u8> {
    let mut i = 2; // past SOI
    while i + 4 <= jpeg.len() {
        if jpeg[i] != 0xFF {
            return None;
        }
        let marker = jpeg[i + 1];
        // SOS: everything after this is entropy-coded; stop walking.
        if marker == 0xDA {
            return None;
        }
        let len = usize::from(u16::from_be_bytes([jpeg[i + 2], jpeg[i + 3]]));
        if marker == 0xEE {
            let seg = jpeg.get(i + 4..i + 2 + len)?;
            // TN #5116 §18: `Adobe` (5 bytes), version (2), flags0 (2),
            // flags1 (2), then the one-byte colour transform code.
            if seg.starts_with(b"Adobe") {
                return seg.get(11).copied();
            }
        }
        i += 2 + len;
    }
    None
}

/// The pixels an [`ImportedImage`]'s stored stream decodes to, through
/// pdfcer's own filter stack.
///
/// Not `flate::decode` directly: a verbatim `IDAT` passthrough is a
/// `/Predictor 15` stream, so inflating it without un-predicting leaves the
/// per-row filter-type bytes in place and every sample offset by its
/// neighbour. Comparing against *that* would make a correct encoder look
/// broken (and, worse, could make a broken one look correct).
fn stored_samples(img: &ImportedImage) -> Vec<u8> {
    let mut dict = Dict::new();
    let flate = || Object::Name(Name::from(b"FlateDecode"));
    match img.filter {
        ImportFilter::DctDecode => return decode_dct(&img.data).samples,
        ImportFilter::Flate => {
            dict.insert(Name::from(b"Filter"), flate());
        }
        ImportFilter::FlatePngPredictor {
            colors,
            bits_per_component,
            columns,
        } => {
            dict.insert(Name::from(b"Filter"), flate());
            let mut parms = Dict::new();
            parms.insert(Name::from(b"Predictor"), Object::Integer(15));
            parms.insert(Name::from(b"Colors"), Object::Integer(i64::from(colors)));
            parms.insert(
                Name::from(b"BitsPerComponent"),
                Object::Integer(i64::from(bits_per_component)),
            );
            parms.insert(Name::from(b"Columns"), Object::Integer(i64::from(columns)));
            dict.insert(Name::from(b"DecodeParms"), Object::Dict(parms));
        }
        other => panic!("stored_samples does not know filter {other:?}"),
    }
    pdfcer_core::filters::decode_stream(&dict, &img.data).expect("the stored stream decodes")
}

/// Mean absolute difference per sample between two equal-length buffers.
fn mean_abs_diff(a: &[u8], b: &[u8]) -> f64 {
    assert_eq!(a.len(), b.len(), "buffers must be comparable");
    let total: u64 = a
        .iter()
        .zip(b)
        .map(|(&x, &y)| u64::from(x.abs_diff(y)))
        .sum();
    total as f64 / a.len() as f64
}

/// The quality knob does something, and what it does is monotone in size
/// while both results still resemble the source.
///
/// Two halves, and both are needed. A knob that changes nothing would pass
/// a "the pixels are close" test trivially; a knob wired to the wrong thing
/// could change the size while destroying the picture. Asserting both pins
/// the encoder as *doing lossy compression at a selectable rate* rather than
/// merely producing bytes.
#[test]
fn two_jpeg_qualities_differ_in_size_and_both_resemble_the_source() {
    let low = imported_as("rgb8.png", ImageCompression::Jpeg { quality: 20 });
    let high = imported_as("rgb8.png", ImageCompression::Jpeg { quality: 95 });

    assert_eq!(low.filter, ImportFilter::DctDecode);
    assert_eq!(high.filter, ImportFilter::DctDecode);
    assert!(
        low.data.len() < high.data.len(),
        "quality 20 must store fewer bytes than quality 95 ({} vs {})",
        low.data.len(),
        high.data.len()
    );
    assert_eq!(low.notes.jpeg_quality, Some(20));
    assert_eq!(high.notes.jpeg_quality, Some(95));
    assert_eq!(
        high.notes.applied_compression,
        ImageCompression::Jpeg { quality: 95 },
        "the applied policy carries the quality that actually ran"
    );

    // The source's exact pixels are the reference. `rgb8.png` is lossless
    // either way, so its stored stream IS the truth to compare against.
    let exact = imported_as("rgb8.png", ImageCompression::Lossless);
    let reference = stored_samples(&exact);

    for (name, img, tolerance) in [("q20", &low, 48.0), ("q95", &high, 12.0)] {
        let got = decode_dct(&img.data);
        assert_eq!(got.width, exact.width, "{name}");
        assert_eq!(got.height, exact.height, "{name}");
        assert_eq!(got.bits_per_component, 8, "{name}: Table 89 fixes DCT at 8");
        let delta = mean_abs_diff(&got.samples, &reference);
        assert!(
            delta < tolerance,
            "{name}: mean |Δ| per sample was {delta:.2}, which is not 'approximately the source'"
        );
    }

    // Both are lossy, but neither source was: the compounding disclosure
    // must stay OFF here, or it means nothing when it comes on.
    assert!(!low.notes.jpeg_from_lossy);
    assert!(!high.notes.jpeg_from_lossy);
    assert_eq!(
        low.notes.recompressed,
        Some(RecompressReason::JpegRequested)
    );
}

/// **THE POLARITY TEST.** Re-encoding a CMYK image must not turn it into a
/// photographic negative.
///
/// Asserted in SAMPLE VALUES, not in the presence of a `/Decode` array,
/// because that is the only place the bug lives. Decision 006 §1.3: getting
/// this wrong produces an inverse that renders cleanly, warns about nothing,
/// and cannot be spotted by a reviewer who has not seen the original. A
/// structural check would pass on every one of those files.
///
/// The invariant is round-trip stability through pdfcer's own decoder:
/// whatever ink `pdfcer-render` reads out of the source, it must read
/// approximately the same ink out of the re-encode. An inversion would show
/// as a mean |Δ| near the complement instead of near zero.
#[test]
fn re_encoding_a_cmyk_jpeg_keeps_its_ink_polarity() {
    let source = imported("cmyk.jpg");
    let before = decode_dct(&source.data);

    let re = imported_as("cmyk.jpg", ImageCompression::Jpeg { quality: 95 });
    assert_eq!(
        re.color_space,
        pdfcer_core::image_import::ImportColorSpace::DeviceCmyk
    );
    assert_eq!(re.filter, ImportFilter::DctDecode);

    // The written codestream is the TRANSFORM-2 (YCCK) shape — decision
    // 006 §4.4's benign census, not R30's ambiguous transform-0 shape. A
    // writer that emits the shape its own diagnostic warns about has misread
    // its rules.
    assert_eq!(
        app14_transform(&re.data),
        Some(2),
        "the re-encode must declare YCCK in its Adobe APP14 marker"
    );
    assert!(
        !re.notes.cmyk_polarity_unverifiable,
        "transform 2 is never the polarity-ambiguous shape"
    );

    let after = decode_dct(&re.data);
    assert_eq!(after.components, 4, "four ink channels, still");
    assert_eq!(after.width, before.width);
    assert_eq!(after.height, before.height);

    let delta = mean_abs_diff(&after.samples, &before.samples);
    let complement: Vec<u8> = before.samples.iter().map(|&v| 255 - v).collect();
    let inverted_delta = mean_abs_diff(&after.samples, &complement);
    assert!(
        delta < 16.0,
        "the re-encode must decode to approximately the same INK: mean |Δ| was {delta:.2}"
    );
    assert!(
        inverted_delta > 4.0 * delta.max(1.0),
        "and must be nowhere near its complement (|Δ| to source {delta:.2}, \
         |Δ| to complement {inverted_delta:.2}) — this is the photographic-negative check"
    );

    // NAMED PIXEL VALUES, in the tradition decision 006 §6.4 asked for.
    // `cmyk.jpg`'s top-left pixel is a saturated corner, which is exactly
    // where an inversion is unmistakable: the complement of [0, 0, 255, 255]
    // is [255, 255, 0, 0], and no tolerance can confuse the two.
    assert_eq!(
        &before.samples[0..4],
        &[0, 0, 255, 255],
        "the fixture's top-left ink, as pdfcer reads it today"
    );
    for c in 0..4 {
        assert!(
            after.samples[c].abs_diff(before.samples[c]) <= 4,
            "top-left component {c}: {} became {} — an inversion would read {}",
            before.samples[c],
            after.samples[c],
            255 - before.samples[c]
        );
    }

    // The rest of the named pixels, so a regression reports WHICH ink moved
    // rather than an aggregate that could hide a single blown channel.
    for px in [0usize, 1, 5] {
        for c in 0..4 {
            let i = px * 4 + c;
            let (b, a) = (before.samples[i], after.samples[i]);
            assert!(
                b.abs_diff(a) <= 40,
                "pixel {px} component {c}: {b} became {a}, which is not the same ink"
            );
        }
    }

    // No `/Decode` is written on any branch. R29 says `/Decode` is the sole
    // polarity control; this writer's output needs no polarity control at
    // all, and inventing one would be the start of the argument decision 006
    // closed.
    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &re))
        .unwrap();
    let pdf = saved(&mut s);
    let body = object_body(&pdf, out.image_id.num);
    assert!(contains(&body, b"/ColorSpace /DeviceCMYK"), "{body:?}");
    assert!(contains(&body, b"/Filter /DCTDecode"), "{body:?}");
    assert!(contains(&body, b"/BitsPerComponent 8"), "{body:?}");
    assert!(!contains(&body, b"/Decode"), "R29 holds on every branch");
    assert_eq!(
        stream_payload(&body),
        re.data,
        "the codestream reaches the file intact"
    );
}

/// A quality outside 1–100 is REFUSED BY NAME, not clamped — and refused
/// before the file is parsed, so the operator hears about their flag rather
/// than about their picture.
#[test]
fn an_out_of_range_jpeg_quality_is_refused_rather_than_clamped() {
    for quality in [0u8, 101, 255] {
        let options = ImportOptions::new().with_compression(ImageCompression::Jpeg { quality });
        let err = image_import::import_with(&image_bytes("rgb8.png"), &options).unwrap_err();
        assert_eq!(err, ImageImportError::InvalidQuality { quality });
        let msg = err.to_string();
        assert!(msg.contains("between 1 and 100"), "{msg}");
        assert!(
            msg.contains("does not clamp"),
            "the message must say that nothing was substituted: {msg}"
        );

        // Checked FIRST: bytes that are not an image at all still report the
        // quality, not a second-order complaint about the file.
        assert_eq!(
            image_import::import_with(b"not an image", &options).unwrap_err(),
            ImageImportError::InvalidQuality { quality }
        );
    }

    // The endpoints are IN range — an off-by-one here would silently make
    // quality 100 unreachable.
    for quality in [1u8, 100] {
        let options = ImportOptions::new().with_compression(ImageCompression::Jpeg { quality });
        let img = image_import::import_with(&image_bytes("rgb8.png"), &options).unwrap();
        assert_eq!(img.notes.jpeg_quality, Some(quality));
    }
}

/// **The regression that would matter most**: the new encoder path must not
/// disturb the old verbatim one.
///
/// Two forms, because they fail differently. First, an unqualified
/// passthrough is still byte-identical to the source's own compressed data.
/// Second — and this is the one a "just add a match arm" change can break —
/// a passthrough placed in the SAME SESSION as a re-encode is still
/// byte-identical, so nothing about having run the encoder leaks into the
/// image beside it.
#[test]
fn passthrough_is_still_byte_identical_after_the_encoder_exists() {
    // Form 1: the import itself.
    let jpeg = imported("rgb.jpg");
    assert_eq!(
        jpeg.data,
        image_bytes("rgb.jpg"),
        "the codestream, verbatim"
    );
    assert_eq!(jpeg.notes.recompressed, None);
    assert_eq!(
        jpeg.notes.applied_compression,
        ImageCompression::Passthrough
    );

    let png = imported("rgb8.png");
    assert_eq!(
        png.data,
        extract_idat(&image_bytes("rgb8.png")),
        "IDAT, verbatim"
    );

    // Form 2: side by side with a re-encode, in one document.
    let recoded = imported_as("rgb8.png", ImageCompression::Jpeg { quality: 60 });
    let mut s = session();
    let a = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &jpeg))
        .unwrap();
    let b = s
        .add_image(&NewImage::new(0, rect(100.0, 0.0, 160.0, 40.0), &recoded))
        .unwrap();
    let c = s
        .add_image(&NewImage::new(0, rect(200.0, 0.0, 260.0, 40.0), &png))
        .unwrap();
    let pdf = saved(&mut s);

    assert_eq!(
        stream_payload(&object_body(&pdf, a.image_id.num)),
        image_bytes("rgb.jpg"),
        "the passthrough JPEG's bytes must survive the presence of an encoder"
    );
    assert_eq!(
        stream_payload(&object_body(&pdf, c.image_id.num)),
        extract_idat(&image_bytes("rgb8.png")),
        "and so must the passthrough PNG's IDAT"
    );
    let recoded_body = object_body(&pdf, b.image_id.num);
    assert!(contains(&recoded_body, b"/Filter /DCTDecode"));
    assert_ne!(
        stream_payload(&recoded_body),
        extract_idat(&image_bytes("rgb8.png")),
        "the re-encoded one, by contrast, is genuinely different bytes"
    );
}

/// Re-encoding an ALREADY-LOSSY source is a distinct act from re-encoding a
/// lossless one, and is disclosed as such.
///
/// The two share a `RecompressReason`; they do not share a sentence. A
/// second DCT pass quantises the first pass's artefacts *into* the picture,
/// which is not what "lossy compression at quality 90" leads anyone to
/// expect.
#[test]
fn re_encoding_a_jpeg_names_the_compounding_generation_loss() {
    let from_lossy = imported_as("rgb.jpg", ImageCompression::Jpeg { quality: 90 });
    let from_lossless = imported_as("rgb8.png", ImageCompression::Jpeg { quality: 90 });

    assert!(
        from_lossy.notes.jpeg_from_lossy,
        "a JPEG source means the DCT has now run twice"
    );
    assert!(!from_lossless.notes.jpeg_from_lossy);
    assert_eq!(
        from_lossy.notes.recompressed,
        Some(RecompressReason::JpegRequested)
    );
    assert_eq!(
        from_lossy.notes.recompressed.unwrap().key(),
        "jpeg-requested"
    );

    // The size change is reported for BOTH, without anyone having to diff
    // the output.
    assert_eq!(from_lossy.notes.source_bytes, image_bytes("rgb.jpg").len());
    assert_eq!(from_lossy.notes.stored_bytes, from_lossy.data.len());
    assert!(from_lossy.notes.stored_bytes > 0);

    // And it reaches the placement disclosures, which is where a front end
    // reads it.
    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &from_lossy))
        .unwrap();
    assert!(out.disclosures.jpeg_from_lossy);
    assert_eq!(out.disclosures.jpeg_quality, Some(90));
    assert_eq!(out.disclosures.source_bytes, image_bytes("rgb.jpg").len());
    assert!(out.disclosures.any());
}

/// Size is reported for EVERY policy, not only the re-encoding ones — the
/// question "did this get smaller?" must never need a byte diff.
#[test]
fn every_policy_reports_the_size_it_stored() {
    for (name, policy) in [
        ("rgb.jpg", ImageCompression::Passthrough),
        ("rgb.jpg", ImageCompression::Lossless),
        ("rgba8.png", ImageCompression::Passthrough),
        ("rgb24.bmp", ImageCompression::Passthrough),
    ] {
        let img = imported_as(name, policy);
        assert_eq!(
            img.notes.source_bytes,
            image_bytes(name).len(),
            "{name} {policy:?}"
        );
        let expect = img.data.len() + img.soft_mask.as_ref().map_or(0, |m| m.data.len());
        assert_eq!(img.notes.stored_bytes, expect, "{name} {policy:?}");
        assert!(img.notes.stored_bytes > 0, "{name} {policy:?}");
    }
}

/// A colour-key `/Mask` is refused by name rather than silently corrupted.
///
/// §8.9.6.4 masks by exact sample ranges and DCT moves sample values, so a
/// re-encode would leave transparency speckled in both directions — holes in
/// the picture and stray opaque pixels in the background — with nothing to
/// report it afterwards. The refusal names the property of the image, not
/// just the policy, because "use passthrough" is only actionable if the
/// operator knows what they would be giving up.
#[test]
fn a_colour_key_masked_image_refuses_the_jpeg_policy_by_name() {
    // Sanity: this fixture really does carry the colour-key mask.
    assert!(imported("rgb-trns.png").color_key_mask.is_some());

    let options = ImportOptions::new().with_compression(ImageCompression::Jpeg { quality: 85 });
    let err = image_import::import_with(&image_bytes("rgb-trns.png"), &options).unwrap_err();
    let ImageImportError::CompressionRefused { policy, reason } = err else {
        panic!("expected a named compression refusal, got {err:?}");
    };
    assert_eq!(policy, "jpeg");
    assert!(reason.contains("transparent"), "{reason}");
    assert!(
        reason.contains("passthrough") && reason.contains("lossless"),
        "the refusal must name what DOES work: {reason}"
    );

    // The same file places perfectly well under the other policies — the
    // refusal is about this policy, not about this file.
    assert!(
        imported_as("rgb-trns.png", ImageCompression::Lossless)
            .color_key_mask
            .is_some()
    );
}

/// An `/SMask` survives the re-encode UNTOUCHED and lossless.
///
/// §8.9.5 Table 89 makes the soft mask a separate image XObject, so nothing
/// requires it to share the base image's filter — and JPEG is at its very
/// worst along the hard edges an alpha channel is mostly made of. The base
/// goes lossy because that was asked for; the opacity stays exact because it
/// was not.
#[test]
fn a_soft_mask_survives_the_jpeg_re_encode_unchanged() {
    let lossless = imported("rgba8.png");
    let recoded = imported_as("rgba8.png", ImageCompression::Jpeg { quality: 70 });

    let (Some(before), Some(after)) = (&lossless.soft_mask, &recoded.soft_mask) else {
        panic!("both imports must carry a soft mask");
    };
    assert_eq!(
        before.data, after.data,
        "the alpha channel's bytes must be identical — it was never re-encoded"
    );
    assert_eq!(before.bits_per_component, after.bits_per_component);
    assert_eq!(recoded.filter, ImportFilter::DctDecode);
    assert_eq!(
        recoded.notes.requires_pdf_version,
        Some(PdfFeature::SoftMask),
        "the version floor is recomputed from what is STORED, and only the \
         soft mask still raises it"
    );

    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &recoded))
        .unwrap();
    let pdf = saved(&mut s);
    let mask_id = out.soft_mask_id.expect("an /SMask object was written");
    let mask_body = object_body(&pdf, mask_id.num);
    assert!(
        contains(&mask_body, b"/Filter /FlateDecode"),
        "{mask_body:?}"
    );
    assert!(contains(&mask_body, b"/ColorSpace /DeviceGray"));
    assert_eq!(stream_payload(&mask_body), after.data);
}

/// A palette and a sub-byte bit depth both reach the encoder correctly.
///
/// JPEG has neither, so the palette must be EXPANDED (never scaled — an
/// index is not a colour, and scaling one turns a 4-bit palette image into
/// noise) and the 4-bit samples unpacked high-order-bit-first. The result is
/// a three-component `/DeviceRGB` image, which is the only faithful
/// `/DCTDecode` shape for palette data.
#[test]
fn an_indexed_sub_byte_png_expands_to_devicergb_for_the_encoder() {
    let source = imported("indexed4.png");
    assert!(matches!(
        source.color_space,
        pdfcer_core::image_import::ImportColorSpace::Indexed { .. }
    ));
    assert_eq!(source.bits_per_component, 4);

    let re = imported_as("indexed4.png", ImageCompression::Jpeg { quality: 95 });
    assert_eq!(
        re.color_space,
        pdfcer_core::image_import::ImportColorSpace::DeviceRgb
    );
    assert_eq!(re.bits_per_component, 8);
    assert_eq!(re.width, source.width);
    assert_eq!(re.height, source.height);

    let decoded = decode_dct(&re.data);
    assert_eq!(decoded.components, 3);
    assert_eq!(
        decoded.samples.len(),
        (source.width * source.height * 3) as usize
    );
    // Not a uniform block: an index mistaken for a colour, or a palette
    // lookup that always hit entry 0, would flatten the whole image.
    let first = decoded.samples[0];
    assert!(
        decoded.samples.iter().any(|&v| v.abs_diff(first) > 16),
        "the expanded palette must still carry distinct colours"
    );
}

/// The policy is per image, not global: two policies in one session land two
/// differently-stored images on the same page.
#[test]
fn two_images_on_one_page_can_use_different_policies() {
    let verbatim = imported("rgb.jpg");
    let lossless = imported_as("rgb.jpg", ImageCompression::Lossless);
    let mut s = session();
    let a = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &verbatim))
        .unwrap();
    let b = s
        .add_image(&NewImage::new(0, rect(100.0, 0.0, 160.0, 40.0), &lossless))
        .unwrap();
    let pdf = saved(&mut s);
    assert!(contains(
        &object_body(&pdf, a.image_id.num),
        b"/Filter /DCTDecode"
    ));
    assert!(contains(
        &object_body(&pdf, b.image_id.num),
        b"/Filter /FlateDecode"
    ));
    assert_eq!(
        stream_payload(&object_body(&pdf, a.image_id.num)),
        image_bytes("rgb.jpg"),
        "the passthrough placement is unaffected by the other one's policy"
    );
}

/// Every policy key round-trips as the stable string the CLI prints.
#[test]
fn policy_keys_are_stable() {
    assert_eq!(ImageCompression::Passthrough.key(), "passthrough");
    assert_eq!(ImageCompression::Lossless.key(), "lossless");
    assert_eq!(ImageCompression::Jpeg { quality: 85 }.key(), "jpeg");
    assert_eq!(RecompressReason::AlphaSplit.key(), "alpha-split");
    assert_eq!(
        RecompressReason::NoCompressedSource.key(),
        "no-compressed-source"
    );
    assert_eq!(
        RecompressReason::LosslessRequested.key(),
        "lossless-requested"
    );
}

/// The strongest available check that `Lossless` did not mangle anything:
/// for every JPEG in the corpus, the samples it stores must be **identical**
/// to what the passthrough placement decodes to through pdfcer's ordinary
/// image pipeline.
///
/// Both paths run the same codec, so any difference means `to_lossless`
/// mis-sized a buffer, transposed a stride, or picked the wrong colour
/// space — none of which any structural assertion would catch, and all of
/// which look like a corrupted picture rather than an error.
#[test]
fn lossless_stores_exactly_what_the_passthrough_placement_decodes_to() {
    for name in ["rgb.jpg", "gray.jpg", "progressive.jpg", "cmyk.jpg"] {
        // The passthrough placement, decoded back out of a saved document.
        let verbatim = imported(name);
        let mut s = session();
        let out = s
            .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &verbatim))
            .unwrap();
        let pdf = saved(&mut s);
        let (doc, dict, raw) = reloaded_image(&pdf, out.image_id);
        let through_pdf = pdfcer_core::image_codec::decode_image(&doc, &dict, &raw, false)
            .unwrap_or_else(|e| panic!("{name}: {e}"));

        // The lossless import, un-deflated.
        let lossless = imported_as(name, ImageCompression::Lossless);
        let stored = pdfcer_core::filters::flate::decode(&lossless.data, None).unwrap();

        assert_eq!(
            stored, through_pdf.samples,
            "{name}: lossless storage must hold exactly the pixels the \
             passthrough placement renders from"
        );
        assert_eq!(lossless.width, through_pdf.width, "{name} width");
        assert_eq!(lossless.height, through_pdf.height, "{name} height");
        assert_eq!(
            lossless.bits_per_component, through_pdf.bits_per_component,
            "{name} bit depth"
        );
    }
}

/// An EXIF orientation survives the lossless path — it is a property of the
/// picture, not of how the picture is stored, and losing it there would
/// rotate the image only for operators who chose lossless.
#[test]
fn lossless_keeps_the_exif_orientation() {
    let img = imported_as("exif-rot90.jpg", ImageCompression::Lossless);
    assert_eq!(img.orientation, Orientation::Rotate90);
    assert_eq!(img.notes.exif_orientation, Some(6));
    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 120.0, 120.0), &img))
        .unwrap();
    assert_eq!(out.disclosures.exif_orientation_applied, Some(6));
    let p = out.placed_rect;
    assert!(
        (p.urx - p.llx - 80.0).abs() < 1e-9 && (p.ury - p.lly - 120.0).abs() < 1e-9,
        "the DISPLAYED 4x6 shape still drives the fit: {p:?}"
    );
}

// ---------------------------------------------------------------------------
// The pure DPI preview (`pdfcer-gui` request, 2026-08-19)
// ---------------------------------------------------------------------------

/// ★★ THE PROPERTY THE REQUEST WAS ACTUALLY ABOUT: the preview and the
/// outcome cannot disagree, because they are the same code.
///
/// The requesting shell was explicit that the arithmetic was not the ask —
/// they could have written four lines themselves. What they wanted was that
/// `add_image` compute its disclosure **by calling** the pure method, so a
/// number shown beside a size spinner and the number reported after placing
/// can never drift. Their words: *"If that is awkward for how the outcome is
/// assembled, I would rather have nothing than have two implementations."*
///
/// So this test compares the two across placements chosen to disagree if the
/// derivations were ever separated — including `Contain`, where the placed
/// rectangle is **not** the requested one and a second implementation would
/// plausibly measure the wrong rectangle.
#[test]
fn the_pure_dpi_preview_equals_what_the_outcome_reports() {
    let img = imported("rgba8.png");

    for (label, spec) in [
        ("stretch, square", {
            let mut n = NewImage::new(0, rect(0.0, 0.0, 100.0, 100.0), &img);
            n.fit = ImageFit::Stretch;
            n
        }),
        (
            // Contain into a rectangle whose aspect differs from the image's:
            // `placed_rect()` letterboxes, so the placed rectangle is smaller
            // than the requested one and the DPI is HIGHER than a naive
            // measurement of `rect` would give.
            "contain, letterboxed",
            {
                let mut n = NewImage::new(0, rect(0.0, 0.0, 400.0, 100.0), &img);
                n.fit = ImageFit::Contain;
                n
            },
        ),
        ("tiny box -- very high dpi", {
            let mut n = NewImage::new(0, rect(10.0, 10.0, 14.0, 14.0), &img);
            n.fit = ImageFit::Stretch;
            n
        }),
        ("huge box -- below screen resolution", {
            let mut n = NewImage::new(0, rect(0.0, 0.0, 2000.0, 2000.0), &img);
            n.fit = ImageFit::Stretch;
            n
        }),
    ] {
        let preview = spec.effective_dpi();
        let preview_soft = spec.below_screen_resolution();

        let mut s = session();
        let out = s.add_image(&spec).expect("placement succeeds");

        assert_eq!(
            preview, out.disclosures.effective_dpi,
            "{label}: the pure preview and the outcome must be the SAME number \
             -- if they differ, `add_image` has stopped calling \
             `NewImage::effective_dpi` and the drift this request existed to \
             prevent has been reintroduced one layer down"
        );
        assert_eq!(
            preview_soft, out.disclosures.below_screen_resolution,
            "{label}: the soft-resolution flag must agree too"
        );
    }
}

/// The preview measures the PLACED rectangle, not the requested one.
///
/// Under `Contain` those differ, and a second implementation written from the
/// request's own sketch (`display_size_px().0 / (placed_width_pt / 72.0)`)
/// would be right only if it remembered to letterbox first. Pinned so the
/// distinction is a test rather than a comment.
#[test]
fn contain_measures_the_letterboxed_rectangle_not_the_requested_one() {
    let img = imported("rgba8.png");
    let wide = rect(0.0, 0.0, 400.0, 100.0);
    let mut spec = NewImage::new(0, wide, &img);
    spec.fit = ImageFit::Contain;

    let placed = spec.placed_rect();
    let placed_w = placed.urx - placed.llx;
    assert!(
        placed_w < 399.0,
        "the fixture must actually letterboxs, or this test proves nothing; \
         placed width {placed_w}"
    );

    let (dpi_x, _) = spec.effective_dpi();
    let naive = {
        let (px_w, _) = img.display_size_px();
        f64::from(px_w) * 72.0 / (wide.urx - wide.llx)
    };
    assert!(
        dpi_x > naive * 1.5,
        "measuring the REQUESTED rectangle gives {naive:.1} dpi; the placed \
         one gives {dpi_x:.1}. They must not be close, or the test cannot \
         tell which rectangle was used."
    );
}

/// A degenerate placement reports `0.0`, not an infinity.
///
/// Zero is not a resolution, but it is a number a spinner label can render;
/// `inf` is not, and `NaN` compares false against itself, which would make
/// the agreement test above pass vacuously.
#[test]
fn a_zero_area_placement_reports_zero_dpi_rather_than_infinity() {
    let img = imported("rgba8.png");
    let spec = {
        let mut n = NewImage::new(0, rect(10.0, 10.0, 10.0, 10.0), &img);
        n.fit = ImageFit::Stretch;
        n
    };
    let (x, y) = spec.effective_dpi();
    assert_eq!(
        (x, y),
        (0.0, 0.0),
        "a zero-area placement has no resolution"
    );
    assert!(x.is_finite() && y.is_finite());
    // And it counts as below screen resolution, which is the honest reading:
    // it is certainly not sharp.
    assert!(spec.below_screen_resolution());
}
