//! Importing a TIFF and placing it on a page (TIFF 6.0 → §8.9.5 image XObject).
//!
//! ## Why this is a separate integration test from `image_placement.rs`
//!
//! That file proves the **placement machinery** — four coordinated writes,
//! the page patch, the fitting arithmetic — using PNG/JPEG/BMP sources. This
//! one proves the **container reader**, and TIFF's failure modes are a
//! different shape from the other three formats':
//!
//! - PNG has one layout and JPEG has one codestream. A TIFF is a *directory
//!   of tags*, and the same picture is legally storable in dozens of ways.
//!   Nothing in the file is redundant enough to catch a misread, so a wrong
//!   `PlanarConfiguration`, a missed byte swap or an unhandled predictor
//!   produces a **plausible-looking, entirely wrong picture** rather than an
//!   error anywhere.
//! - The load-bearing assertions are therefore mostly **"these two files must
//!   import to identical samples"** pairs: the same picture in `II` and `MM`,
//!   the same picture under five compressions, the same picture with straight
//!   and premultiplied alpha. A single-file assertion cannot distinguish "the
//!   decoder is right" from "the decoder and the fixture generator are wrong
//!   in the same direction"; a pair can.
//!
//! Where a claim is about **bytes** — that a single-strip Deflate TIFF's own
//! strip payload reaches the document unchanged — the assertion runs over the
//! SAVED FILE, extracted with a deliberately dumb byte scanner, per **R159**:
//! *"a defect that lives in the BYTES must be asserted in the BYTES."*
//!
//! ## Fixture provenance
//!
//! Every file under `fixtures/synthetic/tiff/` is generated by
//! `fixtures/synthetic/tiff/gen-tiff-fixtures.py` from pixel data this
//! project authored. Nothing is downloaded (project rule 7, `LEGAL.md` §5).
//! See that directory's `PROVENANCE.md` — including why the generator sits
//! beside its output rather than in `tools/`.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use pdfcer_core::document::Document;
use pdfcer_core::edit::{EditSession, NewImage};
use pdfcer_core::filters::flate;
use pdfcer_core::image_import::{
    self, ImageFormat, ImageImportError, ImportColorSpace, ImportFilter, ImportedImage,
    Orientation, RecompressReason, SUPPORTED_FORMATS,
};
use pdfcer_core::page_tree::Rect;
use pdfcer_core::writer::SaveOptions;
use std::path::{Path, PathBuf};

// ---------------------------------------------------------------------------
// Harness
// ---------------------------------------------------------------------------

fn fixture(rel: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures/synthetic")
        .join(rel)
}

fn tiff_bytes(name: &str) -> Vec<u8> {
    std::fs::read(fixture(&format!("tiff/{name}")))
        .unwrap_or_else(|e| panic!("read fixture tiff/{name}: {e}"))
}

fn imported(name: &str) -> ImportedImage {
    image_import::import(&tiff_bytes(name)).unwrap_or_else(|e| panic!("import tiff/{name}: {e}"))
}

/// The decoded sample buffer of an imported TIFF.
///
/// Every TIFF lands on plain `/FlateDecode` (there is no predictor variant
/// to describe a TIFF, and `/DCTDecode` is not reachable from this reader),
/// so one branch is enough — and asserting that is itself worth doing, which
/// the `filter` check here does.
fn samples(img: &ImportedImage) -> Vec<u8> {
    assert_eq!(
        img.filter,
        ImportFilter::Flate,
        "a TIFF always lands on plain /FlateDecode"
    );
    flate::decode(&img.data, None).expect("the stream inflates")
}

fn mask_samples(img: &ImportedImage) -> Vec<u8> {
    let mask = img.soft_mask.as_ref().expect("this image has a soft mask");
    flate::decode(&mask.data, None).expect("the mask inflates")
}

fn session() -> EditSession {
    EditSession::new(Document::load(&fixture("dimension/plain-base.pdf")).expect("load fixture"))
}

fn rect(llx: f64, lly: f64, urx: f64, ury: f64) -> Rect {
    Rect { llx, lly, urx, ury }
}

fn saved(s: &mut EditSession) -> Vec<u8> {
    s.to_incremental_bytes(&SaveOptions::identity())
        .expect("incremental save")
        .0
}

/// The body of indirect object `id` **as it appears in the saved bytes**.
///
/// A byte scan, not a parse: this helper must not be able to repair or
/// reinterpret anything on the way in — that is the point of asserting here
/// rather than on a model (R159). Takes the LAST occurrence, because an
/// incremental update appends a new definition after the original.
fn object_body(pdf: &[u8], id: u32) -> Vec<u8> {
    let needle = format!("\n{id} 0 obj");
    let start = pdf
        .windows(needle.len())
        .enumerate()
        .filter(|(_, w)| *w == needle.as_bytes())
        .map(|(i, _)| i + needle.len())
        .next_back()
        .unwrap_or_else(|| panic!("object {id} is not in the saved file"));
    let end = pdf
        .windows(6)
        .enumerate()
        .skip(start)
        .find(|(_, w)| *w == b"endobj")
        .map(|(i, _)| i)
        .unwrap_or_else(|| panic!("object {id} has no endobj"));
    pdf.get(start..end).unwrap_or_default().to_vec()
}

/// The raw stream payload inside an object body (§7.3.8.1).
fn stream_payload(body: &[u8]) -> Vec<u8> {
    let kw = b"stream";
    let at = body
        .windows(kw.len())
        .enumerate()
        .find(|(_, w)| *w == kw)
        .map(|(i, _)| i + kw.len())
        .expect("the object has a stream keyword");
    let start = if body.get(at) == Some(&b'\r') {
        at + 2
    } else {
        at + 1
    };
    let end = body
        .windows(9)
        .enumerate()
        .filter(|(_, w)| *w == b"endstream")
        .map(|(i, _)| i)
        .next_back()
        .expect("the object has an endstream");
    let mut stop = end;
    if body.get(stop.wrapping_sub(1)) == Some(&b'\n') {
        stop -= 1;
    }
    if body.get(stop.wrapping_sub(1)) == Some(&b'\r') {
        stop -= 1;
    }
    body.get(start..stop).unwrap_or_default().to_vec()
}

fn contains(hay: &[u8], needle: &[u8]) -> bool {
    hay.windows(needle.len()).any(|w| w == needle)
}

/// The authored colour ramp, as `/DeviceRGB` samples — computed here rather
/// than copied from the generator, so the two are independent statements of
/// the same intent.
fn expected_rgb() -> Vec<u8> {
    let (w, h) = (6u32, 4u32);
    let mut out = Vec::new();
    for y in 0..h {
        for x in 0..w {
            let r = (255 * x / (w - 1)) as u8;
            let g = (255 * y / (h - 1)) as u8;
            out.extend_from_slice(&[r, g, 255 - r]);
        }
    }
    out
}

fn expected_gray() -> Vec<u8> {
    let (w, h) = (6u32, 4u32);
    let mut out = Vec::new();
    for y in 0..h {
        for x in 0..w {
            out.push((255 * (x + y) / (w + h - 2)) as u8);
        }
    }
    out
}

/// The authored alpha ramp — deliberately non-binary, which is what makes
/// associated and unassociated alpha distinguishable at all.
fn expected_alpha() -> Vec<u8> {
    let (w, h) = (6u32, 4u32);
    let mut out = Vec::new();
    for y in 0..h {
        for x in 0..w {
            out.push((255 * (x * h + y) / (w * h - 1)) as u8);
        }
    }
    out
}

// ---------------------------------------------------------------------------
// Byte order — the single most common TIFF bug
// ---------------------------------------------------------------------------

/// The same picture stored `II` and `MM` must import to identical samples.
///
/// This pair catches a reader that ignores the byte-order mark entirely; it
/// does **not** catch one that reads the tags correctly and the sample data
/// incorrectly, which is what the 16-bit pair below is for.
#[test]
fn both_byte_orders_of_the_same_8_bit_image_agree() {
    let be = imported("gray8-be.tif");
    let le = imported("gray8-le.tif");
    assert_eq!(be.color_space, ImportColorSpace::DeviceGray);
    assert_eq!((be.width, be.height), (6, 4));
    assert_eq!(samples(&be), expected_gray());
    assert_eq!(
        samples(&be),
        samples(&le),
        "II and MM are the same picture and must decode identically"
    );
}

/// **The endianness assertion that matters.** TIFF stores 16-bit *sample
/// data* in the file's byte order; ISO 32000-1 §8.9.3 requires PDF samples
/// high-order byte first. So an `II` file's pixels must be byte-swapped, and
/// a reader that swaps the tags but not the samples passes the 8-bit pair
/// above and fails here — producing an image whose every channel is
/// scrambled into noise that still has the right dimensions.
#[test]
fn sixteen_bit_samples_are_big_endian_whatever_the_file_said() {
    let be = imported("gray16-be.tif");
    let le = imported("gray16-le.tif");
    assert_eq!(be.bits_per_component, 16);
    assert_eq!(le.bits_per_component, 16);

    let expected: Vec<u8> = expected_gray()
        .into_iter()
        .flat_map(|v| (u16::from(v) * 257).to_be_bytes())
        .collect();
    assert_eq!(samples(&be), expected);
    assert_eq!(
        samples(&le),
        expected,
        "an II file's 16-bit samples must be swapped into PDF's byte order"
    );
}

// ---------------------------------------------------------------------------
// Compression — five encodings of one picture
// ---------------------------------------------------------------------------

/// Every compression pdfcer accepts must decode to the **same** samples.
///
/// One table rather than five tests, because the property under test is
/// exactly that they agree: a per-compression test could pass with five
/// different pictures.
#[test]
fn every_accepted_compression_decodes_to_the_same_picture() {
    let want = expected_rgb();
    for name in [
        "rgb8-none.tif",
        "rgb8-lzw.tif",
        "rgb8-deflate.tif",
        "rgb8-deflate-strips.tif",
        "rgb8-packbits.tif",
    ] {
        let img = imported(name);
        assert_eq!(img.format, ImageFormat::Tiff);
        assert_eq!(img.color_space, ImportColorSpace::DeviceRgb);
        assert_eq!(img.bits_per_component, 8);
        assert_eq!(samples(&img), want, "{name}");
    }
}

/// `rgb8-lzw.tif` is LZW **plus `Predictor 2` plus three strips** — the
/// shape a real tool writes, and three independent things to get wrong at
/// once. Called out separately from the table above so a failure names which
/// property broke.
#[test]
fn lzw_with_horizontal_differencing_across_strips_reassembles() {
    let img = imported("rgb8-lzw.tif");
    assert_eq!(samples(&img), expected_rgb());
    assert_eq!(
        img.notes.recompressed,
        Some(RecompressReason::SourceCodecNotReusable),
        "pdfcer writes no LZW encoder (R28), so nothing can be passed through"
    );
}

/// **The PackBits divergence.** TIFF 6.0 §9 makes `0x80` a *no-op*;
/// ISO 32000-1 §7.4.5 makes `128` *end-of-data*. `rgb8-packbits.tif` carries
/// one deliberately, mid-strip. A TIFF reader that called pdfcer's own
/// `RunLengthDecode` filter would stop there and lose the rest of the image.
#[test]
fn a_packbits_strip_survives_its_embedded_0x80_no_op() {
    let img = imported("rgb8-packbits.tif");
    let got = samples(&img);
    assert_eq!(
        got.len(),
        6 * 4 * 3,
        "the whole image, not just the bytes before the 0x80"
    );
    assert_eq!(got, expected_rgb());
}

// ---------------------------------------------------------------------------
// Passthrough — the bytes assertion (R159)
// ---------------------------------------------------------------------------

/// A single-strip, `Predictor 1`, Deflate TIFF's strip payload **is** a
/// conforming plain `/FlateDecode` stream, and reaches the document byte for
/// byte.
///
/// Asserted over the SAVED FILE rather than over the in-memory image: a
/// re-deflate would produce a working document with a correct-looking
/// picture and slightly different bytes, which only a byte comparison
/// catches.
#[test]
fn a_single_strip_deflate_tiff_reaches_the_document_byte_identical() {
    let img = imported("rgb8-deflate.tif");
    assert!(
        img.notes.recompressed.is_none(),
        "nothing had to be transformed, so nothing had to be re-compressed"
    );

    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(20.0, 20.0, 140.0, 100.0), &img))
        .expect("place the TIFF");
    let pdf = saved(&mut s);

    let body = object_body(&pdf, out.image_id.num);
    assert_eq!(
        stream_payload(&body),
        img.data,
        "the /FlateDecode stream IS the TIFF's own strip"
    );
    assert!(contains(&body, b"/Filter /FlateDecode"), "{body:?}");
    assert!(
        !contains(&body, b"/DecodeParms"),
        "a plain Flate stream carries no predictor parameters: {body:?}"
    );
    assert!(contains(&body, b"/Width 6"));
    assert!(contains(&body, b"/Height 4"));
    assert!(contains(&body, b"/ColorSpace /DeviceRGB"));
    assert!(contains(&body, b"/BitsPerComponent 8"));
}

/// …and the same picture in **three** strips must NOT be passed through:
/// three concatenated zlib streams are not one zlib stream. Paired with the
/// test above so the gate is exercised in both directions — a gate that only
/// ever says "yes" is not a gate.
#[test]
fn a_multi_strip_deflate_tiff_is_rebuilt_not_passed_through() {
    let one = imported("rgb8-deflate.tif");
    let many = imported("rgb8-deflate-strips.tif");
    assert_eq!(samples(&one), samples(&many), "the same picture");
    assert_eq!(
        many.notes.recompressed,
        Some(RecompressReason::SourceCodecNotReusable)
    );
    assert_eq!(
        many.notes.recompressed.map(RecompressReason::key),
        Some("source-codec-not-reusable"),
        "the stable key a front end reports"
    );
}

// ---------------------------------------------------------------------------
// Photometric interpretation
// ---------------------------------------------------------------------------

/// `PhotometricInterpretation 0` means **0 is white** — the reverse of
/// `/DeviceGray` (§8.6.4.2). Read without the complement, a bilevel scan
/// imports as a photographic negative, which is how monochrome CAD output
/// and every fax-lineage scan would look.
#[test]
fn a_white_is_zero_bilevel_scan_lands_in_devicegray_polarity() {
    let img = imported("bilevel-whiteiszero.tif");
    assert_eq!(img.bits_per_component, 1);
    assert_eq!(img.color_space, ImportColorSpace::DeviceGray);
    assert!(img.notes.tiff_white_is_zero_inverted);

    // The generator writes bit 1 where (x + y) % 3 == 0, and 1 means WHITE
    // in a WhiteIsZero-complemented world... which is to say: the stored bit
    // was 1 = "not zero" = black-ish in TIFF terms, and after the complement
    // it must read 0 in PDF terms.
    let got = samples(&img);
    assert_eq!(got.len(), 4, "one byte per row at 6 bits + padding");
    for (y, byte) in got.iter().enumerate() {
        for x in 0..6usize {
            let stored = u8::from((x + y) % 3 == 0);
            let bit = (byte >> (7 - x)) & 1;
            assert_eq!(
                bit,
                1 - stored,
                "sample ({x}, {y}) must be the complement of what was stored"
            );
        }
    }
}

/// TIFF 6.0 §16 stores a `ColorMap` as three consecutive **blocks** (all
/// red, then all green, then all blue) while §8.6.6.3 wants interleaved
/// triples. A reader that copies the field straight through gets a palette
/// whose every colour is wrong.
#[test]
fn a_colormap_is_deblocked_into_an_indexed_lookup() {
    let img = imported("pal8.tif");
    let ImportColorSpace::Indexed { hival, lookup } = &img.color_space else {
        panic!("a palette TIFF must become /Indexed: {:?}", img.color_space);
    };
    assert_eq!(*hival, 255, "2^8 entries, so hival is 255");
    assert_eq!(lookup.len(), 256 * 3);
    assert_eq!(
        lookup.get(0..18).unwrap(),
        &[
            0, 0, 0, // 0 black
            255, 0, 0, // 1 red
            0, 255, 0, // 2 green
            0, 0, 255, // 3 blue
            255, 255, 0, // 4 yellow
            255, 255, 255, // 5 white
        ],
        "the three ColorMap blocks must interleave into RGB triples"
    );
    assert!(!img.notes.tiff_palette_assumed_8bit);

    let indices: Vec<u8> = (0..4u8)
        .flat_map(|y| (0..6u8).map(move |x| (x + 2 * y) % 6))
        .collect();
    assert_eq!(samples(&img), indices);
}

/// The recorded standard-vs-practice divergence: a `ColorMap` whose 16-bit
/// fields all hold 0–255 was written 8-bit, and trusting TIFF 6.0 §16
/// literally renders it almost entirely black. pdfcer applies libtiff's
/// heuristic **and discloses that it fired** — the two fixtures together
/// prove the heuristic fires when it should and not when it should not.
#[test]
fn an_eight_bit_colormap_is_detected_disclosed_and_matches_the_16_bit_one() {
    let spec = imported("pal8.tif");
    let real = imported("pal8-8bit-colormap.tif");
    assert!(!spec.notes.tiff_palette_assumed_8bit);
    assert!(
        real.notes.tiff_palette_assumed_8bit,
        "the heuristic fired and must say so (rule 4)"
    );
    assert_eq!(
        spec.color_space, real.color_space,
        "both spellings of the same palette must produce the same lookup"
    );
}

// ---------------------------------------------------------------------------
// Alpha — ExtraSamples (TIFF 6.0 §18)
// ---------------------------------------------------------------------------

/// Straight (`unassociated`) alpha splits directly into a `/DeviceRGB` base
/// and an 8-bit `/SMask` — and the placement writes the mask as its own
/// object, referenced by `/SMask`.
#[test]
fn unassociated_alpha_becomes_a_soft_mask() {
    let img = imported("rgba8-unassociated.tif");
    assert_eq!(img.color_space, ImportColorSpace::DeviceRgb);
    assert_eq!(samples(&img), expected_rgb());
    assert_eq!(mask_samples(&img), expected_alpha());
    assert!(img.notes.alpha_to_soft_mask);
    assert!(!img.notes.tiff_associated_alpha_unpremultiplied);
    assert_eq!(img.notes.recompressed, Some(RecompressReason::AlphaSplit));

    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 120.0, 80.0), &img))
        .expect("place the RGBA TIFF");
    let mask_id = out.soft_mask_id.expect("a soft-mask object was written");
    let pdf = saved(&mut s);

    let body = object_body(&pdf, out.image_id.num);
    assert!(
        contains(&body, format!("/SMask {} 0 R", mask_id.num).as_bytes()),
        "the base image must reference its mask: {body:?}"
    );
    let mask_body = object_body(&pdf, mask_id.num);
    assert!(contains(&mask_body, b"/ColorSpace /DeviceGray"));
    assert!(contains(&mask_body, b"/Width 6"));
    assert!(contains(&mask_body, b"/Height 4"));
    assert_eq!(
        flate::decode(&stream_payload(&mask_body), None).unwrap(),
        expected_alpha()
    );
}

/// **The compositing trap.** `ExtraSamples 1` means the colour samples are
/// PREMULTIPLIED by alpha; a `/SMask` is a straight alpha channel. Stored
/// as-is, every partly-transparent pixel composites double-dark — the more
/// transparent, the darker — which reads as "pdfcer lost the transparency"
/// rather than as an inverted convention.
///
/// The two fixtures carry the **same picture**, so the assertion is that
/// they agree, not merely that something happened. They cannot agree
/// exactly: premultiplication quantises, and nothing can put back what it
/// discarded. The tolerance is the honest statement of that, and it is
/// checked to be *tight where it can be* — at full opacity the recovery is
/// exact.
#[test]
fn associated_alpha_is_unpremultiplied_back_to_the_straight_picture() {
    let straight = imported("rgba8-unassociated.tif");
    let premultiplied = imported("rgba8-associated.tif");

    assert!(premultiplied.notes.tiff_associated_alpha_unpremultiplied);
    assert!(!straight.notes.tiff_associated_alpha_unpremultiplied);
    assert_eq!(
        mask_samples(&premultiplied),
        mask_samples(&straight),
        "the alpha channel itself is untouched by either convention"
    );

    let want = samples(&straight);
    let got = samples(&premultiplied);
    let alpha = expected_alpha();
    assert_eq!(got.len(), want.len());

    let mut exact_at_full_alpha = 0usize;
    for (i, (g, w)) in got.iter().zip(want.iter()).enumerate() {
        let a = alpha.get(i / 3).copied().unwrap_or(0);
        if a == 0 {
            // A fully transparent pixel's premultiplied colour is all-zero
            // and carries NO information; any value is equally right.
            continue;
        }
        // The reconstruction error is bounded by the quantisation the
        // premultiply performed: about one output step per unit of alpha.
        let tolerance = (255 / u32::from(a).max(1)) as u8 + 1;
        assert!(
            g.abs_diff(*w) <= tolerance,
            "sample {i} (alpha {a}): recovered {g}, want {w}, tolerance {tolerance}"
        );
        if a == 255 {
            assert_eq!(g, w, "at full opacity the recovery is EXACT");
            exact_at_full_alpha += 1;
        }
    }
    assert!(
        exact_at_full_alpha > 0,
        "the fixture must contain at least one fully-opaque pixel, or the \
         exactness claim above is never tested"
    );
}

/// `ExtraSamples 0` — and an omitted tag — is *"unspecified data"*, not
/// opacity. Reading it as alpha is how an otherwise-perfect image renders
/// entirely invisible; the channel is dropped and the drop is disclosed.
#[test]
fn unspecified_extra_samples_are_dropped_not_read_as_opacity() {
    let img = imported("rgba8-unspecified.tif");
    assert!(
        img.soft_mask.is_none(),
        "a channel of undeclared meaning is not an alpha channel"
    );
    assert_eq!(samples(&img), expected_rgb());
    assert_eq!(img.notes.tiff_extra_samples_dropped, 1);
    assert!(!img.notes.alpha_to_soft_mask);
}

// ---------------------------------------------------------------------------
// Multi-page
// ---------------------------------------------------------------------------

/// A sheet-fed scanner's ordinary output. pdfcer places the **first** page and
/// COUNTS the rest — silently dropping them is what rule 4 forbids, and
/// refusing outright would turn the commonest scanner output into a dead end.
#[test]
fn a_multi_page_tiff_places_the_first_page_and_discloses_the_rest() {
    let img = imported("multipage.tif");
    assert_eq!(
        img.notes.tiff_pages_ignored, 2,
        "three IFDs: one placed, two disclosed"
    );
    assert_eq!(
        samples(&img),
        vec![0x11u8; 24],
        "the FIRST page's shade, not the last one's"
    );
}

#[test]
fn a_single_page_tiff_discloses_no_ignored_pages() {
    assert_eq!(imported("gray8-be.tif").notes.tiff_pages_ignored, 0);
}

// ---------------------------------------------------------------------------
// Metadata
// ---------------------------------------------------------------------------

/// Every fixture declares 300 dpi in inches, and none of them is placed at
/// that size unless asked — the resolution is REPORTED, never applied
/// silently (rule 4; see `ImportedImage::natural_size_pt`).
#[test]
fn a_declared_resolution_is_reported_and_not_applied() {
    let img = imported("rgb8-none.tif");
    let (dx, dy) = img.dpi.expect("the fixtures declare 300 dpi");
    assert!((dx - 300.0).abs() < 0.5, "{dx}");
    assert!((dy - 300.0).abs() < 0.5, "{dy}");
    assert_eq!(img.orientation, Orientation::Identity);

    // Natural size at 300 dpi: 6 px = 1.44 pt, 4 px = 0.96 pt.
    let (w, h) = img.natural_size_pt();
    assert!((w - 1.44).abs() < 1e-6, "{w}");
    assert!((h - 0.96).abs() < 1e-6, "{h}");

    // …but the placement uses the caller's rectangle, not that.
    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 120.0, 80.0), &img))
        .expect("place the TIFF");
    assert!((out.placed_rect.urx - out.placed_rect.llx - 120.0).abs() < 1e-6);
}

// ---------------------------------------------------------------------------
// Refusals — by name, with a stable key (R27)
// ---------------------------------------------------------------------------

/// Every TIFF sub-feature pdfcer declines fails with its own key, never a
/// generic "decode failed". A wrong-looking image is the worse outcome, and
/// these are precisely the tag combinations that produce one when guessed at.
#[test]
fn declined_tiff_sub_features_are_refused_by_name() {
    for (name, feature) in [
        ("tiled.tif", "TIFF/tiled"),
        ("planar.tif", "TIFF/planar-separate"),
        ("ccittg4.tif", "TIFF/ccitt-g4"),
        ("float32.tif", "TIFF/sample-format-float"),
    ] {
        let err = image_import::import(&tiff_bytes(name)).unwrap_err();
        assert_eq!(
            err,
            ImageImportError::Unsupported { feature },
            "{name} must be refused by name"
        );
        assert!(
            err.to_string().contains(feature),
            "the message names the feature: {err}"
        );
    }
}

/// BigTIFF is a different parser, not a sub-feature of classic TIFF, so it is
/// refused at the **sniffer** under its own format name — and the message
/// names what does work, which now includes TIFF. Refusing it as "TIFF" would
/// produce a sentence that contradicts itself.
#[test]
fn bigtiff_is_refused_as_its_own_format_and_the_message_names_tiff() {
    let err = image_import::import(&tiff_bytes("bigtiff.tif")).unwrap_err();
    assert_eq!(
        err,
        ImageImportError::UnsupportedFormat { format: "BigTIFF" }
    );
    let msg = err.to_string();
    assert!(msg.contains("BigTIFF"), "{msg}");
    assert!(msg.contains(SUPPORTED_FORMATS), "{msg}");
    assert!(
        SUPPORTED_FORMATS.contains("TIFF"),
        "the supported-format sentence must now include TIFF"
    );
}

/// The sniffer recognises classic TIFF in both byte orders and routes it to
/// the reader rather than to a refusal.
#[test]
fn the_sniffer_routes_classic_tiff_to_the_reader() {
    for name in ["gray8-be.tif", "gray8-le.tif"] {
        assert_eq!(
            image_import::sniff(&tiff_bytes(name)).unwrap(),
            ImageFormat::Tiff,
            "{name}"
        );
    }
    assert_eq!(ImageFormat::Tiff.name(), "TIFF");
}

/// Truncation must be a diagnosis, never a panic: `pdfcer-core` denies
/// unchecked indexing crate-wide precisely because this input is untrusted.
/// Run over every fixture, including the refusals, because a refusal path
/// that panics on a short file is still a denial-of-service bug.
#[test]
fn every_truncation_of_every_fixture_is_diagnosed_not_panicked() {
    for name in [
        "rgb8-lzw.tif",
        "rgb8-packbits.tif",
        "rgba8-associated.tif",
        "multipage.tif",
        "pal8.tif",
        "tiled.tif",
    ] {
        let bytes = tiff_bytes(name);
        for cut in 0..bytes.len() {
            // The result is irrelevant; not unwinding is the assertion.
            let _ = image_import::import(bytes.get(..cut).unwrap());
        }
    }
}
