//! PKCS#12 import against the synthetic containers in
//! `fixtures/synthetic/signing/` (generated by `tools/gen-signing-fixtures.py`
//! with OpenSSL — an independent producer, which is what makes these files an
//! oracle for the importer rather than a mirror of it).
//!
//! What is asserted, and why each matters:
//!
//! - The **modern** (PBES2/AES-256, MAC SHA-256) and **legacy**
//!   (3DES key bag, RC2-40 cert bags, MAC SHA-1) RSA containers wrap the SAME
//!   key and certificate, so both eras must decrypt to identical material —
//!   one test proves both decryption paths at once.
//! - The extracted leaf equals the DER certificate beside the store
//!   byte-for-byte.
//! - A wrong password is refused **at the MAC**, before anything is
//!   decrypted, with the named error.
//! - Each signer signs and pdfcer's own in-crate verifier accepts the
//!   signature — RSA PKCS#1 v1.5, RSA-PSS and ECDSA P-256 all round-trip.
//!   The verifier (`crypto/rsa.rs`, `crypto/ecdsa.rs`) is an independent
//!   implementation from the signing crates, so this is a real cross-check,
//!   not a tautology.

// The whole file needs the `signing` feature (default on); a
// `--no-default-features` build compiles it to nothing rather than failing.
#![cfg(feature = "signing")]
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::path::{Path, PathBuf};

use pdfcer_core::sign::pkcs12::{Pkcs12Error, Pkcs12Signer};
use pdfcer_core::sign::{SignatureAlgorithm, Signer};

fn fixture(name: &str) -> Vec<u8> {
    let p: PathBuf = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures/synthetic/signing")
        .join(name);
    std::fs::read(&p).unwrap_or_else(|e| panic!("read {}: {e}", p.display()))
}

#[test]
fn modern_and_legacy_containers_yield_the_same_key_and_certificate() {
    let modern =
        Pkcs12Signer::from_der(&fixture("rsa2048-modern.pfx"), "pdfcer").expect("modern opens");
    let legacy =
        Pkcs12Signer::from_der(&fixture("rsa2048-legacy.pfx"), "pdfcer").expect("legacy opens");

    // Both eras decrypted — the report names which.
    assert_eq!(modern.report().mac.as_deref(), Some("SHA-256"));
    assert!(
        modern
            .report()
            .key_scheme
            .starts_with("PBES2/PBKDF2-HMAC-SHA-256/AES-256-CBC"),
        "{}",
        modern.report().key_scheme
    );
    assert_eq!(legacy.report().mac.as_deref(), Some("SHA-1"));
    assert!(
        legacy
            .report()
            .key_scheme
            .starts_with("pbeWithSHAAnd3-KeyTripleDES-CBC"),
        "{}",
        legacy.report().key_scheme
    );
    assert!(
        legacy
            .report()
            .cert_schemes
            .iter()
            .any(|s| s.contains("RC2-40")),
        "{:?}",
        legacy.report().cert_schemes
    );

    // Same certificate, and it is the one on disk.
    assert_eq!(modern.certificate_chain(), legacy.certificate_chain());
    assert_eq!(
        modern.certificate_chain().len(),
        1,
        "a self-signed leaf is the whole chain"
    );
    assert_eq!(modern.certificate_chain()[0], fixture("rsa2048.cer"));
    assert_eq!(modern.key_label(), "RSA-2048");
    assert_eq!(legacy.key_label(), "RSA-2048");
    assert!(
        modern
            .report()
            .subject
            .contains("pdfcer synthetic RSA signer"),
        "{}",
        modern.report().subject
    );
    assert_eq!(modern.report().friendly_name.as_deref(), Some("pdfcer-rsa"));

    // Same key: a deterministic ECDSA would prove it directly; RSA PKCS#1
    // v1.5 is deterministic in the VALUE even though pdfcer blinds the
    // computation, so two signatures of one message must be byte-equal.
    let msg = b"the same private key in two wrappers";
    let a = modern
        .sign(SignatureAlgorithm::RsaPkcs1v15Sha256, msg)
        .unwrap();
    let b = legacy
        .sign(SignatureAlgorithm::RsaPkcs1v15Sha256, msg)
        .unwrap();
    assert_eq!(
        a, b,
        "PKCS#1 v1.5 is deterministic, so equal signatures mean equal keys"
    );
    assert_eq!(a.len(), 256);
}

#[test]
fn a_wrong_password_fails_at_the_mac_by_name() {
    for name in [
        "rsa2048-modern.pfx",
        "rsa2048-legacy.pfx",
        "ecp256-modern.pfx",
    ] {
        let err = Pkcs12Signer::from_der(&fixture(name), "not-the-password").expect_err(name);
        assert!(
            matches!(err, Pkcs12Error::MacMismatch { .. }),
            "{name}: {err:?}"
        );
    }
    let err = Pkcs12Signer::from_der(b"not a pfx at all", "pdfcer").expect_err("garbage");
    assert!(
        matches!(err, Pkcs12Error::Malformed { what: "PFX" }),
        "{err:?}"
    );
}

#[test]
fn the_ec_container_opens_and_defaults_to_ecdsa() {
    let ec = Pkcs12Signer::from_der(&fixture("ecp256-modern.pfx"), "pdfcer").expect("ec opens");
    assert_eq!(ec.key_label(), "EC P-256");
    assert_eq!(ec.default_algorithm(), SignatureAlgorithm::EcdsaP256Sha256);
    assert_eq!(ec.certificate_chain()[0], fixture("ecp256.cer"));
    // An RSA algorithm on an EC key is refused by name, not mis-signed.
    let err = ec
        .sign(SignatureAlgorithm::RsaPkcs1v15Sha256, b"x")
        .expect_err("mismatch");
    assert!(
        matches!(err, pdfcer_core::sign::SignError::AlgorithmMismatch { .. }),
        "{err:?}"
    );
    // P-384 on a P-256 key likewise.
    let err = ec
        .sign(SignatureAlgorithm::EcdsaP384Sha384, b"x")
        .expect_err("mismatch");
    assert!(
        matches!(err, pdfcer_core::sign::SignError::AlgorithmMismatch { .. }),
        "{err:?}"
    );
}

#[test]
fn every_signature_the_signers_make_is_accepted_by_pdfcers_own_verifier() {
    // The in-crate verifier is a separate implementation (decision 129: it
    // is the one that may NOT hold a private key), so it is an oracle here.
    let rsa = Pkcs12Signer::from_der(&fixture("rsa2048-modern.pfx"), "pdfcer").unwrap();
    let ec = Pkcs12Signer::from_der(&fixture("ecp256-modern.pfx"), "pdfcer").unwrap();
    let msg = b"signed attributes stand-in";
    for (signer, alg) in [
        (&rsa, SignatureAlgorithm::RsaPkcs1v15Sha256),
        (&rsa, SignatureAlgorithm::RsaPssSha256),
        (&ec, SignatureAlgorithm::EcdsaP256Sha256),
    ] {
        let sig = signer.sign(alg, msg).unwrap();
        let verdict =
            pdfcer_core::sign::verify_raw_signature(&signer.certificate_chain()[0], alg, msg, &sig);
        assert_eq!(verdict, Ok(()), "{alg:?}");
        // And a flipped bit is caught.
        let mut bad = sig.clone();
        bad[10] ^= 0x01;
        assert!(
            pdfcer_core::sign::verify_raw_signature(&signer.certificate_chain()[0], alg, msg, &bad)
                .is_err(),
            "{alg:?}: a corrupted signature verified"
        );
    }
}
