//! Subpath-level hit testing: the second selection level a CAD export needs.
//!
//! # The problem this capability answers
//!
//! A PDF path object may contain any number of subpaths, and a CAD producer
//! typically emits an entire drawing view as one. Measured on a real SolidWorks
//! export: page 1 object 5870 is a single stroked path with **1194 subpaths and
//! 6681 anchors** covering a 550×500 pt isometric view. Per-object hit testing
//! is working perfectly when it selects that object — and it is useless to the
//! operator, whose report was exactly this: *"how do I click on individual
//! lines and nodes to move or delete them?"*
//!
//! [`hit_test_subpaths`] is the query for the level below the object. The shell
//! decides WHEN to descend (a double-click); this decides WHAT is under the
//! pointer once it has.
//!
//! # Why the fixture is synthetic
//!
//! The export that motivated this is proprietary work product and is not in
//! this repository (`docs/LEGAL.md` §5). Only the structure is reproduced —
//! six lines between one `q` and one `S`, generated by
//! `tools/gen-multi-subpath-fixture.py`. The defect never needed 1194
//! subpaths; it needed more than one.

use std::path::{Path, PathBuf};

use pdfcer_core::document::Document;
use pdfcer_core::page_tree;
use pdfcer_core::vector::{
    Matrix, Point, decompose_page, hit_test_point_all, hit_test_subpaths, subpath_bounds,
};

fn fixture() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures/synthetic/vector/multi-subpath-one-object.pdf")
}

fn objects() -> pdfcer_core::vector::PageObjects {
    let bytes = std::fs::read(fixture())
        .unwrap_or_else(|e| panic!("missing fixture {}: {e}", fixture().display()));
    let doc = Document::from_bytes(bytes).expect("fixture parses");
    let pages = page_tree::pages(&doc).expect("pages");
    let page = pages.first().expect("one page");
    decompose_page(&doc.view(), page, Matrix::IDENTITY).expect("page decomposes")
}

/// The shape of the problem: six visible lines really are ONE object.
///
/// Asserted so the fixture cannot silently stop reproducing the condition. If
/// a future change split these into six objects, every assertion below would
/// still pass while testing nothing of interest.
#[test]
fn the_fixture_really_is_many_subpaths_in_one_object() {
    let m = objects();
    assert_eq!(
        m.objects.len(),
        1,
        "the six lines must decompose to ONE object, or this fixture no longer \
         reproduces the CAD-export structure"
    );
    let pdfcer_core::vector::VectorObject::Path(p) = &m.objects[0] else {
        panic!("expected a path object");
    };
    assert_eq!(p.subpaths.len(), 6, "six subpaths, one per line");
}

/// **The capability.** A click near one line names THAT line, not all six.
#[test]
fn a_click_names_the_one_subpath_it_landed_on() {
    let m = objects();
    // Just above horizontal B (y = 280), well clear of A (340) and C (220).
    let hits = hit_test_subpaths(&m, 0, Point::new(200.0, 281.0), 3.0);
    assert_eq!(
        hits.first().copied(),
        Some(1),
        "the nearest subpath to (200, 281) is horizontal B, index 1; got {hits:?}"
    );
}

/// **The ordering contract.** Nearest first, not paint order.
///
/// Placed between two horizontals but closer to the lower one, with a tolerance
/// wide enough that BOTH are hits — so the assertion is about the order, which
/// paint order would get wrong.
#[test]
fn overlapping_hits_come_back_nearest_first() {
    let m = objects();
    // y = 235: 15 pt above C (220), 45 pt below B (280). Tolerance 50 catches
    // both.
    let hits = hit_test_subpaths(&m, 0, Point::new(200.0, 235.0), 50.0);
    assert!(
        hits.len() >= 2,
        "the tolerance must be wide enough to hit both, or this tests nothing: {hits:?}"
    );
    assert_eq!(
        hits[0], 2,
        "horizontal C is 15 pt away and must come first; horizontal B is 45 pt away. \
         Paint order would put B first, which is the bug this asserts against. Got {hits:?}"
    );
    assert_eq!(hits[1], 1, "then horizontal B");
}

/// Empty space inside the object's bounding box hits no subpath.
///
/// The object's `page_bbox` spans 50,50 → 350,340 and most of that area is
/// blank. A subpath query that fell back to the bbox — the exact defect that
/// made a page-spanning text object win every click — would return hits here.
#[test]
fn empty_space_within_the_objects_bbox_hits_nothing() {
    let m = objects();
    // (250, 250) sits between the horizontals and clear of every vertical
    // (which stop at y = 180).
    assert!(
        hit_test_subpaths(&m, 0, Point::new(250.0, 250.0), 3.0).is_empty(),
        "a subpath query must not degrade into the object's bounding box"
    );
    // Positive control: the point IS inside the object's bbox, so this test is
    // exercising the discrimination rather than an early bbox reject.
    assert!(
        !hit_test_point_all(&m, Point::new(250.0, 250.0), 300.0).is_empty(),
        "the point must be within the object's reach for this to prove anything"
    );
}

/// A subpath's bounds describe the LINE, not the whole object.
///
/// This is what a shell outlines once a subpath is selected. Returning the
/// object's bbox here would draw a 300×290 rectangle around a 300×0 line and
/// tell the operator they had selected the whole view again.
#[test]
fn subpath_bounds_describe_the_subpath_not_the_object() {
    let m = objects();
    let b = subpath_bounds(&m, 0, 1).expect("horizontal B has bounds");
    assert!(
        (b.min.x - 50.0).abs() < 0.01 && (b.max.x - 350.0).abs() < 0.01,
        "x extent must be the line's own: {b:?}"
    );
    assert!(
        (b.max.y - b.min.y).abs() < 0.01 && (b.min.y - 280.0).abs() < 0.01,
        "a horizontal line must have zero height at its own y: {b:?}"
    );
}

/// Out-of-range and wrong-kind queries answer emptily rather than panicking.
///
/// The shell's selection depth is state that can outlive an edit, so a stale
/// index really can arrive here.
#[test]
fn out_of_range_queries_are_empty_rather_than_a_panic() {
    let m = objects();
    assert!(hit_test_subpaths(&m, 99, Point::new(200.0, 280.0), 3.0).is_empty());
    assert!(subpath_bounds(&m, 99, 0).is_none());
    assert!(subpath_bounds(&m, 0, 99).is_none());
}
