//! Tests for `pdfcer_core::form_script`, run against its public API.
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing
)]

use pdfcer_core::form_script::*;

/// The canonical generated calculate call classifies, with its operands
/// read out in source order.
#[test]
fn the_canonical_calculate_call_classifies_with_its_operands() {
    let js = br#"AFSimple_Calculate("SUM", new Array("Item.1","Item.2","Item.3"));"#;
    let ScriptClass::Calculate(CalcHelper::Simple { op, operands }) =
        classify(js, Trigger::Calculate)
    else {
        panic!("the canonical generated form must classify");
    };
    assert_eq!(op, SimpleOp::Sum);
    assert_eq!(operands.len(), 3);
    assert_eq!(operands[0], b"Item.1".to_vec());
    assert_eq!(operands[2], b"Item.3".to_vec());
}

/// All five operation codes match, and nothing else does.
#[test]
fn exactly_the_five_operation_codes_match() {
    for (code, want) in [
        ("SUM", SimpleOp::Sum),
        ("AVG", SimpleOp::Average),
        ("PRD", SimpleOp::Product),
        ("MIN", SimpleOp::Minimum),
        ("MAX", SimpleOp::Maximum),
    ] {
        let js = format!(r#"AFSimple_Calculate("{code}", ["A"]);"#);
        let ScriptClass::Calculate(CalcHelper::Simple { op, .. }) =
            classify(js.as_bytes(), Trigger::Calculate)
        else {
            panic!("{code} must classify");
        };
        assert_eq!(op, want);
    }
    for code in ["Sum", "sum", "TOTAL", "SUMX", ""] {
        let js = format!(r#"AFSimple_Calculate("{code}", ["A"]);"#);
        assert_eq!(
            classify(js.as_bytes(), Trigger::Calculate),
            ScriptClass::Custom,
            "{code:?} is not one of the five and must not be guessed at"
        );
    }
}

/// The canonical generated format call classifies with all six of its
/// parameters captured.
#[test]
fn the_canonical_number_format_call_classifies_with_all_parameters() {
    let js = br#"AFNumber_Format(2, 0, 0, 1, "$", true);"#;
    let ScriptClass::Format(FormatHelper::Number {
        decimals,
        separator_style,
        negative_style,
        currency_style,
        currency,
        prepend_currency,
    }) = classify(js, Trigger::Format)
    else {
        panic!("the canonical generated form must classify");
    };
    assert_eq!(decimals, 2);
    assert_eq!(separator_style, 0);
    assert_eq!(negative_style, 0);
    assert_eq!(currency_style, 1);
    assert_eq!(currency, b"$".to_vec());
    assert!(prepend_currency);
}

/// Each single-argument format helper classifies to its own variant, so
/// a date is never mistaken for a time.
#[test]
fn the_single_argument_format_helpers_stay_distinct() {
    assert_eq!(
        classify(b"AFDate_Format(1);", Trigger::Format),
        ScriptClass::Format(FormatHelper::Date { index: 1 })
    );
    assert_eq!(
        classify(b"AFTime_Format(1);", Trigger::Format),
        ScriptClass::Format(FormatHelper::Time { index: 1 })
    );
    assert_eq!(
        classify(b"AFSpecial_Format(0);", Trigger::Format),
        ScriptClass::Format(FormatHelper::Special { selector: 0 })
    );
    assert_eq!(
        classify(br#"AFDate_FormatEx("yyyy-mm-dd");"#, Trigger::Format),
        ScriptClass::Format(FormatHelper::DateEx {
            format: b"yyyy-mm-dd".to_vec()
        })
    );
}

/// **A helper on the wrong trigger does not classify.**
///
/// The pairing check exists for one case above all: a format helper
/// must never be reachable through a path that writes `/V`. Acrobat
/// generates calculation helpers on `/C` and format helpers on `/F`; a
/// crossed pair was not generated by Acrobat, and pdfcer declines to
/// guess what it was.
#[test]
fn a_helper_on_the_wrong_trigger_is_custom() {
    assert_eq!(
        classify(br#"AFNumber_Format(2,0,0,0,"",true);"#, Trigger::Calculate),
        ScriptClass::Custom,
        "a format helper on the calculate trigger must not be reachable \
         from a code path that writes /V"
    );
    assert_eq!(
        classify(br#"AFSimple_Calculate("SUM", ["A"]);"#, Trigger::Format),
        ScriptClass::Custom,
        "and a calculation helper on the format trigger is equally not \
         what it appears to be"
    );
}

/// A whitelisted name with an argument list that does not fit is
/// `Custom` — pdfcer does not fill in a missing argument with a default
/// it invented.
#[test]
fn a_known_name_with_an_unknown_signature_is_custom() {
    for js in [
        br#"AFNumber_Format(2, 0, 0, 0, "");"#.as_slice(),
        br#"AFNumber_Format(2, 0, 0, 0, "", true, 9);"#,
        br#"AFNumber_Format("2", 0, 0, 0, "", true);"#,
        br#"AFNumber_Format(2.5, 0, 0, 0, "", true);"#,
        br#"AFNumber_Format(2, 0, 0, 0, "", 1);"#,
    ] {
        assert_eq!(
            classify(js, Trigger::Format),
            ScriptClass::Custom,
            "{}",
            String::from_utf8_lossy(js)
        );
    }
    for js in [
        br#"AFSimple_Calculate("SUM");"#.as_slice(),
        br#"AFSimple_Calculate("SUM", ["A"], 1);"#,
        br#"AFSimple_Calculate("SUM", "A");"#,
        br#"AFSimple_Calculate("SUM", ["A", 2]);"#,
    ] {
        assert_eq!(
            classify(js, Trigger::Calculate),
            ScriptClass::Custom,
            "{}",
            String::from_utf8_lossy(js)
        );
    }
}

/// `AFRange_Validate` is disclosed as a constraint, and a **disabled**
/// bound is reported as absent rather than as its meaningless number.
#[test]
fn range_validate_reports_only_the_bounds_that_are_enabled() {
    assert_eq!(
        classify(b"AFRange_Validate(true, 1, true, 100);", Trigger::Validate),
        ScriptClass::Advisory(AdvisoryHelper::RangeValidate {
            lower: Some(1.0),
            upper: Some(100.0)
        })
    );
    assert_eq!(
        classify(b"AFRange_Validate(true, 1, false, 0);", Trigger::Validate),
        ScriptClass::Advisory(AdvisoryHelper::RangeValidate {
            lower: Some(1.0),
            upper: None
        }),
        "a disabled bound's number is not a bound"
    );
}

/// The keystroke family is recognised by shape, and only on its own
/// trigger.
#[test]
fn the_keystroke_family_is_disclosed_but_only_on_its_own_trigger() {
    let js = br#"AFNumber_Keystroke(2, 0, 0, 0, "", true);"#;
    assert_eq!(
        classify(js, Trigger::Keystroke),
        ScriptClass::Advisory(AdvisoryHelper::Keystroke {
            name: "AFNumber_Keystroke".to_owned()
        })
    );
    assert_eq!(
        classify(js, Trigger::Format),
        ScriptClass::Custom,
        "a keystroke filter on the format trigger is not a format helper"
    );
}

/// An advisory is recognised but **not** reproducible — the distinction
/// a caller uses to decide whether to offer a recompute.
#[test]
fn advisories_are_recognised_but_not_reproducible() {
    let advisory = classify(b"AFRange_Validate(true, 1, true, 9);", Trigger::Validate);
    assert_ne!(advisory, ScriptClass::Custom, "it is recognised");
    assert!(!advisory.is_reproducible(), "and still not reproducible");

    let calc = classify(br#"AFSimple_Calculate("SUM", ["A"]);"#, Trigger::Calculate);
    assert!(calc.is_reproducible());
    assert!(!ScriptClass::Custom.is_reproducible());
}

/// Author code that merely mentions a helper name is `Custom`, which is
/// the whole safety property restated at the classifier's own boundary.
#[test]
fn author_code_mentioning_a_helper_is_still_custom() {
    for js in [
        b"var t = 0; AFSimple_Calculate(\"SUM\", [\"A\"]);".as_slice(),
        b"if (this.getField(\"X\").value) AFSimple_Calculate(\"SUM\", [\"A\"]);",
        b"event.value = this.getField(\"A\").value * 2;",
        b"myAFSimple_Calculate(\"SUM\", [\"A\"]);",
    ] {
        assert_eq!(
            classify(js, Trigger::Calculate),
            ScriptClass::Custom,
            "{}",
            String::from_utf8_lossy(js)
        );
    }
}
