//! Integration tests for cross-reference RECOVERY (decision 013 Pass B).
//!
//! Pass B adds a rebuild-by-scan fallback: when a file's stored
//! cross-reference machinery cannot be parsed, pdfcer reconstructs the
//! cross-reference table and trailer by scanning the whole buffer for
//! `N G obj` headers and walking recovered object streams. These tests
//! drive that path over the synthetic controls in
//! `fixtures/synthetic/xref-recover/` (generated by
//! `tools/gen-xref-recover-fixtures.py`); each is a deliberately-damaged
//! or headerless document that STRICT loading rejects.
//!
//! What is asserted, per fixture:
//! - the recoverable ones **open** via [`Document::from_bytes`], expose a
//!   [`RecoveryReport`] (never `None`), and resolve their `/Catalog`;
//! - the counted disclosure is populated (fuzzy-never-sneaky, R20);
//! - the recovered document REFUSES `save_incremental` by name and its
//!   `save_full` produces a reloadable file with a fresh valid classic xref
//!   (the recovered-base-forces-full-rewrite rule, decision 013 §9);
//! - the unrecoverable one **refuses** cleanly (no `/Catalog`), never
//!   returning a garbage document.
//!
//! Structure mirrors `tests/xref_eol.rs` (Pass A).

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::path::PathBuf;

use pdfcer_core::document::{DocError, Document};
use pdfcer_core::object::Object;
use pdfcer_core::recover::{RecoverError, RecoveryReason, TrailerSource};
use pdfcer_core::writer::{DirtySet, SaveOptions, WriteError, save_full, save_incremental};

/// Read a fixture from `fixtures/synthetic/xref-recover/`.
fn fixture(name: &str) -> Vec<u8> {
    let path: PathBuf = [
        env!("CARGO_MANIFEST_DIR"),
        "..",
        "..",
        "fixtures",
        "synthetic",
        "xref-recover",
        name,
    ]
    .iter()
    .collect();
    std::fs::read(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
}

/// Load a fixture, asserting it opened VIA RECOVERY (not the strict path)
/// and resolves to a one-page document, and return the loaded `Document`.
fn assert_recovers(name: &str) -> Document {
    let doc = Document::from_bytes(fixture(name))
        .unwrap_or_else(|e| panic!("{name} failed to recover: {e}"));
    let report = doc
        .recovery()
        .unwrap_or_else(|| panic!("{name} loaded but was NOT flagged as recovered"));
    // The disclosure must be populated: at least one object recovered.
    assert!(
        report.file_level_objects + report.objstm_objects > 0,
        "{name}: recovery report has no objects"
    );
    // The catalog must resolve — recovery refuses without one, so a loaded
    // recovered document always has it.
    let cat = doc
        .catalog()
        .unwrap_or_else(|e| panic!("{name}: catalog: {e}"));
    assert_eq!(
        cat.get(b"Type")
            .and_then(Object::as_name)
            .map(|n| n.as_bytes()),
        Some(&b"Catalog"[..]),
        "{name}: /Root is not a /Catalog"
    );
    doc
}

/// A recovered document must refuse `save_incremental` by name and produce a
/// reloadable file from `save_full` (the recovered-base rule).
fn assert_full_rewrite_only(name: &str, doc: &Document) {
    let refused = save_incremental(doc, &DirtySet::empty(), &SaveOptions::identity());
    assert!(
        matches!(refused, Err(WriteError::RecoveredBaseForbidsIncremental)),
        "{name}: save_incremental should be refused by name, got {refused:?}"
    );

    let (bytes, _report) = save_full(doc, &DirtySet::empty(), &SaveOptions::identity())
        .unwrap_or_else(|e| panic!("{name}: save_full: {e}"));
    // The rewritten file must load CLEANLY now — a fresh valid classic xref
    // means recovery does NOT fire on the second load.
    let back = Document::from_bytes(bytes).unwrap_or_else(|e| panic!("{name}: reload: {e}"));
    assert!(
        back.recovery().is_none(),
        "{name}: the full-rewrite output still triggers recovery (its xref is not clean)"
    );
    assert_eq!(
        back.object_count(),
        doc.object_count(),
        "{name}: object count changed across the recovered full rewrite"
    );
}

#[test]
fn offset_shifted_startxref_recovers() {
    let doc = assert_recovers("offset-shifted-startxref.pdf");
    let r = doc.recovery().unwrap();
    assert_eq!(r.reason, RecoveryReason::NotAnXrefSection);
    assert_eq!(r.trailer_source, TrailerSource::TrailerKeyword);
    assert_eq!(doc.object_count(), 4);
    assert_full_rewrite_only("offset-shifted-startxref.pdf", &doc);
}

#[test]
fn no_startxref_recovers() {
    let doc = assert_recovers("no-startxref.pdf");
    assert_eq!(
        doc.recovery().unwrap().reason,
        RecoveryReason::StartxrefNotFound
    );
    assert_eq!(doc.object_count(), 4);
    assert_full_rewrite_only("no-startxref.pdf", &doc);
}

#[test]
fn startxref_out_of_range_recovers() {
    let doc = assert_recovers("startxref-out-of-range.pdf");
    assert_eq!(
        doc.recovery().unwrap().reason,
        RecoveryReason::BadStartxrefOffset
    );
    assert_eq!(doc.object_count(), 4);
    assert_full_rewrite_only("startxref-out-of-range.pdf", &doc);
}

#[test]
fn xref_stream_corrupt_recovers_file_level_and_objstm() {
    let doc = assert_recovers("xref-stream-corrupt.pdf");
    let r = doc.recovery().unwrap();
    // The trailer comes from the /Type /XRef dictionary (no `trailer` kw).
    assert_eq!(r.trailer_source, TrailerSource::XrefStreamDict);
    // Object 6 is compressed in the object stream (object 5): it must be
    // recovered as a type-2 entry.
    assert!(
        r.objstm_objects >= 1,
        "expected at least one ObjStm-recovered object, got {}",
        r.objstm_objects
    );
    // Objects 1-5 + 7 file-level, 6 from the ObjStm = 7 total.
    assert_eq!(doc.object_count(), 7);
    // Object 6 (the ExtGState in the ObjStm) resolved.
    let g6 = doc
        .resolve(&Object::Reference(pdfcer_core::object::ObjId::new(6, 0)))
        .as_dict()
        .cloned();
    assert!(
        g6.is_some(),
        "compressed object 6 not resolvable after recovery"
    );
    assert_full_rewrite_only("xref-stream-corrupt.pdf", &doc);
}

#[test]
fn duplicate_superseded_last_wins() {
    let doc = assert_recovers("duplicate-superseded.pdf");
    let r = doc.recovery().unwrap();
    assert!(
        r.last_wins_collisions >= 1,
        "expected a last-wins collision for the duplicated object 3"
    );
    // Last-valid-wins: the SECOND definition of object 3 governs.
    let page3 = doc
        .get(pdfcer_core::object::ObjId::new(3, 0))
        .expect("object 3 present");
    let note = page3
        .value
        .as_dict()
        .and_then(|d| d.get(b"Note"))
        .and_then(|o| match o {
            Object::String(s) => Some(s.clone()),
            _ => None,
        });
    assert_eq!(
        note.as_deref(),
        Some(&b"SECOND"[..]),
        "recovery picked the wrong revision of the duplicated object"
    );
    assert_full_rewrite_only("duplicate-superseded.pdf", &doc);
}

#[test]
fn offset_start_recovers_header_independent() {
    let doc = assert_recovers("offset-start.pdf");
    let r = doc.recovery().unwrap();
    assert_eq!(r.reason, RecoveryReason::MissingHeader);
    assert!(
        r.offset_start,
        "offset_start flag should be set for leading junk"
    );
    // Version was still detected by the whole-buffer %PDF- scan.
    assert_eq!(doc.version().to_string(), "1.7");
    assert_eq!(doc.object_count(), 4);
    assert_full_rewrite_only("offset-start.pdf", &doc);
}

/// The LF→CRLF conversion shape — the cause behind 337 of the 341
/// corpus files that were unopenable with `BadContents`.
///
/// Both halves of the damage are asserted: the object count proves the
/// content stream was NOT dropped by confirmation (it was, before the
/// `StreamLengthPolicy::RecoverFromEndstream` fix, leaving 3 of 4), and
/// `stream_lengths_recovered` proves the repair is counted for disclosure
/// rather than applied silently. Extracting the text proves the recovered
/// extent is the real payload and not a truncation — a file that "opens"
/// as a blank page would satisfy every structural assertion above and
/// still be a non-fix.
#[test]
fn crlf_shifted_lengths_recovers_the_content_stream() {
    let doc = assert_recovers("crlf-shifted-lengths.pdf");
    let r = doc.recovery().unwrap();
    assert_eq!(r.reason, RecoveryReason::NotAnXrefSection);
    assert_eq!(
        r.file_level_objects, 4,
        "the content stream must survive confirmation despite its stale /Length"
    );
    assert_eq!(
        r.stream_lengths_recovered, 1,
        "the one re-derived extent is counted, not silently absorbed"
    );
    assert_eq!(doc.object_count(), 4);

    // The page resolves to a real content stream, and that stream holds
    // the real text.
    let pages = pdfcer_core::page_tree::pages(&doc).expect("page tree");
    assert_eq!(pages.len(), 1);
    assert_eq!(pages[0].contents.len(), 1);
    assert_eq!(
        pages[0].contents_unresolved, 0,
        "nothing degraded — the object was genuinely recovered"
    );
    let text = pdfcer_core::text_extract::extract_document(
        &doc,
        &pdfcer_core::text_extract::ExtractOptions::default(),
    )
    .expect("extract");
    assert!(
        text.plain_text().contains("crlf shifted lengths"),
        "recovered stream must carry the real content, got {:?}",
        text.plain_text()
    );

    assert_full_rewrite_only("crlf-shifted-lengths.pdf", &doc);
}

/// A dangling single `/Contents` reference on a file whose cross-reference
/// table is VALID: it loads on the strict path (no recovery), yields an
/// empty page, discloses the omission, and — the §5 point — still saves
/// byte-identically, because degrading a `/Contents` element changes
/// nothing about the bytes pdfcer is holding.
#[test]
fn dangling_contents_degrades_on_the_strict_path_and_round_trips() {
    let source = fixture("dangling-contents.pdf");
    let doc = Document::from_bytes(source.clone()).expect("must load");
    assert!(
        doc.recovery().is_none(),
        "this fixture's xref is valid — it must NOT take the recovery path"
    );

    let pages = pdfcer_core::page_tree::pages(&doc).expect("a dangling /Contents is not fatal");
    assert_eq!(pages.len(), 1);
    assert!(
        pages[0].contents.is_empty(),
        "Table 30: absent /Contents = an empty page"
    );
    assert_eq!(
        pages[0].contents_unresolved, 1,
        "the omission is disclosed, so an empty page is distinguishable from a blank one"
    );

    // ARCHITECTURE.md §5: nothing was touched, so an empty-dirty-set
    // incremental save must reproduce the source bytes exactly.
    let (bytes, _report) =
        save_incremental(&doc, &DirtySet::empty(), &SaveOptions::identity()).expect("save");
    assert_eq!(
        bytes, source,
        "a document that opens via a degraded /Contents must still round-trip byte-identically"
    );
}

/// The array form: the dangling element is dropped, the two real streams
/// survive **in order**, and the count discloses the one omission.
#[test]
fn dangling_contents_array_keeps_the_surviving_streams_in_order() {
    let source = fixture("dangling-contents-array.pdf");
    let doc = Document::from_bytes(source.clone()).expect("must load");
    assert!(doc.recovery().is_none());

    let pages = pdfcer_core::page_tree::pages(&doc).expect("must walk");
    assert_eq!(pages.len(), 1);
    let nums: Vec<u32> = pages[0].contents.iter().map(|id| id.num).collect();
    assert_eq!(
        nums,
        vec![4, 6],
        "surviving elements keep their order — Table 30 concatenates them"
    );
    assert_eq!(pages[0].contents_unresolved, 1);

    let (bytes, _report) =
        save_incremental(&doc, &DirtySet::empty(), &SaveOptions::identity()).expect("save");
    assert_eq!(bytes, source, "\u{a7}5 holds for the array form too");
}

#[test]
fn unrecoverable_no_catalog_refuses_clean() {
    let err = Document::from_bytes(fixture("unrecoverable-no-catalog.pdf")).unwrap_err();
    assert!(
        matches!(err, DocError::Recovery(RecoverError::NoCatalog)),
        "expected a clean NoCatalog refusal, got {err:?}"
    );
}

/// The `/Pages` node has no `endobj`, and pdfcer must not lose it — nor
/// write a catalog naming an object it dropped.
///
/// # The defect this exists for
///
/// Found 2026-08-07 by `tools/verapdf-parse-gate.py`, the first
/// independent judge of pdfcer's own output. On qpdf's `bad6.pdf` pdfcer
/// wrote a document whose catalog said `/Pages 2 0 R` while object 2 was
/// **absent from the file**: the missing `endobj` made
/// `confirm_candidates` drop it, and the writer emitted the dangling
/// reference without complaint. veraPDF could recover the original and
/// could not recover pdfcer's rewrite of it — a file made strictly worse
/// by passing through pdfcer.
///
/// # Why this asserts on BYTES (R159)
///
/// Every forms/round-trip test that missed the equivalent flatten defect
/// asserted through pdfcer's own model, and `Document::get` follows
/// §7.3.10 by resolving a dangling reference to **null rather than an
/// error**. So a model-level check cannot distinguish "object 2 is
/// present" from "object 2 is missing and reads as null" — the exact
/// blindness R159 was minted for. The assertion is therefore on the saved
/// bytes.
#[test]
fn missing_endobj_on_page_tree_is_recovered_and_saved() {
    let doc = assert_recovers("missing-endobj-page-tree.pdf");
    let r = doc.recovery().unwrap();

    assert_eq!(
        r.missing_endobj_recovered, 1,
        "exactly one definition (the /Pages node) omits endobj, and the \
         repair must be COUNTED so it can be disclosed (R20) rather than \
         silently absorbed",
    );
    assert_eq!(
        doc.object_count(),
        4,
        "all four objects survive; before the fix object 2 was dropped and \
         this was 3",
    );

    // R162: prove the container could hold the thing being asserted.
    // "object 2 is in the file" means nothing unless the catalog actually
    // asks for object 2 — otherwise this test would pass against a
    // document that never referenced it.
    let root = doc.catalog().expect("recovered document resolves /Root");
    let pages_ref = root
        .get(b"Pages")
        .and_then(Object::as_reference)
        .expect("the catalog names a /Pages object");
    assert_eq!(
        pages_ref.num, 2,
        "the fixture's catalog must reference object 2 for this test to \
         be about anything",
    );

    let bytes = save_full(&doc, &DirtySet::empty(), &SaveOptions::default())
        .expect("a recovered document saves by full rewrite")
        .0;

    // The byte-level claim. A dangling /Pages resolves to null under
    // §7.3.10, so only the bytes can answer this.
    let has_obj_2 = bytes.windows(b"2 0 obj".len()).any(|w| w == b"2 0 obj");
    assert!(
        has_obj_2,
        "the saved file must DEFINE object 2, not merely reference it — \
         the catalog says /Pages 2 0 R, and a file that names a page tree \
         it does not contain is unreadable to any conforming reader",
    );

    // And the document pdfcer wrote must be one pdfcer can read back with
    // its page tree intact — the property that was actually broken.
    let back = Document::from_bytes(bytes).expect("saved file reloads");
    let reloaded_pages = back
        .catalog()
        .ok()
        .and_then(|c| c.get(b"Pages").cloned())
        .map(|p| back.resolve(&p).as_dict().is_some())
        .unwrap_or(false);
    assert!(
        reloaded_pages,
        "the reloaded catalog's /Pages must resolve to a dictionary",
    );
}

/// A full rewrite REFUSES a file whose highest object number would make
/// the cross-reference table astronomically large — instead of grinding.
///
/// # The defect this pins
///
/// §7.5.4 obliges a single-section full rewrite to emit one entry per
/// object number from 0 to the highest **defined in the file**, "even if
/// one or more of the object numbers in this range do not actually occur".
/// The writer's cost is therefore set by the largest object NUMBER, not by
/// how many objects exist — so a 639-byte document naming
/// `2147483648 0 obj` asks for 2,147,483,649 entries, about 40 GB.
///
/// Found by `tools/verapdf-parse-gate.py` on pdfium's `bug_455199.pdf`,
/// which stalled a corpus sweep for over thirty minutes. Measured at
/// ~27 MB/s of steady allocation with the CPU pinned: **not an infinite
/// loop**, which is exactly what made it dangerous — it looks like
/// progress the whole way down, and in the GUI it is an unrecoverable
/// freeze with no error, no cancel and no save.
///
/// # Why this test is not vacuous (R162)
///
/// Two halves, and the second is what gives the first meaning:
///
/// 1. The document must **LOAD CLEANLY** — no recovery. If it failed to
///    parse, the refusal below would be a parse failure wearing a
///    writer's name, and the test would pass while proving nothing about
///    the writer.
/// 2. The refusal must be **this** refusal, by variant, not merely some
///    `Err`. A test asserting `is_err()` would have passed before the fix
///    existed only by hanging, and would keep passing if the guard were
///    later replaced by an unrelated failure.
///
/// Verified to fail without the fix by the only means available for a
/// non-terminating defect: with the guard removed this call does not
/// return, and the CLI equivalent was measured hanging past 30 minutes.
#[test]
fn full_rewrite_refuses_an_astronomical_object_number() {
    let bytes = fixture("huge-object-number.pdf");
    let doc = Document::from_bytes(bytes).expect("the fixture must parse on the STRICT path");

    // Half one: it really did load without recovery, so what follows is a
    // writer verdict rather than a reader one.
    assert!(
        doc.recovery().is_none(),
        "this fixture must load with NO cross-reference recovery — if it \
         needed recovery, the refusal below would prove nothing about the \
         writer, only that a damaged file was rejected",
    );

    let err = save_full(&doc, &DirtySet::empty(), &SaveOptions::identity())
        .expect_err("a full rewrite must REFUSE rather than build a 2-billion-entry table");

    // Half two: the specific refusal, by variant.
    match err {
        WriteError::ObjectNumberTooLarge { num, max } => {
            assert_eq!(
                num, 2_147_483_648,
                "the offending object number is reported"
            );
            assert!(
                max < num,
                "the bound must be below the offending number, or the guard \
                 could not have fired on it",
            );
        }
        other => panic!(
            "expected ObjectNumberTooLarge, got {other:?} — any other error \
             means the hang is being avoided for an unrelated reason and this \
             test is no longer pinning the defect it names"
        ),
    }
}
