//! # `pdfcer embed-font` integration tests
//!
//! Black-box tests over the **real binary** for Pass 67.0 phase E — the fix
//! for the problem that started the Pass: a print-on-demand service rejecting
//! a book because a font the PDF names is not carried inside it.
//! `pdfcer_core::font_embed_missing`'s own unit tests pin the planning and the
//! object surgery; these pin the *contract the CLI publishes* — the stdout
//! shape a batch sweep parses, the exit codes a script branches on, and the
//! disclosures that make an inference something an operator can consent to.
//!
//! ## What these tests are protecting
//!
//! 1. **The dry run is the default.** Not because embedding destroys
//!    anything — it does not — but because it is an *inference*: pdfcer is
//!    choosing font programs the document did not carry, and on a typical run
//!    some of those are stand-ins. A command that wrote on the first
//!    invocation would make "show me what you would pick" and "pick it" the
//!    same act (project rule 4).
//!
//! 2. **★ `match=` is on every embedded row.** `exact` means the folder held
//!    the face the document names; `alias` means a metric-compatible stand-in;
//!    `bundled` means one of pdfcer's own faces. That is the disclosure rule 4
//!    governs, and it is asserted directly — a report that said only "3 fonts
//!    embedded" would look correct and would have lost the point.
//!
//! 3. **★ `not_embedded_after` is on the summary line.** The number the
//!    operator is actually trying to drive to zero, and the one a report that
//!    showed only pdfcer's successes would omit. A file where three of seven
//!    fonts were embedded is a file a print service will still reject.
//!
//! 4. **Every refusal is printed by name, with its reason.** Same posture as
//!    `unembed-font`, and the reason *sentence* is asserted rather than the
//!    token alone, because the sentence is what tells the operator what would
//!    fix it.
//!
//! 5. **The input is never touched**, in any mode. Asserted by byte
//!    comparison, because "nothing currently writes to the input" is not a
//!    contract.
//!
//! ## Why `--use-bundled-fonts` is what these tests embed from
//!
//! It is the only donor source that exists on every machine CI might run on.
//! A test that pointed `--font-dir` at `C:\Windows\Fonts` would pass on the
//! author's laptop and be vacuous everywhere else — and a vacuous test that
//! passes is worse than no test. Coverage against a real system font folder
//! is measured by `tools/embed-sweep`, which is a harness rather than a gate
//! precisely because its numbers depend on the machine.
//!
//! Fixtures (provenance in `fixtures/synthetic/embed/PROVENANCE.md`).

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::path::{Path, PathBuf};
use std::process::Command;

const BIN: &str = env!("CARGO_BIN_EXE_pdfcer");

/// `exit::EDIT_REFUSED`. Spelled out rather than imported, so a change to the
/// number is a test failure rather than an invisible contract break.
const EDIT_REFUSED: i32 = 9;

fn fixture(rel: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures/synthetic")
        .join(rel)
}

/// Run `embed-font` and return `(exit code, stdout, stderr)`.
fn run(rel: &str, args: &[&str]) -> (i32, String, String) {
    let out = Command::new(BIN)
        .arg("embed-font")
        .arg(fixture(rel))
        .args(args)
        .output()
        .expect("pdfcer runs");
    (
        out.status.code().unwrap_or(-1),
        String::from_utf8_lossy(&out.stdout).into_owned(),
        String::from_utf8_lossy(&out.stderr).into_owned(),
    )
}

/// The synthetic donor folder, generated by `tools/gen-embed-fixtures.py`.
///
/// Each file is a copy of the project's own synthetic sfnt, named for a
/// fixture's `/BaseFont`, so `--font-dir`'s filename-stem registration
/// resolves it on ANY machine. See this file's header for why pointing these
/// tests at a real system font folder would be worse than useless.
fn fonts_dir() -> PathBuf {
    fixture("embed/fonts")
}

/// A folder holding ONLY the `fsType`-Restricted donor, under the name the
/// fixture asks for — so the licence guard is exercised without the
/// permissive copy of the same face shadowing it.
fn restricted_dir() -> PathBuf {
    let dir = std::env::temp_dir().join("pdfcer-embed-restricted");
    std::fs::create_dir_all(&dir).expect("temp dir");
    std::fs::copy(
        fixture("embed/fonts/pdfceRestricted.ttf"),
        dir.join("pdfceMissing.ttf"),
    )
    .expect("copy donor");
    dir
}

fn temp_out(name: &str) -> PathBuf {
    let dir = std::env::temp_dir().join("pdfcer-embed-tests");
    std::fs::create_dir_all(&dir).expect("temp dir");
    dir.join(name)
}

fn list_fonts(path: &Path) -> String {
    let out = Command::new(BIN)
        .arg("list-fonts")
        .arg(path)
        .output()
        .expect("pdfcer runs");
    String::from_utf8_lossy(&out.stdout).into_owned()
}

/// The default is a DRY RUN: the full report is printed, the exit is clean,
/// and nothing is written.
#[test]
fn the_default_is_a_dry_run() {
    let (code, stdout, stderr) = run(
        "embed/embed-std14-bare.pdf",
        &["--all-missing", "--use-bundled-fonts"],
    );
    assert_eq!(code, 0, "stderr:\n{stderr}");
    assert!(stdout.contains("applied=0"), "stdout:\n{stdout}");
    assert!(
        stderr.contains("DRY RUN"),
        "the dry run says so, in words:\n{stderr}"
    );
    assert!(stdout.contains("embed name=\"Helvetica\""), "{stdout}");
}

/// ★ The exact-vs-substitute disclosure is on the row, and the stand-in
/// warning is on stderr. Rule 4: pdfcer is choosing a font the document did
/// not carry, and the operator sees WHICH before it becomes document state.
#[test]
fn the_match_quality_is_disclosed_per_font() {
    let (_, stdout, stderr) = run(
        "embed/embed-std14-bare.pdf",
        &["--all-missing", "--use-bundled-fonts"],
    );
    assert!(stdout.contains("match=bundled"), "stdout:\n{stdout}");
    assert!(stdout.contains("face=\"FoxitSans\""), "stdout:\n{stdout}");
    assert!(stdout.contains("exact=0 substitute=1"), "stdout:\n{stdout}");
    assert!(
        stderr.contains("STAND-IN face"),
        "a substitute must be called one, in words:\n{stderr}"
    );
    // ★ And the fear this feature has to defuse, stated as the certainty it
    // is: the text cannot move.
    assert!(
        stderr.contains("POSITIONS do not change"),
        "stderr:\n{stderr}"
    );
}

/// ★ `not_embedded_after` reaches 0, and `list-fonts` on the OUTPUT agrees.
///
/// The end-to-end proof that the operator's actual problem is solved: the
/// report's own claim is checked against a fresh parse by a different
/// command, so a report that lied would fail here rather than at a print
/// service.
#[test]
fn embedding_drives_not_embedded_to_zero_and_list_fonts_agrees() {
    let out = temp_out("std14-bare.pdf");
    let (code, stdout, stderr) = run(
        "embed/embed-std14-bare.pdf",
        &[
            "--all-missing",
            "--use-bundled-fonts",
            "--apply",
            "-o",
            out.to_str().unwrap(),
        ],
    );
    assert_eq!(code, 0, "stderr:\n{stderr}");
    assert!(
        stdout.contains("not_embedded_before=1 not_embedded_after=0"),
        "stdout:\n{stdout}"
    );
    let listing = list_fonts(&out);
    assert!(
        !listing.contains("not-embedded="),
        "the output must carry no non-embedded font at all:\n{listing}"
    );
    assert!(listing.contains("embedded=FontFile3"), "{listing}");
}

/// Partial success is the COMMON case and is reported per font: what was
/// embedded, what was refused, and how many are still missing.
#[test]
fn partial_success_names_every_font_and_states_what_is_left() {
    let (code, stdout, stderr) = run(
        "embed/embed-mixed.pdf",
        &["--all-missing", "--use-bundled-fonts"],
    );
    assert_eq!(code, 0, "stderr:\n{stderr}");
    // Embedded.
    assert!(stdout.contains("embed name=\"Helvetica\""), "{stdout}");
    // Refused, each by name.
    assert!(
        stdout.contains("refused name=\"pdfceComposite\""),
        "{stdout}"
    );
    assert!(stdout.contains("reason=composite"), "{stdout}");
    assert!(stdout.contains("reason=type3"), "{stdout}");
    assert!(stdout.contains("reason=already-embedded"), "{stdout}");
    // ★ The reason SENTENCE, not just the token — it is what tells the
    // operator that no other font file could ever satisfy a CID font.
    assert!(
        stdout.contains("would draw the wrong characters"),
        "the composite refusal must explain itself:\n{stdout}"
    );
    // ★ And what is still unsolved, on the summary line and on stderr.
    assert!(stdout.contains("not_embedded_after=3"), "{stdout}");
    assert!(
        stderr.contains("will STILL have no embedded program"),
        "stderr:\n{stderr}"
    );
}

/// With no donor source at all, every missing font is refused BY NAME and the
/// message says what would fix it. This is the commonest headless outcome.
#[test]
fn with_no_font_source_every_font_is_refused_by_name() {
    let (code, stdout, stderr) = run("embed/embed-std14-bare.pdf", &["--all-missing"]);
    assert_eq!(
        code, EDIT_REFUSED,
        "a dry run that can do nothing exits non-zero"
    );
    assert!(stdout.contains("refused name=\"Helvetica\""), "{stdout}");
    assert!(stdout.contains("reason=no-source-font"), "{stdout}");
    assert!(
        stdout.contains("C:\\Windows\\Fonts"),
        "the refusal must name where to point pdfcer:\n{stdout}"
    );
    assert!(
        stderr.contains("no font folder supplied"),
        "stderr:\n{stderr}"
    );
}

/// `--apply` without `--output` is refused before the document is opened.
#[test]
fn apply_without_output_is_refused() {
    let (code, _, stderr) = run(
        "embed/embed-std14-bare.pdf",
        &["--all-missing", "--use-bundled-fonts", "--apply"],
    );
    assert_eq!(code, EDIT_REFUSED);
    assert!(stderr.contains("--apply needs --output"), "{stderr}");
}

/// A `--font` name that matches nothing exits non-zero rather than reporting
/// success over a document it did not change.
#[test]
fn an_unmatched_name_is_reported_and_exits_non_zero() {
    let (code, stdout, stderr) = run(
        "embed/embed-std14-bare.pdf",
        &["--font", "NoSuchFont", "--use-bundled-fonts"],
    );
    assert_eq!(code, EDIT_REFUSED);
    assert!(stdout.contains("unmatched \"NoSuchFont\""), "{stdout}");
    assert!(stderr.contains("matched no font"), "{stderr}");
}

/// The `Attach` shape, end to end, and the sharpest round-trip claim in the
/// Pass: ONE key onto ONE descriptor, and the input revision left
/// byte-identical inside the output by the incremental save.
#[test]
fn attaching_adds_one_key_and_leaves_the_input_revision_byte_identical() {
    let out = temp_out("attach.pdf");
    let input = fixture("embed/embed-attach.pdf");
    let before = std::fs::read(&input).unwrap();
    let (code, stdout, stderr) = run(
        "embed/embed-attach.pdf",
        &[
            "--all-missing",
            "--font-dir",
            fonts_dir().to_str().unwrap(),
            "--apply",
            "-o",
            out.to_str().unwrap(),
        ],
    );
    assert_eq!(
        code, 0,
        "stdout:
{stdout}
stderr:
{stderr}"
    );
    assert!(stdout.contains("shape=attach"), "{stdout}");
    assert!(stdout.contains("key=FontFile2"), "{stdout}");
    assert!(
        stdout.contains("match=exact"),
        "the stem IS the name:
{stdout}"
    );
    assert!(
        stdout.contains("widths=0 encoding=0 descriptor=0"),
        "attach writes NOTHING but the one key:
{stdout}"
    );
    assert!(
        stdout.contains("objects=2"),
        "one descriptor + one stream, nothing else:
{stdout}"
    );
    // The round-trip invariant, over BYTES: an incremental save appends, so
    // every byte of the input must still be there, in place, unaltered.
    let written = std::fs::read(&out).unwrap();
    assert!(
        written.starts_with(&before),
        "an incremental save must leave the input revision byte-identical"
    );
    // And the input file itself is untouched, which has to hold in every
    // mode including the ones that refuse.
    assert_eq!(std::fs::read(&input).unwrap(), before);
}

/// ★ §9.9's opening paragraph at the CLI boundary: a donor whose own
/// `fsType` says it may not be embedded is refused BY NAME.
///
/// Paired with the permissive donor over the same fixture in the test above,
/// so this cannot pass by refusing everything — which is exactly how this
/// guard would look correct while doing nothing.
#[test]
fn a_donor_whose_licence_forbids_embedding_is_refused() {
    let (code, stdout, _) = run(
        "embed/embed-attach.pdf",
        &[
            "--font",
            "pdfceMissing",
            "--font-dir",
            restricted_dir().to_str().unwrap(),
        ],
    );
    assert_eq!(code, EDIT_REFUSED, "{stdout}");
    assert!(stdout.contains("reason=embedding-forbidden"), "{stdout}");
    assert!(
        stdout.contains("may not be embedded"),
        "the refusal must say whose decision it is:
{stdout}"
    );
}

/// ★ Two differently-named fonts through one `/FontDescriptor` block BOTH —
/// where unembedding the same shape is idempotent and does not. The
/// divergence from the mirror module, asserted where an operator would meet
/// it.
#[test]
fn a_shared_descriptor_blocks_both_fonts() {
    let (code, stdout, _) = run(
        "embed/embed-shared-descriptor.pdf",
        &["--all-missing", "--font-dir", fonts_dir().to_str().unwrap()],
    );
    assert_eq!(code, EDIT_REFUSED, "{stdout}");
    assert_eq!(
        stdout.matches("reason=descriptor-shared").count(),
        2,
        "both fonts refuse, both by name:
{stdout}"
    );
}

/// A bare `ZapfDingbats` takes pdfcer's own bundled face, because pdfcer writes
/// the Annex D.6 name table itself and glyph selection then runs BY NAME — so
/// a donor lacking a glyph draws a visible hole rather than a plausible wrong
/// symbol. The narrowed symbolic guard, at the CLI boundary.
#[test]
fn a_bare_symbolic_standard_14_font_takes_the_bundled_face() {
    let (code, stdout, stderr) = run(
        "embed/embed-std14-dingbats.pdf",
        &["--all-missing", "--use-bundled-fonts"],
    );
    assert_eq!(
        code, 0,
        "stderr:
{stderr}"
    );
    assert!(stdout.contains("face=\"FoxitDingbats\""), "{stdout}");
    assert!(stdout.contains("key=FontFile3 subtype=Type1C"), "{stdout}");
    assert!(
        stdout.contains("encoding=1"),
        "pdfcer pins the mapping itself:
{stdout}"
    );
}

/// The dry run and the apply print the SAME plan. A preview that could
/// disagree with the commit is a disclosure that can lie, which is the whole
/// reason the core exposes one function for both.
#[test]
fn the_dry_run_and_the_apply_report_the_same_plan() {
    let out = temp_out("same-plan.pdf");
    let (_, dry, _) = run(
        "embed/embed-std14-bare.pdf",
        &["--all-missing", "--use-bundled-fonts"],
    );
    let (_, applied, _) = run(
        "embed/embed-std14-bare.pdf",
        &[
            "--all-missing",
            "--use-bundled-fonts",
            "--apply",
            "-o",
            out.to_str().unwrap(),
        ],
    );
    let row = |s: &str| {
        s.lines()
            .find(|l| l.trim_start().starts_with("embed name="))
            .unwrap_or_default()
            .to_owned()
    };
    assert_eq!(row(&dry), row(&applied), "dry:\n{dry}\napplied:\n{applied}");
}

// ---------------------------------------------------------------------------
// Selecting nothing, and describing what was not selected
// ---------------------------------------------------------------------------
//
// ★ WHY THESE TWO TESTS EXIST, AND WHY EVERY TEST ABOVE MISSED WHAT THEY
// CATCH. Every case above passes `--all-missing`. That is the mode the sweep
// harness runs and the mode the feature was developed in, and under it both
// bugs below are invisible: the selection is never empty, and
// `unexplained_missing()` is zero by construction. The operator found both
// within minutes of running the command the way the help text reads —
// `embed-font <file> --font-dir C:\Windows\Fonts` — and got
// `fonts=0 exact=0 substitute=0 refused=0 unmatched=0` on a document with a
// missing font and a folder that could resolve it. It looked exactly like a
// feature that does not work, on the very Pass that had just reported a
// 4,023-file sweep embedding 1,330 fonts. The sweep's numbers were real; the
// shell in front of them was not reachable by that invocation.
//
// R151's shape again — a core path that works, with a shell that cannot get
// to it — and, as in R151, a green unit suite said nothing, because the suite
// only ever exercised the shell the way its author already knew to.

/// `clap`'s usage-error exit. Spelled out for the same reason
/// `EDIT_REFUSED` is.
const USAGE_ERROR: i32 = 2;

/// ★ An invocation that names NO fonts is REFUSED, not answered with a
/// report of zeros.
///
/// The regression this pins: `--font` and `--all-missing` share a `clap`
/// group, but the group was not `required`, so passing neither parsed
/// cleanly into `EmbedSelection::Named(vec![])`. That selects nothing; an
/// empty name list produces no `unmatched` rows (there are no names to fail
/// to match); and under a non-`AllMissing` selection an unselected font is
/// deliberately NOT reported as a refusal, because under an explicit
/// selection a font the operator never named is not one. Every branch was
/// individually correct and the composition was a silent no-op.
///
/// The assertion is deliberately two-sided. Exit 2 alone would still pass if
/// someone later "helpfully" defaulted the selection to all-missing; the
/// second half pins that no plan was printed, which is what makes this a test
/// of the refusal rather than of the exit code.
#[test]
fn naming_no_fonts_is_refused_rather_than_reported_as_zero() {
    let (code, stdout, stderr) = run("embed/embed-mixed.pdf", &["--use-bundled-fonts"]);
    assert_eq!(
        code, USAGE_ERROR,
        "an invocation that selects nothing must not be accepted.\n\
         stdout:\n{stdout}\nstderr:\n{stderr}"
    );
    assert!(
        !stdout.contains("fonts=0"),
        "the old bug: a zero-report instead of a refusal.\nstdout:\n{stdout}"
    );
    // The refusal has to teach the flag, or it just moves the confusion.
    assert!(
        stderr.contains("--all-missing") && stderr.contains("--font"),
        "the refusal names both ways to satisfy it:\n{stderr}"
    );
}

/// ★ The report never claims a reason it did not print.
///
/// With `--font` naming one of three missing fonts, two remain missing and
/// this run says nothing about either — correctly, because they were not part
/// of the operation. The bug was the *sentence*: `not_embedded_after` was
/// followed by "Every one is listed above with its reason" when nothing was
/// listed at all, sending the operator to look for output that does not
/// exist. Project rule 4 is about pdfcer disclosing what it inferred; a tool
/// that misdescribes its own output fails it just as squarely as one that
/// hides an inference.
#[test]
fn fonts_left_missing_by_an_explicit_selection_are_not_claimed_to_be_explained() {
    let (code, stdout, stderr) = run(
        "embed/embed-mixed.pdf",
        &["--use-bundled-fonts", "--font", "Helvetica"],
    );
    assert_eq!(code, 0, "stderr:\n{stderr}");
    // The hazard has to actually occur, or the guard is untested (R187):
    // one font embedded, more than one still missing, and no `refused` row.
    assert!(
        stdout.contains("not_embedded_after=") && !stdout.contains("not_embedded_after=0"),
        "the hazard must occur for this test to mean anything:\nstdout:\n{stdout}"
    );
    assert!(
        !stdout.contains("  refused "),
        "and nothing may be listed, or the claim would be true:\nstdout:\n{stdout}"
    );
    assert!(
        !stderr.contains("listed above with its reason"),
        "the false claim, verbatim — nothing was listed above:\n{stderr}"
    );
    assert!(
        stderr.contains("NOT part of this operation"),
        "the honest replacement says why there is no reason to read:\n{stderr}"
    );
    assert!(
        stderr.contains("--all-missing"),
        "and points at what would consider them:\n{stderr}"
    );
}

/// The other half of the same message: when the fonts left missing DID get a
/// refusal row, the report says so and points at it.
///
/// Guards against "fixing" the test above by simply deleting the claim — the
/// wording is still owed to the operator in the case where it is true.
#[test]
fn fonts_left_missing_with_a_printed_reason_are_pointed_at() {
    let (_, stdout, stderr) = run("embed/embed-mixed.pdf", &["--all-missing"]);
    assert!(
        stdout.contains("  refused "),
        "no donors supplied, so every missing font is refused:\nstdout:\n{stdout}"
    );
    assert!(
        stderr.contains("listed above as `refused`"),
        "the claim is owed when it is true:\n{stderr}"
    );
    assert!(
        !stderr.contains("NOT part of this operation"),
        "under --all-missing nothing is left unexplained:\n{stderr}"
    );
}

/// The dry-run summary does not claim reasons over an empty list either.
///
/// A document with no fonts at all produces no targets AND no refusals. The
/// old wording said "Every refusal is printed above with its reason" — true
/// only vacuously, and it reads as though the operator missed some output.
/// Third instance of the same claim-vs-behaviour smell in one command, which
/// is why it is pinned rather than left as wording.
#[test]
fn a_document_with_nothing_to_embed_is_told_that_rather_than_pointed_at_reasons() {
    let (code, stdout, stderr) = run("minimal.pdf", &["--all-missing", "--use-bundled-fonts"]);
    assert_eq!(code, EDIT_REFUSED, "stdout:\n{stdout}");
    assert!(
        !stdout.contains("  refused "),
        "the hazard: nothing is listed:\nstdout:\n{stdout}"
    );
    assert!(
        !stderr.contains("Every refusal is printed above"),
        "so the claim must not be made:\n{stderr}"
    );
    assert!(
        stderr.contains("no font that is missing its program"),
        "the honest answer names the actual situation:\n{stderr}"
    );
}
