//! # `pdfcer extract-text` integration tests
//!
//! Black-box tests over the **real binary**, asserting the process
//! contract a script depends on and a refactor cannot see: the exit
//! code, which stream carries which payload, the stable `key=value`
//! result line, and the shape of `--json`.
//!
//! Unlike the sibling `render_page.rs`, these use the **committed
//! fixtures** in `fixtures/synthetic/text/` rather than building PDFs
//! inline. That is deliberate: those fixtures already exist for the
//! `pdfcer-core` integration tests, each one is a worked example from a
//! specific ISO 32000-1 clause (see the directory's `PROVENANCE.md`),
//! and duplicating them here would create two sources of truth for what
//! "the `/ActualText` fixture" means. `docs/LEGAL.md` §5 is satisfied
//! the same way either route — every byte is synthetic, generated by
//! `tools/gen-text-fixtures.py`.
//!
//! ## The channel-routing contract, restated
//!
//! `extract-text` has two things to say and must never mix them:
//!
//! | invocation | stdout | stderr |
//! |---|---|---|
//! | plain, no `-o` | the text | the result line + notes |
//! | plain, `-o FILE` | the result line | the notes |
//! | `--json`, no `-o` | the JSON | the result line + notes |
//! | `--json`, `-o FILE` | the result line | the notes |
//!
//! A pipeline (`extract-text f.pdf | grep …`) therefore gets clean text
//! and still shows the honesty line on the terminal.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::path::{Path, PathBuf};
use std::process::{Command, Output};

/// Path to the freshly built binary — Cargo sets this for integration
/// tests, so the test always exercises the binary from the same build.
const BIN: &str = env!("CARGO_BIN_EXE_pdfcer");

/// A committed fixture path.
fn fixture(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures/synthetic/text")
        .join(name)
}

/// Run `extract-text` with the given extra arguments.
fn run(name: &str, args: &[&str]) -> Output {
    let mut cmd = Command::new(BIN);
    cmd.arg("extract-text").arg(fixture(name));
    for arg in args {
        cmd.arg(arg);
    }
    cmd.output().expect("the binary runs")
}

fn stdout(out: &Output) -> String {
    String::from_utf8_lossy(&out.stdout).into_owned()
}

fn stderr(out: &Output) -> String {
    String::from_utf8_lossy(&out.stderr).into_owned()
}

/// Parse the stable result line's `key=value` pairs from a stream.
fn result_line(text: &str) -> std::collections::HashMap<String, String> {
    let line = text
        .lines()
        .find(|l| l.starts_with("extracted "))
        .unwrap_or_else(|| panic!("no result line in:\n{text}"));
    line.split_whitespace()
        .filter_map(|token| token.split_once('='))
        .map(|(k, v)| (k.to_string(), v.to_string()))
        .collect()
}

// ---------------------------------------------------------------------------
// Channel routing
// ---------------------------------------------------------------------------

#[test]
fn text_goes_to_stdout_and_the_result_line_to_stderr() {
    let out = run("simple-winansi.pdf", &[]);
    assert_eq!(out.status.code(), Some(0));
    let text = stdout(&out);
    assert!(text.starts_with("Hello world"), "stdout: {text:?}");
    assert!(
        !text.contains("extracted "),
        "the result line must not pollute piped text"
    );
    assert!(stderr(&out).contains("extracted "));
}

#[test]
fn with_an_output_file_the_result_line_takes_stdout() {
    // Per-call-unique temp dir: `process::id()` is binary-safe and the
    // process-global atomic counter is thread-safe, so no two concurrent tests
    // can collide on this scratch dir (fully-qualified `atomic` types keep the
    // guard self-contained without adding a `use`).
    let dir = {
        static N: std::sync::atomic::AtomicU32 = std::sync::atomic::AtomicU32::new(0);
        let n = N.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
        std::env::temp_dir().join(format!("pdfcer-extract-{}-{n}", std::process::id()))
    };
    std::fs::create_dir_all(&dir).unwrap();
    let path = dir.join("out.txt");
    let out = run("simple-winansi.pdf", &["--output", path.to_str().unwrap()]);
    assert_eq!(out.status.code(), Some(0));
    assert!(stdout(&out).starts_with("extracted "));
    let written = std::fs::read_to_string(&path).unwrap();
    assert!(written.starts_with("Hello world"));
    assert!(written.ends_with('\n'), "a text file ends with a newline");
    let _ = std::fs::remove_dir_all(&dir);
}

// ---------------------------------------------------------------------------
// The counters
// ---------------------------------------------------------------------------

#[test]
fn the_result_line_reports_the_ladder_rung_by_rung() {
    let out = run("simple-winansi.pdf", &[]);
    let kv = result_line(&stderr(&out));
    assert_eq!(kv["codes"], "21");
    assert_eq!(kv["via_encoding"], "21");
    assert_eq!(kv["via_tounicode"], "0");
    assert_eq!(kv["failed"], "0");
    assert_eq!(kv["sourced_pct"], "100.0");
    // The derived half is reported separately, and is non-zero here.
    assert_eq!(kv["spaces_derived"], "1");
    assert_eq!(kv["lines_derived"], "1");
}

#[test]
fn the_identity_h_dead_end_is_visible_in_the_result_line() {
    let out = run("identity-h-no-tounicode.pdf", &[]);
    let err = stderr(&out);
    let kv = result_line(&err);
    assert_eq!(kv["failed"], kv["codes"], "every code must fail");
    assert_eq!(kv["sourced_pct"], "0.0");
    assert_eq!(kv["identity_no_tounicode"], "1");
    assert!(
        err.contains("no Unicode is recoverable"),
        "the named diagnostic must reach the operator: {err}"
    );
}

#[test]
fn to_unicode_resolution_is_reported_as_rung_one() {
    let out = run("identity-h-tounicode.pdf", &[]);
    let kv = result_line(&stderr(&out));
    assert_eq!(kv["via_encoding"], "0", "a composite font has no rung 2");
    assert!(kv["via_tounicode"].parse::<u64>().unwrap() > 0);
    assert_eq!(kv["failed"], "1", "the deliberately uncovered code");
}

#[test]
fn document_level_facts_appear_in_the_result_line() {
    let out = run("tagged-marked.pdf", &[]);
    let kv = result_line(&stderr(&out));
    assert_eq!(kv["tagged"], "true");
    assert_eq!(kv["suspects"], "true");
    assert_eq!(kv["struct_tree"], "true");
}

// ---------------------------------------------------------------------------
// Policy flags
// ---------------------------------------------------------------------------

#[test]
fn artifacts_are_excluded_by_default_and_included_on_request() {
    let without = stdout(&run("artifact-and-reversed.pdf", &[]));
    assert!(!without.contains("Running head"));
    assert!(without.contains("Real content"));

    let with = stdout(&run("artifact-and-reversed.pdf", &["--include-artifacts"]));
    assert!(with.contains("Running head"));
}

#[test]
fn a_page_selection_is_honoured_and_a_bad_one_is_refused_by_name() {
    let ok = run("simple-winansi.pdf", &["--pages", "1"]);
    assert_eq!(ok.status.code(), Some(0));

    // Exit 9 is EDIT_REFUSED: the document was readable and pdfcer
    // declined the request as asked — distinct from "broken file".
    let bad = run("simple-winansi.pdf", &["--pages", "1-9"]);
    assert_eq!(bad.status.code(), Some(9));
    assert!(stderr(&bad).contains("--pages"));
}

// ---------------------------------------------------------------------------
// --json
// ---------------------------------------------------------------------------

#[test]
fn json_exposes_the_sourced_derived_split_run_by_run() {
    let out = run("simple-winansi.pdf", &["--json"]);
    assert_eq!(out.status.code(), Some(0));
    let json = stdout(&out);

    // The derived space is present, flagged as NOT sourced.
    assert!(json.contains("\"origin\": \"derived_word_space\""));
    assert!(json.contains("\"origin\": \"derived_line_break\""));
    assert!(json.contains("\"origin\": \"glyphs\""));
    assert!(json.contains("\"sourced\": false"));
    assert!(json.contains("\"sourced\": true"));

    // Per-glyph ladder provenance.
    assert!(json.contains("\"rung\": \"encoding_agl\""));
    // Counters and the document-level facts.
    assert!(json.contains("\"codes_total\": 21"));
    assert!(json.contains("\"tagged\": false"));
    assert!(json.contains("\"sourced_fraction\": 1.000000"));
}

#[test]
fn json_output_is_syntactically_well_formed() {
    // No JSON parser in the dependency graph, so this checks the two
    // properties a hand-rolled emitter actually gets wrong: unbalanced
    // brackets, and unescaped control characters or quotes inside string
    // literals. The fixture set deliberately includes a derived line
    // break (a literal `\n` inside a run's text), which is exactly the
    // case a naive emitter breaks on.
    for name in [
        "simple-winansi.pdf",
        "identity-h-tounicode.pdf",
        "identity-h-no-tounicode.pdf",
        "actual-text-drucker.pdf",
        "artifact-and-reversed.pdf",
        "tagged-marked.pdf",
    ] {
        let json = stdout(&run(name, &["--json"]));
        assert!(json.starts_with('{'), "{name}");
        assert!(json.trim_end().ends_with('}'), "{name}");

        let mut depth = 0i32;
        let mut in_string = false;
        let mut escaped = false;
        for ch in json.chars() {
            if in_string {
                if escaped {
                    escaped = false;
                } else if ch == '\\' {
                    escaped = true;
                } else if ch == '"' {
                    in_string = false;
                } else {
                    assert!(
                        (ch as u32) >= 0x20,
                        "{name}: raw control character inside a JSON string"
                    );
                }
                continue;
            }
            match ch {
                '"' => in_string = true,
                '{' | '[' => depth += 1,
                '}' | ']' => depth -= 1,
                _ => {}
            }
            assert!(depth >= 0, "{name}: unbalanced brackets");
        }
        assert_eq!(depth, 0, "{name}: unbalanced brackets");
        assert!(!in_string, "{name}: unterminated string");
    }
}

#[test]
fn json_marks_an_actual_text_run_atomic() {
    // §14.9.4 N4: no per-character correspondence exists across a
    // replacement, so the JSON must carry no `glyphs` array for it —
    // and must still mark the run sourced, because the VALUE is.
    let json = stdout(&run("actual-text-drucker.pdf", &["--json"]));
    let run_json = json
        .lines()
        .find(|l| l.contains("\"origin\": \"actual_text\""))
        .expect("the replacement run is present");
    assert!(run_json.contains("\"sourced\": true"));
    assert!(!run_json.contains("\"glyphs\""));
    assert!(
        run_json.contains("\"bbox\""),
        "the covered region is all it has"
    );
}

// ---------------------------------------------------------------------------
// Failure modes
// ---------------------------------------------------------------------------

#[test]
fn a_missing_file_maps_to_the_io_exit_code() {
    let out = Command::new(BIN)
        .arg("extract-text")
        .arg("no-such-file-anywhere.pdf")
        .output()
        .expect("runs");
    assert_eq!(out.status.code(), Some(3));
}

#[test]
fn a_non_pdf_maps_to_the_not_a_pdf_exit_code() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../fixtures/synthetic/not-a-pdf.bin");
    let out = Command::new(BIN)
        .arg("extract-text")
        .arg(&path)
        .output()
        .expect("runs");
    assert_eq!(out.status.code(), Some(4));
}
