//! # `pdfcer` save-refusal hints — the remedy has to be typeable
//!
//! Black-box tests over the **real binary** for one narrow contract: when a
//! save is refused for a reason the operator can actually act on, the CLI
//! prints the action *in the form they would type it*.
//!
//! ## The defect these exist to prevent
//!
//! [`pdfcer_core::writer::WriteError::RecoveredBaseForbidsIncremental`] ends
//! its message with `(save_full)`. That is correct for the **core's**
//! audience — `pdfcer-core` is a library, and a Rust caller reaching for
//! [`pdfcer_core::writer::save_full`] wants the function's real name. It is
//! wrong for the audience that reaches it through this binary, who cannot
//! type `save_full` anywhere and will not find it in any `--help` output.
//!
//! The refusal itself is right and is deliberately NOT weakened here: a
//! document whose base cross-reference was invalid genuinely cannot take an
//! incremental append, because the bytes an append would preserve are the
//! ones already known to be broken (ISO 32000-1 §7.5.6; standing rule R67).
//! What was missing was the second half — what to do instead.
//!
//! This was found by running `embed-font` against a real-world file whose
//! xref pdfcer had recovered by scan. The plan was complete and correct
//! (`not_embedded_after=0`, `applied=1`), the operator was told the save was
//! refused, and the only remedy offered was a symbol from the library API.
//! Standing rule **R174** — read a gate's output as its audience reads it.
//!
//! ## Why the second test matters more than the first
//!
//! Asserting the hint's *text* only proves a string is printed. The hazard
//! that actually costs an operator their afternoon is a hint that names a
//! flag which does not work — advice confidently given and wrong. So the
//! second test **follows the advice**: it re-runs the identical command with
//! the suggested flag and requires a file to come out the other side that
//! reloads cleanly. If `--mode full` were renamed, restricted, or made to
//! fail on a recovered base, that test breaks — the string assertion alone
//! would sail through (standing rule R187: prove a guard by making the
//! hazard occur).
//!
//! ## Why the fixtures are the `xref-recover` corpus
//!
//! Those files are synthetic and committed (`fixtures/synthetic/xref-recover/`,
//! generated by `tools/gen-xref-recover-fixtures.py`), each deliberately
//! damaged in one specific way, so the recovered-base condition is reached on
//! every machine rather than only where a real-world damaged PDF happens to
//! sit. Three distinct damage shapes are covered because the refusal is
//! raised by the *recovery flag on the loaded document*, not by the damage —
//! a regression that made recovery set that flag inconsistently would show up
//! as one of these passing and the others not.

use std::path::{Path, PathBuf};
use std::process::Command;

const BIN: &str = env!("CARGO_BIN_EXE_pdfcer");

/// `exit::SAVE_REFUSED`. Spelled out rather than imported, so a change to the
/// number is a visible test failure rather than a silent contract break.
const SAVE_REFUSED: i32 = 8;

fn fixture(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures/synthetic/xref-recover")
        .join(name)
}

fn temp_out(name: &str) -> PathBuf {
    let dir = std::env::temp_dir().join("pdfcer-save-hint-tests");
    std::fs::create_dir_all(&dir).expect("temp dir");
    dir.join(name)
}

/// Run `rotate` on a recovered fixture, optionally with extra flags.
///
/// `rotate` is used rather than `embed-font` deliberately: the hint lives on
/// the CLI's **shared save boundary**, not in any one subcommand, so the test
/// should reach it through an ordinary mutating command. Any of them would
/// do; this one needs no donor fonts and no per-fixture setup.
fn rotate(fixture_name: &str, extra: &[&str]) -> (i32, String, String, PathBuf) {
    let out_path = temp_out(&format!("{}-{}.pdf", fixture_name, extra.join("")));
    let _ = std::fs::remove_file(&out_path);
    let out = Command::new(BIN)
        .arg("rotate")
        .arg(fixture(fixture_name))
        .args(["--degrees", "90", "-o"])
        .arg(&out_path)
        .args(extra)
        .output()
        .expect("pdfcer runs");
    (
        out.status.code().unwrap_or(-1),
        String::from_utf8_lossy(&out.stdout).into_owned(),
        String::from_utf8_lossy(&out.stderr).into_owned(),
        out_path,
    )
}

/// The refusal must name the flag an operator can type — and must not leave
/// the library's function name as the only thing on offer.
#[test]
fn a_recovered_base_refusal_names_the_flag_not_the_api_function() {
    for name in [
        "no-startxref.pdf",
        "offset-shifted-startxref.pdf",
        "xref-stream-corrupt.pdf",
    ] {
        let (code, _stdout, stderr, out_path) = rotate(name, &[]);
        assert_eq!(code, SAVE_REFUSED, "{name}: stderr:\n{stderr}");
        assert!(
            !out_path.exists(),
            "{name}: a refused save must not leave an output file behind"
        );
        assert!(
            stderr.contains("--mode full"),
            "{name}: the remedy must be given in typeable form:\n{stderr}"
        );
        // The cost is stated, not just the flag. Offering the destructive
        // path without naming what it destroys is the "sneaky" half of
        // project rule 4 — steering the operator into the mode that happens
        // to make the command succeed.
        assert!(
            stderr.contains("signature"),
            "{name}: the hint must state what --mode full costs:\n{stderr}"
        );
    }
}

/// ★ The load-bearing one: the advice is FOLLOWED, and must work.
///
/// A hint naming a flag that does not actually resolve the situation is worse
/// than no hint — it spends the operator's trust and their time. So this
/// re-runs the exact command with the suggested flag and requires real output
/// that reloads without recovery firing a second time.
#[test]
fn following_the_hint_actually_produces_a_file() {
    for name in [
        "no-startxref.pdf",
        "offset-shifted-startxref.pdf",
        "xref-stream-corrupt.pdf",
    ] {
        let (code, stdout, stderr, out_path) = rotate(name, &["--mode", "full"]);
        assert_eq!(
            code, 0,
            "{name}: the hinted flag must succeed:\nstdout:\n{stdout}\nstderr:\n{stderr}"
        );
        assert!(
            out_path.exists(),
            "{name}: the hinted flag must actually write the file"
        );

        // And the result must be a genuinely repaired file: loading it again
        // must NOT trip recovery, or the operator has been handed something
        // that will refuse the same way on their next edit.
        let reread = Command::new(BIN)
            .arg("inspect")
            .arg(&out_path)
            .output()
            .expect("pdfcer runs");
        assert!(
            reread.status.success(),
            "{name}: the rewritten file must reload:\n{}",
            String::from_utf8_lossy(&reread.stderr)
        );
        let bytes = std::fs::read(&out_path).expect("read output");
        assert!(
            bytes.starts_with(b"%PDF-"),
            "{name}: output is not a PDF at all"
        );
    }
}
