//! # `pdfcer tab-order` — black-box over the real binary
//!
//! `Pass 307.0`, request `G019`. The shell for `pdfcer-core`'s
//! `EditSession::page_tab_sequence` (ISO 32000-1 §12.5.1, ISO 32000-2
//! §12.5.1 for `/A` and `/W`).
//!
//! ## Why a shell test exists when the core is already covered
//!
//! `edit.rs`'s unit tests pin the derivation itself — which annotation is
//! second on a rotated right-to-left page is settled there. They
//! structurally cannot pin any of the following, and each is a way a
//! correct core ships behind a broken command:
//!
//! * **Flag wiring.** `--pages` and `--row-tolerance` can be declared,
//!   documented in `--help`, and never reach the core call. This project
//!   has a standing lesson for exactly that shape.
//! * **The 0-based / 1-based boundary.** `page_tab_sequence` takes a
//!   0-based index and every `page=` printed here is 1-based. That
//!   conversion lives only in the shell.
//! * **The six `basis=` tokens.** They *are* the disclosure: collapsing
//!   `row` into `stated-array`, or `not-derived` into anything at all,
//!   turns "pdfcer worked this out from geometry" into "the file says
//!   so". Only the shell emits them.
//! * **★ That the `note` lines are on STDOUT.** Under `basis=row`,
//!   `column` and `array-convention` the order above them is pdfcer's
//!   inference, and rule 4 makes saying so part of the answer rather
//!   than commentary on it. A script that keeps stdout and discards
//!   stderr must still receive them. A core test cannot observe which
//!   stream a line went to.
//! * **The summary line**, which must print even when every count is
//!   zero, so "no annotations here" stays distinguishable from "this
//!   tool did not look".
//! * **Exit codes**, the CLI's contract with a script.
//!
//! ## Fixtures
//!
//! `fixtures/synthetic/tab-order/`, provenance in that directory's
//! `PROVENANCE.md`, regenerated by `tools/gen-tab-order-fixtures.py`.
//! ★ On every page, `/Annots` is listed in an order that is **none** of
//! the orders these tests expect — so an implementation that returned
//! the array unchanged fails rather than passes.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::path::{Path, PathBuf};
use std::process::{Command, Output};

const BIN: &str = env!("CARGO_BIN_EXE_pdfcer");
/// `exit::RUNTIME_ERROR` — a bad invocation the command itself rejected.
const RUNTIME_ERROR: i32 = 1;
/// `exit::NOT_A_PDF` in the CLI's stable exit-code contract.
const NOT_A_PDF: i32 = 4;

fn fixture(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join(format!("../../fixtures/synthetic/tab-order/{name}"))
}

fn run(args: &[&str]) -> Output {
    Command::new(BIN)
        .args(args)
        .output()
        .expect("the CLI binary runs")
}

/// Stdout as text, with the exit code asserted first — a command that
/// failed and printed nothing would otherwise pass every `!contains`.
fn stdout_ok(args: &[&str]) -> String {
    let out = run(args);
    assert_eq!(
        out.status.code(),
        Some(0),
        "exit code; stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    String::from_utf8_lossy(&out.stdout).into_owned()
}

/// The `obj=` numbers of the `tab` lines for one page, in visit order.
fn visit_order(text: &str, page: u32) -> Vec<u32> {
    text.lines()
        .filter(|l| l.starts_with(&format!("tab page={page} ")))
        .map(|l| {
            l.split_whitespace()
                .find_map(|f| f.strip_prefix("obj="))
                .expect("every tab line names an object")
                .parse()
                .expect("obj= is a number")
        })
        .collect()
}

/// One `key=value` field off the `page-order` line for a page.
fn page_field(text: &str, page: u32, key: &str) -> String {
    text.lines()
        .find(|l| l.starts_with(&format!("page-order page={page} ")))
        .unwrap_or_else(|| panic!("no page-order line for page {page}"))
        .split_whitespace()
        .find_map(|f| f.strip_prefix(&format!("{key}=")))
        .unwrap_or_else(|| panic!("no {key}= on page {page}"))
        .to_owned()
}

fn notes(text: &str, page: u32) -> String {
    text.lines()
        .filter(|l| l.starts_with(&format!("note page={page} ")))
        .collect::<Vec<_>>()
        .join(" ")
}

// ---- the six bases ----------------------------------------------------

#[test]
fn every_tabs_state_reports_its_own_basis() {
    let out = stdout_ok(&["tab-order", fixture("modes.pdf").to_str().unwrap()]);
    for (page, tabs, basis, derived) in [
        (1, "A", "stated-array", "0"),
        (2, "W", "stated-widget", "0"),
        (3, "R", "row", "1"),
        (4, "C", "column", "1"),
        (5, "S", "not-derived", "0"),
        (6, "absent", "array-convention", "1"),
        (7, "/Q", "array-convention", "1"),
    ] {
        assert_eq!(page_field(&out, page, "tabs"), tabs, "page {page} tabs");
        assert_eq!(page_field(&out, page, "basis"), basis, "page {page} basis");
        assert_eq!(
            page_field(&out, page, "derived"),
            derived,
            "page {page} derived"
        );
    }
    assert!(
        out.lines().any(|l| l.starts_with("tab-order ")
            && l.contains("pages=7;")
            && l.contains("derived_pages=4")
            && l.contains("not_derived_pages=1")),
        "the summary line: {out}"
    );
}

#[test]
fn row_order_and_column_order_disagree_on_the_same_grid() {
    // The single most informative assertion here. Both pages carry the
    // identical four annotations in the identical scrambled array; only
    // /Tabs differs. If these two came back equal, the geometry is not
    // being read at all.
    let out = stdout_ok(&["tab-order", fixture("modes.pdf").to_str().unwrap()]);
    let rows = visit_order(&out, 3);
    let cols = visit_order(&out, 4);
    assert_ne!(rows, cols, "row order must differ from column order");
    // And neither is the array order, which page 1 prints verbatim.
    let array = visit_order(&out, 1);
    assert_ne!(rows, array);
    assert_ne!(cols, array);
    assert_eq!(rows.len(), 4);
    assert_eq!(cols.len(), 4);
}

#[test]
fn structure_order_prints_no_tab_lines_at_all() {
    // Not an empty page — a page pdfcer declines to answer for. A fall
    // back to array order here would be indistinguishable from an answer,
    // which is the whole reason the sequence comes back empty.
    let out = stdout_ok(&["tab-order", fixture("modes.pdf").to_str().unwrap()]);
    assert!(visit_order(&out, 5).is_empty());
    assert_eq!(page_field(&out, 5, "visited"), "0");
    assert!(notes(&out, 5).contains("structure tree"));
}

#[test]
fn an_unknown_tabs_value_is_reported_verbatim() {
    // "/Q", not "unknown". A disclosure that names the value the file
    // carries can be checked against the file; one that says "something
    // else" cannot.
    let out = stdout_ok(&["tab-order", fixture("modes.pdf").to_str().unwrap()]);
    assert_eq!(page_field(&out, 7, "tabs"), "/Q");
    assert!(notes(&out, 7).contains("/Q"));
}

#[test]
fn widget_order_puts_the_fields_first_and_names_the_contradiction() {
    let out = stdout_ok(&["tab-order", fixture("modes.pdf").to_str().unwrap()]);
    let order = visit_order(&out, 2);
    // The two widgets are the top row; both must precede both non-widgets.
    let subtype_of = |obj: u32| {
        out.lines()
            .find(|l| l.contains(&format!("obj={obj} ")))
            .and_then(|l| {
                l.split_whitespace()
                    .find_map(|f| f.strip_prefix("subtype="))
            })
            .unwrap_or("?")
            .to_owned()
    };
    assert_eq!(subtype_of(order[0]), "Widget");
    assert_eq!(subtype_of(order[1]), "Widget");
    assert_ne!(subtype_of(order[2]), "Widget");
    assert!(notes(&out, 2).contains("contradicts itself"));
}

// ---- the disclosure is on stdout --------------------------------------

#[test]
fn the_rule_four_notes_are_on_stdout_not_stderr() {
    // ★ The one assertion a core test structurally cannot make. A script
    // that keeps stdout and throws stderr away must still be told that
    // the order it just received was worked out rather than read.
    let out = run(&["tab-order", fixture("modes.pdf").to_str().unwrap()]);
    assert_eq!(out.status.code(), Some(0));
    let text = String::from_utf8_lossy(&out.stdout);
    assert!(text.contains("note page=3 text="), "notes belong on stdout");
    let err = String::from_utf8_lossy(&out.stderr);
    assert!(!err.contains("note page="), "and not on stderr: {err}");
}

#[test]
fn the_page_that_states_its_order_owes_no_disclosure() {
    // /Tabs /A is the one basis that infers nothing, and a note there
    // would be noise that trains an operator to ignore the real ones.
    let out = stdout_ok(&["tab-order", fixture("modes.pdf").to_str().unwrap()]);
    assert!(
        notes(&out, 1).is_empty(),
        "page 1 notes: {}",
        notes(&out, 1)
    );
    assert!(!notes(&out, 3).is_empty(), "but page 3 owes one");
}

// ---- geometry ---------------------------------------------------------

#[test]
fn page_rotation_reaches_the_order() {
    let out = stdout_ok(&["tab-order", fixture("geometry.pdf").to_str().unwrap()]);
    assert_eq!(page_field(&out, 1, "rotate"), "90");
    // Rotating clockwise turns the LEFT column into the TOP row, so the
    // first two visited are the two left-hand annotations.
    let order = visit_order(&out, 1);
    let rect_of = |obj: u32| {
        out.lines()
            .find(|l| l.contains(&format!("obj={obj} ")))
            .and_then(|l| l.split_whitespace().find_map(|f| f.strip_prefix("rect=")))
            .unwrap_or("?")
            .to_owned()
    };
    assert!(rect_of(order[0]).starts_with("100,"));
    assert!(rect_of(order[1]).starts_with("100,"));
    assert!(notes(&out, 1).contains("rotated 90 degrees"));
}

#[test]
fn right_to_left_is_read_from_the_document_and_reported() {
    let out = stdout_ok(&["tab-order", fixture("rtl.pdf").to_str().unwrap()]);
    assert_eq!(page_field(&out, 1, "direction"), "r2l");
    assert!(notes(&out, 1).contains("/Direction /R2L"));
    // And an ordinary document says l2r rather than leaving the field off.
    let plain = stdout_ok(&["tab-order", fixture("modes.pdf").to_str().unwrap()]);
    assert_eq!(page_field(&plain, 3, "direction"), "l2r");
}

#[test]
fn what_a_reader_never_visits_is_printed_rather_than_dropped() {
    let out = stdout_ok(&["tab-order", fixture("geometry.pdf").to_str().unwrap()]);
    let skipped: Vec<String> = out
        .lines()
        .filter(|l| l.starts_with("skipped page=2 "))
        .map(|l| {
            l.split_whitespace()
                .find_map(|f| f.strip_prefix("why="))
                .unwrap_or("?")
                .to_owned()
        })
        .collect();
    assert_eq!(skipped, ["hidden", "no-view", "popup", "trap-net"]);
    // NoView + ToggleNoView STAYS: under ISO 32000-2 that bit makes the
    // annotation appear when selected, and tabbing to it is what selects.
    assert_eq!(page_field(&out, 2, "visited"), "2");
    // A dictionary written straight into /Annots has no identity to name.
    assert_eq!(page_field(&out, 2, "pinned"), "1");
    assert!(notes(&out, 2).contains("cannot say where"));
}

// ---- flag wiring ------------------------------------------------------

#[test]
fn the_pages_flag_reaches_the_call() {
    let out = stdout_ok(&[
        "tab-order",
        fixture("modes.pdf").to_str().unwrap(),
        "--pages",
        "4",
    ]);
    assert!(out.contains("page-order page=4 "));
    assert!(!out.contains("page-order page=3 "), "only page 4: {out}");
    assert_eq!(page_field(&out, 4, "basis"), "column");
}

#[test]
fn the_row_tolerance_flag_changes_the_answer_and_the_note() {
    let path = fixture("geometry.pdf");
    let path = path.to_str().unwrap();
    // The two annotations' tops are 2 points apart. Tight: two rows, so
    // the higher one comes first even though it is on the right.
    let tight = stdout_ok(&["tab-order", path, "--pages", "3", "--row-tolerance", "0.5"]);
    let loose = stdout_ok(&["tab-order", path, "--pages", "3", "--row-tolerance", "3"]);
    assert_ne!(
        visit_order(&tight, 3),
        visit_order(&loose, 3),
        "the tolerance must reach the grouping"
    );
    assert!(notes(&tight, 3).contains("within 0.5 points of"));
    assert!(notes(&loose, 3).contains("within 3 points of"));
}

// ---- refusals ---------------------------------------------------------

#[test]
fn an_out_of_range_page_selection_is_refused() {
    let out = run(&[
        "tab-order",
        fixture("modes.pdf").to_str().unwrap(),
        "--pages",
        "99",
    ]);
    assert_eq!(out.status.code(), Some(RUNTIME_ERROR));
}

#[test]
fn a_file_that_is_not_a_pdf_is_refused_by_its_own_code() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../fixtures/synthetic/not-a-pdf.bin");
    let out = run(&["tab-order", path.to_str().unwrap()]);
    assert_eq!(out.status.code(), Some(NOT_A_PDF));
}
