//! Throwaway measurement (`R238`, `R219`): **what does the SHIPPING build do**
//! at the eight deletion-collateral sites the `Pass 191.0` audit named?
//!
//! # Why this exists rather than a reading of the code
//!
//! `Pass 191.0` fixed one instance of a defect class — *a verb dereferences a
//! dictionary key, assumes the pointee is the kind of object that key is
//! defined to hold, and deletes it, or deletes and overwrites objects reached
//! through it.* The audit that followed (R219: enumerate the class rather than
//! wait for the next fuzz finding) named **eight more sites**.
//!
//! Those eight are **claims**. An audit that reads code can be wrong about
//! reachability in either direction — it can miss a guard three call frames up
//! that makes the input unconstructible, and it can miss a second route that
//! makes a "theoretical" site trivially reachable. `R238` says how to close
//! that: *a `debug_assert` tells you **where the check runs**, never **what the
//! shipping build does when the property is false***. The answer is one of
//! three, and only measurement distinguishes them:
//!
//! 1. **panics anyway** (some other guard catches it) — a robustness bug;
//! 2. **returns an error** — correct behaviour, the assert is a tripwire only;
//! 3. **returns `Ok` and writes wrong bytes** — release-visible corruption,
//!    and the only one of the three that is urgent.
//!
//! `badkid_probe.rs` is this probe's direct ancestor and answered exactly that
//! question for the one site `191.0` fixed (it was case 3). This one asks it
//! twelve more times, plus seven controls.
//!
//! # ★ Run BOTH profiles, and read the RELEASE one as the answer
//!
//! ```text
//! cargo run -p pdfcer-core --example collateral_probe            # debug_assertions ON
//! cargo run -p pdfcer-core --release --example collateral_probe  # the shipping build
//! ```
//!
//! `debug_assert_page_tree_still_walks` is `#[cfg(debug_assertions)]`, so the
//! debug run may **panic** where the release run returns `Ok` — and the release
//! run is the shipping behaviour, which is the thing under test. The assert is
//! not the subject; it is the machinery that was compiled away when the defect
//! shipped.
//!
//! A panic in debug would end the process and leave every later case
//! unmeasured, so **every case runs inside `catch_unwind`** and a panicking
//! case is reported as `PANIC` rather than taking the run down with it. The
//! panic hook is silenced for the duration for the same reason: a hundred lines
//! of backtrace between two table rows makes the table unreadable, and the row
//! already says which case panicked.
//!
//! # What each row means
//!
//! | Column | Question it answers |
//! |---|---|
//! | `verb` | the exact `Result` the shipping build returns — `Ok`, `Err(..)`, or `PANIC` |
//! | `walks` | does `page_tree::pages_in` still walk the LIVE session graph? |
//! | `save+reload` | does `to_full_bytes` produce bytes that reload with a walkable page tree? |
//!
//! `save+reload` is the stronger observable and the one that decides severity.
//! `to_full_bytes` is measured rather than `to_incremental_bytes` for the
//! reason `badkid_probe.rs` records at length: on the `191.0` reproducer the
//! incremental path refused the document for a **completely unrelated** reason
//! (an invalid base cross-reference), which suppressed the evidence and would
//! have let the route be sized as harmless. **A refusal that fires for an
//! unrelated reason is not a guard.** The full rewrite is also the sanctioned
//! path for a recovered document and therefore the one an operator reaches.
//!
//! # The controls are half the measurement
//!
//! Seven of the nineteen cases are marked `CONTROL`. They are documents where
//! the same verb has a legitimate job to do, and they must read
//! `Ok / yes / yes`. They are here because the cheapest way to make every
//! hostile file behave is to refuse everything — which would silently break
//! ce-dimension deletion, redaction-mark rejection, form flattening, bookmark
//! deletion, comment deletion, attachment detachment and font unembedding.
//! A run where a hostile row is clean and a control row is not has not
//! measured a fix; it has measured a regression.
//!
//! # Terminology (project rule 15)
//!
//! Sites 1 and 2 concern **ce dimensions** — the `/Line` + `/IT
//! /LineDimension` annotations pdfcer authors, with their `/PieceInfo` sidecar.
//! No **pdf dimension** (a measurement a CAD exporter drew into page content)
//! is involved anywhere in this probe; page content is not reachable by key
//! from any of these verbs.
//!
//! # Fixtures
//!
//! `fixtures/synthetic/deletion-collateral/`, generated by
//! `tools/gen-deletion-collateral-fixtures.py`, which documents per file the
//! claim that file makes falsifiable. Wholly synthetic, byte-authored,
//! `LEGAL.md` §5 category (a).

use pdfcer_core::document::Document;
use pdfcer_core::edit::EditSession;
use pdfcer_core::font_unembed::UnembedRequest;
use pdfcer_core::object::ObjId;
use pdfcer_core::writer::SaveOptions;

/// Where the generated fixtures live, relative to `pdfcer-core`'s manifest.
const DIR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../fixtures/synthetic/deletion-collateral/"
);

/// One measured case: what was run, and the three observables.
struct Row {
    site: &'static str,
    fixture: &'static str,
    control: bool,
    verb: String,
    walks: String,
    reload: String,
}

/// Does `page_tree::pages_in` still walk the live session graph?
///
/// The property `debug_assert_page_tree_still_walks` asserts, restated as
/// something a caller can observe in **any** profile — which is the entire
/// reason this probe exists rather than a `cargo test` run.
fn walks_now(session: &EditSession) -> String {
    match pdfcer_core::page_tree::pages_in(&session.graph()) {
        Ok(p) => format!("yes ({})", p.len()),
        Err(e) => format!("NO ({e:?})"),
    }
}

/// Does a **full rewrite** round-trip through `Document::from_bytes` with a
/// walkable page tree?
///
/// The strongest observable, and the one that separates "pdfcer's in-memory
/// model is briefly odd" from "pdfcer wrote a file it cannot reopen". A file
/// that reloads but has no walkable page tree is flagged with a star because
/// it is the shape of both the 2026-08-20 `/Contents` corruption and the
/// `Pass 191.0` `BadKid`: the reader accepts the bytes and finds no page.
fn saves_and_reloads(session: &EditSession) -> String {
    match session.to_full_bytes(&SaveOptions::identity()) {
        Ok((bytes, _)) => match Document::from_bytes(bytes.clone()) {
            Ok(d) => match pdfcer_core::page_tree::pages_in(d.view().graph()) {
                Ok(p) => format!("yes ({} pg, {} B)", p.len(), bytes.len()),
                Err(e) => format!("★ NO PAGE TREE ({e:?})"),
            },
            Err(e) => format!("★ UNLOADABLE ({e})"),
        },
        Err(e) => format!("refused ({e})"),
    }
}

/// Run one case: load the fixture, apply `verb`, record the three observables.
///
/// `verb` returns the string this row prints in its `verb` column — the
/// caller formats its own `Result` because every verb here has a different
/// `Ok` payload and a bare `is_ok()` would throw away the part that matters
/// (a `DimensionLabelChange` that reports `changed: false` did nothing, and a
/// row that said `Ok` for it would be a lie by omission).
///
/// Everything runs inside `catch_unwind` so that one `debug_assert` firing in
/// the debug profile cannot cost the measurement of the eighteen cases after
/// it. `AssertUnwindSafe` is honest here: a poisoned `EditSession` is dropped
/// immediately and never read again.
fn run(
    site: &'static str,
    fixture: &'static str,
    control: bool,
    verb: impl FnOnce(&mut EditSession) -> String,
) -> Row {
    let mut row = Row {
        site,
        fixture,
        control,
        verb: "-".to_owned(),
        walks: "-".to_owned(),
        reload: "-".to_owned(),
    };
    let path = format!("{DIR}{fixture}");
    let Ok(data) = std::fs::read(&path) else {
        row.verb = "FIXTURE MISSING".to_owned();
        return row;
    };
    let outcome = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let doc = Document::from_bytes(data).expect("fixture must load");
        let mut session = EditSession::new(doc);
        let verb_result = verb(&mut session);
        (
            verb_result,
            walks_now(&session),
            saves_and_reloads(&session),
        )
    }));
    match outcome {
        Ok((v, w, r)) => {
            row.verb = v;
            row.walks = w;
            row.reload = r;
        }
        Err(_) => row.verb = "PANIC".to_owned(),
    }
    row
}

/// `Result` rendered the way every row wants it: the error text in full,
/// because *which* refusal fired is the whole answer for a NOT-REPRODUCED
/// site.
fn show<T, E: std::fmt::Display>(r: Result<T, E>, ok: impl FnOnce(T) -> String) -> String {
    match r {
        Ok(v) => ok(v),
        Err(e) => format!("Err({e})"),
    }
}

/// The first ce dimension the session's sidecar model knows about.
///
/// Read from the model rather than hard-coded, because the model is what the
/// verbs address and a hand-written `DimensionId` that the sidecar parser had
/// silently dropped would make every ce-dimension row report
/// `DimensionNotFound` — a NOT-REPRODUCED answer produced by the probe's own
/// bug rather than by a guard, which is the worst outcome this file can have.
fn first_dimension(session: &EditSession) -> Option<pdfcer_core::dimension::DimensionId> {
    session.dimension_model().dimensions().first().map(|d| d.id)
}

fn main() {
    println!(
        "profile: debug_assertions = {}   (the RELEASE run is the shipping behaviour)",
        cfg!(debug_assertions)
    );

    // Silence the panic hook: in the debug profile a `debug_assert` firing
    // would otherwise interleave a backtrace between two table rows. The row
    // itself reports `PANIC`, so nothing is lost.
    let previous_hook = std::panic::take_hook();
    std::panic::set_hook(Box::new(|_| {}));

    let rows = vec![
        // -- SITE 1: delete_dimension, the ce-dimension sidecar ------------
        run(
            "1  delete_dimension /Ap",
            "dim-sidecar-ap-names-pagetree.pdf",
            false,
            |s| {
                let Some(d) = first_dimension(s) else {
                    return "no ce dimension in model".to_owned();
                };
                show(s.delete_dimension(d), |()| "Ok".to_owned())
            },
        ),
        run(
            "1  delete_dimension /Annot",
            "dim-sidecar-annot-names-pagetree.pdf",
            false,
            |s| {
                let Some(d) = first_dimension(s) else {
                    return "no ce dimension in model".to_owned();
                };
                show(s.delete_dimension(d), |()| "Ok".to_owned())
            },
        ),
        run(
            "1  delete_dimension CONTROL",
            "dim-sidecar-control.pdf",
            true,
            |s| {
                let Some(d) = first_dimension(s) else {
                    return "no ce dimension in model".to_owned();
                };
                show(s.delete_dimension(d), |()| "Ok".to_owned())
            },
        ),
        // -- SITE 2: regenerate_dimension_writes, via a LABEL EDIT ---------
        //
        // The verb chosen deliberately: `set_dimension_label` is the least
        // destructive-looking operation that reaches
        // `regenerate_dimension_writes`, and the audit's claim is that a label
        // edit can destroy the page tree.
        run(
            "2  set_dimension_label /Ap",
            "dim-sidecar-ap-names-pagetree.pdf",
            false,
            |s| {
                let Some(d) = first_dimension(s) else {
                    return "no ce dimension in model".to_owned();
                };
                show(s.set_dimension_label(d, Some("HOLD")), |c| {
                    format!("Ok(changed={})", c.changed)
                })
            },
        ),
        run(
            "2  set_dimension_label CONTROL",
            "dim-sidecar-control.pdf",
            true,
            |s| {
                let Some(d) = first_dimension(s) else {
                    return "no ce dimension in model".to_owned();
                };
                show(s.set_dimension_label(d, Some("HOLD")), |c| {
                    format!("Ok(changed={})", c.changed)
                })
            },
        ),
        // -- SITE 3: delete_redaction_mark ---------------------------------
        run(
            "3  delete_redaction_mark /AP /N",
            "redact-ap-names-pagetree.pdf",
            false,
            |s| {
                show(s.delete_redaction_mark(ObjId::new(4, 0)), |()| {
                    "Ok".to_owned()
                })
            },
        ),
        run(
            "3  delete_redaction_mark annot_id",
            "redact-mark-is-pagetree-node.pdf",
            false,
            |s| {
                show(s.delete_redaction_mark(ObjId::new(2, 0)), |()| {
                    "Ok".to_owned()
                })
            },
        ),
        run(
            "3  delete_redaction_mark CONTROL",
            "redact-control.pdf",
            true,
            |s| {
                show(s.delete_redaction_mark(ObjId::new(4, 0)), |()| {
                    "Ok".to_owned()
                })
            },
        ),
        // -- SITE 4: flatten_fields ----------------------------------------
        run(
            "4  flatten_fields /Fields->/Page",
            "flatten-field-is-page.pdf",
            false,
            |s| {
                show(s.flatten_fields(None), |o| {
                    format!(
                        "Ok(fields={}, widgets={})",
                        o.fields_flattened, o.widgets_burned
                    )
                })
            },
        ),
        run(
            "4  flatten_fields CONTROL",
            "flatten-control.pdf",
            true,
            |s| {
                show(s.flatten_fields(None), |o| {
                    format!(
                        "Ok(fields={}, widgets={})",
                        o.fields_flattened, o.widgets_burned
                    )
                })
            },
        ),
        // -- SITE 5: outline_subtree / delete_outline_item ------------------
        run(
            "5  outline /First->/Pages",
            "outline-first-names-pagetree.pdf",
            false,
            |s| {
                show(s.delete_outline_item(ObjId::new(5, 0)), |n| {
                    format!("Ok({n})")
                })
            },
        ),
        run(
            "5  delete_outline_item(page)",
            "outline-item-is-page.pdf",
            false,
            |s| {
                show(s.delete_outline_item(ObjId::new(3, 0)), |n| {
                    format!("Ok({n})")
                })
            },
        ),
        run("5  outline CONTROL", "outline-control.pdf", true, |s| {
            show(s.delete_outline_item(ObjId::new(5, 0)), |n| {
                format!("Ok({n})")
            })
        }),
        // -- SITE 6: cascade 1's /Popup ------------------------------------
        run(
            "6  delete_annotation /Popup",
            "popup-is-pagetree-node.pdf",
            false,
            |s| {
                show(s.delete_annotation(ObjId::new(4, 0)), |d| {
                    format!("Ok(popup_removed={})", d.popup_removed)
                })
            },
        ),
        run(
            "6  delete_annotation CONTROL",
            "popup-control.pdf",
            true,
            |s| {
                show(s.delete_annotation(ObjId::new(4, 0)), |d| {
                    format!("Ok(popup_removed={})", d.popup_removed)
                })
            },
        ),
        // -- SITE 7: detach_file -------------------------------------------
        run(
            "7  detach_file name-tree value",
            "attach-namevalue-is-pagetree.pdf",
            false,
            |s| show(s.detach_file(b"trap"), |()| "Ok".to_owned()),
        ),
        run(
            "7  detach_file /EF /F",
            "attach-ef-is-pagetree.pdf",
            false,
            |s| show(s.detach_file(b"trap"), |()| "Ok".to_owned()),
        ),
        run("7  detach_file CONTROL", "attach-control.pdf", true, |s| {
            show(s.detach_file(b"note.txt"), |()| "Ok".to_owned())
        }),
        // -- SITE 8: unembed_fonts's /CIDSet -------------------------------
        run(
            "8  unembed_fonts /CIDSet",
            "cidset-names-pagetree.pdf",
            false,
            |s| {
                show(s.unembed_fonts(&UnembedRequest::all_removable()), |p| {
                    format!("Ok(targets={})", p.targets.len())
                })
            },
        ),
        run(
            "8  unembed_fonts CONTROL",
            "cidset-control.pdf",
            true,
            |s| {
                show(s.unembed_fonts(&UnembedRequest::all_removable()), |p| {
                    format!("Ok(targets={})", p.targets.len())
                })
            },
        ),
    ];

    std::panic::set_hook(previous_hook);

    println!();
    println!(
        "{:<32} {:<38} {:<34} {:<16} SAVE_FULL + RELOAD",
        "SITE", "FIXTURE", "VERB RESULT", "WALKS AFTER"
    );
    println!("{}", "-".repeat(160));
    for r in &rows {
        let mark = if r.control { "  [CONTROL]" } else { "" };
        println!(
            "{:<32} {:<38} {:<34} {:<16} {}{}",
            r.site, r.fixture, r.verb, r.walks, r.reload, mark
        );
    }

    // The one-line verdict, so a reader does not have to scan the table for
    // the shape that matters: `Ok` plus a broken reload is R238 rung 3, the
    // urgent one, and it is silent by construction in a release build.
    println!();
    let corrupt: Vec<&Row> = rows
        .iter()
        .filter(|r| !r.control && r.verb.starts_with("Ok") && r.reload.starts_with('★'))
        .collect();
    println!(
        "R238 rung 3 (returns Ok AND writes wrong bytes): {} of {} hostile cases",
        corrupt.len(),
        rows.iter().filter(|r| !r.control).count()
    );
    for r in corrupt {
        println!("    {}  [{}]", r.site, r.fixture);
    }
    let broken_controls: Vec<&Row> = rows
        .iter()
        .filter(|r| r.control && !(r.verb.starts_with("Ok") && r.reload.starts_with("yes")))
        .collect();
    println!("controls not clean: {}", broken_controls.len());
    for r in broken_controls {
        println!("    {}  [{}]  {}", r.site, r.fixture, r.verb);
    }
}
