use super::*;

/// Parse the command line and dispatch to the subcommand's `cmd_*` handler.
pub(crate) fn run() -> ExitCode {
    // `Cli::parse()` would ship the doc comments verbatim; `scrub_help` takes
    // the Markdown and the internal Pass IDs out first. See `plain_help`.
    let cli = {
        use clap::{CommandFactory as _, FromArgMatches as _};
        let matches = scrub_help(Cli::command()).get_matches();
        match Cli::from_arg_matches(&matches) {
            Ok(cli) => cli,
            Err(err) => err.exit(),
        }
    };

    // Resolve the password BEFORE any subcommand runs, so a bad
    // --password-file fails immediately and by name rather than surfacing
    // later as "this document is password-protected".
    match resolve_cli_password(cli.open_password, cli.open_password_file) {
        Ok(pw) => {
            let _ = CLI_PASSWORD.set(pw);
        }
        Err(msg) => {
            eprintln!("pdfcer: {msg}");
            return ExitCode::from(3);
        }
    }

    let _ = CLI_LOAD_OPTIONS.set(cli.on_malformed.to_load_options());

    let code = match cli.command {
        Command::Inspect {
            file,
            text_blocks,
            pages,
            json,
            reflow_preview,
            block,
            width,
            align,
            leading,
            forms,
        } => {
            if forms {
                cmd_inspect_forms(&file, &pages)
            } else if reflow_preview {
                cmd_inspect_reflow_preview(
                    &file,
                    &pages,
                    block,
                    width,
                    align.as_deref(),
                    leading,
                    json,
                )
            } else if text_blocks {
                cmd_inspect_text_blocks(&file, &pages, json)
            } else {
                cmd_inspect(&file)
            }
        }
        // The remaining stubs are named individually (rather than via a
        // catch-all) so `--help` still documents each one's real
        // argument shape.
        Command::Merge {
            inputs,
            output,
            no_bookmarks,
        } => cmd_merge(&inputs, &output, !no_bookmarks),
        Command::Split {
            input,
            out_dir,
            every,
            after,
            bookmarks,
            name_template,
            force,
        } => cmd_split(
            &input,
            &out_dir,
            every,
            after.as_deref(),
            bookmarks,
            &name_template,
            force,
        ),
        Command::ExtractPages {
            input,
            pages,
            output,
        } => cmd_extract_pages(&input, &pages, &output),
        Command::PlaceStamp {
            input,
            from,
            stamp_page,
            stamp,
            page,
            rect,
            at,
            output,
            mode,
        } => cmd_place_stamp(
            &input,
            &from,
            stamp_page,
            stamp.as_deref(),
            page,
            rect.as_deref(),
            at.as_deref(),
            &output,
            mode,
        ),
        Command::ScanOffpage {
            paths,
            recursive,
            tolerance,
            output,
            detail,
            files_only,
        } => cmd_scan_offpage(
            &paths,
            recursive,
            tolerance,
            output.as_deref(),
            detail,
            files_only,
        ),
        Command::RedactOffpage {
            paths,
            residual_scope,
            recursive,
            output,
            out_dir,
            suffix,
            force,
            tolerance,
            dry_run,
        } => cmd_redact_offpage_batch(
            &paths,
            residual_scope,
            recursive,
            output.as_deref(),
            out_dir.as_deref(),
            &suffix,
            force,
            tolerance,
            dry_run,
        ),
        Command::InsertPages {
            input,
            source,
            source_pages,
            before,
            after,
            output,
        } => cmd_insert_pages(&input, &source, &source_pages, before, after, &output),
        Command::DeletePages {
            input,
            pages,
            output,
            mode,
            verify_undo,
        } => cmd_delete_pages(&input, &pages, &output, mode, verify_undo),
        Command::ReorderPages {
            input,
            order,
            output,
            mode,
            verify_undo,
        } => cmd_reorder_pages(&input, &order, &output, mode, verify_undo),
        Command::Rotate {
            input,
            degrees,
            pages,
            output,
            mode,
            verify_undo,
        } => cmd_rotate(&input, degrees, &pages, &output, mode, verify_undo),
        Command::BatesStamp { .. } => unimplemented_stub("bates-stamp"),
        Command::ToPdfa { .. } => unimplemented_stub("to-pdfa"),
        Command::ValidatePdfa { .. } => unimplemented_stub("validate-pdfa"),
        #[cfg(feature = "signing")]
        Command::Sign {
            input,
            cert,
            password,
            output,
            format,
            algorithm,
            signing_time,
            name,
            reason,
            location,
            contact,
            certify,
            mdp_level,
            field_name,
            visible,
            page,
            reserve,
        } => cmd_sign(&SignArgs {
            input: &input,
            cert: &cert,
            password: &password,
            output: &output,
            format,
            algorithm,
            signing_time: signing_time.as_deref(),
            name: name.as_deref(),
            reason: reason.as_deref(),
            location: location.as_deref(),
            contact: contact.as_deref(),
            certify,
            mdp_level,
            field_name: field_name.as_deref(),
            visible: visible.as_deref(),
            page,
            reserve,
        }),
        Command::ListOutline { input, flat, json } => cmd_list_outline(&input, flat, json),
        Command::MergeDocument {
            input,
            source,
            before,
            after,
            at_start,
            output,
            mode,
            verify_undo,
        } => cmd_merge_document(
            &input,
            &source,
            before,
            after,
            at_start,
            &output,
            mode,
            verify_undo,
        ),
        Command::AddNamedDest {
            input,
            name,
            page,
            top,
            output,
            mode,
            verify_undo,
        } => cmd_add_named_dest(&input, &name, page, top, &output, mode, verify_undo),
        Command::AdoptWidget {
            input,
            page,
            index,
            name,
            dry_run,
            output,
            mode,
            verify_undo,
        } => cmd_adopt_widget(
            &input,
            page,
            index,
            name.as_deref(),
            dry_run,
            output.as_deref(),
            mode,
            verify_undo,
        ),
        Command::RenameBookmark {
            input,
            n,
            title,
            output,
            mode,
        } => cmd_edit_bookmark(&input, n, Some(&title), &output, mode),
        Command::DeleteBookmark {
            input,
            n,
            output,
            mode,
        } => cmd_edit_bookmark(&input, n, None, &output, mode),
        Command::MoveBookmark {
            input,
            n,
            before,
            after,
            under,
            to_top_level,
            first,
            output,
            mode,
        } => cmd_move_bookmark(
            &input,
            n,
            before,
            after,
            under,
            to_top_level,
            first,
            &output,
            mode,
        ),
        Command::SetBookmarkOpen {
            input,
            n,
            collapse,
            output,
            mode,
        } => cmd_set_bookmark_open(&input, n, collapse, &output, mode),
        Command::AddBookmark {
            input,
            title,
            page,
            top,
            under,
            dest_name,
            output,
            mode,
            verify_undo,
        } => cmd_add_bookmark(
            &input,
            &title,
            page,
            top,
            under,
            dest_name.as_deref(),
            &output,
            mode,
            verify_undo,
        ),
        Command::ListAttachments { input } => cmd_list_attachments(&input),
        Command::ExtractAttachment {
            input,
            name,
            output,
            cut,
            mode,
        } => cmd_extract_attachment(&input, &name, &output, cut.as_deref(), mode),
        Command::AttachFile {
            input,
            file,
            name,
            desc,
            apply,
            output,
            mode,
        } => cmd_attach_file(
            &input,
            &file,
            name.as_deref(),
            desc.as_deref(),
            apply,
            output.as_deref(),
            mode,
        ),
        Command::DetachFile {
            input,
            name,
            apply,
            output,
            mode,
        } => cmd_detach_file(&input, &name, apply, output.as_deref(), mode),
        Command::ListLayers { input } => cmd_list_layers(&input),
        Command::ListFonts {
            input,
            reasons,
            by_size,
        } => cmd_list_fonts(&input, reasons, by_size),
        Command::FontPreflight {
            input,
            page,
            find,
            pin_span,
            candidate,
            json,
        } => cmd_font_preflight(
            &input,
            page,
            &find,
            pin_span.as_deref(),
            candidate.as_deref(),
            json,
        ),
        Command::RunRepertoire {
            input,
            page,
            find,
            pin_span,
            list,
        } => cmd_run_repertoire(&input, page, &find, pin_span.as_deref(), list),
        Command::ListSignatures { input } => cmd_list_signatures(&input),
        Command::VerifySignatures {
            input,
            trust_from_acrobat,
        } => cmd_verify_signatures(&input, trust_from_acrobat),
        Command::ListPrinters => cmd_list_printers(),
        Command::Print {
            input,
            printer,
            scale,
            scale_percent,
            pages,
            send,
            max_dpi,
            to_file,
            copies,
            uncollated,
            subset,
            reverse,
            orientation,
            duplex,
            pick_tray,
            paper,
            paper_size,
            printer_config,
            comments,
            n_up,
            n_up_border,
            booklet,
            poster,
            poster_scale,
            poster_overlap,
            poster_large_only,
            poster_max_tiles,
            binding,
            booklet_subset,
            line_width,
            poster_cut_marks,
            poster_labels,
        } => cmd_print(
            &input,
            printer.as_deref(),
            scale,
            scale_percent,
            &pages,
            send,
            max_dpi,
            to_file,
            copies,
            uncollated,
            subset,
            reverse,
            orientation,
            duplex,
            pick_tray,
            paper.as_deref(),
            paper_size.as_deref(),
            printer_config.as_deref(),
            comments,
            n_up,
            n_up_border,
            booklet,
            poster,
            poster_scale,
            poster_overlap,
            poster_large_only,
            poster_max_tiles,
            binding,
            booklet_subset,
            line_width,
            poster_cut_marks,
            poster_labels,
        ),
        Command::PrintPreview {
            input,
            printer,
            scale,
            pages,
            scale_percent,
            orientation,
            paper,
            paper_size,
        } => cmd_print_preview(
            &input,
            printer.as_deref(),
            scale,
            scale_percent,
            &pages,
            orientation,
            paper.as_deref(),
            paper_size.as_deref(),
        ),
        Command::ListPaperSizes { printer } => cmd_list_paper_sizes(printer.as_deref()),
        Command::PrinterProperties {
            printer,
            save,
            from,
            no_dialog,
        } => cmd_printer_properties(
            printer.as_deref(),
            save.as_deref(),
            from.as_deref(),
            no_dialog,
        ),
        Command::FindText {
            input,
            needle,
            ignore_case,
        } => cmd_find_text(&input, &needle, ignore_case),
        Command::ExtractText {
            input,
            pages,
            output,
            json,
            include_artifacts,
            spans,
        } => cmd_extract_text(
            &input,
            &pages,
            output.as_deref(),
            json,
            include_artifacts,
            spans,
        ),
        Command::FetchOcrModels { dir } => cmd_fetch_ocr_models(dir.as_deref()),
        Command::ListStandards { standard } => cmd_list_standards(standard.as_deref()),
        Command::Ocr {
            input,
            page,
            output,
            in_place,
            dpi,
            ocr_engine,
            model_dir,
            ocr_lang,
            words,
            dump_image,
            existing,
        } => cmd_ocr(
            &input,
            page,
            output.as_deref(),
            in_place,
            dpi,
            ocr_engine,
            model_dir.as_deref(),
            &ocr_lang,
            words,
            dump_image.as_deref(),
            existing,
        ),
        Command::StampList { input } => cmd_stamp_list(&input),
        Command::StampPack {
            input,
            category,
            stamps,
            stamps_from,
            output,
        } => cmd_stamp_pack(&input, &category, &stamps, stamps_from.as_deref(), &output),
        Command::RenderPage {
            input,
            page,
            scale,
            standard,
            region,
            output,
            no_annotations,
            fast_subpixel,
            max_cmyk_buffer_bytes,
            probe_ink,
            font_dirs,
            show_layers,
            hide_layers,
            print_state,
            overprint_zero_tint_scope,
            spot_colorant_device_model,
        } => cmd_render_page(
            &input,
            page,
            scale,
            standard.as_deref(),
            overprint_zero_tint_scope.as_deref(),
            spot_colorant_device_model.as_deref(),
            region.as_deref(),
            &output,
            !no_annotations,
            fast_subpixel,
            max_cmyk_buffer_bytes.as_deref(),
            probe_ink.as_deref(),
            &font_dirs,
            &show_layers,
            &hide_layers,
            print_state,
        ),
        Command::ExportImage {
            input,
            pages,
            format,
            dpi,
            transparent,
            quality,
            background,
            output,
            output_dir,
            standard,
            overprint_zero_tint_scope,
            spot_colorant_device_model,
            no_annotations,
            fast_subpixel,
            max_cmyk_buffer_bytes,
            font_dirs,
            show_layers,
            hide_layers,
            print_state,
            svg_text,
            emf_text,
        } => cmd_export_image(ExportImageArgs {
            input: &input,
            pages: &pages,
            format,
            dpi,
            transparent,
            quality,
            background: background.as_deref(),
            output: output.as_deref(),
            output_dir: output_dir.as_deref(),
            standard: standard.as_deref(),
            overprint_zero_tint_scope: overprint_zero_tint_scope.as_deref(),
            spot_colorant_device_model: spot_colorant_device_model.as_deref(),
            annotations: !no_annotations,
            fast_subpixel,
            max_cmyk_buffer_bytes: max_cmyk_buffer_bytes.as_deref(),
            font_dirs: &font_dirs,
            show_layers: &show_layers,
            hide_layers: &hide_layers,
            print_state,
            svg_text,
            emf_text,
        }),
        Command::CopyPage {
            input,
            page,
            dpi,
            no_svg,
            no_emf,
            no_raster,
            no_pdf,
            background,
            no_annotations,
            font_dirs,
            show_layers,
            hide_layers,
        } => cmd_copy_page(CopyPageArgs {
            input: &input,
            page,
            dpi,
            svg: !no_svg,
            emf: !no_emf,
            raster: !no_raster,
            pdf: !no_pdf,
            background: background.as_deref(),
            annotations: !no_annotations,
            font_dirs: &font_dirs,
            show_layers: &show_layers,
            hide_layers: &hide_layers,
        }),
        Command::ListAnnotations { input, pages } => cmd_list_annotations(&input, &pages),
        Command::TabOrder {
            input,
            pages,
            row_tolerance,
        } => cmd_tab_order(&input, &pages, row_tolerance),
        Command::ListLinks { input, pages } => cmd_list_links(&input, &pages),
        Command::DumpObject {
            input,
            id,
            generation,
            depth,
            streams,
            max_stream_bytes,
        } => cmd_dump_object(&input, id, generation, depth, streams, max_stream_bytes),
        Command::DumpStructure {
            input,
            root,
            max_objects,
            streams,
            max_stream_bytes,
        } => cmd_dump_structure(&input, &root, max_objects, streams, max_stream_bytes),
        Command::ListObjects {
            input,
            filter_type,
            layout_only,
            show_unreferenced,
        } => cmd_list_objects(
            &input,
            filter_type.as_deref(),
            layout_only,
            show_unreferenced,
        ),
        Command::ExportStructure { input, output } => cmd_export_structure(&input, &output),
        Command::ImportStructure {
            input,
            edited,
            output,
            full,
            dry_run,
        } => cmd_import_structure(&input, &edited, &output, full, dry_run),
        Command::ListFields {
            input,
            fillable_only,
            rich_text,
            widgets,
        } => cmd_list_fields(&input, fillable_only, rich_text, widgets),
        Command::AddTextField {
            input,
            name,
            page,
            rect,
            value,
            max_len,
            tooltip,
            no_tooltip,
            multiline,
            read_only,
            required,
            password,
            comb,
            border,
            border_width,
            background,
            border_color,
            visibility,
            output,
            mode,
            defaults_from,
            verify_undo,
        } => cmd_add_text_field(&AddTextFieldArgs {
            input: &input,
            name: &name,
            page,
            rect: &rect,
            value: value.as_deref(),
            max_len,
            tooltip: tooltip.as_deref(),
            no_tooltip,
            multiline,
            read_only,
            required,
            password,
            comb,
            border,
            border_width,
            background: background.as_deref(),
            border_color: border_color.as_deref(),
            visibility,
            output: &output,
            mode,
            defaults_from: defaults_from.as_deref(),
            verify_undo,
        }),
        Command::AddImage {
            input,
            image,
            page,
            rect,
            stretch,
            natural,
            compression,
            quality,
            output,
            mode,
            verify_undo,
        } => cmd_add_image(&AddImageArgs {
            input: &input,
            image: &image,
            page,
            rect: &rect,
            stretch,
            natural,
            compression: compression.policy(quality),
            output: &output,
            mode,
            verify_undo,
        }),
        Command::BookmarkCopy {
            input,
            item,
            clip,
            cut,
            mode,
        } => cmd_bookmark_copy(&BookmarkCopyArgs {
            input: &input,
            item,
            clip: &clip,
            cut: cut.as_deref(),
            mode,
        }),
        Command::BookmarkPaste {
            input,
            clip,
            under,
            output,
            mode,
        } => cmd_bookmark_paste(&BookmarkPasteArgs {
            input: &input,
            clip: &clip,
            under,
            output: &output,
            mode,
        }),
        Command::PageCopy {
            input,
            pages,
            clip,
            cut,
            mode,
        } => cmd_page_copy(&PageCopyArgs {
            input: &input,
            pages: &pages,
            clip: &clip,
            cut: cut.as_deref(),
            mode,
        }),
        Command::PagePaste {
            input,
            clip,
            at,
            output,
            mode,
        } => cmd_page_paste(&PagePasteArgs {
            input: &input,
            clip: &clip,
            at: &at,
            output: &output,
            mode,
        }),
        Command::CopyField {
            input,
            name,
            output,
            cut,
            mode,
        } => cmd_copy_field(&CopyFieldArgs {
            input: &input,
            name: &name,
            output: &output,
            cut: cut.as_deref(),
            mode,
        }),
        Command::InspectFieldClip { clip } => cmd_inspect_field_clip(&clip),
        Command::PasteField {
            input,
            clip,
            page,
            rect,
            as_new,
            as_widget_of,
            copy_value,
            copy_actions,
            tooltip,
            carry_tooltip,
            no_tooltip,
            output,
            mode,
            verify_undo,
        } => cmd_paste_field(&PasteFieldArgs {
            input: &input,
            clip: &clip,
            page,
            rect: &rect,
            as_new: as_new.as_deref(),
            as_widget_of: as_widget_of.as_deref(),
            copy_value,
            copy_actions,
            tooltip: tooltip.as_deref(),
            carry_tooltip,
            no_tooltip,
            output: &output,
            mode,
            verify_undo,
        }),
        Command::AddCheckBox {
            input,
            name,
            page,
            rect,
            on_state,
            checked,
            tooltip,
            no_tooltip,
            read_only,
            required,
            output,
            mode,
            defaults_from,
            verify_undo,
            border,
            border_width,
            background,
            border_color,
            visibility,
            check_style,
        } => cmd_add_check_box(&AddCheckBoxArgs {
            input: &input,
            name: &name,
            page,
            rect: &rect,
            on_state: &on_state,
            checked,
            tooltip: tooltip.as_deref(),
            no_tooltip,
            read_only,
            required,
            output: &output,
            mode,
            defaults_from: defaults_from.as_deref(),
            verify_undo,
            border,
            border_width,
            background: background.as_deref(),
            border_color: border_color.as_deref(),
            visibility,
            check_style: check_style.as_deref(),
        }),
        Command::AddRadioButton {
            input,
            name,
            page,
            rect,
            export_value,
            selected,
            tooltip,
            no_tooltip,
            no_toggle_to_off,
            radios_in_unison,
            read_only,
            required,
            output,
            mode,
            defaults_from,
            verify_undo,
            border,
            border_width,
            background,
            border_color,
            visibility,
        } => cmd_add_radio_button(&AddRadioButtonArgs {
            input: &input,
            name: &name,
            page,
            rect: &rect,
            export_value: &export_value,
            selected,
            tooltip: tooltip.as_deref(),
            no_tooltip,
            no_toggle_to_off,
            radios_in_unison,
            read_only,
            required,
            output: &output,
            mode,
            defaults_from: defaults_from.as_deref(),
            verify_undo,
            border,
            border_width,
            background: background.as_deref(),
            border_color: border_color.as_deref(),
            visibility,
        }),
        Command::DeleteField {
            input,
            name,
            output,
            mode,
            verify_undo,
        } => cmd_delete_form_field(&input, &name, None, &output, mode, verify_undo),
        Command::DeleteFieldGroup {
            input,
            name,
            output,
            yes,
            mode,
            verify_undo,
        } => cmd_delete_field_group(&input, &name, &output, yes, mode, verify_undo),
        Command::DeleteWidget {
            input,
            name,
            index,
            output,
            mode,
            verify_undo,
        } => cmd_delete_form_field(&input, &name, Some(index), &output, mode, verify_undo),
        Command::SetMarkupNote {
            input,
            page,
            index,
            note,
            note_author,
            note_date,
            clear,
            output,
            mode,
        } => cmd_set_markup_note(
            &input,
            (page, index),
            (
                note.as_deref(),
                note_author.as_deref(),
                note_date.as_deref(),
            ),
            clear,
            &output,
            mode,
        ),
        Command::SetTextAnnotStyle {
            input,
            page,
            index,
            icon,
            color,
            font_size,
            stamp_fit,
            output,
            mode,
        } => cmd_set_text_annot_style(
            &input,
            page,
            index,
            icon,
            color.as_deref(),
            font_size,
            stamp_fit,
            &output,
            mode,
        ),
        Command::SetReviewState {
            input,
            page,
            index,
            state,
            author,
            note_date,
            output,
            mode,
        } => cmd_set_review_state(
            &input,
            page,
            index,
            (state, &author, note_date.as_deref()),
            &output,
            mode,
        ),
        Command::AddReply {
            input,
            page,
            index,
            note,
            note_author,
            note_date,
            output,
            mode,
        } => cmd_add_reply(
            &input,
            page,
            index,
            (&note, note_author.as_deref(), note_date.as_deref()),
            &output,
            mode,
        ),
        Command::SetAnnotationOpen {
            input,
            page,
            index,
            open,
            output,
            mode,
        } => cmd_set_annotation_open(&input, page, index, open, &output, mode),
        Command::SetAnnotationFlags {
            input,
            page,
            index,
            invisible,
            hidden,
            print,
            no_zoom,
            no_rotate,
            no_view,
            locked,
            locked_contents,
            output,
            mode,
        } => {
            // The whole word, assembled from the flags the operator passed.
            // Table 165's bit VALUES live on `AnnotFlags`; this shell does not
            // restate them, so a bit cannot be numbered differently here than
            // in the engine.
            use pdfcer_core::annot::AnnotFlags as F;
            let mut w = 0u32;
            for (on, bit) in [
                (invisible, F::INVISIBLE),
                (hidden, F::HIDDEN),
                (print, F::PRINT),
                (no_zoom, F::NO_ZOOM),
                (no_rotate, F::NO_ROTATE),
                (no_view, F::NO_VIEW),
                (locked, F::LOCKED),
                (locked_contents, F::LOCKED_CONTENTS),
            ] {
                if on {
                    w |= bit;
                }
            }
            cmd_set_annotation_flags(&input, (page, index), F(w), &output, mode)
        }
        Command::SetMarkupStyle {
            input,
            page,
            index,
            color,
            interior,
            width,
            opacity,
            dash,
            output,
            mode,
            verify_undo,
        } => cmd_set_markup_style(
            &input,
            page,
            index,
            &MarkupStyleArg {
                color: color.as_deref(),
                interior: interior.as_deref(),
                width,
                opacity: opacity.as_deref(),
                dash: dash.as_deref(),
            },
            &output,
            mode,
            verify_undo,
        ),
        Command::DeleteAnnotation {
            input,
            page,
            index,
            output,
            mode,
            verify_undo,
        } => cmd_delete_annotation(&input, page, index, &output, mode, verify_undo),
        Command::MoveWidget {
            input,
            name,
            index,
            dx,
            dy,
            output,
            mode,
        } => cmd_move_widget(&input, &name, index, dx, dy, &output, mode),
        Command::SetFieldScript {
            input,
            name,
            format_number,
            format_percent,
            format_date,
            format_date_string,
            format_time,
            format_special,
            validate_range,
            calculate,
            clear,
            trigger,
            output,
            mode,
            verify_undo,
        } => cmd_set_field_script(&SetFieldScriptArgs {
            input: &input,
            name: &name,
            format_number: format_number.as_deref(),
            format_percent: format_percent.as_deref(),
            format_date,
            format_date_string: format_date_string.as_deref(),
            format_time,
            format_special,
            validate_range: validate_range.as_deref(),
            calculate: calculate.as_deref(),
            clear,
            trigger: trigger.as_deref(),
            output: &output,
            mode,
            verify_undo,
        }),
        Command::SetButtonAction {
            input,
            name,
            reset,
            reset_only,
            reset_except,
            submit,
            submit_format,
            submit_only,
            submit_except,
            submit_get,
            submit_coordinates,
            include_no_value_fields,
            canonical_dates,
            include_annotations,
            only_current_user_annotations,
            include_incremental_updates,
            exclude_document_path,
            embed_form,
            goto_page,
            goto_view,
            hide,
            show,
            named,
            uri,
            clear,
            output,
            mode,
            verify_undo,
        } => cmd_set_button_action(&SetButtonActionArgs {
            input: &input,
            name: &name,
            reset,
            reset_only: &reset_only,
            reset_except: &reset_except,
            submit: submit.as_deref(),
            submit_format,
            submit_only: &submit_only,
            submit_except: &submit_except,
            submit_get,
            submit_coordinates,
            include_no_value_fields,
            canonical_dates,
            include_annotations,
            only_current_user_annotations,
            include_incremental_updates,
            exclude_document_path,
            embed_form,
            goto_page,
            goto_view,
            hide: &hide,
            show: &show,
            named,
            uri: uri.as_deref(),
            clear,
            output: &output,
            mode,
            verify_undo,
        }),
        Command::RotateWidget {
            input,
            name,
            index,
            degrees,
            output,
            mode,
            verify_undo,
        } => cmd_rotate_widget(&RotateWidgetArgs {
            input: &input,
            name: &name,
            index,
            degrees,
            output: &output,
            mode,
            verify_undo,
        }),
        Command::MoveAnnotation {
            input,
            page,
            index,
            dx,
            dy,
            output,
            mode,
        } => cmd_move_annotation(&input, page, index, dx, dy, &output, mode),
        Command::ReorderAnnotations {
            input,
            page,
            order,
            output,
            mode,
            verify_undo,
        } => cmd_reorder_annotations(&input, page, &order, &output, mode, verify_undo),
        Command::RotateAnnotation {
            input,
            page,
            index,
            degrees,
            absolute,
            anchor_x,
            anchor_y,
            output,
            mode,
        } => cmd_rotate_annotation(
            &input,
            (page, index),
            degrees,
            absolute,
            (anchor_x, anchor_y),
            &output,
            mode,
        ),
        Command::ResizeAnnotation {
            input,
            page,
            index,
            sx,
            sy,
            anchor_x,
            anchor_y,
            scale_stroke_width,
            keep_rect_differences,
            allow_appearance_distortion,
            output,
            mode,
        } => cmd_resize_annotation(
            &input,
            (page, index),
            (sx, sy),
            (anchor_x, anchor_y),
            &pdfcer_core::edit::ResizeOptions::new()
                .with_scale_stroke_width(scale_stroke_width)
                .with_keep_rect_differences(keep_rect_differences)
                .with_allow_appearance_distortion(allow_appearance_distortion),
            &output,
            mode,
        ),
        Command::EditField {
            input,
            name,
            required,
            read_only,
            tooltip,
            multiline,
            password,
            comb,
            max_len,
            no_toggle_to_off,
            radios_in_unison,
            combo,
            editable,
            multi_select,
            sort,
            options,
            quadding,
            clear_quadding,
            default_value,
            clear_default_value,
            no_export,
            file_select,
            no_spell_check,
            no_scroll,
            commit_on_sel_change,
            mapping_name,
            clear_mapping_name,
            font,
            font_resource,
            font_size,
            font_color,
            output,
            mode,
        } => cmd_edit_field(&EditFieldArgs {
            input: &input,
            name: &name,
            required,
            read_only,
            tooltip: tooltip.as_deref(),
            multiline,
            password,
            comb,
            max_len,
            no_toggle_to_off,
            radios_in_unison,
            combo,
            editable,
            multi_select,
            sort,
            quadding,
            clear_quadding,
            default_value: default_value.as_deref(),
            clear_default_value,
            no_export,
            file_select,
            no_spell_check,
            no_scroll,
            commit_on_sel_change,
            mapping_name: mapping_name.as_deref(),
            clear_mapping_name,
            font: font.as_deref(),
            font_resource: font_resource.as_deref(),
            font_size,
            font_color: font_color.as_deref(),
            options: &options,
            output: &output,
            mode,
        }),
        Command::EditWidget {
            input,
            name,
            index,
            rect,
            border_style,
            border_width,
            visibility,
            caption,
            background,
            border_color,
            scale_stroke_width,
            keep_rect_differences,
            allow_appearance_distortion,
            output,
            mode,
        } => cmd_edit_widget(&EditWidgetArgs {
            input: &input,
            name: &name,
            index,
            rect: rect.as_deref(),
            border_style: border_style.as_deref(),
            border_width,
            visibility: visibility.as_deref(),
            caption: caption.as_deref(),
            background: background.as_deref(),
            border_color: border_color.as_deref(),
            resize: pdfcer_core::edit::ResizeOptions::new()
                .with_scale_stroke_width(scale_stroke_width)
                .with_keep_rect_differences(keep_rect_differences)
                .with_allow_appearance_distortion(allow_appearance_distortion),
            output: &output,
            mode,
        }),
        Command::RenameField {
            input,
            name,
            to,
            output,
            mode,
            verify_undo,
        } => cmd_rename_field(&input, &name, &to, &output, mode, verify_undo),
        Command::AddPushButton {
            input,
            name,
            page,
            rect,
            caption,
            tooltip,
            no_tooltip,
            read_only,
            output,
            mode,
            defaults_from,
            verify_undo,
            border,
            border_width,
            background,
            border_color,
            visibility,
        } => cmd_add_push_button(&AddPushButtonArgs {
            input: &input,
            name: &name,
            page,
            rect: &rect,
            caption: &caption,
            tooltip: tooltip.as_deref(),
            no_tooltip,
            read_only,
            output: &output,
            mode,
            defaults_from: defaults_from.as_deref(),
            verify_undo,
            border,
            border_width,
            background: background.as_deref(),
            border_color: border_color.as_deref(),
            visibility,
        }),
        Command::AddChoiceField {
            input,
            name,
            page,
            rect,
            options,
            combo,
            editable,
            multi_select,
            sort,
            tooltip,
            no_tooltip,
            read_only,
            required,
            output,
            mode,
            defaults_from,
            verify_undo,
            border,
            border_width,
            background,
            border_color,
            visibility,
        } => cmd_add_choice_field(&AddChoiceFieldArgs {
            input: &input,
            name: &name,
            page,
            rect: &rect,
            options: &options,
            combo,
            editable,
            multi_select,
            sort,
            tooltip: tooltip.as_deref(),
            no_tooltip,
            read_only,
            required,
            output: &output,
            mode,
            defaults_from: defaults_from.as_deref(),
            verify_undo,
            border,
            border_width,
            background: background.as_deref(),
            border_color: border_color.as_deref(),
            visibility,
        }),
        Command::Recompute {
            input,
            apply,
            output,
            mode,
            comma,
            verify_undo,
        } => cmd_recompute(
            &input,
            apply,
            output.as_deref(),
            mode,
            comma.into(),
            verify_undo,
        ),
        Command::ResetForm {
            input,
            fields,
            apply,
            output,
            mode,
            verify_undo,
        } => cmd_reset_form(&input, &fields, apply, output.as_deref(), mode, verify_undo),
        Command::ListScripts {
            input,
            reproducible_only,
        } => cmd_list_scripts(&input, reproducible_only),
        Command::FillField {
            input,
            sets,
            output,
            mode,
            verify_undo,
            downgrade_rich_text,
        } => cmd_fill_field(
            &input,
            &sets,
            &output,
            mode,
            verify_undo,
            downgrade_rich_text,
        ),
        Command::RegenerateAppearances {
            input,
            output,
            mode,
        } => cmd_regenerate_appearances(&input, &output, mode),
        Command::Flatten {
            input,
            fields,
            output,
            full_rewrite,
        } => cmd_flatten(&input, &fields, &output, full_rewrite),
        Command::ExportData {
            input,
            output,
            format,
        } => cmd_export_data(&input, &output, format),
        Command::ImportData {
            input,
            data,
            output,
            mode,
        } => cmd_import_data(&input, &data, &output, mode),
        Command::RoundTrip {
            input,
            mode,
            output,
            producer,
            scale,
            no_raster,
        } => cmd_round_trip(&input, mode, output.as_deref(), producer, scale, !no_raster),
        Command::EditText {
            input,
            page,
            find,
            replace,
            output,
            pin,
            pin_span,
            span_from_pin,
            font_dirs,
            target,
        } => cmd_edit_text(&EditTextArgs {
            input: &input,
            output: &output,
            page,
            find: &find,
            pin_span: pin_span.as_deref(),
            span_from_pin,
            replace: &replace,
            pin,
            font_dirs: &font_dirs,
            target: &target,
        }),
        Command::FormatText {
            input,
            page,
            find,
            set_size,
            set_color,
            set_font,
            char_spacing,
            word_spacing,
            h_scale,
            render_mode,
            superscript,
            subscript,
            no_script,
            rise,
            bold_synthetic,
            italic_synthetic,
            bold,
            italic,
            style_policy,
            output,
            pin,
            pin_span,
            font_dirs,
            target,
        } => cmd_format_text(&FormatTextArgs {
            input: &input,
            output: &output,
            page,
            find: &find,
            pin_span: pin_span.as_deref(),
            set_size,
            set_color: set_color.as_deref(),
            set_font: set_font.as_deref(),
            char_spacing: char_spacing.as_deref(),
            word_spacing: word_spacing.as_deref(),
            h_scale,
            render_mode,
            rise: rise.as_deref(),
            synthetic: pdfcer_core::text_edit::StyleSynthesis::new(
                bold_synthetic,
                italic_synthetic,
            ),
            style: pdfcer_core::text_edit::StyleSynthesis::new(bold, italic),
            style_policy,
            // clap's `conflicts_with` guarantees at most one is set, so this
            // ladder cannot silently prefer one over another.
            script: if superscript {
                Some(pdfcer_core::text_edit::ScriptPosition::Superscript)
            } else if subscript {
                Some(pdfcer_core::text_edit::ScriptPosition::Subscript)
            } else if no_script {
                Some(pdfcer_core::text_edit::ScriptPosition::Normal)
            } else {
                None
            },
            pin,
            font_dirs: &font_dirs,
            target: &target,
        }),
        Command::Reflow {
            input,
            page,
            block,
            width,
            align,
            leading,
            output,
        } => cmd_reflow(
            &input,
            page,
            block,
            width,
            align.as_deref(),
            leading,
            &output,
        ),
        Command::AddText {
            input,
            page,
            at,
            wrap_box,
            align,
            leading,
            text,
            font,
            size,
            color,
            render_mode,
            font_dirs,
            embed_font,
            output,
        } => cmd_add_text(&AddTextArgs {
            input: &input,
            output: &output,
            page,
            at: at.as_deref(),
            wrap_box: wrap_box.as_deref(),
            align: align.as_deref(),
            leading,
            text: &text,
            font: &font,
            size,
            color: color.as_deref(),
            render_mode,
            font_dirs: &font_dirs,
            embed_font: embed_font.as_deref(),
        }),
        Command::PlaceText {
            text_file,
            output,
            input,
            position,
            paper,
            landscape,
            page_size,
            margin,
            margin_left,
            margin_right,
            margin_top,
            margin_bottom,
            font,
            size,
            leading,
            align,
            color,
            drop_unmappable,
            mode,
            producer,
        } => cmd_place_text(&PlaceTextArgs {
            text_file: &text_file,
            output: &output,
            input: input.as_deref(),
            position: &position,
            paper: &paper,
            landscape,
            page_size: page_size.as_deref(),
            margins: (margin, margin_left, margin_right, margin_top, margin_bottom),
            font: &font,
            size,
            leading,
            align: align.as_deref(),
            color: color.as_deref(),
            drop_unmappable,
            mode,
            producer,
        }),
        Command::DimensionAdd {
            input,
            page,
            kind,
            points,
            group,
            constraint,
            offset,
            treat_as_parallel,
            text_along,
            output,
            mode,
            verify_undo,
        } => cmd_dimension_add(&DimensionAddArgs {
            input: &input,
            page,
            kind,
            points: &points,
            group,
            constraint,
            offset,
            treat_as_parallel,
            text_along,
            output: &output,
            mode,
            verify_undo,
        }),
        Command::DimensionList { input, style } => cmd_dimension_list(&input, style),
        Command::DimensionDelete {
            input,
            dimension,
            output,
            mode,
            verify_undo,
        } => cmd_dimension_delete(&input, dimension, &output, mode, verify_undo),
        Command::GroupSetStandard {
            input,
            group,
            standard,
            output,
            mode,
            verify_undo,
        } => cmd_group_set_standard(&input, group, standard, &output, mode, verify_undo),
        Command::GroupStyle {
            input,
            group,
            text_height,
            line_width,
            arrow_length,
            arrow_form,
            color,
            tolerance,
            tolerance_places,
            clear,
            reset,
            output,
            mode,
            verify_undo,
        } => cmd_group_style(&GroupStyleArgs {
            input: &input,
            group,
            appearance: AppearanceArgs {
                text_height,
                line_width,
                arrow_length,
                arrow_form,
                color,
                tolerance,
                tolerance_places,
            },
            clear: &clear,
            reset,
            output: &output,
            mode,
            verify_undo,
        }),
        Command::DimensionStyle {
            input,
            dimension,
            unit,
            places,
            denominator,
            reduce,
            decimal_marker,
            standard,
            text_height,
            line_width,
            arrow_length,
            arrow_form,
            color,
            tolerance,
            tolerance_places,
            clear,
            reset,
            output,
            mode,
            verify_undo,
        } => cmd_dimension_style(&DimensionStyleArgs {
            input: &input,
            dimension,
            unit: unit.as_deref(),
            places,
            denominator,
            reduce,
            decimal_marker,
            standard,
            appearance: AppearanceArgs {
                text_height,
                line_width,
                arrow_length,
                arrow_form,
                color,
                tolerance,
                tolerance_places,
            },
            clear: &clear,
            reset,
            output: &output,
            mode,
            verify_undo,
        }),
        Command::DimensionRotate {
            input,
            dimension,
            degrees,
            pivot_x,
            pivot_y,
            output,
            mode,
        } => cmd_dimension_rotate(
            &input,
            dimension,
            degrees,
            (pivot_x, pivot_y),
            &output,
            mode,
        ),
        Command::DimensionVertex {
            input,
            dimension,
            op,
            index,
            dx,
            dy,
            at,
            dry_run,
            output,
            mode,
            verify_undo,
        } => cmd_dimension_vertex(&DimensionVertexArgs {
            input: &input,
            dimension,
            op,
            index,
            dx,
            dy,
            at: at.as_deref(),
            dry_run,
            output: output.as_deref(),
            mode,
            verify_undo,
        }),
        Command::AnnotationVertex {
            input,
            page,
            annot,
            op,
            index,
            dx,
            dy,
            at,
            modified,
            dry_run,
            output,
            mode,
            verify_undo,
        } => cmd_annotation_vertex(&AnnotationVertexArgs {
            input: &input,
            page,
            annot,
            op,
            index,
            dx,
            dy,
            at: at.as_deref(),
            modified: modified.as_deref(),
            dry_run,
            output: output.as_deref(),
            mode,
            verify_undo,
        }),
        Command::InkEdit {
            input,
            page,
            annot,
            op,
            stroke,
            point,
            dx,
            dy,
            at,
            points,
            modified,
            dry_run,
            output,
            mode,
            verify_undo,
        } => cmd_ink_edit(&InkEditArgs {
            input: &input,
            page,
            annot,
            op,
            stroke,
            point,
            dx,
            dy,
            at: at.as_deref(),
            points: points.as_deref(),
            modified: modified.as_deref(),
            dry_run,
            output: output.as_deref(),
            mode,
            verify_undo,
        }),
        Command::DimensionOffset {
            input,
            dimension,
            offset,
            text_along,
            output,
            mode,
            verify_undo,
        } => cmd_dimension_offset(&DimensionOffsetArgs {
            input: &input,
            dimension,
            offset,
            text_along,
            output: &output,
            mode,
            verify_undo,
        }),
        Command::DimensionDisplay {
            input,
            dimension,
            show,
            output,
            mode,
            verify_undo,
        } => cmd_dimension_display(&input, dimension, show, &output, mode, verify_undo),
        Command::GroupRename {
            input,
            group,
            name,
            output,
            mode,
            verify_undo,
        } => cmd_group_rename(&input, group, &name, &output, mode, verify_undo),
        Command::GroupDelete {
            input,
            group,
            members,
            to,
            output,
            mode,
            verify_undo,
        } => cmd_group_delete(&GroupDeleteArgs {
            input: &input,
            group,
            members,
            to,
            output: &output,
            mode,
            verify_undo,
        }),
        Command::DimensionGroup {
            input,
            dimension,
            group,
            output,
            mode,
            verify_undo,
        } => cmd_dimension_group(&input, dimension, group, &output, mode, verify_undo),
        Command::DimensionLabel {
            input,
            dimension,
            text,
            clear,
            output,
            mode,
            verify_undo,
        } => cmd_dimension_label(
            &input,
            dimension,
            // `--clear` and `--text` are mutually exclusive at the clap layer
            // and one of them is required, so this reads as the two-state
            // choice it is rather than a three-state one with an unreachable
            // arm.
            if clear { None } else { text.as_deref() },
            &output,
            mode,
            verify_undo,
        ),
        Command::GroupAdd {
            input,
            name,
            unit,
            output,
            mode,
            verify_undo,
        } => cmd_group_add(&input, &name, &unit, &output, mode, verify_undo),
        Command::GroupSetScale {
            input,
            group,
            real_length,
            drawn,
            ratio,
            unit,
            one_to_one,
            precision,
            output,
            mode,
            verify_undo,
        } => cmd_group_set_scale(&GroupSetScaleArgs {
            input: &input,
            group,
            real_length: real_length.as_deref(),
            drawn,
            ratio: ratio.as_deref(),
            unit: &unit,
            one_to_one,
            precision,
            output: &output,
            mode,
            verify_undo,
        }),
        Command::LayerToggle {
            input,
            group,
            hide,
            output,
            mode,
            verify_undo,
        } => cmd_layer_toggle(&input, group, hide, &output, mode, verify_undo),
        Command::ObjectList {
            input,
            page,
            hit,
            all_hits,
            hit_scope,
            line_pick,
            enter,
            tolerance,
        } => cmd_object_list(ObjectListArgs {
            input: &input,
            page_number: page,
            hit: hit.as_deref(),
            all_hits,
            hit_scope,
            line_pick: line_pick.as_deref(),
            enter,
            tolerance,
        }),
        Command::ObjectMove {
            input,
            page,
            object,
            dx,
            dy,
            output,
            mode,
            verify_undo,
        } => cmd_object_move(&ObjectMoveArgs {
            input: &input,
            page,
            object,
            dx,
            dy,
            output: &output,
            mode,
            verify_undo,
        }),
        Command::ObjectTransform {
            input,
            page,
            objects,
            scale,
            rotate,
            translate,
            pivot,
            on_mixed,
            on_singular,
            preview,
            output,
            mode,
            verify_undo,
        } => cmd_object_transform(&ObjectTransformArgs {
            input: &input,
            page,
            objects: &objects,
            scale: scale.as_deref(),
            rotate,
            translate: translate.as_deref(),
            pivot: pivot.as_deref(),
            on_mixed: &on_mixed,
            on_singular: &on_singular,
            preview,
            output: output.as_deref(),
            mode,
            verify_undo,
        }),
        Command::ObjectCopy {
            input,
            page,
            objects,
            annotations,
            clip,
            pdf,
            cut,
            mode,
        } => cmd_object_copy(&ObjectCopyArgs {
            input: &input,
            page,
            objects: &objects,
            annotations: &annotations,
            clip: &clip,
            pdf: pdf.as_deref(),
            cut: cut.as_deref(),
            mode,
        }),
        Command::ObjectPaste {
            input,
            page,
            clip,
            translate,
            scale,
            rotate,
            preview,
            output,
            mode,
            verify_undo,
        } => cmd_object_paste(&ObjectPasteArgs {
            input: &input,
            page,
            clip: &clip,
            translate: translate.as_deref(),
            scale: scale.as_deref(),
            rotate,
            preview,
            output: output.as_deref(),
            mode,
            verify_undo,
        }),
        Command::ObjectDelete {
            input,
            page,
            object,
            output,
            mode,
            verify_undo,
        } => cmd_object_delete(&input, page, object, &output, mode, verify_undo),
        Command::UnshareForm {
            input,
            page,
            form,
            output,
            mode,
            verify_undo,
        } => cmd_unshare_form(&input, page, form, &output, mode, verify_undo),
        Command::SubpathMove {
            input,
            page,
            object,
            leaf,
            subpath,
            dx,
            dy,
            output,
            mode,
            verify_undo,
        } => cmd_subpath_move(&SubpathMoveArgs {
            input: &input,
            page,
            object,
            leaf,
            subpath,
            dx,
            dy,
            output: &output,
            mode,
            verify_undo,
        }),
        Command::ExportDxf {
            input,
            page,
            pages,
            output,
            output_dir,
            units,
            scale,
            no_fit_arcs,
            no_text,
        } => cmd_export_dxf(ExportDxfArgs {
            input: &input,
            page,
            pages: pages.as_deref(),
            output: output.as_deref(),
            output_dir: output_dir.as_deref(),
            units,
            scale,
            fit_arcs: !no_fit_arcs,
            text: !no_text,
        }),
        Command::TextRunDelete {
            input,
            page,
            object,
            leaf,
            run,
            output,
            mode,
            verify_undo,
        } => cmd_text_run_delete(&TextRunDeleteArgs {
            input: &input,
            page,
            object,
            leaf,
            run,
            output: &output,
            mode,
            verify_undo,
        }),
        Command::TextRunMove {
            input,
            page,
            object,
            leaf,
            run,
            dx,
            dy,
            output,
            mode,
            verify_undo,
        } => cmd_text_run_move(&TextRunMoveArgs {
            input: &input,
            page,
            object,
            leaf,
            run: &run,
            dx,
            dy,
            output: &output,
            mode,
            verify_undo,
        }),
        Command::TextRunWidth {
            input,
            object,
            page,
            run,
            width,
            output,
            mode,
            verify_undo,
        } => cmd_text_run_width(&TextRunWidthArgs {
            input: &input,
            page,
            object,
            run,
            width,
            output: &output,
            mode,
            verify_undo,
        }),
        Command::TextRunMerge {
            input,
            object,
            page,
            run,
            separator,
            fit,
            output,
            mode,
            verify_undo,
        } => cmd_text_run_merge(&TextRunMergeArgs {
            input: &input,
            page,
            object,
            runs: &run,
            separator: &separator,
            fit,
            output: &output,
            mode,
            verify_undo,
        }),
        Command::TextObjectSplit {
            input,
            page,
            object,
            granularity,
            before,
            dry_run,
            output,
            mode,
            verify_undo,
        } => cmd_text_object_split(&TextObjectSplitArgs {
            input: &input,
            page,
            object,
            granularity,
            before: &before,
            dry_run,
            output: output.as_deref(),
            mode,
            verify_undo,
        }),
        Command::SubpathDelete {
            input,
            page,
            object,
            subpath,
            output,
            mode,
            verify_undo,
        } => cmd_subpath_delete(&SubpathDeleteArgs {
            input: &input,
            page,
            object,
            subpath,
            output: &output,
            mode,
            verify_undo,
        }),
        Command::NodeDelete {
            input,
            page,
            object,
            node,
            output,
            mode,
            verify_undo,
        } => cmd_node_delete(&NodeDeleteArgs {
            input: &input,
            page,
            object,
            node,
            output: &output,
            mode,
            verify_undo,
        }),
        Command::NodeMove {
            input,
            page,
            object,
            leaf,
            node,
            x,
            y,
            output,
            mode,
            verify_undo,
        } => cmd_node_move(&NodeMoveArgs {
            input: &input,
            page,
            object,
            leaf,
            node,
            x,
            y,
            output: &output,
            mode,
            verify_undo,
        }),
        Command::NodesMove {
            input,
            page,
            object,
            moves,
            output,
            mode,
            verify_undo,
        } => cmd_nodes_move(&input, page, object, &moves, &output, mode, verify_undo),
        Command::HandleMove {
            input,
            page,
            object,
            node,
            side,
            x,
            y,
            output,
            mode,
            verify_undo,
        } => cmd_handle_move(&HandleMoveArgs {
            input: &input,
            page,
            object,
            node,
            side,
            x,
            y,
            output: &output,
            mode,
            verify_undo,
        }),
        Command::RotatePage {
            input,
            page,
            degrees,
            relative,
            output,
            mode,
            verify_undo,
        } => cmd_rotate_page(&input, page, degrees, relative, &output, mode, verify_undo),
        Command::SetPageSize {
            input,
            pages,
            size,
            landscape,
            width,
            height,
            output,
            mode,
            verify_undo,
        } => cmd_set_page_size(
            &input,
            &pages,
            &SheetArg {
                size: size.as_deref(),
                landscape,
                width,
                height,
            },
            &output,
            mode,
            verify_undo,
        ),
        Command::SetInfo {
            input,
            title,
            author,
            subject,
            keywords,
            clear,
            output,
            mode,
            producer,
            verify_undo,
        } => cmd_set_info(
            &input,
            &[
                (InfoFieldArg::Title, title),
                (InfoFieldArg::Author, author),
                (InfoFieldArg::Subject, subject),
                (InfoFieldArg::Keywords, keywords),
            ],
            &clear,
            &output,
            mode,
            producer,
            verify_undo,
        ),
        Command::Annotate {
            input,
            kind,
            page,
            rect,
            line,
            points,
            strokes,
            quads,
            color,
            fill,
            width,
            cloud,
            opacity,
            dash,
            note,
            note_author,
            note_date,
            text,
            font,
            size,
            quad,
            multiline,
            icon,
            stamp_name,
            stamp_font_size,
            stamp_fit,
            output,
            mode,
            verify_undo,
        } => cmd_annotate(&AnnotateArgs {
            input: &input,
            kind,
            page,
            rect: rect.as_deref(),
            line: line.as_deref(),
            points: points.as_deref(),
            strokes: strokes.as_deref(),
            quads: quads.as_deref(),
            color: color.as_deref(),
            fill: fill.as_deref(),
            width,
            cloud,
            opacity,
            dash: dash.as_deref(),
            note,
            note_author,
            note_date,
            text: text.as_deref(),
            font: &font,
            size,
            quad,
            multiline,
            icon,
            stamp_name,
            stamp_font_size,
            stamp_fit,
            output: &output,
            mode,
            verify_undo,
        }),
        Command::RedactMark {
            input,
            rect,
            search,
            pattern,
            ignore_case,
            page,
            fill,
            overlay_text,
            output,
        } => cmd_redact_mark(&RedactMarkArgs {
            input: &input,
            rect: rect.as_deref(),
            search: search.as_deref(),
            pattern: pattern.as_deref(),
            ignore_case,
            page,
            fill: fill.as_deref(),
            overlay_text: overlay_text.as_deref(),
            output: &output,
        }),
        Command::UnembedFont {
            input,
            font,
            all_removable,
            apply,
            output,
            mode,
            verify_undo,
            keep_subset_tag,
            acknowledge_pdfa,
        } => cmd_unembed_font(&UnembedArgs {
            input: &input,
            fonts: &font,
            all_removable,
            apply,
            output: output.as_deref(),
            mode,
            verify_undo,
            keep_subset_tag,
            acknowledge_pdfa,
        }),
        Command::EmbedFont {
            input,
            font,
            all_missing,
            font_dirs,
            use_bundled_fonts,
            apply,
            output,
            mode,
            verify_undo,
        } => cmd_embed_font(&EmbedArgs {
            input: &input,
            fonts: &font,
            all_missing,
            font_dirs: &font_dirs,
            use_bundled_fonts,
            apply,
            output: output.as_deref(),
            mode,
            verify_undo,
        }),
        Command::RedactApply {
            input,
            output,
            residual_scope,
            acknowledge_residuals,
        } => cmd_redact_apply(&input, &output, residual_scope, acknowledge_residuals),
        Command::Encrypt {
            input,
            output,
            user_password,
            user_password_file,
            owner_password,
            owner_password_file,
            allow,
            deny,
            no_encrypt_metadata,
        } => cmd_encrypt(&EncryptCliArgs {
            input: &input,
            output: &output,
            user_password,
            user_password_file,
            owner_password,
            owner_password_file,
            allow: &allow,
            deny: &deny,
            encrypt_metadata: !no_encrypt_metadata,
            rekey: false,
        }),
        Command::SetPermissions {
            input,
            output,
            user_password,
            user_password_file,
            owner_password,
            owner_password_file,
            allow,
            deny,
            no_encrypt_metadata,
        } => cmd_encrypt(&EncryptCliArgs {
            input: &input,
            output: &output,
            user_password,
            user_password_file,
            owner_password,
            owner_password_file,
            allow: &allow,
            deny: &deny,
            encrypt_metadata: !no_encrypt_metadata,
            rekey: true,
        }),
        Command::RemoveEncryption { input, output } => cmd_remove_encryption(&input, &output),
        Command::TrustStoreList {
            file,
            source,
            identities,
        } => cmd_trust_store_list(file.as_deref(), &source, identities),
        Command::ListRedactions { input } => cmd_list_redactions(&input),
    };
    ExitCode::from(code)
}
