//! # Variable-text appearance generation (ISO 32000-1 §12.7.3.3)
//!
//! The **hardest single piece of appearance generation**, isolated into
//! Pass 6.2 so Pass 7 (Forms) inherits a proven generator. Where
//! [`crate::annot_author`] turns *geometry* into an `/AP` `/N` form
//! XObject, this module turns *text* into one: given a text value, a `/DA`
//! default-appearance string, a `/Q` quadding code, and a resource set, it
//! produces the `/Tx BMC … EMC` marked-content body §12.7.3.3 specifies
//! (Figure — the verbatim EXAMPLE in the clause), authored in Base-14
//! metrics with **no embedded font program** (§9.6.2.1 — see
//! [`standard14_font_dict`]).
//!
//! It is a **single pipeline shared by FreeText and text widgets**
//! (`iso32000__s__12.7.3.3.md`): a FreeText `/AP` and a variable-text
//! widget `/AP` are generated by the same `/DA` + `/Q` + value code; only
//! the resource-resolution *root* differs (FreeText resolves the `/DA`
//! font name against the annotation's own `/AP` `/Resources`; a widget
//! against the `/AcroForm` `/DR`). This module parameterizes the root as a
//! `&[FontResource]` and is unaware of which caller supplied it.
//!
//! ## Spec facts this module enacts (from `iso32000__s__12.7.3.3.md`)
//!
//! - **`/DA` is parsed with the REAL content lexer (risk X9).** A `/DA`
//!   string is a *content-stream fragment stored in a PDF string* — it can
//!   carry names, reals, arrays and operators, so a split-on-space scanner
//!   misparses it. [`parse_default_appearance`] runs
//!   [`ContentStream::parse`](crate::content::ContentStream::parse) over
//!   the `/DA` bytes and reads the operators back out — never an ad-hoc
//!   scan.
//! - **The only `shall`-minimum is `Tf`** (font + size). Colour is *not*
//!   required (VT2): absent, text renders in the graphics-state default
//!   `0 g` black. A `/DA` with no `Tf` is [`VarTextError::MissingTf`].
//! - **A font the resource set does not carry is a NAMED refusal**
//!   ([`VarTextError::FontUnresolved`]), never a silent substitution — a
//!   substituted font changes glyph advances, so what the operator sees
//!   would differ from what every other reader sees.
//! - **At most one `Tm`** (VT4): more than one is
//!   [`VarTextError::TooManyTm`]. This generator authors **zero** `Tm` in
//!   the `/DA` and emits exactly one in the body to set the first line's
//!   origin, positioning later lines with `Td` (which is not a `Tm`).
//! - **`size = 0` ⇒ auto-size** (VT1). The spec mandates *that* auto-size
//!   happens ("a function of the height of the annotation rectangle") but
//!   gives **no formula** — so [`auto_size`] is a *reviewable pdfcer
//!   heuristic* (fuzzy-never-sneaky, rule 4), and every appearance that
//!   applied it reports the size it chose ([`VarTextAppearance::applied_autosize`]).
//! - **`BBox = [0 0 Rect_w Rect_h]`, identity `Matrix`.** The body is laid
//!   out in `[0,0]–[W,H]` local coordinates and placed 1:1 into the
//!   annotation `/Rect` by §12.5.5 with no scale (the §8.10 W-B
//!   anti-distortion pattern). The clip is that same box.
//! - **`/RC` rich text is an EXPLICIT non-goal** (VT3): this module
//!   authors *plain* text only. Recognition/round-trip of `/RC`/`/RV`/
//!   `/DS` lives at the annotation layer, not here.
//!
//! ## Font resourcing — Base-14, no embedded program (§9.6.2.1)
//!
//! §9.6.2.1 Table 111 marks `Widths`/`FontDescriptor` "Required **except
//! for the standard 14 fonts**", and for those they "shall either all be
//! present or all be absent". `FontDescriptor` is the sole carrier of the
//! embedded program (§9.8), so a standard-14 dict may omit it and the
//! reader supplies the glyphs (§9.6.2.2). [`standard14_font_dict`]
//! therefore authors a minimal dict with **zero font bytes**, and pdfcer's
//! own renderer paints it through its bundled Foxit substitute face
//! (`pdfcer-render::font::select::by_name`). The `/Q` measurement uses the
//! compiled APAFML advance widths already in [`crate::fontdata`] — all
//! GUI-free, on the correct side of the §3 invariant (decision 008 F5).
//!
//! **Modality choice (recorded, not a blocker):** PDF 1.5+ *deprecates*
//! the bare standard-14 form — writers *should* embed a full descriptor —
//! but readers *shall* still honour the bare form (§9.6.2.1). pdfcer
//! deliberately authors the bare form (universally reader-supported, no
//! font-program bytes to reproduce on round-trip), adding only
//! `/Encoding /WinAnsiEncoding` so byte→glyph is deterministic for Latin
//! text (the same encoding [`measure`] assumes). This is a `should`
//! deviation on the write side and a fully conformant document on the
//! read side.
//!
//! ## Named limits (Base-14 Latin only — R17, no `harfrust`)
//!
//! - **No complex-script / RTL shaping.** Text is laid out left-to-right,
//!   one glyph per `WinAnsi` byte (R17 keeps `harfrust` unshipped — this
//!   is the first text-*authoring* path decision 004 reserved for it, and
//!   it is built without it). Non-Latin scripts are out of scope.
//! - **A character with no `WinAnsi` code is substituted with `?` and
//!   COUNTED** ([`VarTextAppearance::unencodable_chars`]) — disclosed, not
//!   silently dropped (fuzzy-never-sneaky).

use crate::content::{ContentStream, ContentTokenKind};
use crate::fontdata::{self, BaseEncoding, Std14};
use crate::object::{Dict, Name, Object};
use crate::page_tree::Rect;
use crate::writer::content::{ContentBuilder, Paint};

/// A text fill colour parsed from — or authored into — a `/DA` string
/// (§12.7.3.3 Table 222). The array length selects the device colour
/// space exactly as §8.6 does (1 → Gray, 3 → RGB, 4 → CMYK).
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum TextColor {
    /// `g` — DeviceGray (0.0 = black).
    Gray(f64),
    /// `rg` — DeviceRGB.
    Rgb(f64, f64, f64),
    /// `k` — DeviceCMYK.
    Cmyk(f64, f64, f64, f64),
}

impl TextColor {
    /// Emit this colour as the **non-stroking** (text-fill) colour — the
    /// operator a `/DA` string uses to colour its variable text.
    fn apply_fill(self, b: &mut ContentBuilder) {
        match self {
            Self::Gray(g) => b.set_fill_gray(g),
            Self::Rgb(r, g, bl) => b.set_fill_rgb(r, g, bl),
            Self::Cmyk(c, m, y, k) => b.set_fill_cmyk(c, m, y, k),
        }
    }
}

/// Quadding `/Q` (§12.7.3.3 Table 222): the justification of the variable
/// text. Values are reproduced verbatim: `0` left, `1` centre, `2` right;
/// **default `0`** (left).
/// `Default` is `Left`, which is not a convenience choice — Table 222 fixes
/// `/Q`'s default value at `0`, so the derived default and the spec's
/// default are the same fact.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Quadding {
    /// `0` — left-justified (the default).
    #[default]
    Left,
    /// `1` — centred.
    Center,
    /// `2` — right-justified.
    Right,
}

impl Quadding {
    /// The `/Q` integer code (0/1/2).
    #[must_use]
    pub const fn code(self) -> i64 {
        match self {
            Self::Left => 0,
            Self::Center => 1,
            Self::Right => 2,
        }
    }

    /// From a `/Q` code; any value other than 1 or 2 is the default
    /// (left) per Table 222.
    #[must_use]
    pub const fn from_code(code: i64) -> Self {
        match code {
            1 => Self::Center,
            2 => Self::Right,
            _ => Self::Left,
        }
    }
}

/// A font resource the `/DA` font name may resolve against: the resource
/// `name` (as it appears after the `/` in the `/DA` `Tf` operator) and the
/// standard-14 face it denotes. For FreeText this is the single font pdfcer
/// authors into the appearance `/Resources`; for a widget it would be the
/// `/AcroForm` `/DR` `/Font` entries (Pass 7).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FontResource {
    /// The resource name (no leading `/`), e.g. `b"Helv"`.
    pub name: Vec<u8>,
    /// The standard-14 face it maps to.
    pub font: Std14,
}

/// A parsed `/DA` default-appearance string (§12.7.3.3 Table 222).
#[derive(Debug, Clone, PartialEq)]
pub struct DefaultAppearance {
    /// The `Tf` font resource name (no leading `/`).
    pub font_name: Vec<u8>,
    /// The `Tf` size. **`0.0` means auto-size** (VT1).
    pub font_size: f64,
    /// The text colour, or `None` when the `/DA` sets none — in which case
    /// the text renders in the graphics-state default `0 g` black (VT2).
    ///
    /// ★ `None` is AMBIGUOUS ON ITS OWN and must be read with
    /// [`Self::color_unmodelled`]. See that field.
    pub color: Option<TextColor>,
    /// The `/DA` set a colour in a space this parser does not model —
    /// `/Separation`, `/DeviceN`, `/ICCBased`, `/Indexed`, `/Lab` — via
    /// `cs`/`CS` and `sc`/`scn` (`Pass 221.0`).
    ///
    /// # Why a flag beside `color` rather than a `TextColor::Other`
    ///
    /// Because [`TextColor`] is used for WRITING as well as reading, and an
    /// authoring path is entitled to a limited palette. A variant that
    /// `apply_fill` could not emit would push the problem into the emitter,
    /// where the only options are inventing a colour or emitting none.
    ///
    /// # ★★ The defect this closes
    ///
    /// This parser handled `g G rg RG k K` and swallowed everything else in a
    /// `_ => {}` arm, so a `/DA` of `/Sep1 cs 1 scn /Helv 12 Tf` yielded
    /// `color: None`. And `None` already meant something specific — *"the
    /// `/DA` sets none, so the text renders black"*.
    ///
    /// So an unmodellable colour was ALIASED ONTO "the file specified
    /// nothing", and the generated appearance was painted BLACK. That is a
    /// silent inference presented as a fact about the file, and unlike the
    /// sibling defects in the vector model it writes the wrong value into a
    /// generated `/AP` — into the document.
    ///
    /// With this flag the two are distinguishable, so a caller can DISCLOSE
    /// the narrowing (rule 4) exactly as `text_edit::format` already does for
    /// the same situation one module over.
    ///
    /// # Measured rarity, stated so effort is not misjudged
    ///
    /// **Zero** of 268 `/DA` strings across a 500-file sample of the corpus
    /// use a non-device colour space. This is a correctness fix for a case
    /// that is real, cheap to close, and rare — not a common one.
    pub color_unmodelled: bool,
}

/// Why a variable-text appearance could not be generated. Every variant
/// names a condition the operator or caller can act on (C-GOOD-ERR).
#[derive(Debug, Clone, PartialEq, thiserror::Error)]
#[non_exhaustive]
pub enum VarTextError {
    /// The `/DA` bytes are not a well-formed content-stream fragment
    /// (§7.8.2) — the real lexer rejected them (X9).
    #[error("the /DA default-appearance string is not a well-formed content-stream fragment")]
    MalformedDa,
    /// The `/DA` string carries no `Tf` operator. §12.7.3.3 requires one
    /// "at a minimum … along with its two operands, font and size".
    #[error(
        "the /DA string has no Tf (font and size) operator, which ISO 32000-1 §12.7.3.3 requires"
    )]
    MissingTf,
    /// The `/DA` string has more than one `Tm`. §12.7.3.3: "shall contain
    /// at most one Tm operator" (VT4).
    #[error(
        "the /DA string has more than one Tm operator (ISO 32000-1 §12.7.3.3 allows at most one)"
    )]
    TooManyTm,
    /// The `Tf` font name is not present in the resource set. A named
    /// refusal (never a silent substitution): a substituted font changes
    /// glyph advances, so the operator would see different metrics than
    /// every other reader.
    #[error(
        "the /DA font resource /{0} is not in the appearance's font resource set, so its \
         metrics cannot be resolved without silently substituting a different font"
    )]
    FontUnresolved(String),
    /// The `Tf` font resolved to `Symbol`/`ZapfDingbats`. Those carry a
    /// `FontSpecific` built-in encoding, not `WinAnsiEncoding`, so this
    /// `WinAnsi`-based Latin generator cannot lay out text in them
    /// (Base-14 Latin only — a named limit, not a silent mis-encoding).
    #[error(
        "the /DA font /{0} is a symbolic font; pdfcer's variable-text generator is Base-14 Latin only"
    )]
    SymbolicFont(String),
}

/// The result of generating one variable-text appearance body.
#[derive(Debug, Clone, PartialEq)]
pub struct VarTextAppearance {
    /// The `/Tx BMC … EMC` content-stream bytes (raw, unfiltered).
    pub content: Vec<u8>,
    /// The `/Resources` dictionary the body needs: a `/Font` sub-dict
    /// mapping the `/DA` font name to a [`standard14_font_dict`].
    pub resources: Dict,
    /// `Some(size)` when the `/DA` requested auto-size (`size = 0`) and
    /// [`auto_size`] chose `size` — surfaced so the caller can DISCLOSE it
    /// (fuzzy-never-sneaky, VT1). `None` when the `/DA` gave an explicit
    /// size.
    pub applied_autosize: Option<f64>,
    /// WHICH CONSTRAINT decided [`Self::applied_autosize`], when one did.
    ///
    /// Requested by name by a consuming shell: *"if it becomes a fit rather
    /// than a guess, the wording should change from 'a reviewable heuristic'
    /// to naming the constraint that bound, because that is the thing an
    /// operator would query."* An operator who thinks the text is too small
    /// wants to know whether to widen the box or heighten it, and those are
    /// different answers.
    ///
    /// `None` when the `/DA` stated a size, and also for a MULTILINE field,
    /// which still takes the older height-only route — reporting a bound there
    /// would name a constraint that was never evaluated.
    pub applied_autosize_bound: Option<AutoFitBound>,
    /// The `/DA` specified a colour in a space pdfcer does not model, so this
    /// appearance was generated in the §8.6.8 default BLACK instead
    /// (`Pass 221.0`).
    ///
    /// ★ The rule-4 disclosure for a colour NARROWING, and the reason the
    /// parser now distinguishes "no colour" from "a colour I cannot model":
    /// pdfcer is substituting a colour the file did not ask for, into a
    /// generated appearance that is written to the document. Silent would be
    /// the sneaky half.
    pub da_colour_unmodelled: bool,
    /// How many characters had no `WinAnsi` code and were substituted with
    /// `?` (a named Base-14-Latin limit — disclosed, never silent).
    pub unencodable_chars: usize,
    /// The face the text was laid out in.
    pub used_font: Std14,
    /// The final point size (after any auto-size).
    pub used_size: f64,
}

/// The padding inset (points) between the appearance `/BBox` and the text,
/// on every side. A small constant so a box hugs its text without the
/// glyphs touching the border. pdfcer's own choice (the spec fixes none).
const TEXT_PAD: f64 = 2.0;

/// The line advance as a multiple of the font size (leading). 1.15 gives a
/// small amount of inter-line space; pdfcer's own choice.
const LINE_FACTOR: f64 = 1.15;

/// Auto-size bounds and shape (VT1) — a *reviewable heuristic*, not a spec
/// formula. See [`auto_size`].
const AUTOSIZE_MIN: f64 = 4.0;
const AUTOSIZE_MAX: f64 = 12.0;

/// Compute the auto-size point size for a `/DA` `size = 0` from the
/// annotation rectangle height (VT1).
///
/// **This is pdfcer's heuristic, not a spec formula.** §12.7.3.3 mandates
/// only that auto-size be "a function of the height of the annotation
/// rectangle" and gives no ratio, leading rule, or worked example. pdfcer
/// chooses: the usable height (`rect_h` less padding on top and bottom)
/// divided by the line factor, clamped to `[4, 12]` points. The clamp cap
/// keeps a very tall box from producing an absurd size; the floor keeps a
/// very short box legible. Every appearance that applies this reports the
/// chosen size (fuzzy-never-sneaky) so it is a disclosed default, never a
/// silent computed value presented as spec-mandated.
#[must_use]
pub fn auto_size(rect_h: f64) -> f64 {
    ((rect_h - 2.0 * TEXT_PAD) / LINE_FACTOR).clamp(AUTOSIZE_MIN, AUTOSIZE_MAX)
}

/// Which constraint decided an auto-size, for disclosure.
///
/// pdfcer-gui asked for this by name: *"the wording should probably change from
/// 'a reviewable heuristic' to naming the constraint that bound, because that
/// is the thing an operator would query."*
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum AutoFitBound {
    /// The box height set it — the ordinary case.
    Height,
    /// The text was too wide at the height-derived size and was shrunk.
    Width,
    /// Both would have gone below the legibility floor.
    Floor,
}

/// A chosen auto-size and the reason it was chosen.
#[derive(Debug, Clone, Copy, PartialEq)]
#[non_exhaustive]
pub struct AutoFit {
    /// Points.
    pub size: f64,
    /// What bound it.
    pub bound: AutoFitBound,
}

/// Padding either side of the text inside the field rectangle, in points.
///
/// ONE point, not [`TEXT_PAD`]'s two. Measured off an Acrobat-filled field in
/// a real operator document: a 26.40 pt box yields a 21.0975 pt candidate, and
/// `21.0975 x 1.156 = 24.389`, which is `26.40 - 2.011`. A second field gives
/// `13.08 - 2.052`. Both land on one point per side.
const AUTOFIT_PAD: f64 = 1.0;

/// Fit an auto-sized (`0 Tf`) field's text to its rectangle.
///
/// # What was wrong before
///
/// [`auto_size`] divided by a **leading** constant and then clamped to 12 pt,
/// so every auto-sized field in a document came out at 12 pt regardless of its
/// box. An operator filling a shipping form saw pdfcer's rows at two-thirds the
/// size of the row Acrobat had filled on the same sheet, and header fields that
/// would have overflowed a 13 pt box.
///
/// Two distinct errors: the clamp (which made every answer identical) and the
/// divisor (leading is not the quantity that decides whether glyphs fit a box).
///
/// # The formula, and what is measured versus assumed
///
/// **MEASURED**, off Acrobat-authored appearances in a real operator file:
///
/// ```text
/// candidate = (rect_height - 2 x 1pt) / font_bbox_height_em
/// ```
///
/// Helvetica's `/FontBBox` is `[-166 -225 1000 931]`, so its height is
/// `1156/1000 = 1.156 em`. Two Acrobat fields whose boxes differ by a factor of
/// two both land on that ratio to three figures — 1.1565 and 1.1615 — which is
/// what makes it a measurement rather than a fitted constant.
///
/// **ASSUMED**, and stated as such: the width step below. It is required for
/// correctness — a long string must shrink rather than overflow — but it is
/// *not* what Acrobat did in the file that motivated this. See the note.
///
/// # ★★ WHAT ACROBAT DOES THAT THIS DOES NOT, MEASURED AND UNEXPLAINED
///
/// Acrobat writes **two** `Tf` operators per appearance, and the second is
/// always about **1.165x smaller** than the first:
///
/// | candidate | final | ratio |
/// |---|---|---|
/// | 21.0975 | 18.082 | 1.1668 |
/// |  9.5396 |  8.207 | 1.1624 |
/// | 10.0867 |  8.654 | 1.1656 |
///
/// The obvious reading — and the one the request proposed — is that the second
/// step is a width fit. **It is not, in this document.** Measured: *"TC-10
/// Wheel Chocks"* at the 21.0975 candidate needs 200.5 pt in a 253.4 pt usable
/// width, and `TR4177` needs 34 pt in 177 pt. Neither is close to binding, yet
/// both shrank. A width fit would also vary with string length, and this ratio
/// varies by 0.4% across three very different strings.
///
/// ⇒ So pdfcer lands about 16% larger than Acrobat, from a formula whose first
/// step is measured and whose second step is honest. That is a large
/// improvement on a flat 12 pt and it is **not a match**, and pretending
/// otherwise by dividing by an unexplained 1.165 would bake a number nobody can
/// defend into the appearance of every form pdfcer fills.
#[must_use]
pub fn auto_fit(font: Std14, rect_w: f64, rect_h: f64, text: &[u8]) -> AutoFit {
    let bbox = fontdata::std14_descriptor(font).font_bbox;
    // Height extent of the font's bounding box, in ems. Guarded because a
    // malformed descriptor would otherwise divide by zero or invert the size.
    let bbox_em = f64::from(i32::from(bbox[3]) - i32::from(bbox[1])) / 1000.0;
    let candidate = if bbox_em > 0.0 {
        (rect_h - 2.0 * AUTOFIT_PAD) / bbox_em
    } else {
        AUTOSIZE_MIN
    };

    let usable_w = rect_w - 2.0 * AUTOFIT_PAD;
    let at_candidate = measure(font, candidate, text);
    let (size, bound) = if at_candidate > usable_w && at_candidate > 0.0 && usable_w > 0.0 {
        (candidate * usable_w / at_candidate, AutoFitBound::Width)
    } else {
        (candidate, AutoFitBound::Height)
    };

    if size < AUTOSIZE_MIN {
        // The floor is a legibility choice, not a spec rule, and it is the one
        // case where the returned size does NOT fit the constraint that
        // produced it -- so it is named separately rather than folded into
        // Height, which would report a fit that did not happen.
        return AutoFit {
            size: AUTOSIZE_MIN,
            bound: AutoFitBound::Floor,
        };
    }
    AutoFit { size, bound }
}

/// The height (points) of a band that exactly contains one line of text
/// in `font` at `size`: ascent + descent + padding top and bottom. A
/// caller that wants a single centred line (e.g. a Stamp label) passes a
/// `bbox` of this height to [`build_variable_text`] and translates it to
/// the desired vertical position, so the glyphs — including descenders —
/// sit fully inside the band.
#[must_use]
pub fn text_band_height(font: Std14, size: f64) -> f64 {
    let d = fontdata::std14_descriptor(font);
    let ascent = f64::from(d.ascender) / 1000.0 * size;
    let descent = f64::from(d.descender).abs() / 1000.0 * size;
    ascent + descent + 2.0 * TEXT_PAD
}

/// How many lines of `size`-point text fit in a box `box_h` points tall,
/// using the SAME padding and leading [`build_variable_text`] lays lines out
/// with.
///
/// # Why this exists rather than being computed at the call site
///
/// Its one caller is the `/TI` (top index) derivation for a scrollable list
/// box (§12.7.4.4 Table 231): to know whether the selected option is below
/// the fold, you must know where the fold is, and the fold is a function of
/// [`TEXT_PAD`] and [`LINE_FACTOR`] — two private constants that belong to
/// the layout engine. A caller that re-derived the count from its own idea of
/// leading would disagree with the generator the moment either constant
/// changed, and the disagreement would show up as a list box scrolled to the
/// wrong place: quiet, plausible, and attributable to almost anything.
///
/// # Always at least one
///
/// A box too short for a single line still shows part of one, and a visible
/// count of zero would make the caller's arithmetic divide the option list
/// into windows of nothing. One is the honest floor: whatever is on screen,
/// it is some of the first visible option.
#[must_use]
pub fn visible_line_count(box_h: f64, size: f64) -> usize {
    if size <= 0.0 || !size.is_finite() || !box_h.is_finite() {
        return 1;
    }
    let usable = box_h - 2.0 * TEXT_PAD;
    let lines = (usable / (size * LINE_FACTOR)).floor();
    if lines >= 1.0 {
        // Bounded above so the `as` conversion cannot saturate on a
        // pathological `/Rect`; a list box with more than this many visible
        // rows is not a case any real form reaches, and the clamp keeps the
        // conversion total rather than platform-dependent.
        lines.min(4096.0) as usize
    } else {
        1
    }
}

/// Build a `/DA` default-appearance string from friendly parameters:
/// `/name size Tf` + the colour's non-stroking operator. Used by the
/// ergonomic authoring path (a fresh FreeText/Stamp) so the generated
/// `/DA` and the authored `/Resources` font name are guaranteed
/// consistent. The bytes are a valid content-stream fragment that
/// [`parse_default_appearance`] round-trips.
///
/// # Examples
///
/// ```
/// use pdfcer_core::vartext::{default_appearance_string, TextColor};
///
/// let da = default_appearance_string(b"Helv", 12.0, TextColor::Gray(0.0));
/// assert_eq!(da, b"/Helv 12 Tf\n0 g\n");
/// ```
#[must_use]
pub fn default_appearance_string(name: &[u8], size: f64, color: TextColor) -> Vec<u8> {
    let mut b = ContentBuilder::new();
    b.set_font(name, size);
    color.apply_fill(&mut b);
    b.into_bytes()
}

/// The minimal, program-free standard-14 font dictionary (§9.6.2.1) pdfcer
/// authors into an appearance `/Resources` `/Font` (or an `/AcroForm`
/// `/DR` `/Font`).
///
/// Four keys, **no `/Widths` and no `/FontDescriptor`** — the bare form
/// §9.6.2.1 permits for a standard-14 font, reader-renderable with zero
/// font bytes. `/Encoding /WinAnsiEncoding` is added so byte→glyph is
/// deterministic for Latin text (matching [`measure`]); the symbolic
/// fonts, which have no `WinAnsi` encoding, are never authored here (see
/// [`VarTextError::SymbolicFont`]).
///
/// # Examples
///
/// ```
/// use pdfcer_core::vartext::standard14_font_dict;
/// use pdfcer_core::fontdata::Std14;
///
/// let d = standard14_font_dict(Std14::Helvetica);
/// assert_eq!(d.get(b"BaseFont").unwrap().as_name().unwrap().as_bytes(), b"Helvetica");
/// assert!(d.get(b"FontDescriptor").is_none()); // no embedded program
/// ```
#[must_use]
pub fn standard14_font_dict(font: Std14) -> Dict {
    let mut d = Dict::new();
    d.insert(Name::from(b"Type"), Object::Name(Name::from(b"Font")));
    d.insert(Name::from(b"Subtype"), Object::Name(Name::from(b"Type1")));
    d.insert(
        Name::from(b"BaseFont"),
        Object::Name(Name(base_font_name(font).to_vec())),
    );
    d.insert(
        Name::from(b"Encoding"),
        Object::Name(Name::from(b"WinAnsiEncoding")),
    );
    d
}

/// The exact §9.6.2.2 `BaseFont` spelling for a standard-14 face.
const fn base_font_name(font: Std14) -> &'static [u8] {
    match font {
        Std14::Helvetica => b"Helvetica",
        Std14::HelveticaBold => b"Helvetica-Bold",
        Std14::HelveticaOblique => b"Helvetica-Oblique",
        Std14::HelveticaBoldOblique => b"Helvetica-BoldOblique",
        Std14::TimesRoman => b"Times-Roman",
        Std14::TimesBold => b"Times-Bold",
        Std14::TimesItalic => b"Times-Italic",
        Std14::TimesBoldItalic => b"Times-BoldItalic",
        Std14::Courier => b"Courier",
        Std14::CourierBold => b"Courier-Bold",
        Std14::CourierOblique => b"Courier-Oblique",
        Std14::CourierBoldOblique => b"Courier-BoldOblique",
        Std14::Symbol => b"Symbol",
        Std14::ZapfDingbats => b"ZapfDingbats",
    }
}

/// Parse a `/DA` default-appearance string with the REAL content lexer
/// (X9), extracting the `Tf` font/size, the text colour (if any), and
/// enforcing the "at most one `Tm`" rule.
///
/// The `/DA` bytes are a §7.8.2 content-stream fragment, so they are
/// tokenized by [`ContentStream::parse`] and read as *operations* — never
/// split on whitespace. Only operators that matter to layout are
/// consulted (`Tf`, the device-colour operators, `Tm`); any other
/// operator a producer put in the string is ignored, as §12.7.3.3 permits
/// ("any graphics state or text state operators needed").
///
/// The **last** `Tf` and the **last** colour operator win (a later
/// operator overrides an earlier one in the graphics state).
///
/// # Errors
///
/// - [`VarTextError::MalformedDa`] — the bytes do not tokenize.
/// - [`VarTextError::MissingTf`] — no `Tf` operator (the one `shall`).
/// - [`VarTextError::TooManyTm`] — more than one `Tm` (VT4).
///
/// # Examples
///
/// ```
/// use pdfcer_core::vartext::{parse_default_appearance, TextColor};
///
/// let da = parse_default_appearance(b"0 0 1 rg /Helv 14 Tf").unwrap();
/// assert_eq!(da.font_name, b"Helv");
/// assert_eq!(da.font_size, 14.0);
/// assert_eq!(da.color, Some(TextColor::Rgb(0.0, 0.0, 1.0)));
///
/// // A /DA with no Tf is refused, not guessed.
/// assert!(parse_default_appearance(b"0 g").is_err());
/// ```
pub fn parse_default_appearance(da: &[u8]) -> Result<DefaultAppearance, VarTextError> {
    let cs = ContentStream::parse(da.to_vec()).map_err(|_| VarTextError::MalformedDa)?;
    let mut tf: Option<(Vec<u8>, f64)> = None;
    let mut color: Option<TextColor> = None;
    let mut color_unmodelled = false;
    let mut tm_count = 0usize;

    for op in cs.operations() {
        let Some(name) = op.operator_name(&cs.buf) else {
            continue; // an inline image cannot appear in a /DA; ignore.
        };
        match name {
            b"Tf" => {
                // Operands are `/Name size`; take the last Name and the
                // last number among the operand run (defensive against a
                // malformed extra operand).
                let mut font_name: Option<Vec<u8>> = None;
                let mut size: Option<f64> = None;
                for tok in op.operands {
                    if let ContentTokenKind::Operand(obj) = &tok.kind {
                        match obj {
                            Object::Name(n) => font_name = Some(n.0.clone()),
                            Object::Integer(v) => size = Some(*v as f64),
                            Object::Real(v) => size = Some(*v),
                            _ => {}
                        }
                    }
                }
                if let (Some(n), Some(s)) = (font_name, size) {
                    tf = Some((n, s));
                }
            }
            // Non-stroking (text-fill) colour operators — the usual /DA
            // form — plus the stroking operators some producers use to
            // colour /DA text (the value, not the space, is what layout
            // cares about).
            b"g" | b"G" => color = number_operands(&op).first().map(|&v| TextColor::Gray(v)),
            b"rg" | b"RG" => {
                if let [r, g, b] = number_operands(&op)[..] {
                    color = Some(TextColor::Rgb(r, g, b));
                }
            }
            b"k" | b"K" => {
                if let [c, m, y, k] = number_operands(&op)[..] {
                    color = Some(TextColor::Cmyk(c, m, y, k));
                }
            }
            // §8.6.8's colour-space operators. Previously swallowed by the
            // `_ => {}` arm below, which aliased "a colour pdfcer cannot model"
            // onto "the file set no colour" -- and the latter has a defined
            // meaning here (render black), so the generated appearance came
            // out black with no disclosure.
            //
            // `cs`/`CS` alone is enough to set the flag: §8.6.8 says selecting
            // a space also sets the colour to that space's initial value, so a
            // `/Sep1 cs` with no `scn` has still chosen a colour this parser
            // cannot represent.
            b"cs" | b"CS" | b"sc" | b"scn" | b"SC" | b"SCN" => {
                color_unmodelled = true;
                color = None;
            }
            b"Tm" => tm_count += 1,
            _ => {}
        }
    }

    if tm_count > 1 {
        return Err(VarTextError::TooManyTm);
    }
    let (font_name, font_size) = tf.ok_or(VarTextError::MissingTf)?;
    Ok(DefaultAppearance {
        font_name,
        font_size,
        color,
        color_unmodelled,
    })
}

/// The numeric operands of an operation, in order (non-numbers skipped).
fn number_operands(op: &crate::content::Operation<'_>) -> Vec<f64> {
    op.operands
        .iter()
        .filter_map(|tok| match &tok.kind {
            ContentTokenKind::Operand(Object::Integer(v)) => Some(*v as f64),
            ContentTokenKind::Operand(Object::Real(v)) => Some(*v),
            _ => None,
        })
        .collect()
}

/// Generate a plain (non-rich) variable-text appearance body (§12.7.3.3)
/// for `text` in the box `[0 0 bbox.width bbox.height]`.
///
/// The returned [`VarTextAppearance::content`] is the `/Tx BMC … EMC`
/// marked-content section the spec's own EXAMPLE shows: a `q … Q` group
/// clipping to the `/BBox`, a `BT … ET` text object whose text state is
/// set by the `/DA` operators, one `Tm` to place the first line, and one
/// `Tj` per line positioned by `/Q`.
///
/// # Errors
///
/// Any [`VarTextError`] from [`parse_default_appearance`], plus
/// [`VarTextError::FontUnresolved`] (the `/DA` font name is not in
/// `resources`) and [`VarTextError::SymbolicFont`] (it resolves to a
/// symbolic face this Latin generator cannot lay out).
pub fn build_variable_text(
    bbox: Rect,
    text: &str,
    da: &[u8],
    quad: Quadding,
    multiline: bool,
    resources: &[FontResource],
) -> Result<VarTextAppearance, VarTextError> {
    let parsed = parse_default_appearance(da)?;
    let font = resources
        .iter()
        .find(|r| r.name == parsed.font_name)
        .map(|r| r.font)
        .ok_or_else(|| {
            VarTextError::FontUnresolved(String::from_utf8_lossy(&parsed.font_name).into_owned())
        })?;
    if matches!(font, Std14::Symbol | Std14::ZapfDingbats) {
        return Err(VarTextError::SymbolicFont(
            String::from_utf8_lossy(&parsed.font_name).into_owned(),
        ));
    }

    let w = bbox.width();
    let h = bbox.height();

    // Encode to WinAnsi FIRST — the auto-fit below needs the actual bytes to
    // measure, and encoding is what decides how wide they are. (`?` for an
    // unencodable char is a different width from the char it replaces, so
    // measuring before encoding would fit the wrong string.)
    let (bytes, unencodable_chars) = encode_winansi(text);

    // VT1: size 0 ⇒ auto-size, disclosed.
    let (size, applied_autosize, applied_autosize_bound) = if parsed.font_size == 0.0 {
        // ★ SINGLE-LINE ONLY, and the split is a correctness requirement
        // rather than caution.
        //
        // `auto_fit` derives its candidate from the WHOLE box height, which is
        // the right quantity for one line and badly wrong for many: a 200 pt
        // multiline box would ask for ~170 pt text. It also applies a width
        // shrink, and on a multiline field `wrap_lines` already absorbs width
        // by breaking the text — shrinking as well would be the constraint
        // applied twice.
        //
        // A line-count-aware auto-size for multiline fields is a separate
        // question with its own measurement, and is not answered here. Those
        // fields keep the previous behaviour exactly.
        if multiline {
            (auto_size(h), Some(auto_size(h)), None)
        } else {
            let fit = auto_fit(font, w, h, &bytes);
            (fit.size, Some(fit.size), Some(fit.bound))
        }
    } else {
        (parsed.font_size, None, None)
    };
    let max_width = (w - 2.0 * TEXT_PAD).max(0.0);
    let lines = wrap_lines(font, size, &bytes, max_width, multiline);

    // Vertical metrics: ascent from the face descriptor (Base-14, GUI-free).
    let ascent = f64::from(fontdata::std14_descriptor(font).ascender) / 1000.0 * size;
    let line_height = size * LINE_FACTOR;
    let first_baseline = h - TEXT_PAD - ascent;

    let mut b = ContentBuilder::new();
    b.begin_marked_content(b"Tx");
    b.save_state();
    // Clip to the BBox so overflow text is cut, not spilled (§12.7.3.3
    // body; the text is NOT reflowed to fit unless auto-sized — VT1).
    b.rect(0.0, 0.0, w, h);
    b.clip_nonzero();
    b.paint(Paint::NoPaint);
    b.begin_text();
    // The /DA text state: font + size, then colour (default 0 g if the
    // /DA set none — VT2).
    b.set_font(&parsed.font_name, size);
    match parsed.color {
        Some(c) => c.apply_fill(&mut b),
        None => b.set_fill_gray(0.0),
    }

    // First line: one Tm (VT4) at its /Q-aligned origin.
    let first = lines.first().map_or(&[][..], Vec::as_slice);
    let mut running_x = align_x(quad, w, measure(font, size, first));
    b.set_text_matrix(1.0, 0.0, 0.0, 1.0, running_x, first_baseline);
    b.show_text(first);
    // Subsequent lines: relative Td moves (never another Tm).
    for line in lines.iter().skip(1) {
        let x = align_x(quad, w, measure(font, size, line));
        b.text_move(x - running_x, -line_height);
        running_x = x;
        b.show_text(line);
    }

    b.end_text();
    b.restore_state();
    b.end_marked_content();

    let mut fonts = Dict::new();
    fonts.insert(
        Name(parsed.font_name.clone()),
        Object::Dict(standard14_font_dict(font)),
    );
    let mut res = Dict::new();
    res.insert(Name::from(b"Font"), Object::Dict(fonts));

    Ok(VarTextAppearance {
        content: b.into_bytes(),
        resources: res,
        applied_autosize,
        applied_autosize_bound,
        da_colour_unmodelled: parsed.color_unmodelled,
        unencodable_chars,
        used_font: font,
        used_size: size,
    })
}

/// The x origin of a line of width `line_width` in a box of width `w`
/// under quadding `q` (§12.7.3.3 `/Q`). Clamped so a line wider than the
/// box still starts inside it (left-anchored) rather than off the left
/// edge.
fn align_x(q: Quadding, w: f64, line_width: f64) -> f64 {
    match q {
        Quadding::Left => TEXT_PAD,
        Quadding::Center => ((w - line_width) / 2.0).max(TEXT_PAD),
        Quadding::Right => (w - TEXT_PAD - line_width).max(TEXT_PAD),
    }
}

/// The set of `WinAnsi` codes whose glyph is `bullet` only as Annex D.2
/// footnote-3 *fallback* (unused-code) assignments — skipped by
/// [`winansi_code`] so a real character never reverse-maps onto one of
/// them (the canonical bullet is code 149).
const WINANSI_BULLET_FALLBACKS: [u8; 6] = [0x7F, 0x81, 0x8D, 0x8F, 0x90, 0x9D];

/// The `WinAnsi` byte code for a character, for measurement and showing.
///
/// ASCII printable characters map to themselves (`WinAnsi` is
/// ASCII-compatible over `0x20..=0x7E`); other characters reverse-map
/// through the compiled `WinAnsi` table, skipping the footnote-3 bullet
/// fallbacks so a real glyph never resolves onto an unused code. `None`
/// means the character has no `WinAnsi` representation.
fn winansi_code(ch: char) -> Option<u8> {
    if ('\u{20}'..='\u{7E}').contains(&ch) {
        return Some(ch as u8);
    }
    for code in 0x80u8..=0xFF {
        if WINANSI_BULLET_FALLBACKS.contains(&code) {
            continue;
        }
        if let Some(name) = fontdata::encoding_glyph_name(BaseEncoding::WinAnsi, code)
            && fontdata::glyph_name_to_unicode(name) == Some(ch)
        {
            return Some(code);
        }
    }
    None
}

/// Encode `text` to `WinAnsi` bytes, substituting `?` for any character
/// with no `WinAnsi` code and returning how many were substituted (a
/// named Base-14-Latin limit — disclosed, never silently dropped).
///
/// `pub(crate)` since `Pass 68.0`: the ce-dimension `/AP` baker
/// ([`crate::dimension::author_dimension`]) declares the same
/// `/WinAnsiEncoding` Base-14 font this module does, and was writing raw UTF-8
/// into it. That was invisible for as long as every label was ASCII, and
/// became visible the moment angular ce dimensions put a degree sign in one —
/// `77.5°` rendered as `77.5Â°`. One encoder, shared, rather than a second one
/// that would have to learn the same table.
pub(crate) fn encode_winansi(text: &str) -> (Vec<u8>, usize) {
    let mut out = Vec::new();
    let mut miss = 0usize;
    for ch in text.chars() {
        match winansi_code(ch) {
            Some(c) => out.push(c),
            None => {
                out.push(b'?');
                miss += 1;
            }
        }
    }
    (out, miss)
}

/// The advance width (glyph space, 1000/em) of a `WinAnsi` byte in `font`;
/// `0` for a code the face has no glyph for.
fn glyph_width(font: Std14, code: u8) -> u16 {
    fontdata::encoding_glyph_name(BaseEncoding::WinAnsi, code)
        .and_then(|name| fontdata::std14_width(font, name))
        .unwrap_or(0)
}

/// Measure a run of `WinAnsi` bytes in text-space points at `size`
/// (§9.4.4: advance = Σ width/1000 × size, before Tc/Tw/Th, which this
/// generator leaves at their defaults).
#[must_use]
fn measure(font: Std14, size: f64, bytes: &[u8]) -> f64 {
    let units: u32 = bytes.iter().map(|&c| u32::from(glyph_width(font, c))).sum();
    f64::from(units) / 1000.0 * size
}

/// Greedy word-wrap `WinAnsi` bytes into lines that fit `max_width`.
///
/// - **Single-line** (`multiline = false`): the whole text is one line
///   (newlines flattened to spaces); it may overflow horizontally and is
///   clipped by the `/BBox`.
/// - **Multiline**: split on `\n` into paragraphs, then greedily pack
///   words (space-separated) so each line fits `max_width`. A single word
///   wider than `max_width` becomes its own (overflowing, clipped) line
///   rather than looping forever. A blank paragraph yields a blank line.
///
/// The *packing* — accumulate words until the line overflows, break, an
/// oversized word alone on its own line — is **not** open-coded here any
/// more: it is [`crate::linebreak::greedy_pack`], the single greedy breaker
/// this module now shares with the FF-A within-block reflow engine
/// (decision 015 §3.2, option **VT-extend** — one breaker, two callers).
/// This function keeps the Std14-AFM *measurement* ([`measure`]) and the
/// paragraph/`\n` splitting that is specific to a variable-text value; the
/// reflow engine supplies a provenance-advance measurer to the same core.
/// The observable output is byte-identical to the previous inline packing
/// (the appearance-generation tests below pass verbatim).
fn wrap_lines(
    font: Std14,
    size: f64,
    bytes: &[u8],
    max_width: f64,
    multiline: bool,
) -> Vec<Vec<u8>> {
    if !multiline {
        let line: Vec<u8> = bytes
            .iter()
            .map(|&b| if b == b'\n' || b == b'\r' { b' ' } else { b })
            .collect();
        return vec![line];
    }
    let mut lines: Vec<Vec<u8>> = Vec::new();
    for para in bytes.split(|&b| b == b'\n') {
        let para: Vec<u8> = para.iter().copied().filter(|&b| b != b'\r').collect();
        // Non-empty, space-delimited words (runs of spaces collapse, exactly
        // as the previous inline loop's `if word.is_empty() { continue }`).
        let words: Vec<&[u8]> = para
            .split(|&b| b == b' ')
            .filter(|w| !w.is_empty())
            .collect();
        if words.is_empty() {
            // A blank paragraph still yields a blank line (unchanged).
            lines.push(Vec::new());
            continue;
        }
        // The shared greedy core decides the breaks; the closure measures a
        // candidate line = words[start..end] joined by single spaces, in
        // Std14 AFM points — the same bytes and the same `measure` the old
        // inline `candidate` built, so the break points are identical.
        let ranges = crate::linebreak::greedy_pack(words.len(), max_width, |s, e| {
            measure(font, size, &join_words(words.get(s..e).unwrap_or(&[])))
        });
        for r in ranges {
            lines.push(join_words(words.get(r).unwrap_or(&[])));
        }
    }
    if lines.is_empty() {
        lines.push(Vec::new());
    }
    lines
}

/// Join a slice of word byte-strings with a single U+0020 space between
/// each — the natural inter-word spacing [`measure`] assumes and the exact
/// form the previous inline packer built its `candidate`/pushed-line bytes
/// as. An empty slice yields empty bytes.
fn join_words(words: &[&[u8]]) -> Vec<u8> {
    let mut out = Vec::new();
    for (i, word) in words.iter().enumerate() {
        if i > 0 {
            out.push(b' ');
        }
        out.extend_from_slice(word);
    }
    out
}

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::float_cmp
)]
mod tests {
    use super::*;

    fn helv() -> Vec<FontResource> {
        vec![FontResource {
            name: b"Helv".to_vec(),
            font: Std14::Helvetica,
        }]
    }

    fn bbox(w: f64, h: f64) -> Rect {
        Rect {
            llx: 0.0,
            lly: 0.0,
            urx: w,
            ury: h,
        }
    }

    fn content_str(a: &VarTextAppearance) -> String {
        String::from_utf8(a.content.clone()).unwrap()
    }

    // -- /DA parsing (X9) ----------------------------------------------

    #[test]
    fn da_parse_reads_tf_and_colour_via_the_real_lexer() {
        let da = parse_default_appearance(b"0 0 1 rg /Helv 12 Tf").unwrap();
        assert_eq!(da.font_name, b"Helv");
        assert_eq!(da.font_size, 12.0);
        assert_eq!(da.color, Some(TextColor::Rgb(0.0, 0.0, 1.0)));
    }

    #[test]
    fn da_parse_tolerates_names_with_escapes_and_reals() {
        // A split-on-space scanner would choke on the #-escape and the
        // leading-period real; the real lexer does not.
        let da = parse_default_appearance(b"/He#6cv .5 Tf 0.2 g").unwrap();
        assert_eq!(da.font_name, b"Helv"); // #6c == 'l'
        assert_eq!(da.font_size, 0.5);
        assert_eq!(da.color, Some(TextColor::Gray(0.2)));
    }

    #[test]
    fn da_missing_tf_is_refused() {
        assert_eq!(
            parse_default_appearance(b"0 g"),
            Err(VarTextError::MissingTf)
        );
    }

    #[test]
    fn da_two_tm_is_refused() {
        assert_eq!(
            parse_default_appearance(b"/Helv 12 Tf 1 0 0 1 0 0 Tm 1 0 0 1 5 5 Tm"),
            Err(VarTextError::TooManyTm)
        );
    }

    #[test]
    fn da_no_colour_leaves_none_meaning_black() {
        let da = parse_default_appearance(b"/Helv 10 Tf").unwrap();
        assert_eq!(da.color, None);
    }

    // -- font resolution (named refusal, never a silent substitution) ---

    #[test]
    fn unresolvable_font_is_a_named_refusal() {
        let da = default_appearance_string(b"F1", 12.0, TextColor::Gray(0.0));
        let err = build_variable_text(bbox(100.0, 20.0), "hi", &da, Quadding::Left, false, &helv())
            .unwrap_err();
        assert_eq!(err, VarTextError::FontUnresolved("F1".to_owned()));
    }

    #[test]
    fn symbolic_font_is_a_named_limit() {
        let res = vec![FontResource {
            name: b"Sy".to_vec(),
            font: Std14::Symbol,
        }];
        let da = default_appearance_string(b"Sy", 12.0, TextColor::Gray(0.0));
        let err = build_variable_text(bbox(100.0, 20.0), "hi", &da, Quadding::Left, false, &res)
            .unwrap_err();
        assert_eq!(err, VarTextError::SymbolicFont("Sy".to_owned()));
    }

    // -- the /Tx BMC…EMC template + a single Tm (VT4) -------------------

    #[test]
    fn body_is_a_tx_marked_content_section_with_one_tm() {
        let da = default_appearance_string(b"Helv", 12.0, TextColor::Gray(0.0));
        let a = build_variable_text(
            bbox(200.0, 20.0),
            "Hello",
            &da,
            Quadding::Left,
            false,
            &helv(),
        )
        .unwrap();
        let c = content_str(&a);
        assert!(c.starts_with("/Tx BMC\n"), "{c}");
        assert!(c.trim_end().ends_with("EMC"), "{c}");
        assert!(c.contains("BT\n") && c.contains("ET\n"));
        assert!(c.contains("/Helv 12 Tf"));
        assert_eq!(c.matches(" Tm\n").count(), 1, "exactly one Tm (VT4): {c}");
        assert!(c.contains("(Hello) Tj"));
        assert!(c.contains("re\nW\nn\n"), "clips to BBox: {c}");
        // Resources carry the bare standard-14 dict under the DA name.
        let font = a.resources.get(b"Font").unwrap().as_dict().unwrap();
        assert!(font.get(b"Helv").is_some());
    }

    // -- /Q measurement against AFM widths ------------------------------

    #[test]
    fn quadding_places_lines_by_afm_width() {
        // "AV" in Helvetica: A=667, V=667 ⇒ 1334/1000*10 = 13.34 pt.
        let width = measure(Std14::Helvetica, 10.0, b"AV");
        assert!((width - 13.34).abs() < 1e-9, "{width}");
        let da = default_appearance_string(b"Helv", 10.0, TextColor::Gray(0.0));
        let w = 200.0;
        // Right-justified: x0 = w - PAD - width.
        let right =
            build_variable_text(bbox(w, 20.0), "AV", &da, Quadding::Right, false, &helv()).unwrap();
        let expected_x = w - TEXT_PAD - width;
        assert!(
            content_str(&right).contains(&format!("1 0 0 1 {} ", trim_num(expected_x))),
            "right x should be {expected_x}: {}",
            content_str(&right)
        );
        // Centre-justified: x0 = (w - width)/2.
        let center =
            build_variable_text(bbox(w, 20.0), "AV", &da, Quadding::Center, false, &helv())
                .unwrap();
        let cx = (w - width) / 2.0;
        assert!(
            content_str(&center).contains(&format!("1 0 0 1 {} ", trim_num(cx))),
            "centre x should be {cx}: {}",
            content_str(&center)
        );
        // Left-justified: x0 = PAD.
        let left =
            build_variable_text(bbox(w, 20.0), "AV", &da, Quadding::Left, false, &helv()).unwrap();
        assert!(
            content_str(&left).contains("1 0 0 1 2 "),
            "{}",
            content_str(&left)
        );
    }

    /// Format a number the way `emit_number` does, for substring matching.
    fn trim_num(v: f64) -> String {
        let mut out = Vec::new();
        crate::writer::content::emit_number(&mut out, v);
        String::from_utf8(out).unwrap()
    }

    // -- a /DA colour pdfcer cannot model (Pass 221.0) ------------------------

    /// ★★★ A `/DA` colour in a space pdfcer cannot model must be DISTINGUISHABLE
    /// from a `/DA` that sets no colour at all.
    ///
    /// # The defect
    ///
    /// The parser handled `g G rg RG k K` and swallowed everything else in its
    /// `_ => {}` arm, so `/Sep1 cs 1 scn` yielded `color: None`. And `None`
    /// already had a defined meaning — *"the `/DA` sets none, so the text
    /// renders black"*.
    ///
    /// So an unmodellable colour was ALIASED ONTO the file's own instruction,
    /// and the generated appearance was painted black with nothing able to
    /// report it. Unlike the sibling defects in the vector model, this one
    /// writes the wrong value into a generated `/AP` — into the document.
    #[test]
    fn a_da_colour_in_an_unmodelled_space_is_not_confused_with_no_colour() {
        let spot = parse_default_appearance(b"/Sep1 cs 1 scn /Helv 12 Tf").unwrap();
        assert_eq!(spot.color, None, "pdfcer still cannot represent the colour");
        assert!(
            spot.color_unmodelled,
            "★ but it must record that one was SPECIFIED — that is the whole \
             distinction, and painting black without it is a silent inference"
        );

        // The control: a `/DA` that genuinely sets no colour.
        let bare = parse_default_appearance(b"/Helv 12 Tf").unwrap();
        assert_eq!(bare.color, None);
        assert!(
            !bare.color_unmodelled,
            "a /DA with no colour operator at all must NOT claim a narrowing"
        );

        // And a device colour is unaffected in both fields.
        let dev = parse_default_appearance(b"1 0 0 rg /Helv 12 Tf").unwrap();
        assert_eq!(dev.color, Some(TextColor::Rgb(1.0, 0.0, 0.0)));
        assert!(!dev.color_unmodelled);
    }

    /// Selecting a space is enough, even with no value operator.
    ///
    /// §8.6.8: selecting a colour space also sets the colour to that space's
    /// initial value — so `/Sep1 cs` with no `scn` has still chosen a colour
    /// this parser cannot represent.
    #[test]
    fn selecting_a_space_alone_counts_as_a_narrowing() {
        let a = parse_default_appearance(b"/Sep1 cs /Helv 12 Tf").unwrap();
        assert!(a.color_unmodelled);
    }

    /// The narrowing reaches the generated appearance, where a caller can
    /// disclose it.
    #[test]
    fn the_narrowing_is_reported_on_the_generated_appearance() {
        let a = build_variable_text(
            bbox(200.0, 20.0),
            "hi",
            b"/Sep1 cs 1 scn /Helv 12 Tf",
            Quadding::Left,
            false,
            &helv(),
        )
        .unwrap();
        assert!(
            a.da_colour_unmodelled,
            "the appearance must carry the narrowing so a shell can say so"
        );
    }

    // -- auto-size (VT1) ------------------------------------------------

    /// ★★ THIS TEST USED TO PIN THE DEFECT, and is rewritten rather than
    /// deleted so the change is visible.
    ///
    /// It asserted that every auto-size lands in `[4, 12]` and that a huge box
    /// "clamps to the cap, not an absurd size". The cap was the bug: with
    /// `AUTOSIZE_MAX = 12` every auto-sized field in a document came out at
    /// 12 pt regardless of its box, which is what an operator saw as pdfcer's
    /// rows being two-thirds the size of the row Acrobat filled on the same
    /// sheet.
    ///
    /// A test that pins a constant cannot notice that the constant is wrong.
    /// What is pinned now is the PROPERTY the operator actually cares about:
    /// different boxes get different answers, and the answer tracks the box.
    #[test]
    fn auto_size_tracks_the_box_rather_than_a_constant() {
        let da = default_appearance_string(b"Helv", 0.0, TextColor::Gray(0.0));
        let short =
            build_variable_text(bbox(200.0, 13.0), "hi", &da, Quadding::Left, false, &helv())
                .unwrap();
        let tall =
            build_variable_text(bbox(200.0, 26.0), "hi", &da, Quadding::Left, false, &helv())
                .unwrap();
        let s_short = short.applied_autosize.expect("auto-size disclosed");
        let s_tall = tall.applied_autosize.expect("auto-size disclosed");
        assert!(
            s_tall > s_short * 1.5,
            "★ a box twice as tall must get a substantially larger size, not the same capped constant: {s_short} vs {s_tall}"
        );
        assert_eq!(short.used_size, s_short);
        // Height-derived, from Helvetica's own /FontBBox height of 1.156 em,
        // with one point of padding per side. Asserted as the RATIO so the
        // test states the formula rather than a magic number.
        assert!(
            ((13.0 - 2.0) / s_short - 1.156).abs() < 0.01,
            "the candidate must be usable height over the font bbox height; got {s_short}"
        );
        assert_eq!(
            short.applied_autosize_bound,
            Some(AutoFitBound::Height),
            "a short string in a wide box is bound by HEIGHT"
        );
    }

    /// The width step, and the bound it reports.
    ///
    /// Without this the height formula alone would happily return a size whose
    /// text runs straight out of the box.
    #[test]
    fn a_string_too_long_for_the_box_is_shrunk_and_says_so() {
        let da = default_appearance_string(b"Helv", 0.0, TextColor::Gray(0.0));
        let a = build_variable_text(
            bbox(120.0, 26.0),
            "a very long line of text indeed",
            &da,
            Quadding::Left,
            false,
            &helv(),
        )
        .unwrap();
        let size = a.applied_autosize.expect("auto-size disclosed");
        let height_only = (26.0 - 2.0) / 1.156;
        assert!(
            size < height_only,
            "the text does not fit 40 pt at the height-derived {height_only}, so it must shrink; got {size}"
        );
        assert_eq!(a.applied_autosize_bound, Some(AutoFitBound::Width));
    }

    /// ★ The floor is a THIRD outcome and is named separately, because it is
    /// the one case where the returned size does not satisfy the constraint
    /// that produced it — the text WILL overflow, and an operator is entitled
    /// to be told that rather than shown a fit that did not happen.
    ///
    /// Found by writing the test above with too narrow a box: it reported
    /// `Floor` where `Width` was expected, which is the branch behaving
    /// correctly and the fixture being extreme.
    #[test]
    fn a_box_too_small_for_any_legible_size_reports_the_floor() {
        let da = default_appearance_string(b"Helv", 0.0, TextColor::Gray(0.0));
        let a = build_variable_text(
            bbox(40.0, 26.0),
            "a very long line of text indeed",
            &da,
            Quadding::Left,
            false,
            &helv(),
        )
        .unwrap();
        assert_eq!(a.applied_autosize, Some(AUTOSIZE_MIN));
        assert_eq!(a.applied_autosize_bound, Some(AutoFitBound::Floor));
    }

    /// A multiline field keeps the OLD route, and reports no bound.
    ///
    /// Deliberate: `auto_fit` derives from the whole box height, which is right
    /// for one line and badly wrong for many, and its width step would double
    /// up on the wrapping that multiline already does. Naming a bound here
    /// would report a constraint that was never evaluated.
    #[test]
    fn a_multiline_field_is_not_auto_fitted_and_names_no_bound() {
        let da = default_appearance_string(b"Helv", 0.0, TextColor::Gray(0.0));
        let a = build_variable_text(bbox(200.0, 60.0), "hi", &da, Quadding::Left, true, &helv())
            .unwrap();
        assert!(a.applied_autosize.is_some(), "still disclosed");
        assert_eq!(a.applied_autosize_bound, None, "and no bound is claimed");
    }

    #[test]
    fn explicit_size_does_not_report_autosize() {
        let da = default_appearance_string(b"Helv", 11.0, TextColor::Gray(0.0));
        let a = build_variable_text(bbox(200.0, 20.0), "hi", &da, Quadding::Left, false, &helv())
            .unwrap();
        assert_eq!(a.applied_autosize, None);
        assert_eq!(a.used_size, 11.0);
    }

    // -- multiline word-wrap --------------------------------------------

    #[test]
    fn multiline_wraps_within_the_box() {
        let da = default_appearance_string(b"Helv", 12.0, TextColor::Gray(0.0));
        // A narrow box forces the two words onto two lines.
        let a = build_variable_text(
            bbox(40.0, 60.0),
            "hello world",
            &da,
            Quadding::Left,
            true,
            &helv(),
        )
        .unwrap();
        let c = content_str(&a);
        assert!(c.contains("(hello) Tj"), "{c}");
        assert!(c.contains("(world) Tj"), "{c}");
        // Two lines ⇒ one Td move after the single Tm.
        assert_eq!(c.matches(" Td\n").count(), 1, "{c}");
    }

    #[test]
    fn single_line_does_not_wrap() {
        let da = default_appearance_string(b"Helv", 12.0, TextColor::Gray(0.0));
        let a = build_variable_text(
            bbox(40.0, 20.0),
            "hello world",
            &da,
            Quadding::Left,
            false,
            &helv(),
        )
        .unwrap();
        let c = content_str(&a);
        assert!(c.contains("(hello world) Tj"), "{c}");
        assert_eq!(c.matches(" Td\n").count(), 0);
    }

    // -- WinAnsi encoding + the named unencodable limit -----------------

    #[test]
    fn unencodable_characters_are_substituted_and_counted() {
        let da = default_appearance_string(b"Helv", 12.0, TextColor::Gray(0.0));
        // U+4E2D (中) has no WinAnsi code.
        let a = build_variable_text(
            bbox(200.0, 20.0),
            "a中b",
            &da,
            Quadding::Left,
            false,
            &helv(),
        )
        .unwrap();
        assert_eq!(a.unencodable_chars, 1);
        assert!(content_str(&a).contains("(a?b) Tj"));
    }

    #[test]
    fn high_winansi_characters_round_trip_to_octal() {
        let da = default_appearance_string(b"Helv", 12.0, TextColor::Gray(0.0));
        // é is WinAnsi 0xE9 = octal 351.
        let a = build_variable_text(bbox(200.0, 20.0), "é", &da, Quadding::Left, false, &helv())
            .unwrap();
        assert_eq!(a.unencodable_chars, 0);
        assert!(
            content_str(&a).contains("(\\351) Tj"),
            "{}",
            content_str(&a)
        );
    }

    #[test]
    fn generated_body_reparses_as_a_content_stream() {
        // The generator must never emit a stream the tokenizer rejects.
        let da = default_appearance_string(b"Helv", 0.0, TextColor::Rgb(1.0, 0.0, 0.0));
        for (text, ml) in [("Hello (world)\\", false), ("a b c d e f g", true)] {
            let a = build_variable_text(bbox(80.0, 40.0), text, &da, Quadding::Center, ml, &helv())
                .unwrap();
            ContentStream::parse(a.content.clone())
                .unwrap_or_else(|e| panic!("body did not reparse: {e} for {text:?}"));
        }
    }

    #[test]
    fn standard14_dict_is_program_free() {
        let d = standard14_font_dict(Std14::TimesRoman);
        assert_eq!(
            d.get(b"BaseFont").unwrap().as_name().unwrap().as_bytes(),
            b"Times-Roman"
        );
        assert!(d.get(b"FontDescriptor").is_none());
        assert!(d.get(b"Widths").is_none());
        assert_eq!(
            d.get(b"Encoding").unwrap().as_name().unwrap().as_bytes(),
            b"WinAnsiEncoding"
        );
    }
}
