//! # A `Separation`/`DeviceN` image and a fill of the same colour must agree
//!
//! # What was wrong
//!
//! On a page whose group colour space is `/DeviceCMYK`, pdfcer composites in a
//! four-colorant buffer. A `Separation`/`DeviceN` **image** resolved its colour
//! through its tint transform **to sRGB** and never to its `DeviceCMYK`
//! alternate, so it entered that buffer through a `CMYK -> sRGB -> CMYK` round
//! trip. The outbound leg is [`pdfcer_core::color`]'s calibrated conversion,
//! carrying a rendering intent; the return leg is `overprint::rgb_to_cmyk`, a
//! naive maximum-GCR formula. Those two are not an inverse pair, so the ink
//! that arrived was not the ink that left.
//!
//! Measured symptom, on the five-colorant `DeviceN` photograph that opened
//! `Pass 140.0`: **visibly desaturated against Acrobat** — washed toward grey
//! where the reference was saturated green. Mean distance to the Acrobat
//! reference over the photograph, before and after, at scale 2:
//!
//! ```text
//! photograph region     dE 33.06  ->  16.85
//! an inset patch of it  dE 29.57  ->   7.13
//! saturation spread     51.8      ->  90.2      (Acrobat: 87.3)
//! ```
//!
//! # The oracle, and why it needs no reference render
//!
//! Each fixture draws **the same authored colour twice**: once as a flat path
//! fill, once as a sampled image whose every texel carries the identical
//! operands. Same space, same tints, same page. A correct renderer paints them
//! the same colour, so the assertion is *fill == image* — no geometry, no
//! reference image, nothing remembered between runs. This is exactly
//! `shading_ink.rs`'s oracle applied one object type over.
//!
//! ★★ **And it found a second defect, which is the transferable part.** With
//! only the image half fixed, the fixtures reported the fill and the image
//! **8.3 to 9.0 mean levels apart** — and the *additive control page*, which
//! has no colorant buffer and never took the round trip, showed the image was
//! the correct half:
//!
//! ```text
//! page                       fill           image
//! separation, additive       157,207,185    158,208,186
//! separation, subtractive    159,192,194    158,208,186   <- the FILL is the outlier
//! devicen,    subtractive    160, 86,161    160,108,156   <- likewise
//! ```
//!
//! A `Separation`/`DeviceN` **fill** was reconstructing its colorants from the
//! already-resolved sRGB by the same round trip. Before `Pass 140.0` both
//! halves took it and were wrong **together**, which is why nothing had ever
//! reported it. `Pass 140.1` gave the fill the document's own answer too, and
//! all four pages then agreed to within quantisation.
//!
//! ⇒ **Fixing one route of a several-routes-agree-wrongly situation converts a
//! silent shared error into a visible disagreement.** That is an argument *for*
//! fixing one route — the disagreement is information — but it makes the
//! remaining routes urgent in a way they were not before. `R219`.
//!
//! # What this does NOT cover
//!
//! **Overprint.** These pages set no `/OP`, deliberately: an overprinting
//! `Separation`/`DeviceN` image already had a native route
//! (`Canvas::fill_image_overprint`, `Pass 130.2`) and answers Table 149's
//! question — *which components did the source SPECIFY* — from a different
//! table. The two must not be confused, and the fixtures that exercise the
//! overprint half live in `overprint_image.rs`.
//!
//! Fixtures are generated by `tools/gen-devicen-image-fixtures.py`; read its
//! header for why each page exists and why the tint values are the ones they
//! are.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing
)]

use std::path::{Path, PathBuf};

use pdfcer_core::document::Document;
use pdfcer_core::page_tree;
use pdfcer_render::RenderedPage;

const SCALE: f32 = 2.0;

fn render(name: &str) -> RenderedPage {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures/synthetic/devicen-image")
        .join(name);
    let doc = Document::load(Path::new(&path)).expect("fixture loads");
    let pages = page_tree::pages(&doc).expect("page tree");
    pdfcer_render::render_page(&doc, &pages[0], SCALE).expect("renders")
}

/// The mean RGB of a rectangle given in **fractions of the page**, so the
/// assertion does not encode the scale.
///
/// Fractions rather than pixels because `SCALE` is a constant somebody will
/// change, and a hard-coded pixel box would then silently sample the gutter.
fn patch(page: &RenderedPage, x0: f64, x1: f64) -> (f64, f64, f64) {
    let w = f64::from(page.pixmap.width());
    let h = f64::from(page.pixmap.height());
    #[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
    let (px0, px1) = ((w * x0) as u32, (w * x1) as u32);
    #[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
    let (py0, py1) = ((h * 0.25) as u32, (h * 0.75) as u32);
    let stride = page.pixmap.width();
    let px = page.pixmap.pixels();
    let (mut r, mut g, mut b, mut n) = (0.0, 0.0, 0.0, 0.0);
    for y in py0..py1 {
        for x in px0..px1 {
            let p = px[(y * stride + x) as usize];
            r += f64::from(p.red());
            g += f64::from(p.green());
            b += f64::from(p.blue());
            n += 1.0;
        }
    }
    (r / n, g / n, b / n)
}

/// The fill occupies x 20–80 pt of a 200 pt page, the image x 120–180. Both
/// are sampled well inside, so no boundary pixel enters either mean.
fn fill_and_image(page: &RenderedPage) -> ((f64, f64, f64), (f64, f64, f64)) {
    (patch(page, 0.15, 0.35), patch(page, 0.65, 0.85))
}

fn mean_abs(a: (f64, f64, f64), b: (f64, f64, f64)) -> f64 {
    ((a.0 - b.0).abs() + (a.1 - b.1).abs() + (a.2 - b.2).abs()) / 3.0
}

/// ★★★ THE ONE THAT MATTERS. A spot-colour image and a spot-colour fill of the
/// same tint, on a page that composites in ink.
///
/// Measured at **8.33** before `Pass 140.0`/`140.1`, and the fixture's colorant
/// is a saturated green precisely so that the round trip has somewhere to go —
/// a neutral would barely move and the test would pass either way.
#[test]
fn a_separation_image_and_fill_of_one_tint_agree_on_a_subtractive_page() {
    let page = render("separation-image-vs-fill-cmyk.pdf");
    let (fill, image) = fill_and_image(&page);
    let d = mean_abs(fill, image);
    assert!(
        d <= 1.5,
        "★ the SAME authored tint rendered two different colours: fill {fill:?} \
         vs image {image:?}, mean |diff| {d:.2}. One of them resolved through \
         its tint transform to sRGB and back rather than to its DeviceCMYK \
         alternate. Measured at 8.33 before the fix"
    );
}

/// The same, for a `/DeviceN` naming two **process** colorants.
///
/// ★ This page is the one that discriminates the two questions. Its tint
/// transform maps `(t0, t1)` to `(0.9*t0, 0.8*t1, 0.1, 0.05)`, so the
/// components the source *specified* — Table 149's question, `[t0, t1, 0, 0]`
/// — and the components the transform *produces* are different numbers. A
/// renderer that answered the overprint question here would paint
/// `[0.4, 0.8, 0, 0]` and be visibly wrong in the Y and K channels.
#[test]
fn a_devicen_image_and_fill_of_one_tint_agree_on_a_subtractive_page() {
    let page = render("devicen-image-vs-fill-cmyk.pdf");
    let (fill, image) = fill_and_image(&page);
    let d = mean_abs(fill, image);
    assert!(
        d <= 1.5,
        "fill {fill:?} vs image {image:?}, mean |diff| {d:.2}. Measured at 9.00 \
         before the fix. If only this page fails, suspect the authored-tints \
         route being used as a paint colour: it is right for Table 149 and \
         wrong here"
    );
}

/// The `/Indexed` route — a duotone, whose colorants are resolved once at
/// palette-build time rather than per texel.
///
/// A separate test rather than a parameterisation because it is a genuinely
/// separate code path: `resolve_indexed` builds a parallel ink table, and the
/// per-texel loop never sees the base space at all.
#[test]
fn a_duotone_image_and_fill_of_one_palette_entry_agree() {
    let page = render("duotone-image-vs-fill-cmyk.pdf");
    let (fill, image) = fill_and_image(&page);
    let d = mean_abs(fill, image);
    assert!(
        d <= 1.5,
        "fill {fill:?} vs image {image:?}, mean |diff| {d:.2}"
    );
}

/// ★★ The MIXED duotone — `/Indexed` over `/DeviceN [/Black /SpotGreen]`
/// (`Pass 238.0`), the shape the print-conformance suite's duotones take.
///
/// This is the test that found two fill-path bugs the single-colorant
/// duotone above could not see. The fill read the palette INDEX as its
/// operand for both the spot deposit (`authored_spot_inks`) and the authored
/// process tints (`process_tints_only`), so it built the spot's curve from
/// the Indexed space — whose domain is indices — and stated `K = 0` where the
/// palette entry says `K = 0.5`. Two wrongs cancelled on the fill route and it
/// looked right alone; the first image to deposit a true tint into that plane
/// rendered white, and the disagreement was the information.
#[test]
fn a_mixed_duotone_image_and_fill_of_one_palette_entry_agree() {
    let page = render("duotone2-image-vs-fill-cmyk.pdf");
    let (fill, image) = fill_and_image(&page);
    let d = mean_abs(fill, image);
    assert!(
        d <= 1.5,
        "fill {fill:?} vs image {image:?}, mean |diff| {d:.2}. If only this \
         page fails, one route is reading an /Indexed operand as a tint \
         instead of resolving the palette entry first"
    );
    // And the colour is the palette entry's, not the index's: K 0.5 over the
    // spot's green must be a DARK green, not the pale green of tint alone.
    let (_, g, _) = fill;
    assert!(
        g < 160.0,
        "K = 0.5 must darken the entry; a fill that read the index (0) as K \
         paints the spot alone: {fill:?}"
    );
}

/// A STENCIL MASK painted in the spot agrees with a path fill of the same
/// tint (`Pass 238.0`). §8.9.6.2: an image mask "designates places where the
/// current colour shall be painted" — so on an ink page the stencil must
/// carry the fill's spot to its plane exactly as the path does. Before this
/// Pass the stencil route pre-tinted its texels in sRGB and bridged them
/// back, and measured 13+ levels apart from the fill beside it.
#[test]
fn a_stencil_mask_and_fill_of_one_spot_tint_agree_on_a_subtractive_page() {
    let page = render("stencil-spot-vs-fill-cmyk.pdf");
    let (fill, stencil) = fill_and_image(&page);
    let d = mean_abs(fill, stencil);
    assert!(
        d <= 1.5,
        "fill {fill:?} vs stencil {stencil:?}, mean |diff| {d:.2}. A stencil \
         is a fill with an image's shape; on an ink page it must take the \
         fill's route"
    );
}

/// The OVERPRINT shape the suite's duotone patches test (`Pass 238.0`): a
/// `1 0 1 .5 k` process mark, then the mixed duotone image over it under
/// `/OP true`. Table 149 for a `[/Black <spot>]` source: K takes the image,
/// C and Y stay from the mark, the spot deposits. So the right box must
/// differ from the left (the mark alone) — the image painted — and must
/// still carry the mark's cyan and yellow, which a knockout would have
/// erased along with the check marks the suite draws in that ink.
#[test]
fn an_overprinting_mixed_duotone_image_keeps_the_process_mark_beneath_it() {
    let page = render("duotone2-op-image-over-cmyk-mark.pdf");
    let (mark_alone, mark_under_image) = fill_and_image(&page);
    assert!(
        mean_abs(mark_alone, mark_under_image) > 5.0,
        "the image painted nothing over the mark: {mark_alone:?} vs {mark_under_image:?}"
    );
    // The mark alone is `1 0 1 .5 k`: a dark green. Under the image its C and
    // Y survive and K rises to the image's 0.5 (the same), and the spot's
    // green multiplies in — so the result is a DARKER green, never a neutral
    // and never lighter than the mark.
    let (r0, g0, b0) = mark_alone;
    let (r1, g1, b1) = mark_under_image;
    assert!(
        g1 > r1 && g1 > b1,
        "the mark's cyan and yellow must survive as green beneath the image: {mark_under_image:?}"
    );
    assert!(
        r1 + g1 + b1 <= r0 + g0 + b0 + 3.0,
        "an overprinting image over ink cannot LIGHTEN it: {mark_alone:?} -> {mark_under_image:?}"
    );
}

/// The additive control, and it is what identified WHICH half was wrong.
///
/// With no page group there is no colorant buffer, so neither the fill nor the
/// image ever entered ink and neither took a round trip. They agreed before
/// this Pass and must go on agreeing — the two paths are different code, and
/// this stops a future change breaking the additive one behind a passing
/// subtractive test.
///
/// ★ It also pins the ANSWER, not just the agreement: this page's colour is
/// what the document's tint transform produces, computed with no ink anywhere
/// in the pipeline. The subtractive pages above must land on the same colour,
/// which is asserted separately below.
#[test]
fn a_separation_image_and_fill_agree_on_an_additive_page_too() {
    let page = render("separation-image-vs-fill-rgb.pdf");
    let (fill, image) = fill_and_image(&page);
    let d = mean_abs(fill, image);
    assert!(
        d <= 1.5,
        "fill {fill:?} vs image {image:?}, mean |diff| {d:.2}"
    );
}

/// ★★ THE CROSS-PAGE ASSERTION, AND IT IS DELIBERATE WHERE `shading_ink.rs`
/// REFUSES THE EQUIVALENT.
///
/// That file's third test exists to stop somebody pinning a subtractive page
/// against an additive one, because a page that composites in ink converts its
/// result back out at the end and the two are *required* to differ by up to
/// ~100 levels on saturated overlaps.
///
/// This assertion is admissible anyway, and only because of what these
/// particular fixtures paint: a **flat, unblended, fully opaque** patch over
/// bare paper. Nothing overlaps, nothing blends, no backdrop participates — so
/// the round trip out of ink at the end is the only conversion in play, and for
/// a single flat colour it is `cmyk_to_rgb(rgb_to_cmyk(c))`, which
/// `overprint::rgb_to_cmyk`'s own documentation states is exact by
/// construction.
///
/// So the tolerance is wide enough for that pair plus 8-bit quantisation, and
/// **not** wide enough to hide the 8-9 level defect this Pass fixed. If a
/// future change makes these pages blend or overlap, this test must be deleted
/// rather than loosened — see `shading_ink.rs` for why.
#[test]
fn the_subtractive_page_lands_on_the_additive_page_s_colour() {
    let additive = render("separation-image-vs-fill-rgb.pdf");
    let subtractive = render("separation-image-vs-fill-cmyk.pdf");
    let (af, _) = fill_and_image(&additive);
    let (sf, si) = fill_and_image(&subtractive);
    assert!(
        mean_abs(af, sf) <= 2.0,
        "the subtractive FILL {sf:?} left the colour the same tint transform \
         produces with no ink in the pipeline at all, {af:?}. Measured at 8.33 \
         before Pass 140.1"
    );
    assert!(
        mean_abs(af, si) <= 2.0,
        "the subtractive IMAGE {si:?} left the colour the same tint transform \
         produces with no ink in the pipeline at all, {af:?}. Measured at 7.67 \
         before Pass 140.0"
    );
}

/// ★★★ `Pass 140.2` — AN IMAGE'S OWN COLOUR CONVERSIONS MUST BE REPORTED.
///
/// `image::decode` counted its shortfalls into two local `ColorDiagnostics`
/// and **dropped both at the end of the function**. So an image whose
/// `/tintTransform` was missing or malformed rendered as `separation_to_rgb`'s
/// neutral stand-in — a colour the document never specified, whose own note
/// says *"lightness preserved, hue is not the document's"* — and pdfcer
/// reported **nothing**. That is a **rule 4** violation: the rule forbids
/// silence about an inference, and an image is exactly where the operator
/// cannot see the substitution, because a plausible grey looks like a grey the
/// file might have asked for.
///
/// ★★ THE FIXTURES ARE IMAGE-ONLY, AND THAT IS THE WHOLE MEASUREMENT. Every
/// other page in this file carries a fill beside its image, and a fill's
/// conversions ARE counted — so on those pages the counter reads a plausible
/// non-zero number whether or not the image contributes. **A page with a
/// second producer cannot detect a missing producer.** That is how this
/// survived, and it is also how it was found: an engineer read `292` off a
/// spot-colour page and attributed it to the image's cache, when the image had
/// contributed nothing to it.
///
/// Measured before the fix — both pages, both counters, zero:
///
/// ```text
///           tint_applied   tint_not_applied
/// good           0                0
/// broken         0                0
/// ```
///
/// The `good` half is asserted too, and is not padding: a fix that routed only
/// FAILURES to the caller would satisfy the shortfall half and leave the census
/// half still lying by omission, and only the `good` page can tell those apart.
#[test]
fn an_image_s_own_tint_transform_is_reported_whether_it_worked_or_not() {
    let good = render("image-only-good-tint.pdf");
    assert_eq!(
        good.diagnostics.color.tint_transforms_applied, 1,
        "a page whose ONLY content is a spot-colour image ran its tint \
         transform and reported {} — the image's conversions never reached \
         the caller. Measured at 0 before Pass 140.2",
        good.diagnostics.color.tint_transforms_applied
    );
    assert_eq!(
        good.diagnostics.color.tint_transform_not_applied, 0,
        "a WORKING transform must not be reported as a shortfall"
    );

    let broken = render("image-only-broken-tint.pdf");
    assert_eq!(
        broken.diagnostics.color.tint_transform_not_applied, 1,
        "an image whose /tintTransform cannot run was painted as a neutral \
         stand-in and disclosed nothing. Measured at 0 before Pass 140.2"
    );
    assert!(
        broken
            .diagnostics
            .color
            .notes
            .iter()
            .any(|n| n.contains("hue is not the document's")),
        "the COUNTER is not the disclosure — rule 4 wants the operator told \
         what was substituted, and the prose note is what says it. Notes were: \
         {:?}",
        broken.diagnostics.color.notes
    );
}

/// ★ The count is per DISTINCT SAMPLE TUPLE, not per texel, and that is a
/// contract rather than an implementation detail.
///
/// `TintCache` exists so that one broken transform on an eight-megapixel image
/// reports once rather than eight million times — its own docs say so. The
/// `good` fixture above is 8x8 = 64 texels of ONE constant value, so a
/// per-texel count would read 64 and a per-tuple count reads 1. Asserting the
/// exact value pins which of the two a future change kept.
#[test]
fn the_report_counts_distinct_colours_not_texels() {
    let good = render("image-only-good-tint.pdf");
    assert_eq!(
        good.diagnostics.color.tint_transforms_applied, 1,
        "the fixture's image is 64 texels of one constant tint; a count of 64 \
         means the cache stopped bounding the report"
    );
}
