//! # Image transparency — the pixel proofs (§8.9.6, §11.6.5.3)
//!
//! Pins `pdfcer-render`'s `/SMask` and `/Mask` compositing against the ten
//! synthetic fixtures in `fixtures/synthetic/transparency/` (generated by
//! `tools/gen-image-fixtures.py`; see that script's "transparency render
//! fixtures" section for the construction and the geometry).
//!
//! ## Why every page has a blue backdrop
//!
//! This is the load-bearing design decision of the whole suite, and it
//! exists because of a specific failure mode: **a renderer that ignores
//! alpha entirely passes a white-on-white transparency test.** Compositing
//! a transparent image over a white page and comparing against a white
//! reference cannot distinguish "the alpha was applied" from "the alpha
//! was discarded" — both produce white.
//!
//! So each fixture paints an opaque **pure blue** rectangle and places a
//! **pure red** 4×1 image over it. tiny-skia stores premultiplied RGBA
//! and composites `SourceOver`:
//!
//! ```text
//! dst' = src + dst × (1 − a)
//! src  = premultiplied pure red at alpha a = (a, 0, 0, a)
//! dst  = opaque pure blue                  = (0, 0, 255, 255)
//! dst' = (a, 0, 255 − a, 255)
//! ```
//!
//! The rendered pixel's **red channel is the alpha that was applied** and
//! its blue channel is 255 minus it. [`alpha_at`] reads it back directly,
//! so every assertion below is a statement about alpha rather than about
//! a colour that happens to encode one.
//!
//! ## Why the ramp is 0 / 85 / 170 / 255
//!
//! Binary alpha cannot catch a premultiplication bug: at `a == 0` and
//! `a == 255` the wrong formula and the right one agree. The two
//! intermediate values are the only ones that separate them — see
//! `image::premultiplied`'s doc comment, which describes the exact bug
//! (a `min`-clamp where a multiply belonged) these two samples exist to
//! catch, and which was live in the code until this Pass.
//!
//! ## Tolerance
//!
//! ±2 on each channel. The image is placed by a pattern shader through
//! the CTM, so the sampled value at a probe point is subject to
//! tiny-skia's own fixed-point pattern arithmetic; the probes sit at band
//! centres, far from any boundary, so the tolerance covers rounding and
//! nothing else. A polarity error moves a channel by 85 or more and a
//! missing mask moves it by 255 — both orders of magnitude outside it.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::path::PathBuf;

use pdfcer_core::document::Document;
use pdfcer_core::page_tree;
use pdfcer_render::RenderedPage;

/// Load a transparency fixture by file name.
fn fixture(name: &str) -> Document {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures/synthetic/transparency")
        .join(name);
    Document::from_bytes(std::fs::read(&path).expect("fixture file")).expect("fixture parses")
}

/// Render the fixture's only page at scale 1.0 — one device pixel per
/// point, so the probe coordinates below are the ones the generator
/// computed.
fn render(name: &str) -> RenderedPage {
    let doc = fixture(name);
    let pages = page_tree::pages(&doc).expect("page tree");
    pdfcer_render::render_page(&doc, &pages[0], 1.0).expect("renders")
}

/// The four band-centre device pixels, left to right.
///
/// The 4×1 image is placed by `80 0 0 20 10 10 cm`, so band *i* spans
/// user x ∈ [10 + 20i, 30 + 20i) and its centre is at 20 + 20i. Device y
/// is `PAGE_H − 20 = 20` for every one of them (the image band spans user
/// y ∈ [10, 30)).
const PROBES: [(u32, u32); 4] = [(20, 20), (40, 20), (60, 20), (80, 20)];

/// Recover the applied alpha from a rendered pixel.
///
/// The red channel IS the alpha (module docs). Returned as `u8` rather
/// than a float so the expected values in each test read as the ramp the
/// fixture was built from.
fn alpha_at(page: &RenderedPage, x: u32, y: u32) -> u8 {
    page.pixmap.pixel(x, y).expect("pixel in bounds").red()
}

/// The complete RGB triple at a probe, for the colour-key tests where the
/// base image is not uniformly red.
fn rgb_at(page: &RenderedPage, x: u32, y: u32) -> (u8, u8, u8) {
    let p = page.pixmap.pixel(x, y).expect("pixel in bounds");
    (p.red(), p.green(), p.blue())
}

/// Assert the four band alphas, naming the band that failed.
fn assert_alphas(page: &RenderedPage, expected: [u8; 4], what: &str) {
    for (i, (&(x, y), &want)) in PROBES.iter().zip(expected.iter()).enumerate() {
        let got = alpha_at(page, x, y);
        assert!(
            got.abs_diff(want) <= 2,
            "{what}: band {i} at device ({x}, {y}) has alpha {got}, expected {want} \
(the whole ramp was {expected:?})"
        );
        // The blue channel is the backdrop showing through, and it must
        // be the exact complement. Checking it catches a build that
        // wrote the right alpha into the texel but composited with the
        // wrong blend mode — the red channel alone cannot see that.
        let blue = page.pixmap.pixel(x, y).expect("pixel").blue();
        let want_blue = 255u8.saturating_sub(want);
        assert!(
            blue.abs_diff(want_blue) <= 2,
            "{what}: band {i} shows backdrop {blue}, expected {want_blue}"
        );
    }
}

// ---------------------------------------------------------------------------
// /SMask — the main event (§8.9.5 Table 89, §11.6.5.3)
// ---------------------------------------------------------------------------

#[test]
fn smask_alpha_is_applied_and_premultiplied() {
    // THE regression this Pass exists to prevent. Before it, this page
    // rendered as four bands of solid red — the file was right and the
    // preview lied about it, which `EditSession`'s
    // `transparency_not_previewed` disclosure existed to say out loud.
    let page = render("smask-ramp.pdf");
    assert_alphas(&page, [0, 85, 170, 255], "/SMask ramp");
    assert_eq!(page.diagnostics.images_masked, 1);
    assert_eq!(page.diagnostics.mask_applied.get("smask"), Some(&1));
    assert_eq!(page.diagnostics.images_mask_unsupported, 0);
    assert_eq!(
        page.diagnostics.masks_resampled, 0,
        "the mask matches the base image's dimensions"
    );
}

#[test]
fn smask_decode_one_zero_inverts_the_alpha() {
    // §8.9.5.2's inversion idiom applied to a soft mask: `Dmin > Dmax`
    // is the ONLY way PDF expresses "invert", there is no flag, and a
    // build that `min`/`max`-normalizes the pair — correct for a `/BBox`
    // (§7.9.5), catastrophic here — renders this identically to
    // `smask-ramp.pdf`. That identity is what this test forbids.
    let page = render("smask-decode.pdf");
    assert_alphas(&page, [255, 170, 85, 0], "/SMask with /Decode [1 0]");

    // Stated as a relation as well as as values, so the test still means
    // something if the fixture's ramp is ever changed.
    let plain = render("smask-ramp.pdf");
    for &(x, y) in &PROBES {
        let a = u16::from(alpha_at(&plain, x, y));
        let b = u16::from(alpha_at(&page, x, y));
        assert!(
            (a + b).abs_diff(255) <= 4,
            "inverted alpha at ({x}, {y}) must complement the plain one: {a} + {b}"
        );
    }
}

#[test]
fn a_smaller_smask_is_stretched_over_the_base() {
    // §8.9.6.3: "The base image and the image mask need not have the same
    // resolution … but since all images shall be defined on the unit
    // square in user space, their boundaries on the page will coincide."
    //
    // A 2×1 mask of [0, 255] over a 4×1 base: the left half vanishes, the
    // right half is opaque. A reader that indexed the mask with the
    // base's own x would read samples 2 and 3 past the end of a 2-sample
    // buffer and — under the read-past-the-end-is-zero rule — make the
    // right half vanish INSTEAD. That is a plausible-looking, entirely
    // wrong picture, which is why it gets its own fixture.
    let page = render("smask-small.pdf");
    assert_alphas(&page, [0, 0, 255, 255], "2x1 /SMask over a 4x1 base");
    assert_eq!(page.diagnostics.masks_resampled, 1);
    assert_eq!(page.diagnostics.images_masked, 1);
}

#[test]
fn a_larger_smask_is_point_sampled_at_texel_centres() {
    // The other direction, and the one that pins WHICH sample is taken.
    // The 8×1 mask is [9, 0, 9, 85, 9, 170, 9, 255]: the odd indices
    // carry the ramp and the even ones carry a decoy. Base texel i's
    // centre is at (i + ½)/4, which lands in mask sample 2i + 1 — the
    // ramp. A `floor(i × mw / bw)` mapping (no half-texel offset) would
    // take sample 2i instead and render all four bands at alpha 9.
    let page = render("smask-large.pdf");
    assert_alphas(&page, [0, 85, 170, 255], "8x1 /SMask over a 4x1 base");
    assert_eq!(page.diagnostics.masks_resampled, 1);
}

#[test]
fn a_sixteen_bit_smask_scales_to_the_same_alpha() {
    // Table 145 makes the mask's `/BitsPerComponent` "Required" and
    // imposes **no** value restriction, so Table 89's 1/2/4/8/16 all
    // apply. This is not a spec curiosity: pdfcer's own importer writes a
    // 16-bit `/SMask` for a colour-type-6 16-bit PNG, so it is the
    // operator's path for `rgba16.png`.
    //
    // The failure this forbids is reading 16-bit samples at 8 bits —
    // which unpacks two neighbours out of every sample, halves the
    // effective width, and produces an alpha ramp that is wrong
    // everywhere without ever looking obviously broken.
    let page = render("smask-16bit.pdf");
    assert_alphas(&page, [0, 85, 170, 255], "16-bit /SMask");
    assert_eq!(page.diagnostics.mask_applied.get("smask"), Some(&1));
}

#[test]
fn a_smask_reaches_the_indexed_palette_path_too() {
    // `decode_sampled`'s palette fast path is a separate arm from the
    // component path — it does a table lookup and no colour maths at all
    // — so "alpha is applied" has to be proved for it separately. This
    // is the shape a palette-`tRNS` PNG (`indexed-trns.png`) becomes: a
    // passed-through `/Indexed` base plus a decoded 8-bit `/SMask`.
    let page = render("smask-indexed.pdf");
    assert_alphas(&page, [0, 85, 170, 255], "/SMask over /Indexed");
    assert_eq!(page.diagnostics.mask_applied.get("smask"), Some(&1));
    assert_eq!(page.diagnostics.images_mask_unsupported, 0);
}

#[test]
fn matte_preblending_is_undone_before_the_colour_conversion() {
    // §11.6.5.3, the inverse of the normative `c′ = m + α × (c − m)`:
    //
    //     c = m + (c′ − m) / α
    //
    // The fixture stores a WHITE-matte preblend of pure red, so the
    // stored strip ramps white → red as alpha rises, and undoing it must
    // recover pure red at every sample. (A black matte would make the
    // preblend identical to tiny-skia's own premultiplied storage and the
    // test would pass without the code — see the fixture's own comment.)
    //
    // Two independent assertions, and the second is the load-bearing one:
    //
    // - the ALPHA ramp is unchanged, proving the mask still works;
    // - the GREEN channel is ~0, proving the preblend was removed. If it
    //   were not, band 1 would render (85, 57, 227) instead of
    //   (85, 0, 170) — the white matte still mixed into the colour.
    let page = render("smask-matte.pdf");
    assert_alphas(&page, [0, 85, 170, 255], "/SMask with /Matte");
    assert_eq!(page.diagnostics.mattes_undone, 1);
    assert_eq!(page.diagnostics.mattes_not_undone, 0);
    for (i, &(x, y)) in PROBES.iter().enumerate().skip(1) {
        let (_, g, _) = rgb_at(&page, x, y);
        assert!(
            g <= 2,
            "band {i}: green {g} — the white matte is still mixed into the colour, \
so the preblend was not undone (it would be ~57 at band 1)"
        );
    }
    assert_eq!(page.diagnostics.images_masked, 1);
}

#[test]
fn a_dimension_mismatched_matte_is_dropped_by_name_and_the_alpha_still_applies() {
    // Table 145's `Width` row: "If a `Matte` entry … is present, shall be
    // the same as the `Width` value of the parent image; otherwise
    // independent of it." A mismatch means the file is wrong about one of
    // the two, and un-premultiplying with a RESAMPLED α divides each
    // sample by an alpha that is not its own — recovering colours from
    // the wrong equation, confidently.
    //
    // So the alpha is honoured (that half is conformant either way) and
    // the colour correction is dropped BY NAME. `fuzzy, never sneaky`:
    // the operator is told the colours are shifted rather than left to
    // discover it.
    let page = render("smask-matte-mismatch.pdf");
    assert_eq!(page.diagnostics.mattes_undone, 0);
    assert_eq!(page.diagnostics.mattes_not_undone, 1);
    assert!(
        page.diagnostics
            .image_notes
            .iter()
            .any(|n| n.contains("matte/dimension-mismatch")),
        "the reason must be visible in the notes, not only in a counter: {:?}",
        page.diagnostics.image_notes
    );
    // The 2×1 mask of [0, 255] still stretches over the base, so the
    // left half vanishes and the right half is opaque.
    //
    // `assert_alphas` is deliberately NOT used here: it also asserts that
    // the backdrop shows through at exactly `255 − α`, which holds only
    // when the base image is uniformly pure red. This fixture's base is
    // the white-matte PREBLEND, so band 2 is stored as (255, 85, 85) and
    // its blue channel is 85 rather than 0. That residue is the point of
    // the test, not an error — it is precisely the colour shift that the
    // dropped inversion leaves behind, and asserting it is what proves
    // the inversion really was dropped rather than quietly applied with a
    // resampled α.
    let reds: Vec<u8> = PROBES.iter().map(|&(x, y)| alpha_at(&page, x, y)).collect();
    assert_eq!(reds, vec![0, 0, 255, 255], "the stretched mask's alpha");
    let (_, g, _) = rgb_at(&page, PROBES[2].0, PROBES[2].1);
    assert!(
        g.abs_diff(85) <= 2,
        "band 2 must still carry the un-inverted white-matte residue (~85), got {g}"
    );
    assert_eq!(page.diagnostics.masks_resampled, 1);
    assert_eq!(page.diagnostics.images_masked, 1);
}

#[test]
fn a_three_component_smask_is_refused_rather_than_guessed_at() {
    // There is no sourced rule for reducing three components to one
    // alpha. Luminance? The red channel? The maximum? Each is defensible
    // and each is an invention, and an invented alpha is exactly the
    // "plausible-looking, entirely wrong" outcome the honesty contract
    // forbids. So: base image opaque, refusal named and counted.
    let page = render("smask-rgb-refused.pdf");
    assert_alphas(&page, [255, 255, 255, 255], "refused /SMask draws opaque");
    assert_eq!(page.diagnostics.images_masked, 0);
    assert_eq!(page.diagnostics.images_mask_unsupported, 1);
    assert_eq!(
        page.diagnostics.mask_refused.get("mask/colour-space"),
        Some(&1),
        "the reason must be counted BY NAME (R27): {:?}",
        page.diagnostics.mask_refused
    );
    // Still a rendered image — a refused mask is a fidelity shortfall,
    // not a reason to drop the picture.
    assert_eq!(page.diagnostics.images_rendered, 1);
    assert_eq!(page.diagnostics.images_unsupported, 0);
}

// ---------------------------------------------------------------------------
// /Mask as a stencil (§8.9.6.3)
// ---------------------------------------------------------------------------

#[test]
fn stencil_mask_polarity_zero_shows_the_base_image() {
    // §8.9.6.2, verbatim: "If the `Decode` array is `[ 0 1 ]` (the default
    // for an image mask), a sample value of 0 shall mark the page with the
    // current colour, and a 1 shall leave the previous contents
    // unchanged." Composed with §8.9.6.3's "unmasked areas paint from the
    // base image", 0 SHOWS and 1 HIDES.
    //
    // Note that this is the opposite of the "1 means set" bitmap
    // intuition, which is precisely why it needs a fixture rather than a
    // code comment. The stencil's samples are 0, 1, 0, 1.
    let page = render("stencil-mask.pdf");
    assert_alphas(&page, [255, 0, 255, 0], "/Mask stencil, default /Decode");
    assert_eq!(page.diagnostics.mask_applied.get("stencil"), Some(&1));
}

#[test]
fn stencil_mask_decode_one_zero_reverses_the_polarity() {
    // "If the `Decode` array is `[ 1 0 ]`, these meanings shall be
    // reversed." Rendering this identically to `stencil-mask.pdf` is the
    // silent-inversion bug: the mask would hide exactly the half it was
    // meant to reveal, and the result looks deliberate rather than
    // broken.
    let page = render("stencil-mask-decode.pdf");
    assert_alphas(&page, [0, 255, 0, 255], "/Mask stencil, /Decode [1 0]");

    let plain = render("stencil-mask.pdf");
    for &(x, y) in &PROBES {
        assert_ne!(
            alpha_at(&plain, x, y),
            alpha_at(&page, x, y),
            "the two polarities must differ at every band"
        );
    }
}

// ---------------------------------------------------------------------------
// /Mask as a colour-key array (§8.9.6.4)
// ---------------------------------------------------------------------------

#[test]
fn colour_key_masking_removes_a_colour_not_a_position() {
    // §8.9.6.4: "An image sample shall be masked (not painted) if all of
    // its colour components BEFORE DECODING fall within the specified
    // ranges." The base strip is red, green, red, blue and the ranges are
    // `[255 255  0 0  0 0]` — pure red. Both red bands vanish; the green
    // and blue ones survive with their own colours, over the blue
    // backdrop.
    //
    // This is the mechanism a single-transparent-colour PNG (`tRNS` on a
    // truecolour image) becomes on the way into a PDF, so it is directly
    // on the operator's path.
    let page = render("colour-key.pdf");
    assert_eq!(
        page.diagnostics.mask_applied.get("colour-key"),
        Some(&1),
        "the mechanism must be counted"
    );
    // Bands 0 and 2 are masked: pure blue backdrop shows through.
    for &(x, y) in &[PROBES[0], PROBES[2]] {
        let (r, g, b) = rgb_at(&page, x, y);
        assert!(
            r <= 2 && g <= 2 && b >= 253,
            "a masked red band must show the backdrop, got ({r}, {g}, {b})"
        );
    }
    // Band 1 is green and survives; band 3 is blue-on-blue and is
    // indistinguishable from the backdrop, which is fine — it proves it
    // was NOT masked only in combination with band 1.
    let (r, g, b) = rgb_at(&page, PROBES[1].0, PROBES[1].1);
    assert!(
        r <= 2 && g >= 253 && b <= 2,
        "the green band must be painted, got ({r}, {g}, {b})"
    );
}

#[test]
fn colour_key_over_indexed_counts_the_index_as_one_component() {
    // The inference `iso32000__s__8.9.5.2.md` flags: for an `Indexed`
    // image, "the number of colour components in the image's colour
    // space" is 1 — the INDEX — not the base space's 3, because the
    // image's colour space IS the `Indexed` space. So `/Mask [0 0]` is a
    // well-formed two-integer array masking palette entry 0.
    //
    // A reader that used the base space's component count would see a
    // 2-element array where it expected 6, call it malformed, and mask
    // nothing — rendering a fully opaque strip. This test is what tells
    // those two apart.
    let page = render("colour-key-indexed.pdf");
    assert_eq!(page.diagnostics.mask_applied.get("colour-key"), Some(&1));
    assert_eq!(
        page.diagnostics.images_mask_unsupported, 0,
        "a 2-integer array over an /Indexed image is CORRECT, not malformed: {:?}",
        page.diagnostics.mask_refused
    );
    // Palette indices are 0, 1, 0, 2 (red, green, red, blue) and index 0
    // is masked.
    for &(x, y) in &[PROBES[0], PROBES[2]] {
        let (r, g, b) = rgb_at(&page, x, y);
        assert!(
            r <= 2 && g <= 2 && b >= 253,
            "masked palette entry 0 must show the backdrop, got ({r}, {g}, {b})"
        );
    }
    let (r, g, b) = rgb_at(&page, PROBES[1].0, PROBES[1].1);
    assert!(
        r <= 2 && g >= 253 && b <= 2,
        "palette entry 1 (green) must be painted, got ({r}, {g}, {b})"
    );
}

// ---------------------------------------------------------------------------
// The suite's own guard
// ---------------------------------------------------------------------------

#[test]
fn the_backdrop_is_actually_visible_where_alpha_is_zero() {
    // A meta-test on the fixture design. If the backdrop rectangle ever
    // stopped painting — a content-stream regression, a clip bug — every
    // test above would still pass on a white page for the fully
    // transparent band (red 0 either way) while silently losing its
    // discriminating power everywhere else. Pinning the backdrop
    // explicitly keeps that failure loud.
    let page = render("smask-ramp.pdf");
    let (r, g, b) = rgb_at(&page, PROBES[0].0, PROBES[0].1);
    assert!(
        r <= 2 && g <= 2 && b >= 253,
        "the fully transparent band must show PURE BLUE, not white — the whole \
suite's discriminating power depends on it. Got ({r}, {g}, {b})"
    );
    // And a point outside the image but inside the backdrop rectangle.
    let (r, g, b) = rgb_at(&page, 12, 20);
    assert!(
        b >= 253 && r <= 2 && g <= 2,
        "the backdrop rectangle itself must be blue, got ({r}, {g}, {b})"
    );
}
