#!/usr/bin/env python3
"""Every non-Cargo file pdfcer REDISTRIBUTES must have its licence recorded.

WHY THIS GATE EXISTS
====================

`THIRD_PARTY_LICENSES.md` is generated by `cargo-about` from `Cargo.lock`. It
is complete and correct for what it covers, and it is **structurally
incapable** of covering anything that is not a Cargo dependency. Fonts, icons,
and — imminently — OCR model weights are files pdfcer ships inside its portable
folder, so they are redistributed by pdfcer and carry whatever obligations
their licences impose. `cargo-about` cannot see any of them.

That is not a flaw in `cargo-about`; it is a gap between two tools, and a gap
between tools is exactly where an obligation goes missing without anyone
deciding to drop it. This project has already recorded the same shape twice:
a RAG deliverable that was filed but never handed off, and a formatting rule
that applied to crates no command could reach.

The convention already existed — both shipped asset directories carry a
`PROVENANCE.md` recording where the files came from and under what terms.
Nothing enforced it, so the next asset directory could simply not have one and
nothing would say so.

WHAT IT CHECKS
==============

For every directory under `crates/*/assets/` that contains at least one
shipped (non-documentation) file:

1. A `PROVENANCE.md` exists.
2. That file NAMES A LICENCE — it must contain a recognisable licence
   identifier or an explicit statement of terms. A provenance note that says
   where files came from but not what may be done with them does not discharge
   anything.
3. Every shipped file in the directory is accounted for: the count in the
   directory must not exceed what `PROVENANCE.md` mentions, unless the file
   explicitly states it covers the whole directory.
4. ★ The directory is cited in **`about.hbs`**, the `cargo-about` template.

Check 4 is the one that reaches the OPERATOR rather than the repository.
`PROVENANCE.md` records terms for whoever reads the source tree; it does NOT
ship. The portable package carries `LICENSE`, `THIRD_PARTY_LICENSES.md` and
`README.md` and nothing else — so an asset whose licence is recorded only in
`PROVENANCE.md` is redistributed to end users with no notice attached at all.

`about.hbs` is where that is fixed: it is the handlebars template
`cargo-about` renders, so a hand-written section in it flows into the
generated `THIRD_PARTY_LICENSES.md` and therefore into every release. The
bundled Foxit faces already do this correctly, and that section is the
worked example to copy.

**Own work is exempt.** An asset whose `PROVENANCE.md` says it is pdfcer's own
art under the project licence needs no `about.hbs` entry — the shipped
`LICENSE` already covers it and there is no third-party grant to reproduce.
The GUI icon set is exactly this case, and check 4 flagged it on its first run
before the exemption existed. That was a false positive, and a gate that fires
on a correct state is one people learn to ignore.

Check 3 is deliberately loose — the goal is to catch a directory that quietly
gained twenty model files under a provenance note describing three fonts, not
to demand a table row per icon.

WHY NOT JUST TRUST A REVIEWER
=============================

Because the failure is silent and delayed. A model file added today ships in
every release from now on; the moment anyone notices is after distribution,
and un-distributing is not a thing. A gate costs one CI second.

EXIT CODES
==========

0 — every shipped asset directory records its licensing.
1 — at least one does not. The offending directory is named, with what is
    missing and what to do about it.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Files that are documentation ABOUT the assets rather than shipped assets.
_DOC_SUFFIXES = {".md", ".txt"}

# Recognisable licence identifiers, plus the phrasings this project's existing
# provenance notes actually use. Matched case-insensitively.
#
# Deliberately broad: the check is "did somebody state the terms", not "did
# they pick from an approved list". A bespoke grant ("the operator drew these
# himself and places them under the project licence") is a real answer and
# must pass, which is why the operator/own-work phrasings are here alongside
# the SPDX ids.
_LICENCE_SIGNALS = [
    r"\bMIT\b",
    r"\bApache[- ]2\.0\b",
    r"\bBSD-[23]-Clause\b",
    r"\bCC-BY(-SA)?-\d",
    r"\bCC0\b",
    r"\bSIL\b|\bOFL\b",
    r"\bZlib\b",
    r"\bUnlicense\b",
    r"\bpublic domain\b",
    r"\blicen[cs]e\b.{0,40}\b(grant|terms|is|are)\b",
    r"\bdrawn from scratch\b",
    r"\boriginal work\b",
    r"\bproject licen[cs]e\b",
]
_LICENCE_RE = re.compile("|".join(_LICENCE_SIGNALS), re.IGNORECASE)

#: The cargo-about template. A hand-written section here is the ONLY route by
#: which a non-Cargo asset's licence reaches the shipped
#: `THIRD_PARTY_LICENSES.md`, and therefore the only route by which it reaches
#: anyone who was given a binary rather than the source.
_ABOUT_TEMPLATE = "about.hbs"

# A provenance note may declare that it covers everything beside it, which
# exempts it from the per-file accounting in check 3.
_COVERS_ALL_RE = re.compile(
    r"covers (every|all) (file|asset)|all files in this (directory|folder)",
    re.IGNORECASE,
)

#: Provenance phrasings meaning "this is OUR work, under pdfcer's own licence".
#:
#: Such assets need no entry in `about.hbs`, because the `LICENSE` file that
#: already ships with every release covers them — there is no third-party
#: grant to reproduce. Check 4 exempts them.
#:
#: Added after the first run of check 4 flagged the GUI icon set, which the
#: operator confirmed on 2026-08-02 is his own art carried over from another of
#: his projects. That flag was a FALSE POSITIVE, and a gate that cries wolf on
#: a correct state is one people learn to skip — which would have cost more
#: than the check is worth.
_OWN_WORK_RE = re.compile(
    r"operator's own work|own art|drawn from scratch|no third-party licen[cs]e"
    r"|project licen[cs]e|covered by pdfcer's",
    re.IGNORECASE,
)


def _shipped_files(directory: Path) -> list[Path]:
    """Files in `directory` that are shipped rather than documentation."""
    return [
        p
        for p in sorted(directory.iterdir())
        if p.is_file() and p.suffix.lower() not in _DOC_SUFFIXES
    ]


def main() -> int:
    asset_dirs: list[Path] = []
    crates = ROOT / "crates"
    if crates.is_dir():
        for crate in sorted(crates.iterdir()):
            assets = crate / "assets"
            if not assets.is_dir():
                continue
            for sub in sorted(assets.rglob("*")):
                if sub.is_dir() and _shipped_files(sub):
                    asset_dirs.append(sub)
            if _shipped_files(assets):
                asset_dirs.append(assets)

    if not asset_dirs:
        print("shipped-assets: no shipped asset directories found.")
        return 0

    about_path = ROOT / _ABOUT_TEMPLATE
    about = (
        about_path.read_text(encoding="utf-8", errors="replace")
        if about_path.is_file()
        else ""
    )
    if not about:
        print(
            f"shipped-assets: WARNING — {_ABOUT_TEMPLATE} not found; cannot verify that "
            "asset licences reach the shipped attribution file."
        )

    problems: list[str] = []
    for directory in asset_dirs:
        rel = directory.relative_to(ROOT).as_posix()
        files = _shipped_files(directory)
        prov = directory / "PROVENANCE.md"

        if not prov.is_file():
            problems.append(
                f"  {rel}\n"
                f"      {len(files)} shipped file(s), NO PROVENANCE.md.\n"
                f"      cargo-about cannot see these — if pdfcer redistributes them,\n"
                f"      their licensing exists nowhere. Add PROVENANCE.md recording\n"
                f"      where they came from and under what terms."
            )
            continue

        text = prov.read_text(encoding="utf-8", errors="replace")
        if not _LICENCE_RE.search(text):
            problems.append(
                f"  {rel}/PROVENANCE.md\n"
                f"      Records provenance but NAMES NO LICENCE. Saying where a file\n"
                f"      came from does not say what may be done with it, and pdfcer\n"
                f"      ships these to other people."
            )
            continue

        if not _COVERS_ALL_RE.search(text):
            # Loose accounting: at least one shipped filename (or its stem)
            # should appear. Catches a directory that gained a whole new class
            # of asset under a note describing the old ones.
            named = sum(1 for f in files if f.name in text or f.stem in text)
            if named == 0:
                problems.append(
                    f"  {rel}/PROVENANCE.md\n"
                    f"      Names a licence but mentions NONE of the {len(files)} file(s)\n"
                    f"      actually in this directory. Either the files changed and the\n"
                    f"      note did not, or the note covers something else."
                )

        # ★ Check 4 — does the licence reach the people who get a BINARY?
        #
        # PROVENANCE.md does not ship. The portable package carries LICENSE,
        # THIRD_PARTY_LICENSES.md and README.md and nothing else, so an asset
        # documented only in the source tree is redistributed with no notice
        # attached to it at all.
        #
        # about.hbs is the cargo-about TEMPLATE, so a hand-written section in
        # it renders into the generated THIRD_PARTY_LICENSES.md and therefore
        # into every release. Citing the directory path is the convention the
        # bundled Foxit faces already follow.
        if about and rel not in about and not _OWN_WORK_RE.search(text):
            problems.append(
                f"  {rel}\n"
                f"      Has a PROVENANCE.md, but {_ABOUT_TEMPLATE} never cites this\n"
                f"      directory — so its licence does NOT reach the generated\n"
                f"      THIRD_PARTY_LICENSES.md, and therefore never reaches anyone\n"
                f"      who was given a binary rather than the source.\n"
                f"      PROVENANCE.md is for readers of the repository;\n"
                f"      {_ABOUT_TEMPLATE} is for the people you ship to.\n"
                f"      Copy the 'Bundled Foxit substitute faces' section as a model."
            )

    if problems:
        print("shipped-assets: redistributed files with no recorded licensing.\n")
        print("\n".join(problems))
        print(
            "\n  THIRD_PARTY_LICENSES.md is generated by cargo-about from Cargo.lock\n"
            "  and CANNOT cover non-Cargo files. This gate is the only thing that\n"
            "  does. See docs/LEGAL.md §6."
        )
        return 1

    total = sum(len(_shipped_files(d)) for d in asset_dirs)
    print(
        f"shipped-assets: clean — {len(asset_dirs)} asset directory(ies), "
        f"{total} redistributed file(s), all with recorded licensing."
    )
    return 0


if __name__ == "__main__":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except AttributeError:
        pass
    sys.exit(main())
