#!/usr/bin/env python3
"""check-tests-harnessed.py -- every integration-test file is in its crate's one test binary.

Each crate with a ``tests/`` directory sets ``autotests = false`` and builds a
single ``[[test]] name = "all"`` from ``tests/all.rs``, which declares every
other ``tests/*.rs`` as a module. One binary per crate instead of one per file
is what keeps ``cargo test --workspace`` inside this machine's memory: each
binary statically links ``pdfcer-core``.

The cost of ``autotests = false`` is that a new ``tests/foo.rs`` not declared
in ``all.rs`` is never compiled and never run, and nothing goes red. This gate
is that red.

Usage:  python tools/check-tests-harnessed.py [--write]
        --write regenerates every ``tests/all.rs`` from the files on disk.
Exit:   0 every file harnessed (or written), 1 a file is missing or a crate
        is not set up for the single binary.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HARNESS = "all.rs"
HEADER = (
    "//! The crate's one integration-test binary: every other `tests/*.rs` is a\n"
    "//! module here. Generated by `python tools/check-tests-harnessed.py --write`;\n"
    "//! the gate fails when a test file is missing from this list.\n\n"
)


def crates() -> list[Path]:
    return sorted(p.parent for p in (ROOT / "crates").glob("*/tests") if p.is_dir())


def expected(crate: Path) -> str:
    names = sorted(
        p.stem for p in (crate / "tests").glob("*.rs") if p.name != HARNESS
    )
    return HEADER + "".join(f"mod {n};\n" for n in names)


def manifest_ok(crate: Path) -> list[str]:
    text = (crate / "Cargo.toml").read_text(encoding="utf-8")
    problems = []
    if not re.search(r"^autotests\s*=\s*false\s*$", text, re.M):
        problems.append("Cargo.toml lacks `autotests = false` in [package]")
    if not re.search(
        r'^\[\[test\]\]\s*\nname\s*=\s*"all"\s*\npath\s*=\s*"tests/all\.rs"', text, re.M
    ):
        problems.append('Cargo.toml lacks [[test]] name = "all", path = "tests/all.rs"')
    return problems


def main() -> int:
    write = "--write" in sys.argv[1:]
    bad = 0
    for crate in crates():
        harness = crate / "tests" / HARNESS
        want = expected(crate)
        rel = harness.relative_to(ROOT).as_posix()
        if write:
            harness.write_text(want, encoding="utf-8", newline="\n")
        elif not harness.exists() or harness.read_text(encoding="utf-8") != want:
            print(f"tests-harnessed: {rel} does not declare exactly the crate's test files")
            bad += 1
        for p in manifest_ok(crate):
            print(f"tests-harnessed: {crate.name}: {p}")
            bad += 1
    if bad:
        print(
            "  A test file that is not a module of tests/all.rs is never compiled or run.\n"
            "  Fix: python tools/check-tests-harnessed.py --write"
        )
        return 1
    print(f"tests-harnessed: clean -- {len(crates())} crate(s), one test binary each")
    return 0


if __name__ == "__main__":
    sys.exit(main())
