#!/usr/bin/env python3
"""Regenerate fixtures/synthetic/transparency/ — non-isolated groups on a
subtractive (DeviceCMYK) page.

WHY THIS EXISTS
---------------
`Pass 97.1g` gave a **non-isolated ordinary** transparency group on a
DeviceCMYK page its second content walk (ISO 32000-1 §11.4.4): the group's
contents are rendered once over a transparent backdrop to obtain `α_gn`,
once over the group's own initial backdrop to obtain its colour, and the
backdrop is then removed from the second so §11.4.3's *"the backdrop's
contribution … shall be applied only once"* holds.

The print-conformance suite — this project's usual transparency oracle —
**does not exercise it.** Measured, not assumed: rendering all 51 patches
with a binary built before `97.1g` and one built after gives **zero
differing pixels**, on any patch, at any scale tested. Thirteen second
walks do occur, but every one of them is an *over-trigger* of the
deliberately-conservative `backdrop_dependent` test in `interpret.rs` (a
nested isolated child's own interior blending counts toward the outer
group's dependence), and where the interior does not truly read its
backdrop the isolated and non-isolated results are identical by §11.4.4
NOTE 2. The suite's blend-mode patches put their `/BM` in the graphics
state *around* the `Do`, which the group's own composite already honoured.

★ SO WITHOUT THIS FIXTURE THE PASS HAS NO END-TO-END EVIDENCE AT ALL, and a
correct implementation that nothing reaches is indistinguishable from dead
code. The unit tests in `cmyk_buffer.rs` prove the arithmetic; only a real
PDF proves the arithmetic is wired to a content stream.

WHAT THE FIXTURES ARE
---------------------
Four single-page PDFs, identical except for one flag, so a diff between
any two isolates exactly one variable:

| file | group `/I` | interior `/BM` | what it proves |
|---|---|---|---|
| `nonisolated_multiply_cmyk.pdf` | **false** | `Multiply` | the two-walk path: the interior blends against the page backdrop |
| `isolated_multiply_cmyk.pdf` | **true** | `Multiply` | the one-walk path: the same interior blends against nothing |
| `nonisolated_normal_cmyk.pdf` | false | `Normal` | §11.4.4 NOTE 2's exactness: must render identically to the row below |
| `isolated_normal_cmyk.pdf` | true | `Normal` | the partner that makes that identity checkable rather than asserted |

Each page paints a cyan backdrop rectangle in `DeviceCMYK`, then invokes a
Form XObject carrying its own `/Group` dictionary, **through an outer
`/ca 0.5`**. The form paints a magenta rectangle overlapping the backdrop.

★ The `0.5` is load-bearing and is not a stylistic choice — see the comment
at `gso` below. With a neutral outer state a non-isolated group is painted
inline and needs no buffer, which is already correct, so the fixture would
render identically before and after `97.1g` and prove nothing.

The expected relationship, and it is what makes these a test rather than
three pictures:

- `nonisolated_multiply` differs from `isolated_multiply` **inside the
  overlap only**. `Multiply` against a transparent backdrop is the identity
  (§11.3.5: the group's initial backdrop is fully transparent, so the blend
  degenerates), while `Multiply` against cyan darkens.
- `nonisolated_normal` is **byte-identical** to an isolated equivalent,
  because a `Normal` interior does not read its backdrop and §11.4.4's
  removal exactly cancels the seeding.

WHY DeviceCMYK AND NOT DeviceRGB
--------------------------------
Because the additive path has had this walk since before `Pass 97.1`; the
gap `97.1g` closes is specific to a page that carries a **colorant buffer**
(`crates/pdfcer-render/src/cmyk_buffer.rs`). The page group's `/CS` is
`/DeviceCMYK` for exactly that reason — drop it and the page renders
through `Canvas::Paint`, which was already correct, and the fixture stops
testing anything.

PROVENANCE
----------
Authored here, byte by byte, from ISO 32000-1's own object syntax. No
third-party PDF is copied, adapted or consulted (`docs/LEGAL.md` §5). The
files are small enough to read in a text editor, deliberately, so a future
session can check what they claim without running anything.

This script is NOT part of the build and is not a workspace member, so it
never enters the dependency graph or `THIRD_PARTY_LICENSES.md`.

USAGE
-----
    python tools/gen-nonisolated-group-fixtures.py
"""

from __future__ import annotations

import pathlib

OUT = pathlib.Path(__file__).resolve().parent.parent / "fixtures" / "synthetic" / "transparency"


def build(isolated: bool, inner_blend: str) -> bytes:
    """Assemble one single-page PDF with cross-reference table and all.

    The writer is hand-rolled rather than delegated to `pdfcer` on
    purpose: a fixture generated by the program under test cannot falsify
    that program. Offsets are accumulated as the objects are emitted, which
    is the only part of this function with any way to go wrong, so the xref
    is built from the same list the body is.
    """
    # The form's own transparency group. `/I` is the variable under test;
    # `/K` is left absent (default false) so knockout is not in play --
    # §11.4.6 is a different clause with a different code path
    # (`knockout_group_cmyk`), and mixing them would make a difference
    # ambiguous between two features.
    group = (
        b"<< /S /Transparency /CS /DeviceCMYK /I "
        + (b"true" if isolated else b"false")
        + b" >>"
    )

    # The form's content: set the interior blend mode, then paint magenta
    # over the region the page backdrop already covers. `re f` rather than a
    # path with curves keeps the rasterised shape exactly predictable, so a
    # pixel diff between two variants can only come from colour.
    form_stream = (
        b"/GSI gs\n"
        b"0 1 0 0 k\n"
        b"20 20 60 60 re f\n"
    )

    objects: list[bytes] = []

    def add(body: bytes) -> int:
        objects.append(body)
        return len(objects)

    # 1 catalog, 2 pages, 3 page, 4 page content, 5 form, 6 resources of
    # form, 7 outer ExtGState, 8 inner ExtGState. Written in dependency
    # order so no forward reference is guessed.
    catalog = add(b"<< /Type /Catalog /Pages 2 0 R >>")
    pages = add(b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>")

    page_content = (
        # The page backdrop: cyan, DeviceCMYK, opaque. This is the `C_0`
        # the non-isolated group is entitled to see and the isolated one is
        # not.
        b"1 0 0 0 k\n"
        b"10 10 60 60 re f\n"
        # The group invocation. The OUTER blend stays Normal so that any
        # difference between variants is attributable to the interior.
        b"/GSO gs\n"
        b"/Fm0 Do\n"
    )

    page = add(
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 100 100] "
        b"/Group << /S /Transparency /CS /DeviceCMYK /I true >> "
        b"/Resources << /XObject << /Fm0 5 0 R >> "
        b"/ExtGState << /GSO 6 0 R >> >> "
        b"/Contents 4 0 R >>"
    )
    content = add(
        b"<< /Length " + str(len(page_content)).encode() + b" >>\nstream\n"
        + page_content
        + b"endstream"
    )
    form = add(
        b"<< /Type /XObject /Subtype /Form /BBox [0 0 100 100] "
        b"/Group " + group + b" "
        b"/Resources << /ExtGState << /GSI 7 0 R >> >> "
        b"/Length " + str(len(form_stream)).encode() + b" >>\nstream\n"
        + form_stream
        + b"endstream"
    )
    # ★★ `/ca 0.5`, AND THE 0.5 IS THE ENTIRE REASON THIS FIXTURE WORKS.
    #
    # `interpret.rs` computes
    # `needs_buffer = is_transparency_group && (!outer_is_neutral || isolated
    # || knockout)`. A NON-isolated group under a neutral outer state (BM
    # Normal, ca = CA = 1, no soft mask) is therefore painted INLINE, with no
    # buffer at all -- and painting it inline is not an approximation of
    # non-isolated semantics, it IS non-isolated semantics: the interior
    # blends against the real page, which is exactly what §11.4.4 asks for.
    #
    # So the gap `Pass 97.1g` closes exists only where a buffer is FORCED.
    # Buffering a non-isolated group is what turns it into an isolated one
    # (`docs/compositor-plan.md`: *"Buffering ... makes a NON-isolated group
    # into an isolated one"*), and the second content walk is what turns it
    # back. Written with `/ca 1` this fixture rendered identically before and
    # after the Pass, correctly, and proved nothing.
    #
    # `/BM` stays `Normal` so the only blending in the file is the
    # interior's, and any difference between the three variants is
    # attributable to that and nothing else.
    gso = add(b"<< /Type /ExtGState /BM /Normal /ca 0.5 /CA 0.5 >>")
    gsi = add(b"<< /Type /ExtGState /BM /" + inner_blend.encode() + b" /ca 1 /CA 1 >>")

    # ★ THIS ASSERT CHECKS THE LITERALS, NOT JUST THE COUNTER, AND THE
    # DIFFERENCE COST A DIAGNOSTIC CYCLE.
    #
    # It first read `== (1, 2, 3, 4, 5, 6, 7)` -- which is what `add()`
    # returns and therefore cannot fail -- while the dictionaries above
    # spelled `/GSO 7 0 R` and `/GSI 8 0 R`. Both were off by one, so the
    # OUTER graphics state picked up the interior's `Multiply` and the
    # INTERIOR reference dangled. The fixture rendered, reported
    # `blend_modes_applied=1`, and looked entirely plausible; it simply
    # tested the opposite of what it claimed.
    #
    # A vacuous assertion beside a wrong literal is worse than no
    # assertion, because it reads as verification (`R162`). So the check is
    # now against the reference text that is actually emitted.
    refs = {b"/Fm0 " + str(form).encode() + b" 0 R",
            b"/GSO " + str(gso).encode() + b" 0 R",
            b"/GSI " + str(gsi).encode() + b" 0 R"}
    body = b"".join(objects)
    for r in refs:
        assert body.count(r) == 1, (
            f"reference {r!r} is not in the emitted objects exactly once -- "
            "an object number and the literal that points at it have drifted "
            "apart, which renders as a plausible wrong picture rather than an "
            "error"
        )
    assert (catalog, pages, page, content) == (1, 2, 3, 4)

    out = bytearray(b"%PDF-1.7\n%\xe2\xe3\xcf\xd3\n")
    offsets = [0]
    for i, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += str(i).encode() + b" 0 obj\n" + body + b"\nendobj\n"

    startxref = len(out)
    n = len(objects) + 1
    out += b"xref\n0 " + str(n).encode() + b"\n"
    out += b"0000000000 65535 f \n"
    for off in offsets[1:]:
        out += f"{off:010d} 00000 n \n".encode()
    out += (
        b"trailer\n<< /Size " + str(n).encode() + b" /Root 1 0 R >>\n"
        b"startxref\n" + str(startxref).encode() + b"\n%%EOF\n"
    )
    return bytes(out)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    written = {
        "nonisolated_multiply_cmyk.pdf": build(isolated=False, inner_blend="Multiply"),
        "isolated_multiply_cmyk.pdf": build(isolated=True, inner_blend="Multiply"),
        "nonisolated_normal_cmyk.pdf": build(isolated=False, inner_blend="Normal"),
        # The comparison partner for the row above. §11.4.4 NOTE 2's
        # exactness is a claim that these two files render IDENTICALLY, and
        # a claim needs both halves on disk to be checkable -- asserting it
        # against a remembered number would be the wrong-oracle shape
        # (`R215`).
        "isolated_normal_cmyk.pdf": build(isolated=True, inner_blend="Normal"),
    }
    for name, data in written.items():
        (OUT / name).write_bytes(data)
        print(f"wrote {OUT / name}  ({len(data)} bytes)")


if __name__ == "__main__":
    main()
