#!/usr/bin/env python3
"""Regenerate fixtures/synthetic/mesh/ - shading types 4, 5, 6 and 7.

WHY THIS EXISTS
---------------
`Pass 125.0` decodes and rasterises the four **mesh** shading types
(ISO 32000-1 8.7.4.5.5-.8). The only mesh shadings this project has access
to are **two type 7 patches in one licensed print-conformance patch**, which
is not redistributable (`docs/LEGAL.md` §5) and covers exactly one of the
four types, one edge-flag value, one bit-width combination, and neither the
`/Function` form nor any refusal path.

So without these fixtures the Pass would ship with `cargo test` proving the
arithmetic in `mesh.rs`'s unit tests and **nothing proving the arithmetic is
wired to a content stream** for three of the four types. That is the gap
`tools/gen-nonisolated-group-fixtures.py`'s header names for its own Pass,
and it is the same gap here.

THE ORACLE PROBLEM, AND HOW THESE FIXTURES SOLVE IT WITHOUT A REFERENCE
----------------------------------------------------------------------
A rendered gradient has no obvious right answer to assert against, and a
screenshot committed as "known good" only pins whatever the code did on the
day it was taken. These fixtures avoid that by being built in **equivalence
pairs**: two files that the STANDARD says must render identically, by
different code paths. A pair disagreeing is a defect no matter which of the
two is wrong, and neither file has to be blessed by anybody.

| pair | why they must agree | which clause |
|---|---|---|
| `type6_coons.pdf` / `type7_tensor.pdf` | a Coons patch IS a tensor patch whose four internal points are derived from its boundary; the type 7 file carries those four points EXPLICITLY, computed here by the spec's own equations | 8.7.4.5.8, `MSH30` |
| `type4_triangles.pdf` / `type5_lattice.pdf` | the type 4 edge-flag sequence `0,0,0,1` produces exactly the triangle pair a 2x2 type 5 lattice produces | `MSH16`-`MSH19` vs `MSH22` |

Everything else is asserted against a value that is fixed by arithmetic
rather than by taste: a corner pixel must be the corner colour, because
every one of these surfaces interpolates its corners exactly.

THE FILES
---------
| file | what it is | what only it can catch |
|---|---|---|
| `type4_triangles.pdf` | two triangles, edge flags `0,0,0,1` | the flag state machine's relabelling |
| `type5_lattice.pdf` | a 2x2 lattice, no flag field at all | a parser that leaves `BitsPerFlag` in the record |
| `type6_coons.pdf` | one Coons patch, 12 control points | the boundary-curve order, and the corner-colour walk |
| `type7_tensor.pdf` | the same patch as 16 explicit points | the internal-point cycle `p11 p12 p22 p21` |
| `type6_flag1.pdf` | two patches, the second continuing on edge 1 | the inheritance table's flag-1 row: the new `u=0` edge is the previous patch's `v=1` row, NOT reversed |
| `type6_flag2.pdf` | the same, on edge 2 | flag 2 inherits the previous patch's `u=1` column **reversed** |
| `type6_flag3.pdf` | the same, on edge 3 | flag 3 inherits the previous patch's `v=0` row **reversed** |
| `type7_flag1.pdf` | a type 7 continued patch | that a continued type 7 record is **12** coordinate pairs, not 8 - the four internal points are never inherited |
| `type4_parametric.pdf` | type 4 with a NON-LINEAR `/Function` | `f(lerp(t))` versus `lerp(f(t))` - see below |
| `type6_unaligned.pdf` | `BitsPerFlag 4`, `BitsPerCoordinate 12`, `BitsPerComponent 4` | the `MSH-A1` patch-padding ambiguity, which is unobservable on any byte-aligned file |
| `type4_truncated.pdf` | a stream cut part-way through its fourth vertex | that the complete records still paint and the tail is DISCLOSED |
| `type4_indexed.pdf` | an `Indexed` colour space | the `MSH-A4` refusal, which must be a named refusal and not a palette-order rainbow |
| `type6_pattern.pdf` | the same Coons patch reached as a `PatternType 2` FILL rather than by `sh` | the OTHER paint route. The two anchor in opposite coordinate spaces - `sh` in current user space, a pattern in the page's INITIAL space - and a mesh is forward-rasterised, so it inverts the transform the analytic path uses directly. A sign or an inversion dropped there renders a mesh in the wrong place, at the wrong size, or not at all |

★ `type4_parametric.pdf` USES AN EXPONENT OF 2 ON PURPOSE. With a linear
`/Function` (`/N 1`) the two orders of operations agree exactly - `f` is
affine, so `f(lerp(t)) == lerp(f(t))` - and the fixture would pass under the
wrong implementation. `/N 2` makes them differ at every interior point, and
the midpoint of the ramp is where they differ most.

SOURCE MATERIAL AND LICENCE (LEGAL.md §5, project rule 7)
---------------------------------------------------------
**Nothing here derives from a third-party file.** These are `LEGAL.md` §5
category (a): wholly synthetic, authored for this project, generated by this
committed script from geometry and colours this project chose. Nothing was
downloaded from anywhere, and in particular **no byte of any licensed
conformance suite is reproduced or paraphrased here** - the type 7 file is
built from the standard's own equations, not from any sample.

The PDFs are assembled byte by byte with a classic §7.5.4 cross-reference
table, no object streams and no compression, so a failing test can be read
in a hex editor and a fuzzer mutating one keeps producing something the
parser will engage with.

HOW TO REGENERATE
-----------------
    python tools/gen-mesh-fixtures.py
"""

from __future__ import annotations

from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "fixtures" / "synthetic" / "mesh"

# The page, and the square every mesh covers inside it. Kept well away from
# the page edge so that the CRACK_MARGIN_PX fringe on the mesh silhouette
# cannot run off the pixmap and turn a coverage question into a clipping
# question.
PAGE = 120
LO, HI = 10.0, 110.0

# Corner colours, in walk-around order p00, p03, p33, p30 - i.e.
# (u,v) = (0,0), (0,1), (1,1), (1,0). MSH24. Deliberately four saturated
# primaries so that a transposed assignment shows as a completely different
# picture rather than as a subtle shift.
C00 = (1.0, 0.0, 0.0)  # red     at (LO, LO)
C03 = (0.0, 1.0, 0.0)  # green   at (LO, HI)
C33 = (0.0, 0.0, 1.0)  # blue    at (HI, HI)
C30 = (1.0, 1.0, 0.0)  # yellow  at (HI, LO)


# ---------------------------------------------------------------------------
# Bit packing - MSH3: most-significant bit first, fields in the stated order
# ---------------------------------------------------------------------------


class BitWriter:
    """Pack fields MSB-first, with an explicit byte-align.

    The mirror of `mesh.rs`'s `BitReader`, written independently from the
    same clause rather than by transcribing the reader - a packer derived
    from the parser cannot falsify the parser.
    """

    def __init__(self) -> None:
        self.bits: list[int] = []

    def put(self, value: int, width: int) -> None:
        if value < 0 or value >= (1 << width):
            raise ValueError(f"{value} does not fit in {width} bits")
        for i in range(width - 1, -1, -1):
            self.bits.append((value >> i) & 1)

    def align(self) -> None:
        while len(self.bits) % 8:
            # Pad with 1s, not 0s. The clause says the pad bits "shall be
            # ignored"; padding with the value a lazy reader would find
            # least convenient is the cheap way to prove pdfcer ignores them.
            self.bits.append(1)

    def bytes(self) -> bytes:
        out = bytearray()
        bits = list(self.bits)
        while len(bits) % 8:
            bits.append(1)
        for i in range(0, len(bits), 8):
            b = 0
            for bit in bits[i : i + 8]:
                b = (b << 1) | bit
            out.append(b)
        return bytes(out)


def enc(value: float, lo: float, hi: float, width: int) -> int:
    """Inverse of MSH11's decode, so the fixture's numbers survive the round trip.

    `y = Dmin + x*(Dmax-Dmin)/(2^n - 1)`  =>  `x = (y-Dmin)*(2^n-1)/(Dmax-Dmin)`
    """
    span = hi - lo
    if span == 0:
        return 0
    x = round((value - lo) * ((1 << width) - 1) / span)
    return max(0, min((1 << width) - 1, x))


# ---------------------------------------------------------------------------
# Geometry
# ---------------------------------------------------------------------------


def straight_edge(a, b):
    """The two interior control points of a straight cubic from `a` to `b`."""
    return (
        (a[0] + (b[0] - a[0]) / 3.0, a[1] + (b[1] - a[1]) / 3.0),
        (a[0] + 2 * (b[0] - a[0]) / 3.0, a[1] + 2 * (b[1] - a[1]) / 3.0),
    )


def quad_boundary(p00, p03, p33, p30):
    """The 12 boundary control points of a straight-edged patch, in STREAM order.

    Stream order is the boundary walked counterclockwise from `p00`
    (`MSH29`): p00 p01 p02 p03 | p13 p23 p33 | p32 p31 p30 | p20 p10.

    Parameterised by the four CORNERS rather than by a rectangle, because a
    continued patch does not get to choose the orientation of its own `u=0`
    edge - it inherits it, and for edge flags 2 and 3 it inherits it
    REVERSED. A rectangle helper that always ran `p00` to `p03` upward could
    only author the flag-1 case, and authoring the other two with it
    produces a patch twisted into a bowtie. That is not a hypothetical: it
    is what the first draft of this generator emitted, and the picture
    looked enough like "a gradient" to need a second look.
    """
    p01, p02 = straight_edge(p00, p03)
    p13, p23 = straight_edge(p03, p33)
    p32, p31 = straight_edge(p33, p30)
    p20, p10 = straight_edge(p30, p00)
    return [p00, p01, p02, p03, p13, p23, p33, p32, p31, p30, p20, p10]


def square_boundary(x0, y0, x1, y1):
    """A rectangle, as `quad_boundary` corners: p00 lower-left, v upward."""
    return quad_boundary((x0, y0), (x0, y1), (x1, y1), (x1, y0))


def coons_internals(b):
    """The four internal points a Coons patch implies - MSH30, verbatim.

    Computed HERE, in the fixture generator, rather than read out of
    `mesh.rs`. That is what makes `type7_tensor.pdf` an independent check
    of the renderer's own copy of these equations: if the renderer's
    transcription is wrong, the two files stop agreeing.
    """
    (p00, p01, p02, p03, p13, p23, p33, p32, p31, p30, p20, p10) = b

    def f(a, bb, c, d, e, h, i, j):
        return tuple(
            (
                -4.0 * a[t]
                + 6.0 * (bb[t] + c[t])
                - 2.0 * (d[t] + e[t])
                + 3.0 * (h[t] + i[t])
                - j[t]
            )
            / 9.0
            for t in range(2)
        )

    p11 = f(p00, p01, p10, p03, p30, p31, p13, p33)
    p12 = f(p03, p02, p13, p00, p33, p32, p10, p30)
    p21 = f(p30, p31, p20, p33, p00, p01, p23, p03)
    p22 = f(p33, p32, p23, p30, p03, p02, p20, p00)
    # Stream order for the internals is the CYCLE p11 -> p12 -> p22 -> p21,
    # not row-major. MSH29's last four entries.
    return [p11, p12, p22, p21]


# ---------------------------------------------------------------------------
# Stream builders
# ---------------------------------------------------------------------------


def vertex(w, flag, xy, colour, bpf, bpco, bpcp, ncomp):
    if bpf:
        w.put(flag, bpf)
    w.put(enc(xy[0], LO, HI, bpco), bpco)
    w.put(enc(xy[1], LO, HI, bpco), bpco)
    for i in range(ncomp):
        w.put(enc(colour[i], 0.0, 1.0, bpcp), bpcp)
    # MSH12: the padded unit for types 4 and 5 is exactly one vertex, and
    # this one is normative rather than inferred.
    w.align()


def type4_stream(bpf=8, bpco=16, bpcp=8, parametric=False):
    """Two triangles covering the square, flags 0,0,0 then 1.

    The `1` is the point: it says "share side vbc", so the second triangle
    is `(vb, vc, vd)` - which for the vertex order below is exactly the
    second triangle a 2x2 type 5 lattice produces.
    """
    w = BitWriter()
    n = 1 if parametric else 3
    verts = [
        (0, (LO, LO), C00 if not parametric else (0.0,)),
        (0, (LO, HI), C03 if not parametric else (1.0 / 3.0,)),
        (0, (HI, LO), C30 if not parametric else (2.0 / 3.0,)),
        (1, (HI, HI), C33 if not parametric else (1.0,)),
    ]
    for flag, xy, col in verts:
        vertex(w, flag, xy, col, bpf, bpco, bpcp, n)
    return w.bytes()


def type5_stream(bpco=16, bpcp=8):
    """A 2x2 lattice - MSH22 with m = k = 2, and no flag field (MSH7).

    Row-major: V00 V01 then V10 V11. `VerticesPerRow` is 2 and `m` is
    inferred from the stream length, which is itself a thing worth
    exercising: the row count is NOT in the dictionary.

    Vertex order is chosen so the two triangles MSH22 builds -
    `(V00,V01,V10)` and `(V01,V10,V11)` - are the same two, with the same
    colours, that `type4_stream` builds.
    """
    w = BitWriter()
    for xy, col in (
        ((LO, LO), C00),
        ((LO, HI), C03),
        ((HI, LO), C30),
        ((HI, HI), C33),
    ):
        vertex(w, 0, xy, col, 0, bpco, bpcp, 3)
    return w.bytes()


def patch_stream(tensor, patches, bpf=8, bpco=16, bpcp=8, pad=True, truncate=0):
    """A type 6 or type 7 patch stream.

    `patches` is a list of `(flag, points, colours)`. For `flag == 0` the
    points are all 12 (type 6) or all 16 (type 7) in stream order and the
    colours are all four; for a continued patch the caller supplies the
    points and colours the stream actually carries, which is 8/12 points and
    2 colours - the rest are inherited and MUST NOT be repeated.
    """
    w = BitWriter()
    for flag, pts, cols in patches:
        w.put(flag, bpf)
        for p in pts:
            w.put(enc(p[0], LO, HI, bpco), bpco)
            w.put(enc(p[1], LO, HI, bpco), bpco)
        for c in cols:
            for comp in c:
                w.put(enc(comp, 0.0, 1.0, bpcp), bpcp)
        if pad:
            # MSH-A1, reading (a): the padded unit is the patch record.
            w.align()
    data = w.bytes()
    return data[: len(data) - truncate] if truncate else data


# ---------------------------------------------------------------------------
# PDF assembly
# ---------------------------------------------------------------------------


def build(shading_dict: bytes, stream: bytes | None, as_pattern: bool = False) -> bytes:
    """One single-page PDF that paints the shading, by one of its two routes.

    By default `sh`, because `sh` anchors in CURRENT user space with no
    `/Matrix` in the way: the mesh's own coordinates land on the page
    unchanged, so an assertion about a pixel is an assertion about the
    decoded geometry and not about a matrix.

    With `as_pattern`, the same shading is reached as a `PatternType 2` fill
    instead. That is the OTHER route, and it is not a formality: a pattern's
    coordinates are pattern space, mapped by the pattern's own `/Matrix` to
    the page's INITIAL space rather than to the CTM at paint time, so the
    transform a mesh has to invert to rasterise forward is built
    differently. Both `/Matrix` and the CTM are the identity here, so the two
    files must produce the same picture - which is the whole point: a
    difference is a transform bug and cannot be anything else.
    """
    objects: list[bytes] = []

    def add(body: bytes) -> int:
        objects.append(body)
        return len(objects)

    add(b"<< /Type /Catalog /Pages 2 0 R >>")
    add(b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>")
    if as_pattern:
        # Set the Pattern colour space, select the pattern, fill the square
        # the mesh covers. The rectangle is the PAINT AREA; the pattern's
        # own coordinates decide what lands in it.
        content = (
            b"q /Pattern cs /P scn "
            + f"{LO:g} {LO:g} {HI - LO:g} {HI - LO:g}".encode()
            + b" re f Q\n"
        )
        resources = b"/Resources << /Pattern << /P 6 0 R >> >>"
    else:
        content = b"q /Sh sh Q\n"
        resources = b"/Resources << /Shading << /Sh 5 0 R >> >>"
    add(
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 "
        + str(PAGE).encode()
        + b" "
        + str(PAGE).encode()
        + b"] "
        + resources
        + b" /Contents 4 0 R >>"
    )
    add(
        b"<< /Length "
        + str(len(content)).encode()
        + b" >>\nstream\n"
        + content
        + b"endstream"
    )
    if stream is None:
        shading = add(shading_dict)
    else:
        shading = add(
            shading_dict[:-2]
            + b" /Length "
            + str(len(stream)).encode()
            + b" >>\nstream\n"
            + stream
            + b"\nendstream"
        )

    if as_pattern:
        pattern = add(
            b"<< /Type /Pattern /PatternType 2 /Matrix [1 0 0 1 0 0] /Shading "
            + str(shading).encode()
            + b" 0 R >>"
        )
        assert pattern == 6, f"the pattern must be object 6, not {pattern}"

    # R162: assert the LITERAL that is emitted, not the counter that cannot
    # disagree with itself. The reference is written into the page dictionary
    # by hand above, so the check is that the object it names really is the
    # one that was added.
    assert shading == 5, f"the shading must be object 5, not {shading}"
    body = b"".join(objects)
    assert body.count(b"/P 6 0 R" if as_pattern else b"/Sh 5 0 R") == 1

    out = bytearray(b"%PDF-1.7\n%\xe2\xe3\xcf\xd3\n")
    offsets = [0]
    for i, obj in enumerate(objects, start=1):
        offsets.append(len(out))
        out += str(i).encode() + b" 0 obj\n" + obj + b"\nendobj\n"
    startxref = len(out)
    n = len(objects) + 1
    out += b"xref\n0 " + str(n).encode() + b"\n0000000000 65535 f \n"
    for off in offsets[1:]:
        out += f"{off:010d} 00000 n {chr(10)}".encode()
    out += (
        b"trailer\n<< /Size " + str(n).encode() + b" /Root 1 0 R >>\n"
        b"startxref\n" + str(startxref).encode() + b"\n%%EOF\n"
    )
    return bytes(out)


def decode_array(ncomp: int) -> bytes:
    """`[xmin xmax ymin ymax c...]` - MSH10, with MSH14's one-pair form."""
    parts = [f"{LO:g}", f"{HI:g}", f"{LO:g}", f"{HI:g}"]
    parts += ["0", "1"] * ncomp
    return ("[" + " ".join(parts) + "]").encode()


def sh_dict(stype, ncomp, bpco=16, bpcp=8, bpf=8, extra=b"", space=b"/DeviceRGB"):
    d = (
        b"<< /ShadingType "
        + str(stype).encode()
        + b" /ColorSpace "
        + space
        + b" /BitsPerCoordinate "
        + str(bpco).encode()
        + b" /BitsPerComponent "
        + str(bpcp).encode()
    )
    if stype != 5:
        d += b" /BitsPerFlag " + str(bpf).encode()
    d += b" /Decode " + decode_array(ncomp) + extra + b" >>"
    return d


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)

    # Two-patch layouts, one per nonzero edge flag. Each pair tiles the
    # SAME [LO,HI] square, so "did the inheritance land the second patch
    # where the table says?" is answerable by looking at coverage: a
    # mis-oriented inherited edge twists the patch into a bowtie and leaves
    # a large part of the square unpainted.
    #
    # The orientation of each continued patch is forced, not chosen. Under
    # flag 2 and flag 3 the inherited edge arrives REVERSED, so the second
    # patch's own p00 is the corner at the FAR end of the shared edge.
    half = (LO + HI) / 2.0
    # flag 1: A is the lower half; B inherits A's v=1 row (p03 -> p33),
    # left to right, and grows upward.
    f1_a = quad_boundary((LO, LO), (LO, half), (HI, half), (HI, LO))
    f1_b = quad_boundary((LO, half), (HI, half), (HI, HI), (LO, HI))
    # flag 2: A is the left half; B inherits A's u=1 column reversed
    # (p33 -> p30), i.e. top to bottom, and grows rightward.
    f2_a = quad_boundary((LO, LO), (LO, HI), (half, HI), (half, LO))
    f2_b = quad_boundary((half, HI), (half, LO), (HI, LO), (HI, HI))
    # flag 3: A is the upper half; B inherits A's v=0 row reversed
    # (p30 -> p00), i.e. right to left, and grows downward.
    f3_a = quad_boundary((LO, half), (LO, HI), (HI, HI), (HI, half))
    f3_b = quad_boundary((HI, half), (LO, half), (LO, LO), (HI, LO))

    boundary = square_boundary(LO, LO, HI, HI)
    internals = coons_internals(boundary)
    corners = [C00, C03, C33, C30]

    files: dict[str, bytes] = {}

    files["type4_triangles.pdf"] = build(sh_dict(4, 3), type4_stream())
    files["type5_lattice.pdf"] = build(
        sh_dict(5, 3, extra=b" /VerticesPerRow 2"), type5_stream()
    )
    files["type6_coons.pdf"] = build(
        sh_dict(6, 3), patch_stream(False, [(0, boundary, corners)])
    )
    files["type7_tensor.pdf"] = build(
        sh_dict(7, 3), patch_stream(True, [(0, boundary + internals, corners)])
    )
    # The same patch, reached by the OTHER paint route.
    files["type6_pattern.pdf"] = build(
        sh_dict(6, 3), patch_stream(False, [(0, boundary, corners)]), as_pattern=True
    )

    # One file per nonzero edge flag. A continued patch's stream carries
    # stream slots 5..12 (type 6) - everything except the inherited u = 0
    # edge - and TWO corner colours, the ones at the far end.
    #
    # The two supplied colours are magenta and cyan in every file, which
    # neither A nor the walk-around set uses. A continued patch that
    # inherited the wrong pair would still render a plausible gradient with
    # four of the six colours; making the new pair unmistakable is what
    # turns "it looks like a gradient" into an assertion.
    MAG = (1.0, 0.0, 1.0)
    CYA = (0.0, 1.0, 1.0)
    for flag, (a_pts, b_pts) in ((1, (f1_a, f1_b)), (2, (f2_a, f2_b)), (3, (f3_a, f3_b))):
        files[f"type6_flag{flag}.pdf"] = build(
            sh_dict(6, 3),
            patch_stream(
                False,
                [
                    (0, a_pts, [C00, C03, C33, C30]),
                    (flag, b_pts[4:], [MAG, CYA]),
                ],
            ),
        )

    # The type 7 twin of the flag-1 file. A continued TYPE 7 record carries
    # twelve coordinate pairs, not eight: the four internal points are never
    # inherited (Table 86 lists them in every f != 0 row), so a parser that
    # reused the type 6 read count would desynchronise here and nowhere
    # else.
    files["type7_flag1.pdf"] = build(
        sh_dict(7, 3),
        patch_stream(
            True,
            [
                (0, f1_a + coons_internals(f1_a), [C00, C03, C33, C30]),
                (1, f1_b[4:] + coons_internals(f1_b), [MAG, CYA]),
            ],
        ),
    )

    # MSH14: one parametric field per vertex, a six-number /Decode, and an
    # exponent of 2 so that f(lerp(t)) and lerp(f(t)) DIFFER.
    files["type4_parametric.pdf"] = build(
        sh_dict(
            4,
            1,
            extra=(
                b" /Function << /FunctionType 2 /Domain [0 1] "
                b"/C0 [0 0 0] /C1 [1 1 1] /N 2 >>"
            ),
        ),
        type4_stream(parametric=True),
    )

    # MSH-A1 made observable: 4 + 24*12 + 4*3*4 = 340 bits for a new patch,
    # which is not a multiple of 8. Two patches, so the SECOND record's
    # start depends on which reading is in force.
    files["type6_unaligned.pdf"] = build(
        sh_dict(6, 3, bpco=12, bpcp=4, bpf=4),
        patch_stream(
            False,
            [
                (0, f2_a, [C00, C03, C33, C30]),
                (2, f2_b[4:], [MAG, CYA]),
            ],
            bpf=4,
            bpco=12,
            bpcp=4,
        ),
    )

    # MSH-N2: the stream stops part-way through the fourth vertex. The three
    # complete ones still form one triangle, which must still paint.
    full = type4_stream()
    files["type4_truncated.pdf"] = build(sh_dict(4, 3), full[: len(full) - 3])

    # MSH-A4: an Indexed mesh colour space. A literal reading permits it and
    # would interpolate palette INDICES; pdfcer refuses it by name instead.
    files["type4_indexed.pdf"] = build(
        sh_dict(
            4,
            1,
            space=b"[/Indexed /DeviceRGB 3 <FF000000FF000000FFFFFF00>]",
        ),
        type4_stream(parametric=True),
    )

    for name, data in sorted(files.items()):
        (OUT / name).write_bytes(data)
        print(f"wrote {OUT / name}  ({len(data)} bytes)")


if __name__ == "__main__":
    main()
