#!/usr/bin/env python3
"""Generate the `DeviceGray`-over-spot overprint fixtures (`Pass 143.0`).

WHY THIS FILE EXISTS, AND WHY IT IS SEPARATE FROM `gen-overprint-image-fixtures.py`
==================================================================================
It isolates a different claim. That generator's family is about Table 149's
**row 3** — a `Separation`/`DeviceN` source, where the COLORANT LIST decides
what survives. This one is about the interaction between §8.6.7's `OPM 1` and
a source space that is **not** `DeviceCMYK` at all, which is a question row 3
never asks.

★ AND IT EXISTS BECAUSE THE LICENSED CONFORMANCE CORPUS CANNOT SCORE THE
CASE. Measured 2026-08-28 on `4094e49` by rendering every one of its 51
patches twice with the shipped binary — `--overprint-zero-tint-scope
device_cmyk_only`, which reproduces the pre-Pass behaviour exactly, versus
the default — and counting differing pixels: **3 of 51 change (8,491 /
1,827 / 804 px) and 0 of 3 change verdict.** So the corpus — the oracle for
every other overprint Pass — is *touched* by this behaviour and cannot
*score* it, and without these fixtures the `overprint_zero_tint_scope`
setting would be correct, wired, documented and **unexercised by any test in
the repository** (`R151`).

★ CORRECTED 2026-08-28, same day. This paragraph first read "the corpus DOES
NOT CONTAIN THE CASE … zero of them paint a `DeviceGray` source through
Table 149. The patch whose name promises exactly that authors its greys as
`DeviceCMYK [0 0 0 k]`." That scan was taken BETWEEN THE TWO HALVES OF THE
FIX — after the `classify` change, before the `overprint_would_change` repair
that is what lets grey sources reach Table 149 — so it measured the DEFECT,
not the fix. Withdrawn. The fixtures are still necessary and the conclusion
above is unchanged; only its reason moved.

THE AMBIGUITY BEING PINNED
--------------------------
§8.6.7 scopes `OPM 1`'s zero-tint rule to *"a colour component in a
`DeviceCMYK` colour space"*. Its one escape hatch — *"or is implicitly
converted to `DeviceCMYK`; see 8.6.5.7"* — points at a clause titled
**"Implicit Conversion of CIE-Based Colour Spaces"**, so it reaches CIE-based
spaces and nothing else. `DeviceGray` is a *device* space, so:

* the LITERAL reading is that `OPM 1` does not reach it, and a grey fill
  therefore writes all four components and KNOCKS THE SPOT BACKDROP OUT;
* ACROBAT converts grey to K-only `DeviceCMYK` first and then applies
  `OPM 1`, so the zero C, M and Y PRESERVE the backdrop.

Both are defensible. pdfcer ships the setting and defaults to Acrobat's.

WHAT EACH FIXTURE ASSERTS
-------------------------
Every file is the same page with one variable changed, so a difference can
only come from that variable:

| file | source | `/OP` | the claim |
|---|---|---|---|
| `grey_op_over_spot.pdf` | `DeviceGray` 0.5 | true | **the discriminator.** Under `grey_as_k_only` the spot's C/M/Y survive; under `device_cmyk_only` they are knocked out. |
| `grey_noop_over_spot.pdf` | `DeviceGray` 0.5 | false | the CONTROL. Overprint is off, so *no* setting may move this pixel. A fix that moves it is over-broad. |
| `cmyk_k_op_over_spot.pdf` | `DeviceCMYK` `0 0 0 0.5` | true | the REFERENCE. Already gets `OPM 1` under every setting, and is the colour `grey_op_over_spot.pdf` must MATCH under `grey_as_k_only` -- that equality is the whole meaning of "treat grey as the K-only CMYK it converts to", and it is checkable without a reference render. |
| `grey_image_op_over_spot.pdf` | `DeviceGray` **image** | true | the SECOND CONTROL, and the sharper one. Table 149 gives the direct-CMYK row the qualifier *"and not in a sampled image"*, so a CMYK image already falls to the process row where `OPM 0` and `OPM 1` are identical. A grey image is that case's exact analogue: it must NOT move under any setting, or a grey image would have an overprint behaviour a CMYK image does not get. |

★ THE THIRD ROW IS THE ONE THAT NEEDS NO ORACLE. `grey_op_over_spot.pdf` and
`cmyk_k_op_over_spot.pdf` differ in exactly one way -- one says `0.5 g`, the
other says `0 0 0 0.5 k` -- and under the default setting they must land on
IDENTICAL pixels. No remembered expected colour, no reference engine, no
threshold. That is the `R215` shape: a self-consistency pair beats a
memorised value, because a memorised value can be memorised wrong.

The backdrop is a `/Separation /Spot` whose tint transform is deliberately
CHROMATIC (C=0.8 M=0.2 Y=0.9 K=0, a green-dominant ink). A neutral backdrop
would make "preserved" and "knocked out" differ only in lightness, which a
rounding change could imitate; a green one cannot be reached by accident.

The writer is hand-rolled rather than delegated to `pdfcer`, for the reason
the sibling generator states: a fixture generated by the program under test
cannot falsify that program.
"""

import pathlib
import sys

OUT = pathlib.Path(__file__).resolve().parent.parent / "fixtures" / "synthetic" / "overprint"

# The spot ink. Green-dominant so that "preserved" and "knocked out" differ in
# HUE, not merely in lightness -- see the module docstring.
SPOT_C, SPOT_M, SPOT_Y, SPOT_K = 0.8, 0.2, 0.9, 0.0

# Pure red. Its `rgb_to_cmyk` conversion is C=0, M=1, Y=1, K=0 -- so exactly
# one component is zero and the backdrop's CYAN is what `AllProcessSpaces`
# preserves and `GreyAsKOnly` must not. Defined as a constant because the
# newline inside it does not survive being written through a shell heredoc.
RGB_MARK = b"1 0 0 rg\n60 60 80 80 re f\n"


def obj(n: int, body: bytes) -> bytes:
    return b"%d 0 obj\n" % n + body + b"\nendobj\n"


def serialize(objects: dict[int, bytes]) -> bytes:
    """Body + xref + trailer, with offsets accumulated as objects are emitted.

    The xref is built from the same list the body is, so the two cannot drift
    apart -- the failure mode of a generator that computes offsets twice.
    """
    out = bytearray(b"%PDF-1.7\n")
    offsets: dict[int, int] = {}
    for n in sorted(objects):
        offsets[n] = len(out)
        out += obj(n, objects[n])
    start = len(out)
    top = max(objects) + 1
    out += b"xref\n0 %d\n" % top
    out += b"0000000000 65535 f \n"
    for n in range(1, top):
        out += b"%010d 00000 n \n" % offsets.get(n, 0)
    out += b"trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n" % (top, start)
    return bytes(out)


def stream(dict_body: str, data: bytes) -> bytes:
    head = f"<< {dict_body} /Length {len(data)} >>\nstream\n".encode("ascii")
    return head + data + b"\nendstream"


def build(*, source: str, overprint: bool, backdrop: str = "spot") -> bytes:
    """One page: a backdrop, then a mark of `source` over it.

    `backdrop` is `"spot"` (a full-tint `/Separation` fill, the original and
    still the default) or `"cmyk"` (a plain `0.5 0 1 0 k` process fill).

    ★★ THE `"cmyk"` BACKDROP IS THE ONLY GEOMETRY THAT CAN CHECK THE CLAIM THE
    DEFAULT IS NAMED AFTER, and its absence is why a false claim survived.

    Every fixture in this file was `_over_spot`, and over a spot BOTH readings
    of `OverprintZeroTintScope` produce a defensible picture -- they differ
    from each other, so the tests looked discriminating, but neither picture
    tells you which reading Acrobat uses. The project's own note `OP-N3` says
    exactly this: "the discriminating case is grey over PROCESS components".
    That case was named as missing and then not built, so a test called
    `the_shipped_default_is_the_acrobat_reading` asserted on spot geometry --
    a claim about Acrobat checked against a picture that cannot see it.

    Over a PROCESS backdrop the two readings separate with a known ground
    truth:

      GreyAsKOnly     grey converts to K-only CMYK, whose zero C/M/Y take the
                      backdrop under Table 149 row 1's value-dependent OPM-1
                      cell -- the backdrop SURVIVES.
      DeviceCmykOnly  Table 149 row 2 puts a DeviceGray source in "any process
                      colour space", which is `c_s` in all three columns -- the
                      backdrop is REPLACED.

    Measured against Acrobat on a print-conformance patch of this exact shape:
    Acrobat renders it REPLACED (255,255,255 where pdfcer's shipped default
    renders 142,198,63). So the literal reading matches and the default does
    not, which falsifies the default's stated justification.

    `source` is one of `"grey"` (a `0.5 g` fill), `"grey_white"` (a `1 g`
    fill -- the case that makes the comparison airtight, because `1 g`
    converts to `0 0 0 0` under ANY profile, so "convert then apply OPM 1"
    cannot explain Acrobat's result), `"cmyk"` (a `0 0 0 0.5 k`
    fill -- the same ink stated the other way) or `"grey_image"` (a one-sample
    `DeviceGray` image at the same value).

    The page declares `/Group << /S /Transparency /CS /DeviceCMYK >>` so it
    composites in a four-colorant buffer WITHOUT depending on an output
    intent. That matters: routing this through an output intent would make the
    fixture also a test of `page_blend_space_source`, and a fixture that can
    fail for two reasons cannot tell you which one it hit.
    """
    op = b"/OP true /op true /OPM 1" if overprint else b"/OP false /op false /OPM 1"

    if source == "grey":
        mark = b"0.5 g\n60 60 80 80 re f\n"
    elif source == "grey_white":
        # `1 g` -- white. Converts to `0 0 0 0` under every CMYK profile, so
        # no "it converted differently" explanation can survive a comparison
        # built on it.
        mark = b"1 g\n60 60 80 80 re f\n"
    elif source == "cmyk":
        mark = b"0 0 0 0.5 k\n60 60 80 80 re f\n"
    elif source == "rgb":
        # A DeviceRGB fill whose CMYK conversion has a ZERO component, so
        # `AllProcessSpaces` has something to preserve and `GreyAsKOnly` must
        # leave it alone. Pure red converts to C=0, M=1, Y=1, K=0 under
        # `rgb_to_cmyk`, so the backdrop's CYAN is the channel at stake.
        mark = RGB_MARK
    elif source == "grey_image":
        # A 1x1 `DeviceGray` sample at 0.5 (128/255), scaled over the same
        # rectangle. `/Interpolate` is omitted so no smoothing can blur the
        # comparison at the edges.
        mark = b"q 80 0 0 80 60 60 cm /Im0 Do Q\n"
    else:
        raise ValueError(f"unknown source {source!r}")

    # ★ THE BACKDROP IS PAINTED WITH OVERPRINT OFF, AND THAT IS NOT A DETAIL.
    #
    # The first cut of this generator wrapped BOTH paints in one `/OP true`
    # graphics state, and every fixture came out identical under both
    # settings — which read exactly like "the setting does nothing".
    #
    # It was the fixture. A `/Separation` source under `/OP true` gets
    # Table 149 row 3, which leaves every process component it does not name
    # standing FROM THE BACKDROP — and the backdrop there was blank paper. So
    # the spot laid down no ink at all, and "preserved" versus "knocked out"
    # were being compared over white. The measurement was of nothing.
    #
    # `/GSnorm` paints the backdrop normally so there is real ink to preserve;
    # `/GSop` then governs only the mark, which is the paint under test.
    content = (
        b"q\n"
        b"/GSnorm gs\n"
        # Full-tint spot, painted FIRST and larger than the mark so the mark's
        # edge sits on ink rather than on paper.
        + (b"/CS0 cs 1 scn\n" if backdrop == "spot" else b"0.5 0 1 0 k\n")
        + b"40 40 120 120 re f\n"
        b"/GSop gs\n" + mark + b"Q\n"
    )

    objects: dict[int, bytes] = {
        1: b"<< /Type /Catalog /Pages 2 0 R >>",
        2: b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        3: (
            b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] "
            b"/Group << /S /Transparency /CS /DeviceCMYK >> "
            b"/Resources << /ExtGState << /GSop 5 0 R /GSnorm 9 0 R >> "
            b"/ColorSpace << /CS0 6 0 R >> "
            b"/XObject << /Im0 8 0 R >> >> "
            b"/Contents 4 0 R >>"
        ),
        4: stream("", content),
        5: b"<< /Type /ExtGState " + op + b" >>",
        6: b"[/Separation /Spot /DeviceCMYK 7 0 R]",
        # Type 2 exponential: one input, four outputs. At tint 1 it yields the
        # chromatic ink above; at 0, no ink.
        7: (
            b"<< /FunctionType 2 /Domain [0 1] /C0 [0 0 0 0] "
            b"/C1 [%f %f %f %f] /N 1 >>" % (SPOT_C, SPOT_M, SPOT_Y, SPOT_K)
        ),
        # Overprint explicitly OFF, so the backdrop lays down real ink.
        9: b"<< /Type /ExtGState /OP false /op false >>",
        8: stream(
            "/Type /XObject /Subtype /Image /Width 1 /Height 1 "
            "/ColorSpace /DeviceGray /BitsPerComponent 8",
            bytes([128]),
        ),
    }
    return serialize(objects)


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    files = {
        "grey_op_over_spot.pdf": build(source="grey", overprint=True),
        # ★ THE DISCRIMINATING CASE, absent until now. Grey over a PROCESS
        # backdrop is the only geometry that can check which reading matches
        # Acrobat; every other fixture here is over a spot, where both
        # readings look defensible and neither identifies the reference.
        "grey_op_over_cmyk.pdf": build(
            source="grey_white", overprint=True, backdrop="cmyk"
        ),
        "grey_noop_over_spot.pdf": build(source="grey", overprint=False),
        "cmyk_k_op_over_spot.pdf": build(source="cmyk", overprint=True),
        "grey_image_op_over_spot.pdf": build(source="grey_image", overprint=True),
        # ★ THE SCOPE DISCRIMINATOR. Without this file `GreyAsKOnly` and
        # `AllProcessSpaces` are indistinguishable by any test in the
        # repository -- verified by sabotage: widening `GreyAsKOnly` to match
        # every space left the whole suite GREEN. A setting whose values
        # cannot be told apart is three names for one behaviour.
        "rgb_op_over_spot.pdf": build(source="rgb", overprint=True),
        # ★ `Pass 238.0`: the SPOT version above can no longer discriminate
        # the scopes, and that is a correctness gain rather than a loss. Once
        # a spot has a plane of its own, Table 149's "any process colour
        # space × spot colorant" row preserves it under EVERY scope, and the
        # backdrop's PROCESS channels are all zero (a pure spot states none)
        # -- so there is nothing left for `AllProcessSpaces` to preserve
        # differently. `OP-N3` said it first: the discriminating case is over
        # PROCESS components. This is that case for the RGB source: red
        # (C=0, M=1, Y=1, K=0) over `0.5 0 1 0 k`, where the backdrop's cyan
        # is real process ink and survives only under the widest scope.
        "rgb_op_over_cmyk.pdf": build(source="rgb", overprint=True, backdrop="cmyk"),
    }
    for name, data in files.items():
        (OUT / name).write_bytes(data)
        print(f"wrote {name} ({len(data)} bytes)")
    print(f"{len(files)} grey-overprint fixture(s) in {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
