#!/usr/bin/env python3
"""gen-icc-rgb-fixtures — the oracle for `Pass 240.0`.

WHAT THIS BUILDS, AND WHY IT NEEDS NO REFERENCE RENDER
======================================================
Each fixture draws **the same authored colour four ways on one page**, all
through ONE embedded `ICCBased /N 3` profile: as a flat path fill, as a direct
sampled image, as an `/Indexed` image whose single palette entry is that
colour, and as a JPEG 2000 image whose codestream carries the profile itself
and whose dictionary names no `/ColorSpace` at all. A correct renderer paints
all four the same colour, so the first assertion is *fill == image == palette
== codestream* and needs no external reference.

That is `tools/gen-devicen-image-fixtures.py`'s oracle applied to a different
colour space, and it is the oracle that found the defects this Pass fixed:
a print-conformance patch draws one colour as a vector and as an image
through one profile, and the two cells disagreed.

THE PROFILE IS DELIBERATELY NOT sRGB, AND THAT IS THE WHOLE FIXTURE
===================================================================
The embedded profile is a v2 matrix/TRC RGB profile whose **red and green
colorants are swapped** — its `rXYZ` is sRGB's green primary and its `gXYZ`
is sRGB's red primary, both as the ICC-published D50-adapted values. Its TRCs
are a plain gamma 2.2. So through the profile the operands `(0.4, 0.2, 0.8)`
mean a colour that is GREEN-dominant; reinterpreted as `DeviceRGB` (Table 66's
fallback, what pdfcer did before this Pass) they paint RED-dominant.

Two consequences, both load-bearing:

1. **The expected pixel is closed-form**, not observed. The chain is
   `lin = v^2.2`, then the swapped colorant matrix into XYZ, then iccce's
   constructed sRGB back out. Because the colorants are exactly sRGB's, the
   matrix round trip is the identity up to iccce's 3-ULP agreement with ICC's
   published table, and the answer is simply the sRGB ENCODING of the
   swapped linear values:

       R_out = enc(0.2^2.2)   G_out = enc(0.4^2.2)   B_out = enc(0.8^2.2)

   `EXPECTED` below is that arithmetic, computed here and asserted by the
   test with a small tolerance for the 3 ULP and for 8-bit rounding.

2. **A renderer that manages nothing cannot pass by luck** (rule R225 — a
   fixture whose two candidate answers coincide cannot distinguish them). The
   unmanaged answer is `(102, 51, 204)`; the managed one is `(48, 102, 205)`
   — and lcms2, run on the generated profile through Pillow's `ImageCms`,
   returns exactly `(48, 102, 205)` too (2026-09-02). Fifty-four levels apart
   in red.

THE THREE PAGES
===============
| file | page group | `/OutputIntents` | route it exercises |
|---|---|---|---|
| `icc-rgb-four-ways-additive.pdf` | none | none | the DISPLAY route alone: every object goes profile -> sRGB and is painted |
| `icc-rgb-four-ways-subtractive-no-intent.pdf` | `/CS /DeviceCMYK` | none | the display route feeding a colorant buffer through `rgb_to_cmyk`: no ink bridge can be built, so all four must bridge from the SAME managed sRGB |
| `icc-rgb-four-ways-subtractive.pdf` | `/CS /DeviceCMYK` | a synthetic CMYK profile | the INK route: every object goes profile -> output-intent CMYK and deposits that as ink |

★ The third page's destination profile is `dest-cmyk.icc`, copied verbatim
from iccce's own synthetic fixture set (`v2-cmyk-chromatic-neutral.icc`, MIT,
generated by iccce's `gen-profiles`). It is a real two-direction CMYK profile
whose B2A0 separates colour into all four inks, so a colour that reaches it
through the bridge lays down chromatic ink that `rgb_to_cmyk` would not have
produced -- the test uses the ink probe to tell the two apart. See
`PROVENANCE.md`.

★★ Operands are EXACTLY representable at 8 bits per component — 0.4 is
102/255, 0.2 is 51/255, 0.8 is 204/255 — so the fill's operand and every
image's sample are the same number rather than nearly the same.

USAGE
=====
    python tools/gen-icc-rgb-fixtures.py

Writes into `fixtures/synthetic/icc-rgb/`. Rights-cleared by construction:
every byte of the PDFs and of the RGB profile is generated here, and the CMYK
profile is the author's own from a sibling MIT project (`LEGAL.md` §5).
Requires Pillow with OpenJPEG for the JPEG 2000 page.
"""

from __future__ import annotations

import io
import pathlib
import struct
import sys

from PIL import Image

OUT = pathlib.Path(__file__).resolve().parent.parent / "fixtures" / "synthetic" / "icc-rgb"

# Exactly representable at 8 bpc: 102/255, 51/255, 204/255.
OPERANDS = (0.4, 0.2, 0.8)
SAMPLES = (102, 51, 204)
GAMMA = 2.2

# ICC's published D50-adapted sRGB colorants (ICC.1 Annex, the values every
# shipped sRGB profile carries in rXYZ/gXYZ/bXYZ), as s15Fixed16 would round
# them. iccce's constructed sRGB agrees with these to 3.02 ULP.
SRGB_R = (0.43607, 0.22249, 0.01392)
SRGB_G = (0.38515, 0.71687, 0.09708)
SRGB_B = (0.14307, 0.06061, 0.71410)
D50 = (0.9642, 1.0, 0.8249)


def srgb_encode(linear: float) -> float:
    """IEC 61966-2-1's transfer function, with the linear toe."""
    if linear <= 0.0031308:
        return 12.92 * linear
    return 1.055 * linear ** (1 / 2.4) - 0.055


def expected_pixel() -> tuple[int, int, int]:
    """The closed-form managed answer — see the module docs."""
    r, g, b = OPERANDS
    lin = (g**GAMMA, r**GAMMA, b**GAMMA)  # swapped: the profile's R is sRGB's G
    return tuple(round(srgb_encode(v) * 255) for v in lin)


EXPECTED = expected_pixel()


# ---------------------------------------------------------------------------
# The swapped-colorant profile
# ---------------------------------------------------------------------------


def s15f16(v: float) -> bytes:
    return struct.pack(">i", round(v * 65536))


def xyz_tag(xyz: tuple[float, float, float]) -> bytes:
    return b"XYZ " + b"\0" * 4 + b"".join(s15f16(c) for c in xyz)


def curv_gamma(gamma: float) -> bytes:
    """A one-entry `curv` is a gamma, encoded u8Fixed8 (ICC.1 §10.5)."""
    return b"curv" + b"\0" * 4 + struct.pack(">I", 1) + struct.pack(">H", round(gamma * 256))


def desc_tag(text: bytes) -> bytes:
    """v2 textDescriptionType: ASCII, then empty Unicode and ScriptCode halves."""
    ascii_ = text + b"\0"
    return (
        b"desc" + b"\0" * 4
        + struct.pack(">I", len(ascii_)) + ascii_
        + struct.pack(">II", 0, 0)          # Unicode language code, count
        + struct.pack(">HB", 0, 0)          # ScriptCode code, count
        + b"\0" * 67                        # ScriptCode block
    )


def swap_rg_profile() -> bytes:
    """A v2.1 `mntr RGB XYZ` profile with sRGB's red and green colorants swapped.

    Tag payloads are 4-byte aligned as ICC.1 requires; the tag table is
    written after the payload offsets are known.
    """
    tags = [
        (b"desc", desc_tag(b"pdfcer synthetic: sRGB colorants with R and G swapped")),
        (b"wtpt", xyz_tag(D50)),
        (b"rXYZ", xyz_tag(SRGB_G)),   # ★ swapped
        (b"gXYZ", xyz_tag(SRGB_R)),   # ★ swapped
        (b"bXYZ", xyz_tag(SRGB_B)),
        (b"rTRC", curv_gamma(GAMMA)),
        (b"gTRC", curv_gamma(GAMMA)),
        (b"bTRC", curv_gamma(GAMMA)),
    ]
    table_len = 4 + 12 * len(tags)
    offset = 128 + table_len
    entries = b""
    payload = b""
    for sig, data in tags:
        pad = (-len(data)) % 4
        entries += sig + struct.pack(">II", offset + len(payload), len(data))
        payload += data + b"\0" * pad
    size = 128 + table_len + len(payload)
    header = bytearray(128)
    struct.pack_into(">I", header, 0, size)
    header[4:8] = b"none"                       # preferred CMM
    header[8:12] = b"\x02\x10\x00\x00"          # version 2.1.0
    header[12:16] = b"mntr"
    header[16:20] = b"RGB "
    header[20:24] = b"XYZ "
    # creation date: 12 bytes of zero is tolerated by every parser tried
    header[36:40] = b"acsp"
    header[40:44] = b"\0\0\0\0"                 # primary platform: none
    header[68:80] = b"".join(s15f16(c) for c in D50)  # illuminant
    header[80:84] = b"pdfc"                     # creator
    return bytes(header) + struct.pack(">I", len(tags)) + entries + payload


# ---------------------------------------------------------------------------
# PDF assembly (same conventions as gen-devicen-image-fixtures.py)
# ---------------------------------------------------------------------------


def build(objs: dict[int, bytes]) -> bytes:
    assert sorted(objs) == list(range(1, len(objs) + 1)), (
        f"object numbers must be contiguous from 1; got {sorted(objs)}"
    )
    out = bytearray(b"%PDF-1.7\n")
    offsets: dict[int, int] = {}
    for n in sorted(objs):
        offsets[n] = len(out)
        out += b"%d 0 obj\n" % n + objs[n] + b"\nendobj\n"
    xref = len(out)
    out += b"xref\n0 %d\n" % (len(objs) + 1)
    out += b"0000000000 65535 f \n"
    for n in sorted(objs):
        out += b"%010d 00000 n \n" % offsets[n]
    out += b"trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n" % (
        len(objs) + 1,
        xref,
    )
    return bytes(out)


def stream(dict_body: bytes, payload: bytes) -> bytes:
    return dict_body[:-2] + b" /Length %d >>\nstream\n" % len(payload) + payload + b"\nendstream"


def jp2_with_icc(profile: bytes) -> bytes:
    """A lossless 8x8 JP2 of one constant colour whose `colr` box carries `profile`.

    Pillow writes an enumerated `colr` (METH 1, sRGB) and ignores
    `icc_profile` for JPEG 2000, so the box is rewritten here: METH 2 with the
    profile as payload, and the enclosing `jp2h` superbox's length corrected.
    The result is asserted to decode back to the same samples, so a fixture
    that half-works cannot be committed.
    """
    img = Image.new("RGB", (8, 8), SAMPLES)
    buf = io.BytesIO()
    img.save(buf, format="JPEG2000", irreversible=False, quality_mode="rates", quality_layers=[1])
    data = bytearray(buf.getvalue())
    assert data.startswith(b"\x00\x00\x00\x0cjP  "), "not a JP2 signature box"

    # Walk the top-level boxes to find jp2h, then its colr child.
    pos = 0
    jp2h = None
    while pos < len(data):
        (length,) = struct.unpack(">I", data[pos : pos + 4])
        kind = bytes(data[pos + 4 : pos + 8])
        if kind == b"jp2h":
            jp2h = (pos, length)
            break
        pos += length
    assert jp2h is not None, "no jp2h box"
    hpos, hlen = jp2h
    cpos = hpos + 8
    colr = None
    while cpos < hpos + hlen:
        (length,) = struct.unpack(">I", data[cpos : cpos + 4])
        kind = bytes(data[cpos + 4 : cpos + 8])
        if kind == b"colr":
            colr = (cpos, length)
            break
        cpos += length
    assert colr is not None, "no colr box inside jp2h"
    cpos, clen = colr
    assert data[cpos + 8] == 1, "expected Pillow's enumerated colr (METH 1)"
    new_colr = struct.pack(">I", 8 + 3 + len(profile)) + b"colr" + bytes([2, 0, 0]) + profile
    data[cpos : cpos + clen] = new_colr
    struct.pack_into(">I", data, hpos, hlen - clen + len(new_colr))
    out = bytes(data)

    back = Image.open(io.BytesIO(out))
    back.load()
    assert back.tobytes() == img.tobytes(), "JPEG 2000 round trip was not lossless"
    # Pillow does not surface a JP2 `colr` profile, so the box is re-walked
    # here rather than trusted: the profile must be found at METH 2, byte for
    # byte, inside a jp2h whose length still spans its children exactly.
    (hlen2,) = struct.unpack(">I", out[hpos : hpos + 4])
    found = None
    p = hpos + 8
    while p < hpos + hlen2:
        (length,) = struct.unpack(">I", out[p : p + 4])
        if out[p + 4 : p + 8] == b"colr":
            assert out[p + 8] == 2, "colr METH is not 2 (restricted ICC)"
            found = out[p + 11 : p + length]
        p += length
    assert p == hpos + hlen2, "jp2h length does not span its children"
    assert found == profile, "the rewritten colr box did not carry the profile"
    return out


def page(objs: dict[int, bytes], *, group: bytes, intent: bytes) -> None:
    """Four 60x60 pt boxes in a row, 10 pt apart, on a 300x100 page.

    Box 1 is the fill, 2 the direct image, 3 the `/Indexed` image, 4 the
    JPEG 2000 image. Each is sampled well inside by the test.
    """
    objs[1] = b"<< /Type /Catalog /Pages 2 0 R " + intent + b">>"
    objs[2] = b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>"
    objs[3] = (
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 100] "
        + group
        + b"/Resources << /ColorSpace << /Cs0 6 0 R /Cs1 7 0 R >> "
        b"/XObject << /Im0 8 0 R /Im1 9 0 R /Im2 10 0 R >> >> /Contents 4 0 R >>"
    )
    operands = b" ".join(b"%.10g" % v for v in OPERANDS)
    content = (
        b"q /Cs0 cs " + operands + b" scn 10 20 60 60 re f Q\n"
        b"q 60 0 0 60 80 20 cm /Im0 Do Q\n"
        b"q 60 0 0 60 150 20 cm /Im1 Do Q\n"
        b"q 60 0 0 60 220 20 cm /Im2 Do Q"
    )
    objs[4] = stream(b"<< >>", content)


def write(name: str, data: bytes) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / name).write_bytes(data)
    print(f"  {name}  {len(data)} bytes")


def main() -> int:
    print(f"writing to {OUT}")
    print(f"expected managed pixel: {EXPECTED}   unmanaged: {SAMPLES}")

    profile = swap_rg_profile()
    write("swap-rg.icc", profile)
    dest = (OUT / "dest-cmyk.icc").read_bytes()
    assert dest[16:20] == b"CMYK", "dest-cmyk.icc is not a CMYK profile"
    jp2 = jp2_with_icc(profile)

    for name, group, with_intent in [
        ("icc-rgb-four-ways-additive.pdf", b"", False),
        (
            "icc-rgb-four-ways-subtractive-no-intent.pdf",
            b"/Group << /S /Transparency /CS /DeviceCMYK >> ",
            False,
        ),
        (
            "icc-rgb-four-ways-subtractive.pdf",
            b"/Group << /S /Transparency /CS /DeviceCMYK >> ",
            True,
        ),
    ]:
        objs: dict[int, bytes] = {}
        intent = b"/OutputIntents [11 0 R] " if with_intent else b""
        page(objs, group=group, intent=intent)
        objs[5] = stream(b"<< /N 3 >>", profile)
        objs[6] = b"[/ICCBased 5 0 R]"
        objs[7] = b"[/Indexed 6 0 R 0 <%02X%02X%02X>]" % SAMPLES
        objs[8] = stream(
            b"<< /Type /XObject /Subtype /Image /Width 8 /Height 8 "
            b"/BitsPerComponent 8 /ColorSpace 6 0 R >>",
            bytes(SAMPLES) * 64,
        )
        objs[9] = stream(
            b"<< /Type /XObject /Subtype /Image /Width 8 /Height 8 "
            b"/BitsPerComponent 8 /ColorSpace 7 0 R >>",
            bytes([0]) * 64,
        )
        # ★ No /ColorSpace: Table 89 lets a JPX image omit it, and then §7.4.9
        # says the codestream's own specification — here the ICC profile in
        # its colr box — shall be used.
        objs[10] = stream(
            b"<< /Type /XObject /Subtype /Image /Width 8 /Height 8 "
            b"/Filter /JPXDecode >>",
            jp2,
        )
        if with_intent:
            objs[11] = (
                b"<< /Type /OutputIntent /S /GTS_PDFX "
                b"/OutputConditionIdentifier (pdfcer synthetic CMYK) "
                b"/DestOutputProfile 12 0 R >>"
            )
            objs[12] = stream(b"<< /N 4 >>", dest)
        write(name, build(objs))
    return 0


if __name__ == "__main__":
    sys.exit(main())
