"""Generate the font-inventory fixtures for `pdfcer_core::fontinfo` (Pass 67.0A).

Every file here exists to pin ONE branch of the inventory sweep or of the
removability classifier, and each is named for that branch. They are written
by hand, object by object, rather than through a PDF library, for the same
reason the rest of this project's generators are: the point of a fixture is
that its exact structure is known and deliberate, and a library that
"helpfully" normalises a resource dictionary would silently defeat the test
that reads it.

Project rule 7 (test-corpus sourcing): every byte here is synthetic and
self-authored. The embedded font programs are the project's own
`fixtures/synthetic/text/subset-fstype-*.ttf` donors, generated by
`tools/gen-subset-font-fixtures.py`. The one `/FontFile` (Type 1) payload is
a deliberate non-program: a run of filler bytes with the `/Length1`,
`/Length2`, `/Length3` split declared. Nothing reads it as a font — the only
assertions against it are its stored size and the fact that a Type 1 program
has no `OS/2` table, both of which are true of filler.

★ WHY THE ENCRYPTED FIXTURE IS HERE AND NOT IN `encryption/`

`fixtures/synthetic/encryption/enc-aes-128.pdf` was assumed (in the Pass 67.0
brief) to exercise the `data_span`-vs-`/Length` hazard for fonts. It does
not: its source document is `forms/demo-form.pdf`, whose only font is a
base-14 `/Helvetica` with **no embedded program at all**. There is nothing
for a font-size reader to measure, so the hazard is not reached.

`enc-aes-128-embedded-font.pdf` closes that. It is `subset-simple-embedded.pdf`
— which really does carry a `/FontFile2` — encrypted by **pypdf**, an
independent implementation, exactly as `gen-encryption-fixtures.py` argues:
agreement between pdfcer's spec-derived decryption and a file pdfcer did not
produce is evidence; agreement with its own output would not be.

Passwords match the rest of the encryption corpus: user `userpw`, owner
`ownerpw`.

Usage:  python tools/gen-fontinfo-fixtures.py
"""

import os
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..'))
TEXT = os.path.join(ROOT, 'fixtures', 'synthetic', 'text')
OUT = os.path.join(ROOT, 'fixtures', 'synthetic', 'fontinfo')

os.makedirs(OUT, exist_ok=True)


def donor(name):
    """Read one of the project's own synthetic sfnt donors."""
    with open(os.path.join(TEXT, f'subset-fstype-{name}.ttf'), 'rb') as f:
        return f.read()


def build(objects, root):
    """Serialise a 1-based list of object bodies into a classic-xref PDF.

    `objects[i]` is the body of object `i + 1`, as bytes. `root` is the
    object number of the catalog. The xref table is written in the plain
    §7.5.4 form — no xref streams, no object streams — because a fixture
    that needs a compressed-object parser to be read is testing two things
    at once.
    """
    out = bytearray(b'%PDF-1.7\n%\xe2\xe3\xcf\xd3\n')
    offsets = []
    for i, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += f'{i} 0 obj\n'.encode('ascii') + body + b'\nendobj\n'
    xref = len(out)
    out += f'xref\n0 {len(objects) + 1}\n'.encode('ascii')
    out += b'0000000000 65535 f \n'
    for off in offsets:
        out += f'{off:010d} 00000 n \n'.encode('ascii')
    out += (
        f'trailer\n<< /Size {len(objects) + 1} /Root {root} 0 R >>\n'
        f'startxref\n{xref}\n%%EOF\n'
    ).encode('ascii')
    return bytes(out)


def stream(dict_body, payload, compress=False):
    """A stream object: dictionary text plus payload, `/Length` correct."""
    if compress:
        payload = zlib.compress(payload)
        dict_body = dict_body.rstrip()[:-2] + b' /Filter /FlateDecode >>'
    head = dict_body.rstrip()
    assert head.endswith(b'>>')
    head = head[:-2] + f' /Length {len(payload)} >>'.encode('ascii')
    return head + b'\nstream\n' + payload + b'\nendstream'


def write(name, data):
    path = os.path.join(OUT, name)
    with open(path, 'wb') as f:
        f.write(data)
    print(f'  {name:44s} {len(data):7d} bytes')


# ---------------------------------------------------------------------------
# 1. Type 3 font, whose own /Resources names a further font.
#
#    Pins two things at once: `Removability::BlockedType3` (a Type 3 font's
#    glyphs are content streams in THIS document, so there is no program to
#    strip and no installed face that could stand in), and the
#    `Surface::Type3CharProcs` walk — the inner font is reachable from
#    nowhere else in the file.
# ---------------------------------------------------------------------------
def type3():
    charproc = stream(b'<< >>', b'10 0 0 0 0 0 d0\n1 0 0 rg\n0 0 10 10 re f\n')
    objs = [
        b'<< /Type /Catalog /Pages 2 0 R >>',
        b'<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
        b'<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] '
        b'/Resources << /Font << /T3 5 0 R >> >> /Contents 4 0 R >>',
        stream(b'<< >>', b'BT /T3 12 Tf 20 100 Td (a) Tj ET\n'),
        # The Type 3 font. Its /Resources is the surface under test.
        b'<< /Type /Font /Subtype /Type3 /FontBBox [0 0 10 10] '
        b'/FontMatrix [0.001 0 0 0.001 0 0] /CharProcs 6 0 R '
        b'/Encoding << /Type /Encoding /Differences [97 /square] >> '
        b'/FirstChar 97 /LastChar 97 /Widths [10] '
        b'/Resources << /Font << /Inner 7 0 R >> >> >>',
        b'<< /square 8 0 R >>',
        # Reachable ONLY through the Type 3 font's own resources.
        b'<< /Type /Font /Subtype /Type1 /BaseFont /Courier '
        b'/Encoding /WinAnsiEncoding >>',
        charproc,
    ]
    return build(objs, 1)


# ---------------------------------------------------------------------------
# 2. Symbolic TrueType with an embedded program and NO /Encoding.
#
#    §9.6.6.1: with no /Encoding the program's built-in encoding governs, and
#    for a symbolic font that is the program's own `cmap` table — inside the
#    bytes an unembed would delete. Classifies as
#    `Unknown(SymbolicBuiltinEncoding)`, which is deliberately neither
#    "removable" nor "blocked": pdfcer genuinely cannot tell.
#
#    The donor is the `Editable` fsType face, so the same fixture also pins a
#    successful `fsType` read through a `/FontFile2`.
# ---------------------------------------------------------------------------
def symbolic_builtin():
    program = donor('editable')
    objs = [
        b'<< /Type /Catalog /Pages 2 0 R >>',
        b'<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
        b'<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] '
        b'/Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',
        stream(b'<< >>', b'BT /F1 12 Tf 20 100 Td (\\001) Tj ET\n'),
        # No /Encoding at all. /Flags 4 == Symbolic (Table 123, bit 3).
        b'<< /Type /Font /Subtype /TrueType /BaseFont /SYMBOL+pdfceSymbolic '
        b'/FirstChar 1 /LastChar 1 /Widths [500] /FontDescriptor 6 0 R >>',
        b'<< /Type /FontDescriptor /FontName /SYMBOL+pdfceSymbolic /Flags 4 '
        b'/FontBBox [0 0 1000 1000] /ItalicAngle 0 /Ascent 800 /Descent -200 '
        b'/CapHeight 700 /StemV 80 /FontFile2 7 0 R >>',
        stream(f'<< /Length1 {len(program)} >>'.encode('ascii'), program),
    ]
    return build(objs, 1)


# ---------------------------------------------------------------------------
# 3. Type 0 with a PREDEFINED, non-Identity CMap.
#
#    The codes map to CIDs in a named character collection, so a substitute
#    font built for that collection would work — but whether one exists is
#    not knowable from the document. `Unknown(PredefinedCMap)`, and
#    deliberately NOT `BlockedIdentityEncoded`: the distinction between "the
#    codes are glyph indices into this program" and "the codes are CIDs in a
#    public collection" is the whole reason the verdict is an enum.
# ---------------------------------------------------------------------------
def predefined_cmap():
    program = donor('installable')
    objs = [
        b'<< /Type /Catalog /Pages 2 0 R >>',
        b'<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
        b'<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] '
        b'/Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',
        stream(b'<< >>', b'BT /F1 12 Tf 20 100 Td <0001> Tj ET\n'),
        b'<< /Type /Font /Subtype /Type0 /BaseFont /pdfceJIS '
        b'/Encoding /UniJIS-UCS2-H /DescendantFonts [6 0 R] >>',
        b'<< /Type /Font /Subtype /CIDFontType2 /BaseFont /pdfceJIS '
        b'/CIDSystemInfo << /Registry (Adobe) /Ordering (Japan1) /Supplement 6 >> '
        b'/FontDescriptor 7 0 R /DW 1000 /CIDToGIDMap /Identity >>',
        b'<< /Type /FontDescriptor /FontName /pdfceJIS /Flags 4 '
        b'/FontBBox [0 0 1000 1000] /ItalicAngle 0 /Ascent 800 /Descent -200 '
        b'/CapHeight 700 /StemV 80 /FontFile2 8 0 R >>',
        stream(f'<< /Length1 {len(program)} >>'.encode('ascii'), program),
    ]
    return build(objs, 1)


# ---------------------------------------------------------------------------
# 4. Type 1 with a `/FontFile` program.
#
#    The only descriptor key with no `OS/2` concept whatsoever, so the
#    fixture pins `FsType::NotApplicable` — which must render differently
#    from both a permission value and an unreadable one, because `fsType == 0`
#    genuinely MEANS "installable" and an absent field must never look like
#    it.
#
#    The payload is filler, not a Type 1 program (see the module docstring).
#    A FlateDecode filter is applied so the fixture also pins the
#    stored-vs-decoded size distinction: the stored figure is what removing
#    the object recovers from the file, the decoded figure is how big the
#    program actually is, and they differ here by construction.
# ---------------------------------------------------------------------------
def fontfile_type1():
    payload = b'%!PS-AdobeFont-1.0: pdfceFiller\n' + b'A' * 512 + b'\n' + b'0' * 512 + b'\ncleartomark\n'
    l1, l2 = 32, 513
    l3 = len(payload) - l1 - l2
    objs = [
        b'<< /Type /Catalog /Pages 2 0 R >>',
        b'<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
        b'<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] '
        b'/Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',
        stream(b'<< >>', b'BT /F1 12 Tf 20 100 Td (Hi) Tj ET\n'),
        b'<< /Type /Font /Subtype /Type1 /BaseFont /QWERTY+pdfceType1 '
        b'/FirstChar 72 /LastChar 105 /Widths ' + (b'[' + b' 500' * 34 + b' ]') +
        b' /Encoding /WinAnsiEncoding /FontDescriptor 6 0 R >>',
        b'<< /Type /FontDescriptor /FontName /QWERTY+pdfceType1 /Flags 32 '
        b'/FontBBox [0 0 1000 1000] /ItalicAngle 0 /Ascent 800 /Descent -200 '
        b'/CapHeight 700 /StemV 80 /FontFile 7 0 R >>',
        stream(
            f'<< /Length1 {l1} /Length2 {l2} /Length3 {l3} >>'.encode('ascii'),
            payload,
            compress=True,
        ),
    ]
    return build(objs, 1)


# ---------------------------------------------------------------------------
# 5. A font reachable ONLY through a form XObject nested inside an annotation
#    appearance stream.
#
#    This is the coverage claim's falsifier. `SurfaceCoverage` asserts that
#    annotation appearance streams and nested form XObjects are both walked;
#    without a file where a font hides behind BOTH at once, that assertion is
#    a marker confirming itself (R186). The font is named from nowhere else
#    in the document, so an inventory that misses either hop misses it
#    entirely — the failure is a missing row, not a wrong field.
# ---------------------------------------------------------------------------
def nested_ap_xobject():
    objs = [
        b'<< /Type /Catalog /Pages 2 0 R >>',
        b'<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
        b'<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] '
        b'/Resources << >> /Contents 4 0 R /Annots [5 0 R] >>',
        stream(b'<< >>', b'0 0 0 rg\n'),
        b'<< /Type /Annot /Subtype /Square /Rect [10 10 110 60] /F 4 '
        b'/AP << /N 6 0 R >> >>',
        # The appearance stream. Its resources hold ONLY a form XObject.
        stream(
            b'<< /Type /XObject /Subtype /Form /BBox [0 0 100 50] '
            b'/Resources << /XObject << /Deep 7 0 R >> >> >>',
            b'q /Deep Do Q\n',
        ),
        # The nested form XObject. THIS is where the font lives.
        stream(
            b'<< /Type /XObject /Subtype /Form /BBox [0 0 100 50] '
            b'/Resources << /Font << /Hidden 8 0 R >> >> >>',
            b'BT /Hidden 10 Tf 2 2 Td (deep) Tj ET\n',
        ),
        b'<< /Type /Font /Subtype /Type1 /BaseFont /pdfceHiddenInAppearance '
        b'/Encoding /WinAnsiEncoding >>',
    ]
    return build(objs, 1)


# ---------------------------------------------------------------------------
# 6. A descriptor whose `/FontFile2` reference dangles.
#
#    §7.3.10 makes a dangling reference a `null`, not an error, so the
#    document loads fine and the font looks embedded until you try to read
#    the program. "Declared but unreadable" is a different fact from "not
#    embedded" — the first is damage, the second is a document relying on
#    substitution — and they lead to different operator actions, so
#    `Program::Unreadable` and `Program::NotEmbedded` are different states.
# ---------------------------------------------------------------------------
def unreadable_program():
    objs = [
        b'<< /Type /Catalog /Pages 2 0 R >>',
        b'<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
        b'<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] '
        b'/Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',
        stream(b'<< >>', b'BT /F1 12 Tf 20 100 Td (Hi) Tj ET\n'),
        b'<< /Type /Font /Subtype /TrueType /BaseFont /pdfceBroken '
        b'/FirstChar 72 /LastChar 73 /Widths [500 500] '
        b'/Encoding /WinAnsiEncoding /FontDescriptor 6 0 R >>',
        # Object 99 does not exist.
        b'<< /Type /FontDescriptor /FontName /pdfceBroken /Flags 32 '
        b'/FontBBox [0 0 1000 1000] /ItalicAngle 0 /Ascent 800 /Descent -200 '
        b'/CapHeight 700 /StemV 80 /FontFile2 99 0 R >>',
    ]
    return build(objs, 1)


# ---------------------------------------------------------------------------
# 7. A font reachable only through an `/ExtGState /SMask /G` group.
#
#    §11.6.5.2: a soft mask's `/G` is a transparency-group form XObject with
#    its own content and its own resources. Nothing else in the resource
#    walk reaches it — not `/XObject`, not `/Pattern` — so a sweep that
#    covers the obvious two still misses this one.
# ---------------------------------------------------------------------------
def softmask_group():
    objs = [
        b'<< /Type /Catalog /Pages 2 0 R >>',
        b'<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
        b'<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] '
        b'/Resources << /ExtGState << /GS0 5 0 R >> >> /Contents 4 0 R >>',
        stream(b'<< >>', b'q /GS0 gs 0 0 100 100 re f Q\n'),
        b'<< /Type /ExtGState /SMask << /S /Luminosity /G 6 0 R >> >>',
        stream(
            b'<< /Type /XObject /Subtype /Form /BBox [0 0 100 100] '
            b'/Group << /S /Transparency /CS /DeviceGray >> '
            b'/Resources << /Font << /Masked 7 0 R >> >> >>',
            b'BT /Masked 10 Tf 2 2 Td (mask) Tj ET\n',
        ),
        b'<< /Type /Font /Subtype /Type1 /BaseFont /pdfceInSoftMask '
        b'/Encoding /WinAnsiEncoding >>',
    ]
    return build(objs, 1)


FILES = [
    ('type3-charprocs.pdf', type3),
    ('symbolic-builtin-encoding.pdf', symbolic_builtin),
    ('predefined-cmap.pdf', predefined_cmap),
    ('fontfile-type1.pdf', fontfile_type1),
    ('nested-ap-xobject.pdf', nested_ap_xobject),
    ('unreadable-program.pdf', unreadable_program),
    ('softmask-group.pdf', softmask_group),
]

print(f'outdir: {OUT}')
for name, fn in FILES:
    write(name, fn())

# ---------------------------------------------------------------------------
# 8. The encrypted fixture — see the ★ note in the module docstring.
# ---------------------------------------------------------------------------
try:
    from pypdf import PdfWriter
except ImportError:  # pragma: no cover - developer convenience
    print('  pypdf not installed; skipping enc-aes-128-embedded-font.pdf')
else:
    src = os.path.join(TEXT, 'subset-simple-embedded.pdf')
    w = PdfWriter(clone_from=src)
    w.encrypt(user_password='userpw', owner_password='ownerpw', algorithm='AES_128')
    path = os.path.join(OUT, 'enc-aes-128-embedded-font.pdf')
    with open(path, 'wb') as f:
        w.write(f)
    print(f'  {"enc-aes-128-embedded-font.pdf":44s} {os.path.getsize(path):7d} bytes')
