#!/usr/bin/env python3
"""Generate the four field-tree shapes on which `delete_field_group`'s two
derivations of "how many grouping nodes went" disagree.

WHY THESE FOUR EXIST
====================

`EditSession::delete_field_group` computes the same quantity twice:

* `group_deletion_preflight` predicts it by walking `form.groups` **by NAME**;
* `remove_fields_from_form` performs it by walking `/Parent` **by OBJECT**.

A `debug_assert_eq!` compares them, and a fuzz target tripped it in 2026-08-30.
The assertion is compiled out of the build operators run, so the *stated*
severity was "a wrong `nodes_removed` in a disclosure". Building these four
fixtures showed that was the mildest of what the disagreement covers: three of
them are visible in the RELEASE build, one of them writes a dangling reference
into the saved file, and one returns `Ok` having done nothing at all.

Nothing here is exotic. Every shape is legal PDF that a real producer emits.

THE SHAPES
==========

`t-less-child.pdf` -- a `/T`-less TERMINAL under a named group.
    §12.7.3.2: a node with no `/T` contributes no segment to the fully
    qualified name, so the child's FQN *equals* its parent's. `descendants_of`
    is a string-prefix match on `"{fqn}."`, which such a child never matches,
    so the subtree is invisible to a name-keyed search. The deletion selects
    nothing and reports success.

`duplicate-t.pdf` -- two sibling grouping nodes with the SAME `/T`.
    Nothing in the standard forbids it. Two nodes then share one FQN, and a
    `Vec<String>` keyed by name cannot represent them separately: the
    prediction collapses them to one entry while the cascade removes both.

`t-less-intermediate.pdf` -- a `/T`-less node BETWEEN two named ones.
    The legal, ordinary way two grouping nodes come to share a name: the
    middle node silently aliases its parent's. Same collapse as above, without
    anybody having written a duplicate name.

`orphan-no-parent.pdf` -- a terminal reachable from `/Kids` with NO `/Parent`.
    §12.7.3.1 makes `/Parent` required for a non-root field, so this is a
    malformed file -- but it is the malformation a fuzzer reaches in seconds
    and a truncated real-world file reaches by accident, and pdfcer's §10
    posture is to degrade rather than refuse. The cascade derives each node's
    container from `/Parent`, so a child without one is deleted while the
    `/Kids` array still naming it is never patched. **That writes a dangling
    reference into the file, in release, with `Ok` returned.**

Hand-rolled rather than produced by `pdfcer`, for the reason the sibling
generator gives: a fixture generated by the program under test cannot falsify
that program.

Provenance: wholly synthetic, `LEGAL.md` §5 category (a). Nothing downloaded.
"""

import pathlib

OUT = (
    pathlib.Path(__file__).resolve().parent.parent
    / "fixtures"
    / "synthetic"
    / "forms"
)


def assemble(objects: list[bytes]) -> bytes:
    """Wrap emitted object bodies in a header, xref table and trailer."""
    out = bytearray(b"%PDF-1.7\n%\xe2\xe3\xcf\xd3\n")
    offsets = [0]
    for i, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += str(i).encode() + b" 0 obj\n" + body + b"\nendobj\n"
    startxref = len(out)
    n = len(objects) + 1
    out += b"xref\n0 " + str(n).encode() + b"\n0000000000 65535 f \n"
    for off in offsets[1:]:
        out += f"{off:010d} 00000 n \n".encode()
    out += (
        b"trailer\n<< /Size " + str(n).encode() + b" /Root 1 0 R >>\n"
        b"startxref\n" + str(startxref).encode() + b"\n%%EOF\n"
    )
    return bytes(out)


def doc(fields_roots: bytes, extra: list[bytes]) -> bytes:
    """Catalog + one page + an `/AcroForm` whose `/Fields` names `fields_roots`.

    The page carries no `/Annots`: these shapes are about the FIELD TREE, and
    a widget on the page would add a second removal cascade that has nothing
    to do with the quantity being measured. Keeping them apart is what makes a
    failure here readable.
    """
    return assemble(
        [
            b"<< /Type /Catalog /Pages 2 0 R /AcroForm << /Fields "
            + fields_roots
            + b" >> >>",
            b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
            b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] >>",
        ]
        + extra
    )


def t_less_child() -> bytes:
    """Group `A` whose only terminal has no `/T`.

    `parse_acroform` reports `fields = ["A"]` and `groups = [(4, "A")]` -- the
    terminal and the group bear the SAME name. That collision is also what
    makes this the one shape the existing `form_edit_sequence` fuzz target can
    reach, since it draws names from `form.fields`.
    """
    return doc(
        b"[4 0 R]",
        [
            b"<< /T (A) /Kids [5 0 R] >>",
            b"<< /FT /Tx /Parent 4 0 R >>",
        ],
    )


def duplicate_t() -> bytes:
    """Two roots both named `A`, each with a distinct terminal beneath it."""
    return doc(
        b"[4 0 R 5 0 R]",
        [
            b"<< /T (A) /Kids [6 0 R] >>",
            b"<< /T (A) /Kids [7 0 R] >>",
            b"<< /FT /Tx /T (X) /Parent 4 0 R >>",
            b"<< /FT /Tx /T (Y) /Parent 5 0 R >>",
        ],
    )


def t_less_intermediate() -> bytes:
    """`A` -> (no `/T`) -> `X`, so the middle node's FQN is also `A`."""
    return doc(
        b"[4 0 R]",
        [
            b"<< /T (A) /Kids [5 0 R] >>",
            b"<< /Kids [6 0 R] /Parent 4 0 R >>",
            b"<< /FT /Tx /T (X) /Parent 5 0 R >>",
        ],
    )


def orphan_no_parent() -> bytes:
    """`A` -> `X`, where `X` carries no `/Parent` back-link.

    Reachable downward from `/Kids`, invisible upward. This is the shape that
    writes a dangling `/Kids` entry.
    """
    return doc(
        b"[4 0 R]",
        [
            b"<< /T (A) /Kids [5 0 R] >>",
            b"<< /FT /Tx /T (X) >>",
        ],
    )


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for name, data in {
        "group-delete-t-less-child.pdf": t_less_child(),
        "group-delete-duplicate-t.pdf": duplicate_t(),
        "group-delete-t-less-intermediate.pdf": t_less_intermediate(),
        "group-delete-orphan-no-parent.pdf": orphan_no_parent(),
    }.items():
        (OUT / name).write_bytes(data)
        print(f"wrote {OUT / name}  ({len(data)} bytes)")


if __name__ == "__main__":
    main()
