#!/usr/bin/env python3
"""Generate the three documents whose page `/Annots` names something that is
not an annotation.

WHY THESE EXIST
===============

`annot::page_annotations` accepts any `/Annots` entry that resolves to a
dictionary. That is correct for a READER under `ARCHITECTURE.md` §10's
fail-clean posture -- one odd entry must not cost the operator the page -- and
it is a hole under a DELETION, which removes the object the entry names.

`fuzz/fuzz_targets/annot_delete_sequence.rs` found it seconds after that target
first existed, on a 173-byte input: a page whose `/Annots` named the **document
catalog**. `delete_annotation` deleted the catalog, returned `Ok`, and produced
a file with no page-tree root. The only thing that noticed was a
`#[cfg(debug_assertions)]` postcondition, compiled out of the build operators
run.

These three fixtures are that input made loadable, plus the two neighbours the
guard has to tell apart.

★ THE THIRD ONE IS THE LOAD-BEARING FIXTURE. `structural-annots-mixed.pdf`
carries a REAL annotation beside a structural entry, so a "fix" that simply
refuses every deletion fails it. Without that file the other two would pass on
an engine that had stopped working entirely.

Provenance: wholly synthetic, `LEGAL.md` §5 category (a). A fuzzer's mutation
of pdfcer's own generated bytes is pdfcer's own bytes; nothing was downloaded.
"""

import pathlib

OUT = (
    pathlib.Path(__file__).resolve().parent.parent
    / "fixtures"
    / "synthetic"
    / "annot"
)


def assemble(objects: list[bytes], root: int = 1) -> bytes:
    """Wrap object bodies in a header, xref table and trailer.

    Hand-rolled rather than produced by `pdfcer`, for the reason the sibling
    generators give: a fixture generated by the program under test cannot
    falsify that program.
    """
    out = bytearray(b"%PDF-1.7\n%\xe2\xe3\xcf\xd3\n")
    offsets = [0]
    for i, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += str(i).encode() + b" 0 obj\n" + body + b"\nendobj\n"
    startxref = len(out)
    n = len(objects) + 1
    out += b"xref\n0 " + str(n).encode() + b"\n0000000000 65535 f \n"
    for off in offsets[1:]:
        out += f"{off:010d} 00000 n \n".encode()
    out += (
        b"trailer\n<< /Size " + str(n).encode() + b" /Root "
        + str(root).encode() + b" 0 R >>\nstartxref\n"
        + str(startxref).encode() + b"\n%%EOF\n"
    )
    return bytes(out)


def catalog_in_annots() -> bytes:
    """The reduced crash input: `/Annots` names the CATALOG (object 1).

    The fuzzer's 173 bytes had a truncated tail and no xref; this is the same
    graph, closed so it loads. `1 0 R` in `/Annots` is the whole defect.
    """
    return assemble(
        [
            b"<< /Type /Catalog /Pages 2 0 R >>",
            b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
            b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] "
            b"/Resources << >> /Annots [1 0 R] >>",
        ]
    )


def pages_node_in_annots() -> bytes:
    """The `BadKid` signature: `/Annots` names the page-tree NODE (object 2).

    Reaches the page-tree half of the guard rather than the `/Type` half, which
    is why it is a separate file and not a second entry in the first one.
    """
    return assemble(
        [
            b"<< /Type /Catalog /Pages 2 0 R >>",
            b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
            b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] "
            b"/Resources << >> /Annots [2 0 R] >>",
        ]
    )


def mixed() -> bytes:
    """A REAL `/Square` annotation beside the catalog in one `/Annots`.

    The control. A guard that refuses everything passes the two files above and
    fails this one.
    """
    return assemble(
        [
            b"<< /Type /Catalog /Pages 2 0 R >>",
            b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
            b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] "
            b"/Resources << >> /Annots [4 0 R 1 0 R] >>",
            b"<< /Type /Annot /Subtype /Square /Rect [10 10 60 60] "
            b"/F 4 /C [1 0 0] >>",
        ]
    )


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for name, data in {
        "structural-annots-catalog.pdf": catalog_in_annots(),
        "structural-annots-pages-node.pdf": pages_node_in_annots(),
        "structural-annots-mixed.pdf": mixed(),
    }.items():
        (OUT / name).write_bytes(data)
        print(f"wrote {OUT / name}  ({len(data)} bytes)")


if __name__ == "__main__":
    main()
