#!/usr/bin/env python3
"""Regenerate the spot-colorant-in-a-transparency-group fixtures
(`fixtures/synthetic/transparency/spot_*.pdf`, `Pass 239.0`).

WHY THIS EXISTS
---------------
`Pass 225.0` gave the colorant buffer one plane per spot colorant, and
`Passes 228.0`-`239.0` taught every paint route to deposit into it. A
transparency group is rendered into a CHILD buffer and merged back into its
parent, and until `Pass 239.0` that merge copied spot planes BY INDEX: a
child's plane 0 landed in the parent's plane 0 whatever colorant either held,
or -- when the parent had allocated fewer planes than the child -- was dropped
by `set_pixel`'s surplus-dropping zip. Silently. So a spot painted inside any
buffered group on an ink page either changed colorant or vanished.

That is not an exotic shape. It is an Illustrator file with a Pantone swatch
at 50 % opacity, which is a transparency group around a spot fill.

THE ORACLE
----------
The same oracle every other spot fixture uses: the same authored paint drawn
twice on one page, once directly and once through the construct under test,
and the two must agree. No reference render, no remembered colour. A merge
that drops the plane leaves the right-hand box white where the left-hand box
is green; a merge that mis-indexes it leaves the right-hand box the wrong
colorant.

| file | the construct on the right | what a wrong merge looks like |
|---|---|---|
| `spot_in_isolated_group_vs_fill.pdf` | the spot fill inside an ISOLATED group (`/I true` forces a child buffer) at full opacity | white: the child's only plane had no parent plane to land in |
| `spot_in_nonisolated_group_vs_fill.pdf` | the spot fill, MULTIPLYING, inside a NON-isolated group at `/ca 0.5` over a process backdrop (the interior blend is what forces the two-walk route; the group is painted before the direct fill so its colorant is new to the parent) | white: `composite_non_isolated` built its source with an empty spot array, and the merge had no plane to allocate |
| `spot_under_knockout_group_vs_direct.pdf` | a spot backdrop, then a KNOCKOUT group whose one element is a 50 % opaque MULTIPLYING process fill; compared to the same element painted directly (under Normal the backdrop removal hides a missing initial spot exactly; Multiply reads it) | the spot gone beneath the element: the knockout's initial backdrop carried no spot planes |

Both boxes of each pair sit at the same y and the same size, so a test samples
well inside either. The spot ink is a saturated green so that "present" and
"absent" differ in hue, not merely in lightness.

The writer is hand-rolled rather than delegated to `pdfcer`, for the
reason every sibling generator states: a fixture generated by the program
under test cannot falsify that program.
"""

import pathlib
import sys

OUT = pathlib.Path(__file__).resolve().parent.parent / "fixtures" / "synthetic" / "transparency"

SPOT_TINT = b"<< /FunctionType 2 /Domain [0 1] /C0 [0 0 0 0] /C1 [0.9 0.0 0.75 0.1] /N 1 >>"


def assemble(objects: list[bytes]) -> bytes:
    out = bytearray(b"%PDF-1.7\n%\xe2\xe3\xcf\xd3\n")
    offsets = [0]
    for i, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += str(i).encode() + b" 0 obj\n" + body + b"\nendobj\n"
    startxref = len(out)
    n = len(objects) + 1
    out += b"xref\n0 " + str(n).encode() + b"\n0000000000 65535 f \n"
    for off in offsets[1:]:
        out += f"{off:010d} 00000 n \n".encode()
    out += (
        b"trailer\n<< /Size " + str(n).encode() + b" /Root 1 0 R >>\n"
        b"startxref\n" + str(startxref).encode() + b"\n%%EOF\n"
    )
    return bytes(out)


def stream(dict_entries: bytes, data: bytes) -> bytes:
    return (
        b"<< " + dict_entries + b" /Length " + str(len(data)).encode() + b" >>\nstream\n"
        + data + b"\nendstream"
    )


def page(content: bytes, form: bytes | None, gs: bytes, extra: list[bytes] | None = None) -> bytes:
    """A 200 x 100 ink page. Object 4 is the content, 5 the form (or a stub),
    6 the colour space, 7 its tint transform, 8 the ExtGState `/GS0`, 9-10 the
    decoy colorant, and 11.. -- when given -- extra objects, the first of
    which is `/GS1`."""
    gs1_ref = b"" if extra is None else b"/GS1 11 0 R "
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 100] "
        b"/Group << /S /Transparency /CS /DeviceCMYK /I true >> "
        b"/Resources << /ColorSpace << /Cs0 6 0 R /Cs1 9 0 R >> /XObject << /Fm0 5 0 R >> "
        b"/ExtGState << /GS0 8 0 R " + gs1_ref + b">> >> /Contents 4 0 R >>",
        stream(b"", content),
        form if form is not None else stream(
            b"/Type /XObject /Subtype /Form /BBox [0 0 200 100]", b""
        ),
        b"[/Separation /SpotGreen /DeviceCMYK 7 0 R]",
        SPOT_TINT,
        gs,
        # The decoy colorant: a blue spot the page names FIRST.
        b"[/Separation /SpotBlue /DeviceCMYK 10 0 R]",
        b"<< /FunctionType 2 /Domain [0 1] /C0 [0 0 0 0] /C1 [1 0.6 0 0] /N 1 >>",
    ]
    if extra is not None:
        objects.extend(extra)
    return assemble(objects)


def isolated() -> bytes:
    # Left: the spot fill directly. Right: the same fill inside an isolated
    # group at full opacity. `/I true` alone forces the child buffer.
    form = stream(
        b"/Type /XObject /Subtype /Form /BBox [0 0 200 100] "
        b"/Group << /S /Transparency /CS /DeviceCMYK /I true >> "
        b"/Resources << /ColorSpace << /Cs0 6 0 R >> >>",
        b"/Cs0 cs 0.7 scn 110 20 80 60 re f\n",
    )
    # ★ A DIFFERENT spot is painted FIRST, off to the side, so the parent's
    # plane 0 is SpotBlue and SpotGreen is its plane 1 -- while inside the
    # child, SpotGreen is plane 0. A merge by index would put the group's
    # green into the parent's BLUE plane. Without this decoy both buffers
    # happen to give the colorant index 0 and an index merge passes by luck
    # (measured: it did).
    content = (
        b"q /Cs1 cs 1 scn 0 0 8 8 re f Q\n"
        b"q /GS0 gs /Fm0 Do Q\n"
        b"q /Cs0 cs 0.7 scn 10 20 80 60 re f Q\n"
    )
    return page(content, form, b"<< /Type /ExtGState /BM /Normal /ca 1 /CA 1 >>")


def nonisolated() -> bytes:
    # A cyan process backdrop under both boxes. Left: the spot fill at 50 %
    # directly. Right: the same fill inside a NON-isolated group invoked at
    # `/ca 0.5` -- the alpha is what forces the two-walk buffer; a
    # non-isolated group under a neutral state is painted inline and would
    # prove nothing (see gen-nonisolated-group-fixtures.py).
    # ★ `/BM /Multiply` INSIDE the group, and it is what makes the fixture
    # reach `composite_non_isolated` at all. A non-isolated group whose
    # interior blends Normal gives the isolated result by §11.4.4 NOTE 2,
    # and the interpreter's `backdrop_dependent` test correctly takes the
    # one-walk route -- measured: `groups_backdrop_reruns=0`, and a
    # sabotage of the two-walk merge left the test green. Multiply reads
    # the backdrop, so the second walk runs. The direct paint on the left
    # multiplies at 50 % through `/GS1`; for one opaque element the two are
    # identical by §11.4.4's own arithmetic.
    form = stream(
        b"/Type /XObject /Subtype /Form /BBox [0 0 200 100] "
        b"/Group << /S /Transparency /CS /DeviceCMYK /I false >> "
        b"/Resources << /ColorSpace << /Cs0 6 0 R >> "
        b"/ExtGState << /GSI 12 0 R >> >>",
        b"/GSI gs /Cs0 cs 0.7 scn 110 20 80 60 re f\n",
    )
    content = (
        b"q /Cs1 cs 1 scn 0 0 8 8 re f Q\n"
        b"q 1 0 0 0 k 10 20 80 60 re f 110 20 80 60 re f Q\n"
        # ★ The GROUP comes first, so SpotGreen is a colorant the parent has
        # never seen when the child hands it back: the merge must ALLOCATE
        # it, not merely re-index it. With the direct fill first, the parent
        # already holds SpotGreen at the same index the child gives it, the
        # copied roster lines up, and a merge with no name mapping passes by
        # luck (measured: it did).
        b"q /GS0 gs /Fm0 Do Q\n"
        b"q /GS1 gs /Cs0 cs 0.7 scn 10 20 80 60 re f Q\n"
    )
    return page(
        content,
        form,
        b"<< /Type /ExtGState /BM /Normal /ca 0.5 /CA 0.5 >>",
        # 11: the direct paint's state -- multiply at 50 %.
        # 12: the form interior's state -- multiply at full opacity; the 50 %
        #     is applied once, to the group's result, by /GS0 at the Do.
        [
            b"<< /Type /ExtGState /BM /Multiply /ca 0.5 /CA 0.5 >>",
            b"<< /Type /ExtGState /BM /Multiply /ca 1 /CA 1 >>",
        ],
    )


def knockout() -> bytes:
    # A spot backdrop under both boxes. Left: a 50 % opaque `0 0 0 0.5 k`
    # fill directly over it. Right: the same fill as the ONE element of a
    # knockout group over the same backdrop. With a single element a
    # knockout group composites it against the initial backdrop -- which is
    # the spot -- and the two must agree; a knockout whose initial backdrop
    # carried no spot planes shows the element over white.
    form = stream(
        b"/Type /XObject /Subtype /Form /BBox [0 0 200 100] "
        b"/Group << /S /Transparency /CS /DeviceCMYK /I false /K true >> "
        b"/Resources << /ExtGState << /GSI 8 0 R >> >>",
        b"/GSI gs 0 0 0 0.5 k 110 20 80 60 re f\n",
    )
    # ★ `/BM /Multiply` on the element, and it is the whole fixture. Under
    # Normal a knockout group's backdrop removal exactly compensates for a
    # missing initial spot -- the direct paint and the group agree whether
    # or not the initial backdrop carried the plane (measured: they did).
    # Multiply READS the backdrop: ink over ink keeps the ink, so a knockout
    # whose initial backdrop has no spot plane multiplies against nothing
    # and comes out different from the direct paint beside it.
    content = (
        b"q /Cs0 cs 0.7 scn 10 20 80 60 re f 110 20 80 60 re f Q\n"
        b"q /GS0 gs 0 0 0 0.5 k 10 20 80 60 re f Q\n"
        b"q /Fm0 Do Q\n"
    )
    return page(content, form, b"<< /Type /ExtGState /BM /Multiply /ca 0.5 /CA 0.5 >>")


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    for name, data in {
        "spot_in_isolated_group_vs_fill.pdf": isolated(),
        "spot_in_nonisolated_group_vs_fill.pdf": nonisolated(),
        "spot_under_knockout_group_vs_direct.pdf": knockout(),
    }.items():
        (OUT / name).write_bytes(data)
        print(f"wrote {name} ({len(data)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
