#!/usr/bin/env python3
"""Regenerate fixtures/synthetic/type3/ - Type 3 fonts (ISO 32000-1 §9.6.5).

WHY THIS EXISTS
---------------
`Pass 126.0` renders Type 3 fonts, whose glyphs are **content streams** rather
than a font program. Two of the rules it has to honour are invisible in a
render that does not deliberately provoke them, and one of them was
**unrecorded for Acrobat** until these fixtures were used to measure it:

* Table 113's `d1` **colour prohibition** - a `d1` glyph procedure's own
  colour operators "shall be ignored" and the glyph takes the colour in force
  at the text-showing operator. `d0` declares the opposite.
* Table 112's **width units** - Type 3 widths are in `FontMatrix` units, NOT
  thousandths of text space. The spec corpus calls this the number-one Type 3
  bug: divide by 1000 *and* apply a typical `[0.001 ...]` matrix and the
  advance is off by a factor of a million.

★ EVERY FIXTURE HERE IS BUILT AROUND A CONTROL, and that is the whole design.
A single glyph that comes out blue proves nothing on its own - a renderer that
painted every Type 3 glyph blue would pass. It is the PAIR, same operator and
opposite outcome, that carries the result.

THE FILES
---------
| file | what it provokes | what only it can catch |
|---|---|---|
| `colour_and_advance.pdf` | `d0` vs `d1` colour, and the advance | a renderer that honours the procedure's colour on a `d1` glyph, or that divides a Type 3 width by 1000 |
| `missing_glyph_advances.pdf` | a code with no `/CharProcs` entry, between two that have one | a renderer that skips the whole code, which mis-positions every later glyph on the line |
| `resources_fallback.pdf` | a font with NO `/Resources` whose glyph names one | Table 112's page-resource fallback, which old files depend on |
| `self_recursive.pdf` | a glyph procedure that shows its own font | an unbounded reader - this is a stack overflow by construction |
| `tounicode_gate.pdf` | three Type 3 fonts, one WITH a `/ToUnicode` and two without | a reader that extracts no Type 3 text at all, and a per-font diagnostic that de-duplicates on the `/BaseFont` a Type 3 font does not have |

★ `colour_and_advance.pdf` IS ALSO THE ACROBAT ORACLE. Rows A-D of it were
rendered in Acrobat Reader on 2026-08-25 and answered a question the
Acrobat-parity corpus had recorded as an open GAP: Acrobat honours the `d1`
ignore (row A blue), treats `d0` as its opposite (row C red), and paints an
image-mask glyph in the graphics-state colour (row D blue). So pdfcer follows
the clause here in the knowledge that the clause and Acrobat agree, rather
than in hope. See
`D:\\Dev\\Rag-Specialized\\Acrobat_Features\\type3fonts__rendering_and_color_semantics.md`.

SOURCE MATERIAL AND LICENCE (LEGAL.md §5, project rule 7)
---------------------------------------------------------
**Nothing here derives from a third-party file.** `LEGAL.md` §5 category (a):
wholly synthetic, authored for this project, generated by this committed
script from geometry this project chose - filled boxes and an 8x8 bitmap.
Nothing was downloaded from anywhere.

Assembled byte by byte with a classic §7.5.4 cross-reference table, no object
streams, no compression, so a failing test can be read in a hex editor.

HOW TO REGENERATE
-----------------
    python tools/gen-type3-fixtures.py
"""

from __future__ import annotations

import io
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "fixtures" / "synthetic" / "type3"

PAGE_W, PAGE_H = 612, 720

# Glyph space is 1000 units/em via the conventional FontMatrix, so a 700-unit
# box at 40 pt is 28 pt and a 750-unit advance is 30 pt. Two numbers a test can
# measure, two points apart, which no rounding can confuse.
EM = 1000
BOXW = 700
ADV = 750
SIZE = 40


def box(w: int = BOXW) -> str:
    return f"0 0 {w} {BOXW} re f\n"


# --- the four glyph procedures the colour probe uses -----------------------
# (a) d1, sets red inside. The probe: red here must NOT win.
PROC_D1_RED = f"{ADV} 0 0 0 {BOXW} {BOXW} d1\n1 0 0 rg\n" + box()
# (b) d1, sets nothing. The control that makes (a) readable.
PROC_D1_PLAIN = f"{ADV} 0 0 0 {BOXW} {BOXW} d1\n" + box()
# (c) d0, sets red inside. The opposite probe: red here MUST win.
PROC_D0_RED = f"{ADV} 0 d0\n1 0 0 rg\n" + box()

# (d) d1 + a 1-bit inline ImageMask - the BITMAP flavour, and the vehicle
# §9.6.5 permits where it forbids a colour image ("an image mask is
# acceptable, since it merely defines a region of the page to be painted with
# the current colour").
#
# An 8x8 hollow square with a diagonal: ASYMMETRIC on purpose, so a transposed
# or bit-reversed decode is visible rather than plausible. `/Decode [1 0]` so a
# SET bit paints - the inverse of the default, and the polarity real
# bitmap-font producers emit.
MASK_ROWS = [0xFF, 0x81, 0xA1, 0x91, 0x89, 0x85, 0x81, 0xFF]
MASK_HEX = "".join(f"{b:02X}" for b in MASK_ROWS)
PROC_D1_MASK = (
    f"{ADV} 0 0 0 {BOXW} {BOXW} d1\n"
    f"{BOXW} 0 0 {BOXW} 0 0 cm\n"
    "BI /W 8 /H 8 /IM true /D [1 0] /F /AHx ID\n" + MASK_HEX + ">\nEI\n"
)

# (e) a narrow box, for the ADVANCE row. Narrower than the advance so the gaps
# between consecutive glyphs are visible and countable; a renderer that got the
# width wrong by 1000x stacks all four on one spot instead.
PROC_NARROW = f"{ADV} 0 0 0 400 {BOXW} d1\n" + box(400)


def pdf(objects: list[bytes]) -> bytes:
    """Serialise objects 1..n with a classic cross-reference table."""
    out = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = [0]
    for i, obj in enumerate(objects, start=1):
        offsets.append(len(out))
        out += str(i).encode() + b" 0 obj\n" + obj + b"\nendobj\n"
    startxref = len(out)
    n = len(objects) + 1
    out += b"xref\n0 " + str(n).encode() + b"\n0000000000 65535 f \n"
    for off in offsets[1:]:
        out += ("%010d 00000 n %s" % (off, chr(10))).encode()
    out += (
        b"trailer\n<< /Size " + str(n).encode() + b" /Root 1 0 R >>\n"
        b"startxref\n" + str(startxref).encode() + b"\n%%EOF\n"
    )
    return bytes(out)


def stream(body: str) -> bytes:
    b = body.encode("latin-1")
    return b"<< /Length " + str(len(b)).encode() + b" >>\nstream\n" + b + b"endstream"


def build(
    procs: dict[str, str],
    diffs: str,
    content: str,
    *,
    first: int = 65,
    widths: list[int] | None = None,
    font_matrix: str = "[0.001 0 0 0.001 0 0]",
    font_resources: bytes | None = None,
    page_resources_extra: bytes = b"",
) -> bytes:
    """One page whose Type 3 font is object 5.

    Object numbering is fixed and asserted, because these dictionaries name
    each other by hand and an off-by-one renders a plausible wrong picture
    rather than an error (`R162`).
    """
    names = list(procs)
    widths = widths if widths is not None else [ADV] * len(names)
    # 1 catalog, 2 pages, 3 page, 4 content, 5 T3 font, 6 Helvetica,
    # 7 CharProcs, 8 Encoding, 9.. the procedures.
    proc_first = 9
    charprocs = b"<< " + b" ".join(
        b"/" + n.encode() + b" " + str(proc_first + i).encode() + b" 0 R"
        for i, n in enumerate(names)
    ) + b" >>"

    font = (
        b"<< /Type /Font /Subtype /Type3 /FontBBox [0 0 "
        + str(BOXW).encode()
        + b" "
        + str(BOXW).encode()
        + b"] /FontMatrix "
        + font_matrix.encode()
        + b" /CharProcs 7 0 R /Encoding 8 0 R /FirstChar "
        + str(first).encode()
        + b" /LastChar "
        + str(first + len(widths) - 1).encode()
        + b" /Widths ["
        + b" ".join(str(w).encode() for w in widths)
        + b"]"
        + (b" /Resources " + font_resources if font_resources else b"")
        + b" >>"
    )

    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 "
        + str(PAGE_W).encode()
        + b" "
        + str(PAGE_H).encode()
        + b"] /Resources << /Font << /T3 5 0 R /F1 6 0 R >>"
        + page_resources_extra
        + b" >> /Contents 4 0 R >>",
        stream(content),
        font,
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
        charprocs,
        b"<< /Type /Encoding /Differences [" + diffs.encode() + b"] >>",
    ]
    objects += [stream(procs[n]) for n in names]

    joined = b"".join(objects)
    # Each hand-written reference is checked in the object that CARRIES it,
    # not across the whole file: `self_recursive.pdf` deliberately names the
    # font a second time, from the font's own /Resources, and a file-wide
    # count would make that legitimate fixture unbuildable (R162 asks for the
    # literal to be checked, not for it to be unique).
    assert objects[2].count(b"/T3 5 0 R") == 1, "the page must name the font once"
    assert objects[4].count(b"/CharProcs 7 0 R") == 1
    assert objects[4].count(b"/Encoding 8 0 R") == 1
    for i, n in enumerate(names):
        ref = b"/" + n.encode() + b" " + str(proc_first + i).encode() + b" 0 R"
        assert joined.count(ref) == 1, ref
    return pdf(objects)


def label(y: int, text: str) -> str:
    return f"BT /F1 11 Tf 200 {y} Td ({text}) Tj ET\n"


def colour_and_advance() -> bytes:
    """Rows A-D: where a glyph's colour comes from. Row E: the advance.

    ★ Rows A-D are the ones rendered in Acrobat. Row E was added afterwards
    because the first four **position every glyph with `Td`** and therefore
    never exercise a width at all - a fixture that avoids the feature's
    precondition cannot tell a correct implementation from one that ignores
    `/Widths` entirely.
    """
    procs = {
        "ga": PROC_D1_RED,
        "gb": PROC_D1_PLAIN,
        "gc": PROC_D0_RED,
        "gd": PROC_D1_MASK,
        "ge": PROC_NARROW,
    }
    content = (
        # Blue, set ONCE, before the text object. A glyph that comes out blue
        # took its colour from the graphics state.
        "0 0 1 rg\n"
        f"BT /T3 {SIZE} Tf\n"
        "60 640 Td (\\101) Tj\n"
        "0 -80 Td (\\102) Tj\n"
        "0 -80 Td (\\103) Tj\n"
        "0 -80 Td (\\104) Tj\n"
        # ★ ROW E: FOUR GLYPHS IN ONE STRING, so the pen is moved by
        # `/Widths` and by nothing else. 750 units under a 0.001 matrix at
        # 40 pt is a 30 pt advance; the box is 400 units = 16 pt. So four
        # boxes, 16 pt wide, 30 pt apart. A renderer that also divided by
        # 1000 advances 0.03 pt and stacks all four into one.
        "0 -80 Td (\\105\\105\\105\\105) Tj\n"
        "ET\n"
        "0 0 0 rg\n"
        + label(645, "A  d1 + proc sets RED   -> BLUE means the ignore is honoured")
        + label(565, "B  d1, proc sets nothing  -> control, must be BLUE")
        + label(485, "C  d0 + proc sets RED     -> RED means d0 keeps its own colour")
        + label(405, "D  d1 + inline ImageMask  -> the bitmap flavour, must be BLUE")
        + label(325, "E  four glyphs, one string -> 16pt boxes 30pt apart")
    )
    return build(procs, "65 /ga /gb /gc /gd /ge", content)


def missing_glyph_advances() -> bytes:
    """§9.6.5 step (b): no glyph painted - and the width still applies.

    Three codes are shown as one string. The middle one is named in
    `/Differences` but is **absent from `/CharProcs`**, which is the case the
    clause names ("if the name is not present as a key in CharProcs, no glyph
    shall be painted"). It says nothing about the width, and `/Widths`
    supplies one independently.

    So the third box must sit **two advances** from the first. A renderer that
    treats a missing glyph as a skipped code puts it one advance along, and
    every later glyph on the line is wrong by the same amount - which reads as
    a layout bug rather than as a missing glyph.
    """
    procs = {"ga": PROC_NARROW}
    content = (
        "0 0 1 rg\n"
        f"BT /T3 {SIZE} Tf 60 600 Td (\\101\\102\\101) Tj ET\n"
        "0 0 0 rg\n"
        + label(605, "middle glyph is absent from CharProcs; third box must be 60pt along")
    )
    # `/Differences` names `gb` at code 66, but CharProcs has no such key.
    return build(procs, "65 /ga /gb", content, widths=[ADV, ADV])


def resources_fallback() -> bytes:
    """Table 112's page-resource fallback.

    "If any glyph descriptions refer to named resources but this dictionary is
    absent, the names shall be looked up in the resource dictionary of the
    PAGE on which the font is used."

    The font here has **no `/Resources`** and its glyph procedure invokes a
    form XObject by name. The name resolves only through the page. Old files
    routinely omit the entry, and a reader without the fallback reports
    "resource not found" on a document that is perfectly well-formed.
    """
    # The glyph draws nothing itself; everything visible comes from the form.
    procs = {"ga": f"{ADV} 0 0 0 {BOXW} {BOXW} d1\n/Fx Do\n"}
    content = (
        "0 0 1 rg\n"
        f"BT /T3 {SIZE} Tf 60 600 Td (\\101) Tj ET\n"
        "0 0 0 rg\n" + label(605, "glyph draws via a form found only in the PAGE resources")
    )
    data = build(
        procs,
        "65 /ga",
        content,
        page_resources_extra=b" /XObject << /Fx 10 0 R >>",
    )
    # Append the form as object 10. `build` emitted 9; the page names /Fx 10.
    form_body = box()
    form = (
        b"<< /Type /XObject /Subtype /Form /BBox [0 0 "
        + str(BOXW).encode()
        + b" "
        + str(BOXW).encode()
        + b"] /Length "
        + str(len(form_body)).encode()
        + b" >>\nstream\n"
        + form_body.encode("latin-1")
        + b"endstream"
    )
    return rebuild_with_extra(data, [form])


def self_recursive() -> bytes:
    """A glyph procedure that shows its own font - a stack overflow by construction.

    §9.6.5 does not forbid it and Annex C sets no limit, so an unbounded
    reader has a guaranteed crash input sitting in the standard. The
    procedure paints a box first, so a bounded reader still renders
    *something* and the fixture can tell "bounded" from "drew nothing".
    """
    procs = {
        "ga": (
            f"{ADV} 0 0 0 {BOXW} {BOXW} d1\n"
            + box(300)
            + f"BT /T3 {SIZE} Tf 300 0 Td (\\101) Tj ET\n"
        )
    }
    content = (
        "0 0 1 rg\n"
        f"BT /T3 {SIZE} Tf 60 600 Td (\\101) Tj ET\n"
        "0 0 0 rg\n" + label(605, "this glyph shows itself; a bounded reader still draws")
    )
    # The font's own /Resources names itself, so the recursion is reachable
    # without relying on the page fallback.
    return build(procs, "65 /ga", content, font_resources=b"<< /Font << /T3 5 0 R >> >>")


# --- Pass 127.0: the EXTRACTION gate ----------------------------------------
# A `/ToUnicode` CMap for codes 65..67 -> "HI!". Hand-written rather than
# generated so the fixture's expected text is legible in the file itself: a
# test that asserts "HI!" and a CMap that says <41> <0048> are two independent
# statements of the same fact, which is what makes disagreement detectable.
TO_UNICODE_HI = b"""/CIDInit /ProcSet findresource begin
12 dict begin
begincmap
/CMapName /pdfcer-type3-HI def
/CMapType 2 def
1 begincodespacerange
<00> <FF>
endcodespacerange
3 beginbfchar
<41> <0048>
<42> <0049>
<43> <0021>
endbfchar
endcmap
CMapName currentdict /CMap defineresource pop
end
end"""


def tounicode_gate() -> bytes:
    """§9.10.2's Type 3 dead end, and its control, on ONE page.

    THREE Type 3 fonts, deliberately:

    * `/TA` carries a `/ToUnicode` CMap. Its three codes must extract as
      ``HI!`` - the CONTROL, without which "nothing extracted" would pass for
      a reader that extracts nothing from any Type 3 font at all.
    * `/TB` and `/TC` carry none. Their glyph names (`/gb1`, `/gc1`, ...) are
      arbitrary `/CharProcs` keys, which is all a Type 3 glyph name ever is
      (Table 112), so no rung of §9.10.2 can reach Unicode for them.

    ★ THE REASON THERE ARE TWO DEAD ENDS AND NOT ONE. Table 112 has **no
    `/BaseFont` entry**: a conformant Type 3 font has no name. pdfcer's
    per-font diagnostics de-duplicated on that name, so before `Pass 127.0`
    every unnamed font on a page collapsed into a single entry and the new
    `type3_fonts_without_to_unicode` counter would have said `1` here. The
    fixture asserts **2**, which is a claim about the de-duplication key and
    not merely about the counter's existence.

    ★ AND THE GLYPH NAMES ARE NOT STANDARD ONES, deliberately. pdfcer keeps a
    counted extension beyond Acrobat: a Type 3 glyph that happens to be named
    `/A` still resolves through the Adobe Glyph List and is counted as
    `via_glyph_name_extension`. Naming these `/gb1` shuts that door, so the
    codes reach §9.10.2's failure clause and the dead end is measured rather
    than papered over by a lucky name.
    """
    # Object plan, fixed and asserted below, because these dictionaries name
    # each other by hand (R162):
    #   1 catalog, 2 pages, 3 page, 4 content,
    #   5 /TA font, 6 /TA CharProcs, 7 /TA Encoding, 8 /TA glyph proc,
    #   9 /TA ToUnicode,
    #   10 /TB font, 11 /TB CharProcs, 12 /TB Encoding, 13 /TB glyph proc,
    #   14 /TC font, 15 /TC CharProcs, 16 /TC Encoding, 17 /TC glyph proc,
    #   18 Helvetica.
    def t3(font_obj: int, names: list[str], to_unicode: int | None) -> bytes:
        cp, enc = font_obj + 1, font_obj + 2
        tu = b" /ToUnicode " + str(to_unicode).encode() + b" 0 R" if to_unicode else b""
        return (
            b"<< /Type /Font /Subtype /Type3 /FontBBox [0 0 "
            + str(BOXW).encode() + b" " + str(BOXW).encode()
            + b"] /FontMatrix [0.001 0 0 0.001 0 0]"
            + b" /CharProcs " + str(cp).encode() + b" 0 R"
            + b" /Encoding " + str(enc).encode() + b" 0 R"
            + b" /FirstChar 65 /LastChar " + str(64 + len(names)).encode()
            + b" /Widths [" + b" ".join(str(ADV).encode() for _ in names) + b"]"
            + tu
            + b" >>"
        )

    # All three fonts share ONE glyph procedure object each; the shape does
    # not matter to extraction, only that a code maps to a painted glyph.
    a_names = ["ga1", "ga2", "ga3"]
    b_names = ["gb1"]
    c_names = ["gc1"]

    content = (
        "0 0 1 rg\n"
        # /TA: three codes, a /ToUnicode - must come out "HI!".
        f"BT /TA {SIZE} Tf 60 620 Td (\\101\\102\\103) Tj ET\n"
        # /TB and /TC: one code each, no /ToUnicode - two dead ends.
        f"BT /TB {SIZE} Tf 60 540 Td (\\101) Tj ET\n"
        f"BT /TC {SIZE} Tf 60 460 Td (\\101) Tj ET\n"
        "0 0 0 rg\n"
        + label(625, "TA has /ToUnicode -> extracts as HI!")
        + label(545, "TB has none -> unsearchable, and it is SAID so")
        + label(465, "TC has none either -> and it is a SECOND font, not the same one")
    )

    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 "
        + str(PAGE_W).encode() + b" " + str(PAGE_H).encode()
        + b"] /Resources << /Font << /TA 5 0 R /TB 10 0 R /TC 14 0 R /F1 18 0 R >> >>"
        + b" /Contents 4 0 R >>",
        stream(content),
        t3(5, a_names, 9),
        b"<< " + b" ".join(
            b"/" + n.encode() + b" 8 0 R" for n in a_names
        ) + b" >>",
        b"<< /Type /Encoding /Differences [65 "
        + b" ".join(b"/" + n.encode() for n in a_names) + b"] >>",
        stream(PROC_NARROW),
        b"<< /Length " + str(len(TO_UNICODE_HI)).encode() + b" >>\nstream\n"
        + TO_UNICODE_HI + b"\nendstream",
        t3(10, b_names, None),
        b"<< /gb1 13 0 R >>",
        b"<< /Type /Encoding /Differences [65 /gb1] >>",
        stream(PROC_NARROW),
        t3(14, c_names, None),
        b"<< /gc1 17 0 R >>",
        b"<< /Type /Encoding /Differences [65 /gc1] >>",
        stream(PROC_NARROW),
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]
    assert len(objects) == 18, len(objects)
    # The three fonts must be three DISTINCT objects, or the fixture cannot
    # make its own central claim.
    assert objects[2].count(b"/TA 5 0 R") == 1
    assert objects[2].count(b"/TB 10 0 R") == 1
    assert objects[2].count(b"/TC 14 0 R") == 1
    # Indices are into the list above: 0 catalog, 1 pages, 2 page,
    # 3 content, 4 /TA font, ... 9 /TB font, ... 13 /TC font.
    assert objects[4].count(b"/ToUnicode 9 0 R") == 1
    assert b"/ToUnicode" not in objects[9]
    assert b"/ToUnicode" not in objects[13]
    return pdf(objects)


def rebuild_with_extra(data: bytes, extra: list[bytes]) -> bytes:
    """Re-serialise a built file with additional objects appended.

    Rebuilding rather than patching the xref: an offset table edited by hand
    is a second place for the file to be wrong, and these fixtures exist to
    test a renderer rather than a recovery path.
    """
    body = data.split(b"xref\n", 1)[0]
    objects: list[bytes] = []
    idx = 1
    while True:
        marker = str(idx).encode() + b" 0 obj\n"
        start = body.find(marker)
        if start < 0:
            break
        start += len(marker)
        end = body.find(b"\nendobj\n", start)
        objects.append(body[start:end])
        idx += 1
    return pdf(objects + extra)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    files = {
        "colour_and_advance.pdf": colour_and_advance(),
        "missing_glyph_advances.pdf": missing_glyph_advances(),
        "resources_fallback.pdf": resources_fallback(),
        "self_recursive.pdf": self_recursive(),
        "tounicode_gate.pdf": tounicode_gate(),
    }
    for name, data in sorted(files.items()):
        (OUT / name).write_bytes(data)
        print(f"wrote {OUT / name}  ({len(data)} bytes)")


if __name__ == "__main__":
    main()
