#!/usr/bin/env python3
"""Generate the five documents that pin `delete_annotation`'s appearance-stream
cascade (cascade 3) to §12.5.5.

WHY THESE EXIST
===============

`EditSession::appearance_streams_owned_by` collects the objects an annotation's
`/AP` reaches and hands the whole set to deletion. It did not check that any of
them was a **stream**.

ISO 32000-1 §12.5.5 is unambiguous on the point: "Each appearance stream **is a
form XObject**", and where Table 168's `/N`, `/R` or `/D` holds a subdictionary
instead, "the subdictionary shall define multiple appearance **streams**". So
every object that function reaches shall be a stream. Anything else is some
other object the file pointed `/AP` at.

THE MEASURED DEFECT
===================

Found on `fuzz/corpus/annot_delete_sequence/seed_openbug_badkid_dupobjnum.bin`
(the `BadKid(ObjId 3)` route left open by `Pass 190.1`). A `/Stamp` whose
`/AP /N` referenced a `/Widget` **dictionary** rather than a stream fell into
the "appearance-state subdictionary" branch, so every reference inside that
widget was harvested as an appearance state -- including its `/P`, which points
at the **page**. The page was deleted, `cut_selection` returned `Ok`, and
`to_full_bytes` wrote a 904-byte file that reloads with `BadKid`.

Nothing complained in a release build. `debug_assert_page_tree_still_walks` is
compiled out, and the incremental path happened to refuse that particular
document for an unrelated reason (a recovered base xref) -- exactly the kind of
accident that lets a route be sized as harmless. `save_full`, the sanctioned
path for a recovered document, carried it through.

WHY FIVE FILES AND NOT TWO
==========================

Three of them are **controls**, and they are the reason this set can tell a fix
from a regression:

  * `ap-cascade-single-stream.pdf` and the two subdictionary files carry REAL
    appearance streams that MUST still be deleted. A "fix" that simply stops
    deleting anything passes the two hostile files and fails all three of
    these.
  * The two subdictionary controls cover the branch that broke (a `/N` that is
    a **reference to** a dictionary) and its inline twin (`/N` written as a
    direct dictionary) separately, because the code takes different paths and
    a fix applied to only one is the shape this project keeps finding.

Provenance: wholly synthetic, `LEGAL.md` §5 category (a). Hand-rolled rather
than produced by `pdfcer`, for the reason the sibling generators give -- a
fixture generated by the program under test cannot falsify that program.
"""

import pathlib

OUT = pathlib.Path(__file__).resolve().parent.parent / "fixtures" / "synthetic" / "annot"

# A minimal, valid form XObject body. Content is irrelevant to the cascade --
# what matters is that the object IS a stream, so the guard admits it.
AP_STREAM = (
    b"<< /Type /XObject /Subtype /Form /BBox [0 0 20 20] /Resources << >> /Length 23 >>\n"
    b"stream\n0 0 0 rg 0 0 20 20 re f\nendstream"
)


def assemble(objects: list[bytes], root: int = 1) -> bytes:
    """Wrap object bodies in a header, xref table and trailer.

    Object bodies are emitted verbatim, so a body may be a dictionary or a
    complete `<<...>>\\nstream\\n...\\nendstream` pair; the offsets are computed
    from the emitted bytes either way.
    """
    out = bytearray(b"%PDF-1.7\n%\xe2\xe3\xcf\xd3\n")
    offsets = [0]
    for i, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += str(i).encode() + b" 0 obj\n" + body + b"\nendobj\n"
    startxref = len(out)
    n = len(objects) + 1
    out += b"xref\n0 " + str(n).encode() + b"\n0000000000 65535 f \n"
    for off in offsets[1:]:
        out += f"{off:010d} 00000 n \n".encode()
    out += (
        b"trailer\n<< /Size " + str(n).encode() + b" /Root "
        + str(root).encode() + b" 0 R >>\nstartxref\n"
        + str(startxref).encode() + b"\n%%EOF\n"
    )
    return bytes(out)


def ap_points_at_widget_reaching_page() -> bytes:
    """THE REPRODUCER, minimized: `/AP /N` names a `/Widget` whose `/P` is the page.

    Object 5 is a dictionary, so the old code took the subdictionary branch and
    harvested `/P 3 0 R` -- the page -- and `/Parent 6 0 R`. Deleting the stamp
    must leave both, and must leave the page tree walking.
    """
    return assemble(
        [
            b"<< /Type /Catalog /Pages 2 0 R >>",
            b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
            b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] "
            b"/Resources << >> /Annots [4 0 R] >>",
            b"<< /Type /Annot /Subtype /Stamp /Rect [0 0 200 200] "
            b"/AP << /N 5 0 R >> >>",
            b"<< /Type /Annot /Subtype /Widget /Parent 6 0 R /P 3 0 R "
            b"/Rect [20 150 200 172] /F 4 >>",
            b"<< /FT /Tx /T (Order) /V (ORD-77) /Kids [5 0 R] >>",
        ]
    )


def ap_points_at_catalog() -> bytes:
    """`/AP /N` names the document CATALOG directly.

    The catalog is a dictionary, so the old code harvested its `/Pages 2 0 R`
    and doomed the page-tree node. A distinct route from the file above -- there
    the structural object was reached one hop further in -- and the one that
    destroys the tree without ever touching a `/Page`.
    """
    return assemble(
        [
            b"<< /Type /Catalog /Pages 2 0 R >>",
            b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
            b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] "
            b"/Resources << >> /Annots [4 0 R] >>",
            b"<< /Type /Annot /Subtype /Stamp /Rect [0 0 100 100] "
            b"/AP << /N 1 0 R >> >>",
        ]
    )


def ap_single_stream() -> bytes:
    """CONTROL: a real, solely-owned appearance stream that MUST be deleted.

    Object 5 is a genuine form XObject nothing else reaches. Cascade 3 exists to
    delete exactly this, and a guard that admitted nothing would orphan it in
    every subsequent save.
    """
    return assemble(
        [
            b"<< /Type /Catalog /Pages 2 0 R >>",
            b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
            b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] "
            b"/Resources << >> /Annots [4 0 R] >>",
            b"<< /Type /Annot /Subtype /Stamp /Rect [0 0 100 100] "
            b"/AP << /N 5 0 R >> >>",
            AP_STREAM,
        ]
    )


def ap_state_subdict_by_reference() -> bytes:
    """CONTROL for the branch that broke: `/N` is a REFERENCE to a state subdictionary.

    Object 5 is a dictionary -- the same shape as the hostile file above -- but a
    legitimate one, whose members really are streams (§12.5.5's checkbox
    example). Both streams must still be deleted. This is the fixture that
    stops the fix from being "a dictionary under `/N` is always suspect".
    """
    return assemble(
        [
            b"<< /Type /Catalog /Pages 2 0 R >>",
            b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
            b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] "
            b"/Resources << >> /Annots [4 0 R] >>",
            b"<< /Type /Annot /Subtype /Stamp /Rect [0 0 100 100] "
            b"/AS /On /AP << /N 5 0 R >> >>",
            b"<< /On 6 0 R /Off 7 0 R >>",
            AP_STREAM,
            AP_STREAM,
        ]
    )


def ap_state_subdict_inline() -> bytes:
    """CONTROL for the inline twin: `/N` is a DIRECT state subdictionary.

    Same obligation, different code path -- the direct-dictionary branch rather
    than the resolve-a-reference one. Kept separate because a fix applied to one
    branch and not the other is a shape this project has shipped before.
    """
    return assemble(
        [
            b"<< /Type /Catalog /Pages 2 0 R >>",
            b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
            b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] "
            b"/Resources << >> /Annots [4 0 R] >>",
            b"<< /Type /Annot /Subtype /Stamp /Rect [0 0 100 100] "
            b"/AS /On /AP << /N << /On 5 0 R /Off 6 0 R >> >> >>",
            AP_STREAM,
            AP_STREAM,
        ]
    )


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for name, data in {
        "ap-cascade-widget-reaches-page.pdf": ap_points_at_widget_reaching_page(),
        "ap-cascade-names-catalog.pdf": ap_points_at_catalog(),
        "ap-cascade-single-stream.pdf": ap_single_stream(),
        "ap-cascade-state-subdict-ref.pdf": ap_state_subdict_by_reference(),
        "ap-cascade-state-subdict-inline.pdf": ap_state_subdict_inline(),
    }.items():
        (OUT / name).write_bytes(data)
        print(f"wrote {OUT / name}  ({len(data)} bytes)")


if __name__ == "__main__":
    main()
